### ISSUE TITLE
eprosima config.h breaks boost native_to_big [8991]

### ISSUE THREAD

**Issue by pvd** [eProsima/Fast-DDS#1001]
When the eprosima **config.h** is (directly or indirectly) include **before** the boost/endian/**conversion.hpp** the function **boost::endian::native_to_big** fails to do a endian swap on a little endian machine.

## Expected Behavior

The native_to_big function should not be affected by other includes. I know this can also be seen as a boost issue but please continue reading...

## Current Behavior

The order the includes drives the behavior of the boost endian conversion function.

## Steps to Reproduce

```C++
#include "fastrtps/publisher/Publisher.h"
#include <boost/endian/conversion.hpp>
int main( /*int argc, char* argv[] */)
{
    uint16_t i = 0x1234;
    uint16_t j = boost::endian::native_to_big(i);
    assert(j == 0x3412);   // The assert fails; When lines 1 and 2 are swapped the native_to_big works as expected.
    return 0;
}
```
## System information

- Fast-RTPS version: 1.8.2
- OS: Windows 10
- Network interfaces: N/A
- ROS2: N/A

## Additional context

Compiler: mingw-w64 i686-8.1.0-posix-dwarf-rt_v6-rev0)
Boost: 1.71

I've been able to trace this to boost endian.h line 106 where a check is done on the existence of the of the __BIG_ENDIAN__ define. Since the eprosima config.h defines this as 0 the boost library assumes the machine is native big endian.

```
106 #   if (defined(__BIG_ENDIAN__) && !defined(__LITTLE_ENDIAN__)) || 
```

**Comment by EduPonz** [comment]
Hi @pvd 

#1361 should solve this issue. Could you verify on your end?

**Comment by EduPonz** [comment]
I'm closing this since #1361 has been merged to master. Please feel free to reopen if the problem persists.
