### ISSUE TITLE
subscriber matches publisher failed [7964]

### ISSUE THREAD

**Issue by Jinwei12** [eProsima/Fast-DDS#1026]
mashine A:Jetason nano as publisher(IP:192.168.1.90)
mashine B:Ubuntu 16.04 with virtual box(IP:192.168.1.100)
(both of mashine in a same subnet)
Sample HelloWorld works fine in any single mashine,but...
I make some changes with the sample.
In HelloWorldPublisher.cpp:
    Locator_t locator;
    std::string wan_ip = "192.168.1.90";
    unsigned short port = 5100;
    IPLocator::setIPv4(locator, wan_ip);
    locator.port = port;
    PParam.rtps.builtin.metatrafficUnicastLocatorList.push_back(locator);
In HelloWorldSubscriber.cpp:
    eprosima::fastrtps::rtps::Locator_t locator;
    IPLocator::setIPv4(locator, "192.168.1.90");
    locator.port = 5100;
    PParam.rtps.builtin.initialPeersList.push_back(locator);

They can match to each other and transport data,but when I start another subscriber at the same time,the latter can not matches publisher.That is not like the meaning of "multicast".Is there any problem in my configuration?Or is there lack of any other configurations?

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @Jinwei12,

After checking your issue in the HelloWorldExample of the master version of the Fast DDS library, the issue have not been reproduced.

Following the steps provided in your issue, all multicast traffic for the Publisher participant (defining only one metatraffic unicast locator) have been disabled. This prevents the participant associated to the Publisher from listening to any discovery data from multicast sources.

At the same time, the Subscriber parameters have been modified to include in the initial peer list the same unicast locator defined for the publisher. The subscriber, therefore, would send announcement messages both through multicast (which would be ignored by the Publisher participant) and through the unicast locator (where the Publisher participant would listen and discover any number of subscribers addressing that unicast locator).

Finally, the example has been launched with one Publisher and three Subscribers and every one of them have matched and shared the HelloWorld message.

I'll go ahead and close the issue considering the question to be answered. However, feel free to comment or reopen at any time if you need further information.
