### ISSUE TITLE
win10 使用cmake  -DTHIRDPARTY=ON -DBUILD_JAVA=ON -DCOMPILE_EXAMPLES=ON -DPERFORMANCE_TESTS=ON .. 出现 Manually-specified variables were not used by the project: DBUILD_JAVA 

### ISSUE THREAD

**Issue by cylovefpc** [eProsima/Fast-DDS#1066]
## Steps to Reproduce

1.
2.
3.
4.

## System information

- Fast-RTPS version: 
- OS: 
- Network interfaces: 
                      
- ROS2: 
        

## Additional resources
- Wireshark capture 
- XML profiles file

**Comment by MiguelCompany** [comment]
@cylovefpc As Fast RTPS generator has moved to a [different repository](https://github.com/eProsima/Fast-RTPS-gen), the `-DBUILD_JAVA` option is not used anymore.
