### ISSUE TITLE
High CPU usage when big message are published on arm32 [8995]

### ISSUE THREAD

**Issue by lukicdarkoo** [eProsima/Fast-DDS#1107]
We compiled ROS2 Eloquent with Fast RTPS middleware implementation on arm32 (Raspberry Pi Zero). In general, it works quite good, but we are experiencing low FPS when we send images locally (publisher and subscriber onboard). We profiled our node and noticed that a lot of images are dropped - the images are acquired and sent (`publisher->publish()`) at 10Hz but the subscriber (`ros2 topic hz image_raw`) receives them at 3 - 4Hz. 

## Expected Behavior
Since both nodes, publisher and subscriber, are running locally I would expect it to easily achieve 10fps. The images are around 1MB (640x480x3).

## Current Behavior
Achieved fps is around 3 - 4 and the CPU is at ~100%

## Steps to Reproduce
1. Publish raw images (640x480) at a high rate
2. Subscribe to the topic on the same device

## System information
- Fast-RTPS version: [tag] release/eloquent/fastrtps/1.9.3-2
- OS: Raspbian Buster
- Network interfaces: lo (127.0.0.1)
- ROS2: Eloquent

I assume that the messages are dropped because the device cannot handle the workload. But since the high CPU usage is caused by Fast RTPS I was wondering if it is possible to reduce it?

**Comment by EduPonz** [comment]
Hi @lukicdarkoo ,

Unfortunately we don't have the hardware to verify your issue, but we did some improvements that can and should affect your case. It'd be nice if you could try with master branch. Furthermore, if both publisher and subscriber are in the same machine, you could benefit from [Fast DDS Shared Memory Transport](https://fast-rtps.docs.eprosima.com/en/latest/fastdds/transport/shared_memory/shared_memory.html). If you have any problems setting it up just let us know and we'll be happy to guide you.
