### ISSUE TITLE
Fast-CDR fails to build in Debian Buster RTI3B+ 

### ISSUE THREAD

**Issue by Reubenyuhe** [eProsima/Fast-DDS#1124]
hello there!
I was trying to build the latest master version on a fresh booted RPI 3B+. Since I am Pretty new to Linux I've followed both build ways and used the default argument. Both the colcon build and Cmake was failed with the same symlink errors: 

```
Scanning dependencies of target fastcdr
[ 14%] Building CXX object src/cpp/CMakeFiles/fastcdr.dir/Cdr.cpp.o
c++: error: unrecognized command line option ‘-Wnull-dereference’
c++: error: unrecognized command line option ‘-Wduplicated-branches’
c++: error: unrecognized command line option ‘-Wduplicated-cond’
c++: error: unrecognized command line option ‘-Wrestrict’
make[2]: *** [src/cpp/CMakeFiles/fastcdr.dir/build.make:63: src/cpp/CMakeFiles/fastcdr.dir/Cdr.cpp.o] Fehler 1
make[1]: *** [CMakeFiles/Makefile2:91: src/cpp/CMakeFiles/fastcdr.dir/all] Fehler 2
make: *** [Makefile:152: all] Fehler 2

```

- OS: Debian buster
- Network interfaces: wlan0(141.30.x.x)
- I was trying to build ROS2 Foxy 

regards.

**Comment by richiware** [comment]
Which GCC version?

**Comment by Reubenyuhe** [comment]
Sorry I have forgotten to comment. I've really forgotten to check the gcc version and I was using a lower GCC version as this issue occurred.
