### ISSUE TITLE
Interoperability between FastRTPS 1.8.3 and > 1.9.4 [8996]

### ISSUE THREAD

**Issue by ShawnSchaerer** [eProsima/Fast-DDS#1130]
We tried to get two machines talking to each other.  One using 1.8.3 and one using 1.9.4
This did not work.
We can make two machines talk using 1.8.x

Before we start to debug and file an official bug, I would like to understand if this a supported use case.

**Comment by MiguelCompany** [comment]
@ShawnSchaerer I just checked 1.8.x <-> 1.9.x communications using our HelloWorldExample and everything went fine. I also checked 1.10.x <-> 1.8.x and everything went fine.

I performed this between my Windows 10 and my VirtualBox with Ubuntu Focal, in order to check the communication between different machines.

Could you give more details on your platform?

**Comment by pedro1713** [comment]
In our case one machine was running QNX 7 x86_64 architecture and the other was running Linux 18.04. 
With a publisher running on the Linux machine and a subscriber on the QNX one, they couldn't see each other. Things worked after the code on the Linux machine was recompiled against version 1.8 of the library.

**Comment by jparisu** [comment]
We have tried to replicate your issue with the two different versions (Fast-RTPS 1.8.3 commit 46e92b3 & Fastd-RTPS 1.9.4 commit f3863b6) using a Linux machine and two different RaspberryPi with Raspbian.
We have not found any issue in the connection between the machines using the Fast-RTPS library examples.
These are the tests executed:

```
raspberry pi @27 => Fast-DDS 1.8.3
raspberry pi @26 => Fast-DDS 1.9.4

Publisher		Subscriber
local/1.8.3		local/1.9.4		Correct
local/1.9.4		local/1.8.3		Correct
@27			@27			Correct
@26			@26			Correct
@27			@26			Correct
@26			@27			Correct
local/1.9.4		@27			Correct
@27			local/1.9.4		Correct
local/1.8.3		@26			Correct
@26			local/1.8.3		Correct
```

In any case we Fast-DDS have a version 2.0.1 you might want to try out.

In case you keep experience this issue, please send us more details about the network architecture and traces and we will be happy to help.
