### ISSUE TITLE
Try to load the default XML file [8997]

### ISSUE THREAD

**Issue by razr** [eProsima/Fast-DDS#1158]
Fast-RTPS always tries to load a default XML file here
    // Try to load the default XML file.
    loadXMLFile(DEFAULT_FASTRTPS_PROFILES);

In my case, it causes a long delay since the directory is mapped via FTP.
Moreover, the file itself does not exist in ROS2, so probably it is better to make it optional

## Expected Behavior

all configuration files shall be located in the data dir
make loadXML optional, similar to 
    if (const char* file_path = std::getenv(DEFAULT_FASTRTPS_ENV_VARIABLE))
    {
        loadXMLFile(file_path);
    }

## Current Behavior

Try to load the default XML file.

## Steps to Reproduce

1. I have started a timer_lambda ROS2 example

## System information

- Fast-RTPS version: v1.8.2 
- OS: VxWorks 
- Network interfaces: N/A 
                      
- ROS2: dashing

**Comment by imontesino** [comment]
This has now been adressed in #1350
