### ISSUE TITLE
FastRTPS v1.10.0 build use cmake .. -DSTRICT_REALTIME=ON, run Example got Segmentation fault [8371]

### ISSUE THREAD

**Issue by phoebossy** [eProsima/Fast-DDS#1201]
build Fast-RTPS v1.10.0 without -DSTRICT_REALTIME=ON was all right, but when use cmake .. -DSTRICT_REALTIME=ON build Fasr-RTPS, run ./HelloWorldExample publisher got a Segmentation fault.
## Expected Behavior
Support real-time behaviour.
## Current Behavior
When I use UDP to send a lot of small packages,  I found when history s full, Publisher.send method will wait for 1 or 2 seconds, It's too slow.  I noticed that there are STRICT_REALTIME option in src/cpp/CMakeLists.txt, so I try it to got better performance. Not only my code get segmentation fault, HelloWorldExample got it too. 

## Steps to Reproduce
1.  code: Fast-RTPS/examples/C++/HelloWorldExample
2.
3.
4.

## System information

- Fast-RTPS version: 1.10.0
- OS:  Ubuntu 18.04
- Network interfaces: 
                      eth0 (192.168.1.10)
- ROS2: None

## Additional context
None

## Additional resources
None

**Comment by EduPonz** [comment]
Hi @phoebossy ,

Did you have a chance to test with #1311 . It will make its way into master soon and we'd appreciate your input.
