### ISSUE TITLE
Dynamic types: How to read map values in a subscriber? [8677]

### ISSUE THREAD

**Issue by bjarnisig** [eProsima/Fast-DDS#1228]
I've been trying to figure out how to read from a map from a message type that is defined using XML.
Take for example this simple message type:

```xml
<type>
    <struct name="MyHelloWorldStruct">
        <member name="myint" type="int32"/>
        <member name="mymap" type="int32" key_type="int32" mapMaxLength="-1"/>
    </struct>
</type>
```

In my publisher I set the map values like this:

```C++
    using namespace eprosima::fastrtps;
    //NOTE:  _data => DynamicData*
    auto intId = _data->get_member_id_by_name("myint");
    _data->set_int32_value(99, intId);

    auto memberId = _data->get_member_id_by_name("mymap");
    if (memberId != MEMBER_ID_INVALID)
    {
        auto mapData = _data->loan_value(memberId);
        types::DynamicType_ptr base = types::DynamicTypeBuilderFactory::get_instance()->create_int32_type();
        types::DynamicData_ptr key(types::DynamicDataFactory::get_instance()->create_data(base));
        types::MemberId keyId;
        types::MemberId valueId;
        // Adding key 42, value 53
        key->set_int32_value(42);
        mapData->insert_map_data(key.get(), keyId, valueId);
        mapData->set_int32_value(53, valueId);

        // Adding key 43, value 54
        key->set_int32_value(43);
        mapData->insert_map_data(key.get(), keyId, valueId);
        mapData->set_int32_value(54, valueId);

        _data->return_loaned_value(mapData);
    }
```

On the subscriber side I can easily read the `myint` variable using `get_member_id_by_name` and `get_int32_value`. However I fail to see how I can read the values of `mymap`.

I've read through the documentation and examples, and even some unit tests. All of these get the `MemberId` of each map value from `insert_map_data`, which is not applicable on the subscriber side.

Am I missing something very obvious here?

**Comment by bjarnisig** [comment]
So far I've found the map keys and values implicitly by guessing that the key/value MemberIds would be arranged incrementally, like the example below (based on hardcoded entries on the publisher side):

```C++
    auto memberId = _data->get_member_id_by_name("mymap");
    if (memberId != MEMBER_ID_INVALID)
    {
        auto mapData = _data->loan_value(memberId);

        std::cout << "Number of items in mapData: " << mapData->get_item_count() << std::endl;
        std::cout << "key1 = "   << mapData->get_int32_value(0) << std::endl;
        std::cout << "value1 = " << mapData->get_int32_value(1) << std::endl;
        std::cout << "key2 = "   << mapData->get_int32_value(2) << std::endl;
        std::cout << "value2 = " << mapData->get_int32_value(3) << std::endl;

        _data->return_loaned_value(mapData);
    }
```

Is this really the way to go?

**Comment by LuisGP** [comment]
Hi @bjarnisig 
Seems that we must improve our documentation and check if we are providing the following behavior:

**Extensible and Dynamic Topic Types for DDS (1.2):**
**Section 7.5.2.11.1 Property: value; Operations: get_member_id_by_name and get_member_id_at_index**
> [...] 
> If this object is of a map type, values correspond to the values of the map. Map keys are implicitly converted to strings and can thus be used to look up map values by name. Map values can also be accessed by index, although the order is unspecified.

So, theoretically, you should be able to access the map's values using the key as "name":

```cpp
MemberId valueId = mapData->get_member_id_by_name(std::to_string(43)); // key 43
int32_t value = mapData->get_int32_value(valueId);
```

I'm not able to test it right now, and I'm not sure if this was implemented. Did you tried it?

**Comment by bjarnisig** [comment]
Hi @LuisGP , thanks for the reply.
I had already read that from the specifications, and tried it. However the MemberId that is returned from **get_member_id_by_name** is always **MEMBER_ID_INVALID** in this case.

Previously I was using v.1.10.x , but I also see this in v.2.0.x.

**Comment by LuisGP** [comment]
Hi @bjarnisig 
I'm sorry to read that. That feature wasn't implemented then. We will address it as soon as possible.
Meanwhile, your only option is to access key/value is knowing that MemberIds are arranged incrementally, as you noticed.

**Comment by EduPonz** [comment]
I'm closing this issue, as the there were no further inquiries. Feel free to reopen at any time
