### ISSUE TITLE
DDS HistoryKind example does not work [9140]

### ISSUE THREAD

**Issue by bjarnisig** [eProsima/Fast-DDS#1256]
I was planning to play around with HistoryQosPolicy and DurabilityQosPolicy, using the fastdds API in version 2.0.0. For my application the initial goal is just for my data readers to be able to get the last data sample in the case when the reader starts up after a data sample has been published by the data writer (basic stuff I guess).

My initial trials where not successful. I figured I must be doing something wrong, so I tried to run the **HistoryKind** example (https://github.com/eProsima/Fast-DDS/tree/master/examples/C%2B%2B/DDS/HistoryKind). It did not work as expected, the data readers did not get any data.
Running the fast-rtps example works as expected.

## Expected Behavior
The subscribers in the example should be able to read the data.
The output should be similar to what is produced by the RTPS example, seen here below:
```
Creating Publisher...
Creating Keep All Subscriber...
Creating Keep Last Subscriber with depth 10...
Publishing 20 samples on the topic...
The Keep All Subscriber holds: 
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 
The Keep Last (Depth 10) Subscriber holds: 
11 12 13 14 15 16 17 18 19 20 
```

## Current Behavior
This is the current output:
```
Creating Publisher...
Creating Keep All Subscriber...
Creating Keep Last Subscriber with depth 10...
Publishing 20 samples on the topic...
The Keep All Subscriber holds: 

The Keep Last (Depth 10) Subscriber holds: 

Deleting Publisher
Deleting Subscribers
```

No data is available for the data readers.

## Steps to Reproduce
Build and run the HistoryKind example: https://github.com/eProsima/Fast-DDS/tree/master/examples/C%2B%2B/DDS/HistoryKind

## System information

- Fast-RTPS version: 2.0.x
- OS: Ubuntu 18.04

**Comment by imontesino** [comment]
Fixed in #1354. The HistoryMemoryPolicy was wrongly set to VOLATILE_DURABILITY_QOS so the DataReaders would not recieve the samples that had been sent before they matched the DataWriter. It should fix your issue,
