### ISSUE TITLE
Question: UDP endpoints for different network interfaces [9142]

### ISSUE THREAD

**Issue by romain-gimenez** [eProsima/Fast-DDS#1265]
Hello,

While I was testing the FastDDS library I've noticed that the first network interface of the system was not handled the same way than the others.

So I've looked inside the code and found this in src/cpp/fastdds/rtps/transport/UDPTransportInterface.cpp:

```cpp
            // Outbounding first interface with already created socket.
            if(!locNames.empty())
            {
                SetSocketOutboundInterface(unicastSocket, (*locNames.begin()).name);
            }

            // If more than one interface, then create sockets for outbounding multicast.
            if (locNames.size() > 1)
            {
                auto locIt = locNames.begin();
                sender_resource_list.emplace_back(
                        static_cast<SenderResource*>(new UDPSenderResource(*this, unicastSocket)));

                // Create other socket for outbounding rest of interfaces.
                for (++locIt; locIt != locNames.end(); ++locIt)
```

Open ports are then:

 - IPv4 UDP *:7400
 - IPv4 UDP *:7412
 - IPv4 UDP *:7413
 - IPv4 UDP *:55782 // I would expect this to be 1.2.3.6:55782 instead ?
 - IPv4 UDP 192.168.12.13:54760
 - IPv4 UDP 192.168.56.101:50689
 - IPv4 UDP 127.0.0.1:55355

Could someone explain why the first interface is using any address instead of the local address please ? It seems that when using a whitelist, all interfaces are used the same way.

Thanks in advance.

Romain

**Comment by jparisu** [comment]
The 3 firsts interfaces are the Default Locator Listeners (https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/listening_locators.html#default-listening-locators) that the library automatically enables.

<b>Next interface [IPv4 UDP *:55782] is the any address used as the default output address for unicast transport</b>. (it leaves the interface choice to the routing table)

The following two interfaces are used **only** to send the multicast information through all the output channels. (if you check the code, UDPTransportInterface.cpp line 313 sets these sockets as multicast_only)

The last address is the loopback address, to keep endpoints in the same local connected in case the external connection fails.

In case the user sets explicitly a _whitelist_, addresses are forced to the one given and non _any_ _address_ is needed.

Feel free to reopen this issue in case you had further doubts regarding this topic.
