### ISSUE TITLE
 [RTCP_MSG_IN Error] Bad RTCP header identifier, closing connection. v2.0.0 [9141]

### ISSUE THREAD

**Issue by wutianze** [eProsima/Fast-DDS#1268]
Hi
One Publisher and one subscriber communicate with each other through the internet using TCPv4TransportDescriptor. The message size is 10k, the qos set for the writer is RELIABLE, max_blocking_time is 5s. The subscriber received some messages(usually 50-90 messages), and then crashed with  [RTCP_MSG_IN Error] Bad RTCP header identifier, closing connection.
When using the default Best Effort setting, I ran into this error too.

- Fast-RTPS version: v2.0.0
- OS: Ubuntu18.04

**Comment by EduPonz** [comment]
Hi @wutianze ,

We had also detected this issue on our side. We will allocate resources for this as soon as we have them, since we'd like a stable TCP transport in the upcoming releases. We'll keep you posted

**Comment by MiguelCompany** [comment]
Should be fixed by #1957

**Comment by MiguelCompany** [comment]
Closing via #1957 and corresponding backports.

Feel free to reopen if still an issue.
