### ISSUE TITLE
Documentation links in readme.md broken

### ISSUE THREAD

**Issue by jwillemsen** [eProsima/Fast-DDS#1287]
Most of the links under https://github.com/eProsima/Fast-DDS#documentation are all broken, give a page doesn't exist

## Expected Behavior
Link to the documentation

## Current Behavior
Page doesn't exist error

## Steps to Reproduce
Go to https://github.com/eProsima/Fast-DDS#documentation and try all links in that section

**Comment by rsanchez15** [comment]
Thank you for the indication. The broken links you mention have been fixed in #1288 .

**Comment by EduPonz** [comment]
I  just merged #1288 . @jwillemsen , please close the issue if the fix is satisfactory.

**Comment by jwillemsen** [comment]
Thanks for the quick fix
