### ISSUE TITLE
several compiler warnings with clang+libcxx [8887]

### ISSUE THREAD

**Issue by dirk-thomas** [eProsima/Fast-DDS#1297]
See:
* https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/482/gcc/folder.1539294886/

  * `TypeObjectFactory.cpp:2076`:

    > loop variable 'a_param' of type 'const eprosima::fastrtps::types::AppliedAnnotationParameter' creates a copy from type 'const eprosima::fastrtps::types::AppliedAnnotationParameter' [-Wrange-loop-construct] for (const AppliedAnnotationParameter a_param : anno_params)

  * `TypeObjectFactory.cpp:2101`:

    > loop variable 'a_param' of type 'const eprosima::fastrtps::types::AppliedAnnotationParameter' creates a copy from type 'const eprosima::fastrtps::types::AppliedAnnotationParameter' [-Wrange-loop-construct] for (const AppliedAnnotationParameter a_param : anno_params)

* https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/482/gcc/folder.1941504058/

  * `sqlite3.c:107898`:

    > implicit conversion from 'long long' to 'double' changes value from 9223372036854775806 to 9223372036854775808 [-Wimplicit-int-float-conversion] if( n==0 && r>=0 && r

  * `sqlite3.c:107900`:

    > implicit conversion from 'long long' to 'double' changes value from 9223372036854775806 to 9223372036854775808 [-Wimplicit-int-float-conversion] }else if( n==0 && r<0 && (-r)

* https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/482/gcc/folder.236002918/

  * `SharedMemUUID.hpp:132`:

    > definition of implicit copy constructor for 'UUID<8>' is deprecated because it has a user-declared copy assignment operator [-Wdeprecated-copy] UUID& operator =(

* https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/482/gcc/folder.360225354/

  * `tree_iterator.hpp:73`:

    > definition of implicit copy assignment operator for 'tree_iterator, 0>::block_ctrl, boost::intrusive::rbtree_node_traits, true>, boost::intrusive::normal_link, boost::intrusive::dft_tag, 3>, false>' is deprecated because it has a user-declared copy constructor [-Wdeprecated-copy] BOOST_INTRUSIVE_FORCEINLINE tree_iterator(tree_iterator const& other)

    > definition of implicit copy assignment operator for 'tree_iterator, true>, boost::intrusive::dft_tag, boost::intrusive::safe_link, boost::intrusive::RbTreeBaseHookId>, char, unsigned int>, boost::intrusive::rbtree_node_traits, true>, boost::intrusive::safe_link, boost::intrusive::dft_tag, 3>, false>' is deprecated because it has a user-declared copy constructor [-Wdeprecated-copy] BOOST_INTRUSIVE_FORCEINLINE tree_iterator(tree_iterator const& other)

* https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/482/gcc/folder.-365770583/

  * `sp_counted_base_clang.hpp:27`:

    > '_Atomic' is a C11 extension [-Wc11-extensions] typedef _Atomic( boost::int_least32_t ) atomic_int_least32_t;

**Comment by MiguelCompany** [comment]
@dirk-thomas We're fixing these on [this branch](https://github.com/eProsima/Fast-DDS/tree/hotfix/clang-warnings/2.0.x)

Even though I've updated sqlite code to 3.32.3 (which solves the warning), if you are not using persistence functionality, you could build Fast DDS with `-DSQLITE3_SUPPORT=OFF` (reducing the time required to build it)

**Comment by dirk-thomas** [comment]
> We're fixing these on this branch

Great, let me know if you want the ROS 2 CI builds to run for that branch at some point.

> Even though I've updated sqlite code to 3.32.3 (which solves the warning), if you are not using persistence functionality, you could build Fast DDS with -DSQLITE3_SUPPORT=OFF (reducing the time required to build it)

ROS 2 builds Fast DDS (as any other package) without customized option. If the option is on by default that is what is being used. We can't make per package customizations.

**Comment by MiguelCompany** [comment]
@dirk-thomas 
> Great, let me know if you want the ROS 2 CI builds to run for that branch at some point.

PR #1304 ready. Please run ROS 2 CI.

**Comment by dirk-thomas** [comment]
Clang+libcxx builds to check for the compiler warnings:
* Before: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11516)](https://ci.ros2.org/job/ci_linux/11516/)
* After: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11517)](https://ci.ros2.org/job/ci_linux/11517/)

Common set of CI builds for all platforms since the PR seems to have several changes:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11527)](http://ci.ros2.org/job/ci_linux/11527/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6697)](http://ci.ros2.org/job/ci_linux-aarch64/6697/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=9431)](http://ci.ros2.org/job/ci_osx/9431/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=11448)](http://ci.ros2.org/job/ci_windows/11448/)
 * It looks like the branch introduces two deprecation warnings on Windows.

**Comment by MiguelCompany** [comment]
@dirk-thomas Windows warnings should have been solved by f582742ece6415ca64d653b7abfa124e4365c0a7

**Comment by dirk-thomas** [comment]
Clang+libcxx builds to check for the compiler warnings:
* After: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11573)](https://ci.ros2.org/job/ci_linux/11573/)

Common set of CI builds for all platforms since the PR seems to have several changes:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11572)](http://ci.ros2.org/job/ci_linux/11572/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=6721)](http://ci.ros2.org/job/ci_linux-aarch64/6721/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=9458)](http://ci.ros2.org/job/ci_osx/9458/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=11535)](http://ci.ros2.org/job/ci_windows/11535/)
  * (The failing test is unrelated.)

Looking good - thank you.

**Comment by MiguelCompany** [comment]
Closing this, as #1304 has been merged.
