### ISSUE TITLE
cross compiling for QNX -> CDR #define HAVE_CXX0X not set [8999]

### ISSUE THREAD

**Issue by amdsobhy** [eProsima/Fast-DDS#1308]
When cross compiling for QNX cdr builds fine and HAVE_CXX0X gets set, but when fastrtps starts to build it fails with the following error:

/home/asobhy/workspace/ros2_foxy/src/eProsima/Fast-DDS/src/cpp/dynamic-types/AnnotationParameterValue.cpp:1696:13:   required from here
/home/asobhy/workspace/ros2_foxy/install/x86_64/include/fastcdr/Cdr.h:429:32: error: 'const struct std::array<unsigned char, 4>' has no member named 'serialize'
                         type_t.serialize(*this);

conplains about the array template because in CDR.h  HAVE_CXX0X is not set and the array templates are not included for serialize and deserialize overloaded operator<< and operator>>

SOLUTION:
-replace in fartrtps in https://github.com/eProsima/Fast-DDS/blob/master/cmake/common/check_configuration.cmake, line 18 with the following:

if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_COMPILER_IS_CLANG OR
        CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR
        CMAKE_CXX_COMPILER_ID MATCHES "QCC")

FastRTPS:
commit 40568fa4784e846f95c461608d43a2b57eaef55b (HEAD -> 2.0.x, tag: v2.0.1, origin/2.0.x)

**Comment by MiguelCompany** [comment]
@amdsobhy Would you mind creating a pull request against 2.0.x branch with that change?

**Comment by asobhy-qnx** [comment]
will do that
