### ISSUE TITLE
Visual Studio 2017:  unresolved external symbol for eprosima::fastrtps::rtps::StringMatching::matchString

### ISSUE THREAD

**Issue by fabval** [eProsima/Fast-DDS#1310]
Installed in Windows 10 the binaries as explained in the installation manual.
Created a new solution in Visual Studio 2017 (I'll have to insert fastdds into an existing project and I need to provide an example for VS 2017).
Added files from HelloWorld examples and added include path and libs path into project settings.

## Expected Behavior
The build should complete with success

## Current Behavior
I get the following link error:
Error	LNK2019	unresolved external symbol __imp_PathMatchSpecA referenced in function "public: static bool __cdecl eprosima::fastrtps::rtps::StringMatching::matchString(char const *,char const *)"

## Steps to Reproduce

1. Create an empty Visual Studio Solution 2017 and add files from Hello World example
2. In Properties>Configuration>C/C++/General>Addictional Include Directories: add: "C:\Program Files\eProsima\fastrtps 2.0.0\include"
3. In Properties>Configuration>Linker/General>Addictional Library Directories add: $(FASTRTPSHOME)\lib\x64Win64VS2017
4. In Properties>Configuration>Linker/>input>Addictional Dependencies add 
libfastcdrd-1.0.lib
libfastrtpsd-2.0.lib
foonathan_memory-0.6.2-dbg.lib
libssl64MDd.lib
libcrypto64MDd.lib

## System information
Windows 10 x64
Visual Studio 2017
FastDds binaries downloaded on 24 July

**Comment by MiguelCompany** [comment]
@fabval You will also need libraries `Shlwapi` and `iphlpapi`.

**Comment by fabval** [comment]
Thanks MiguelCompany!

You solved the issue!

With:

- libfastcdrd-1.0.lib
- libfastrtpsd-2.0.lib
- foonathan_memory-0.6.2-dbg.lib
- libssl64MDd.lib
- libcrypto64MDd.lib
- tinyxml2d.lib
- shlwapi.lib
- iphlpapi.lib

it is working.
