### ISSUE TITLE
Question: Proper participant config to avoid firewall issues on Windows

### ISSUE THREAD

**Issue by alireza-hosseini** [eProsima/Fast-DDS#1315]
Hi,

We are using `FastRTPS version 1.10.0` in our product which shall be run both on Windows and Linux. On Linux we have no issues but on **Windows** even though the default transport layer is shared memory, it is still asking for firewall permissions for every new executable which uses Fast-RTPS inside. I read in your documentation that we have to add custom firewall rules to avoid such issues, but we prefer to don't expose this additional step to our customers and looking for a way to configure the FAST-RTPS in a way that it doesn't collide with a firewall at all (at least as long as all participants are in the same machine). 
Even in case of adding a custom firewall rule, is there any way to set a general rule covering all the executables that are using Fast-RTPS inside (regardless of their path)? Imagine that we have a dozen of test executables that for each of them we have to provide this firewall access manually. 

Would be great if you can give us some hint or resources to find a solution to this issue.

**Comment by MiguelCompany** [comment]
By default, both UDP and shared memory tramsports are enabled. If you are only using communications on the same host, you could follow the code shown on [the documentation](https://fast-dds.docs.eprosima.com/en/v1.10.0/advanced.html#shared-memory-transport-shm) to use shared memory exclusively

**Comment by alireza-hosseini** [comment]
Thanks, we applied this solution.
