### ISSUE TITLE
communication through other node's network [9135]

### ISSUE THREAD

**Issue by MaximeAubanel** [eProsima/Fast-DDS#1319]
Say I have 2 networks and their corresponding nodes inside:

Network_A:
- Node_1
- Node_2

Network_B:
- Node_2
- Node_3

Node_1 publish on /telemetry. How can Node_3 receive the messages on /telemetry from Node_1 WITHOUT having to republishing them manually from Node_2.

Is there a way to do this ?

**Comment by pavelpgt** [comment]
Hi Maxime,
You have to specify the IP address of the Node_3 in QoS of the Node_1. It is done through [InitialPeers](https://fast-dds.docs.eprosima.com/en/latest/fastdds/discovery/simple.html#initial-peers). 
You can do it in XML like this.
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
    <participant profile_name="initialPeers" is_default_profile="true">
        <rtps>
            <builtin>
                <initialPeersList>
                    <locator>
                        <udpv4>
                            <address>192.168.0.2</address>
                        </udpv4>
                    </locator>
                </initialPeersList>
            </builtin>
        </rtps>
    </participant>
</profiles>```
There is more to it. But this is a starting point. 
Give me an info, if it help.

**Comment by EduPonz** [comment]
Hi @MaximeAubanel ,

I'm not sure about what you mean by "other node's network". Do you mean different sub-nets, different LANs (meaning you're using WAN), or nodes running on different domains?

I take you're using Fast DDS via ROS 2. If that is the case, knowing which version of ROS 2 you're using would be helpful to know your Fast DDS' version and give you better advice. In the meantime, I'm posting some links from our documentation that might help your case. Beware that there are different approaches depending on the nature of your set-up.

* https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/tcp/tcp.html#wan-or-internet-communication-over-tcpv4
* https://fast-dds.docs.eprosima.com/en/latest/fastdds/discovery/discovery.html#
* https://fast-dds.docs.eprosima.com/en/latest/fastdds/env_vars/env_vars.html
* https://fast-dds.docs.eprosima.com/en/latest/fastdds/use_cases/well_known_deployments/well_known_deployments.html#well-known-deployments
* https://fast-dds.docs.eprosima.com/en/latest/fastdds/use_cases/wifi/wifi.html
* https://fast-dds.docs.eprosima.com/en/latest/fastdds/use_cases/ros2/ros2.html

**Comment by MaximeAubanel** [comment]
Hello @EduPonz ,

I'm indeed using ROS2, foxy release.

To be short, here is a quick example of my problem:

- Node_1 is in Network_Cloud and Network_Radio.
- Node_2 is in Network_Cloud and Network_Radio.

Network_Cloud is reached through 4G.
Network_Radio is reached through IP_Radio.

Now imagine that for some reason, Node_1 loose connection for an extended period of time to Network_Cloud **only**.

How can Node_1 still reach Network_Cloud through Network_Radio (i.e Node_2) ?

> Note: Ideally we don't want to specify IP, we must use the discovery system.

**Comment by EduPonz** [comment]
Hi @MaximeAubanel ,

Please correct me if I'm wrong. From what I gather, I understand that you have three machines and two networks arranged in the following manner:

* Network_Cloud: 4G
    * Node_1
    * Node_2

* Network_Radio: IP_Radio (does this mean WiFi?)
    * Node_2
    * Node_3

I take that you can access one network from the other (i.e. you can ping one Node_1 from Node_3 and viceversa). What you want is to publish on a topic in Node_1 and subscribe in Node_3 without relaying the messages using Node_2, is that correct?

If that is the case, you could do it using three different approaches:

1. **Initial peers**: Configure Node_1 as an initial peer of Node_3 and viceversa. This is what @pavelpgt suggested. To do that take a look [here](https://fast-dds.docs.eprosima.com/en/latest/fastdds/discovery/simple.html#initial-peers), [here](https://fast-dds.docs.eprosima.com/en/v2.0.0/fastdds/use_cases/wifi/initial_peers.html), and [here](https://fast-dds.docs.eprosima.com/en/v2.0.0/fastdds/use_cases/ros2/ros2.html).
1. **Discovery Server**: You could configure Node_2 as a discovery Server and Node_1 and Node_3 as Clients. This can be done using [XML](https://fast-dds.docs.eprosima.com/en/latest/fastdds/discovery/server_client.html#), or an [environment variable](https://fast-dds.docs.eprosima.com/en/v2.0.0/fastdds/env_vars/env_vars.html).
1. **Adjust Multicast TTL**: If the networks are reachable from each other, you can configure the Time To Live (TTL) of UDP packets (in number of hops). For this, you'd need to create transport descriptor either by [code](https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/udp/udp.html) or [XML](https://fast-dds.docs.eprosima.com/en/v2.0.0/fastdds/xml_configuration/transports.html). The default value of TTL is 1 hop, but if you adjust this correcly, your packets should be able to reach the other network. This approach does not entail address configuration of any kind.

I hope that helps!

**Comment by MaximeAubanel** [comment]
Hi @EduPonz and thanks for your fast reply !

IP_Radio:
> IP_Radio are radios that link themselves through some kind of long range WIFI special frequency. Once connected they form a wireless network.
> Once the IP_Radios pairing is done you can plug your device via Ethernet to an IP_Radio and you'll be on the network and have an IP. If another device is connected to the other linked IP_Radio then you'll also have an IP and the devices will be able to ping each other.

--

As of now I haven't done anything to configure networking between Network_Cloud and Network_Radio on Node_2. Therefore, I cannot ping Node_3 from Node_1.
I thought that I could directly make Node_2 act as a relay without having to configure its network. I though it could take packet coming from Network_Cloud and bridge them over to Network_Radio. And vice-versa. But if I understand it well, this is not doable.

Therefore, I need to be able to ping a device (Node_3) on a network (Network_Radio) from another device (Node_1) on another network (Network_Cloud) through a device (Node_2) connected to both networks. Is that what you meant by **can access one network from the other** if so I have no idea on how to do that so I will look into it.  _If you have some good links/recommandations on how to do that it would be really appreciated._

**Comment by MaximeAubanel** [comment]
Ok, I've had a look at it.

Problem is that with that solution I need to configure networking on Node_2's devices. IPs have to be set one way or another wether it be from the XML file or from the device's networking configuration and I want to avoid doing that.

What I would need is some kind of relay that wouldn't require any kind of IP configuration.

I hope it does make sense to you.

**Comment by EduPonz** [comment]
Hi @MaximeAubanel ,

I'm afraid that with the current implementation, Fast DDS is not able to automatically forward packets to other peers, nor is this option contemplated in the DDS standard. This is because the middleware should not decide which packets need to be forwarded and where should they go, since that, among other things, could raise security concerns. From our point of view, this type of behaviour belongs more to the application layer, where you could use the callbacks on Node_2 listener to resend the packets to their final destination.

If you finally decide to go in that direction, we have some support options you might be interested in. You can contact the sales department in evaluation.support@eprosima.com

**Comment by MaximeAubanel** [comment]
Okay thank you very much for your time and answers.

**Last question:** Is Fast DDS able to resend the exact same packet received ? Like the **exact same**. Not just the data itself. Every a packet is consisting of. Is there any documentation on that ?

**Comment by EduPonz** [comment]
Hi @MaximeAubanel ,

Don't worry about asking questions, we're all about helping each other!

Fast DDS is not able to resend the same exact packet, as it does not resend anything. Unfortunately, you cannot retrieved the the full received packet, as they are broken down and processed internally by the [RTPS layer](https://fast-rtps.docs.eprosima.com/en/latest/fastdds/rtps_layer/rtps_layer.html). You could in principle retrieve the full packet as a "user" of the [Transport layer](https://fast-rtps.docs.eprosima.com/en/latest/fastdds/transport/transport.html). Mind that this layer is not accesible from the [DDS layer](https://fast-rtps.docs.eprosima.com/en/latest/fastdds/dds_layer/dds_layer.html), which means you would need to interact with the Transport layer directly.

This approach would let you build your own "relay transport", although at that point it is probably way less work to try out on of the other approaches I suggested before.

I hope I've clarified something for you. In any case, feel free to ask more questions.

**Comment by MaximeAubanel** [comment]
Hello @EduPonz,

Thanks for your helpful answer !

So, I eventually gave up on transporting the exact same packet through another node.

Instead, I set up my Node_1, Node_2 and Node_3 in order for Node_1 and Node_3 to ping each other.
Once that was done, I used the InitialPeers method and it worked. Thank for that @pavelpgt & @EduPonz !

However, now I have a new question. 
Let's say that Node_1 has 2 ways to reach Node_3 (and vice-versa). One directly (they are on the same VPN) and the other one via Node_2. Is there a way to pass the data to those 2 ways simultaneously ?

**Comment by EduPonz** [comment]
Hi @MaximeAubanel ,

By default, every `DataWriter` sends the packets to every matched `DataReader` using every available network interface in the machine, meaning that if a machine has let's say a WiFi and Ethernet interfaces on the same networks, the `DataWriter` would try to reach the `DataReaders` through both interfaces (unless both `DataWriter` and `DataReader` are in the same machine, case in which localhost is used).

Furthermore, it is possible to define "interfaces affinity" by the means of an [interface whitelist](https://fast-rtps.docs.eprosima.com/en/latest/fastdds/transport/whitelist.html). This list specifies the interfaces that a given `DomainParticipant`, and therefore all its entities, is allowed (and forced) to use. The interface whitelist is part of the `TransportDescriptor` class.

I hope that clarifies your question as I understood it, else feel free to ask again!
