### ISSUE TITLE
[9070] MSVC min/max macro collision with numeric_limits

### ISSUE THREAD

**Issue by fabval** [eProsima/Fast-DDS#1322]
When fastDds libraries are used inside a Windows project which includes windows.h and/or winsock2.h we fall into the error described here [min max macro](https://stackoverflow.com/questions/6884093/warning-c4003-not-enough-actual-parameters-for-macro-max-visual-studio-2010 ).

All the occurences of min and max are subjected to macro expansion, therefore std::limits or BitmapRange::max() are not recognized anymore.

I'm trying to use fastDDS in an existing project and what is usually suggested (setting NOMINMAX) breaks the exisiting code.

## Expected Behavior
Adding fastDDS to an existing project which includes windows.h and/or winsock2.h should not break the build.

## Current Behavior
We get the following errors and warnings:

c:\program files\eprosima\fastrtps 2.0.0\include\fastrtps\utils\fixed_size_bitmap.hpp(164): warning C4003: not enough arguments for function-like macro invocation 'max'
c:\program files\eprosima\fastrtps 2.0.0\include\fastrtps\utils\fixed_size_bitmap.hpp(174): warning C4003: not enough arguments for function-like macro invocation 'min'
c:\program files\eprosima\fastrtps 2.0.0\include\fastrtps\utils\fixed_size_bitmap.hpp(326): warning C4003: not enough arguments for function-like macro invocation 'max'
c:\program files\eprosima\fastrtps 2.0.0\include\fastrtps\utils\fixed_size_bitmap.hpp(164): error C2059: syntax error: ')'
c:\program files\eprosima\fastrtps 2.0.0\include\fastrtps\utils\fixed_size_bitmap.hpp(555): note: see reference to class template instantiation 'eprosima::fastrtps::BitmapRange<T,Diff,NBITS>' being compiled
c:\program files\eprosima\fastrtps 2.0.0\include\fastrtps\utils\fixed_size_bitmap.hpp(164): error C2334: unexpected token(s) preceding ':'; skipping apparent function body
c:\program files\eprosima\fastrtps 2.0.0\include\fastrtps\utils\fixed_size_bitmap.hpp(555): error C2143: syntax error: missing ')' before ';'
c:\program files\eprosima\fastrtps 2.0.0\include\fastrtps\utils\fixed_size_bitmap.hpp(555): error C2059: syntax error: ')'
c:\program files\eprosima\fastrtps 2.0.0\include\fastrtps\utils\fixed_size_bitmap.hpp(555): error C2238: unexpected token(s) preceding ';'
c:\program files\eprosima\fastrtps 2.0.0\include\fastrtps\utils\fixed_size_bitmap.hpp(555): fatal error C1201: unable to continue after syntax error in class template definition

## Steps to Reproduce

1. Open fastDDS HelloWorld example
2. in the first line of the main put the following: #include <windows.h>
3. build
4. you the get errors described above

If you insert in the Visual Studio preprocessor macro "NOMINMAX" or put before the include the following lines
#ifndef NOMINMAX
#define NOMINMAX
 #endif
#include <windows.h>

everything works but it isn't applicabile in an existing application

## System information
Windows 10 x64
Visual Studio 2017
FastDds binaries downloaded on 24 July

**Comment by jwillemsen** [comment]
Another solution is to add parenthesis around the min/max usage

**Comment by fabval** [comment]
> Another solution is to add parenthesis around the min/max usage

Yes, it is correct but the compiler complains on the definiton of methods max e min of BitmapRange, which are used in other places of fastDds libraries. In that case the definitions should be changed too, it is not just a matter of method invocation.

I could modify my version of the libraries but it would be only a temporary fix and a problem for future maintenance.

**Comment by MiguelBarro** [comment]
[Here](https://github.com/MiguelBarro/MFClock) is an example of how to use Fast-DDS in a windows environment like an MFC application. Basically we include the required Fast-DDS headers at the end of the `stdafx.h` file and `#undef` the **min** and **max** macros before our includes.
If for whatever reason the **min-max** macros are required on the sources we can profit from the `#pragma pop_macro` and `#pragma push_macro`, for example:

```c++
#pragma push_macro("max")
#pragma push_macro("min")
#undef max
#undef min

// fastrts dependencies
#include <fastrtps/Domain.h>
#include <fastrtps/publisher/Publisher.h>
#include <fastrtps/subscriber/Subscriber.h>
#include <fastrtps/subscriber/SampleInfo.h>

#pragma pop_macro("max")
#pragma pop_macro("min")
```

**Comment by EduPonz** [comment]
I'm closing this for now, as the answer since to have been satisfactory. If there are further inquiries, please reopen.
