### ISSUE TITLE
Error log messages not visible with latest development ROS2 build

### ISSUE THREAD

**Issue by anamud** [eProsima/Fast-DDS#1328]
Hi,

I want to enable log messages from Fast-DDS included in the latest development source of ROS2.

I read Fast-DDS documentation and understood that the default verbosity is of type Log::Kind::Error and the default consumer is STDOUT. So to test if error messages are logged out to the console, I added two dummy error messages in `eProsima/Fast-DDS/src/cpp/fastdds/publisher/Publisher.cpp` as shown below and built ROS2 successfully.

```
Publisher::Publisher(
        PublisherImpl* p,
        const StatusMask& mask)
    : DomainEntity(mask)
    , impl_(p)
{
    logError(PUBLISHER, "Publisher created");
}

Publisher::Publisher(
        DomainParticipant* dp,
        const PublisherQos& qos,
        PublisherListener* listener,
        const StatusMask& mask)
    : DomainEntity(mask)
    , impl_(dp->create_publisher(qos, listener, mask)->impl_)
{
    logError(PUBLISHER, "Publisher created");
}
```

Next I built and ran a simple C++ ROS2 application with a publisher. I ensured that it is publishing messages successfully.

Surprisingly, the dummy error messages in the Publisher class constructors are not logged out to the console. It could be that these code paths are not encountered and I am naive in thinking that a ROS2 application with a publisher will encounter the constructors in the Publisher class. Another possibility is that I am missing some logging-enabling configuration. 

I tried placing an XML profile file `DEFAULT_FASTRTPS_PROFILES.xml` (see below) in the execution path of the ROS2 application. The file `execution.log` was created but empty. The  expected dummy error messages were not seen on the console.

```
<?xml version="1.0" encoding="UTF-8" ?>
<dds>
    <log>
        <!--
        Clear consumers
        -->
        <use_default>FALSE</use_default>

        <!--
        StdoutConsumer does not have any properties
        -->
        <consumer>
            <class>StdoutConsumer</class>
        </consumer>

        <!--
        FileConsumer openning "execution.log" in append mode
        -->
        <consumer>
            <class>FileConsumer</class>
            <property>
                <name>filename</name>
                <value>execution.log</value>
            </property>
            <property>
                <name>append</name>
                <value>TRUE</value>
            </property>
        </consumer>
    </log>
</dds>
```

Where am I going wrong? Please help.

**Comment by EduPonz** [comment]
Hi @anamud ,

I'm afraid that, as you suspected, that that code does not run when using Fast DDS from ROS 2. The constructors you are looking for are the ones in `eProsima/Fast-DDS/src/cpp/fastrtps_deprecated/publisher/Publisher.cpp`. This is because  `rmw_fastrtps` is still using the now deprecated Fast DDS Pub/Sub API. In the very near future, we plan to update that package to use our DDS compliant API (that's where your logs were), so stay tuned!

**Comment by anamud** [comment]
Thanks for a helpful response! I am now able to see log messages from the deprecated API.
