### ISSUE TITLE
Profile selection for specific ROS2 nodes [9134]

### ISSUE THREAD

**Issue by anamud** [eProsima/Fast-DDS#1336]
Hi, 

I understood from docs chapter 13.6 that all nodes in a ROS2 application can be applied a single participant profile by setting the `is_default_profile` attribute to `true`.

However I would like to apply profiles to ROS2 nodes (participants) selectively. See an example below where different participant profiles are selected for nodes with identifiers `n1` and `n2`.  Assume that these identifiers are known to the ROS2 user.

```
<?xml version="1.0" encoding="UTF-8" ?>
<profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
    <transport_descriptors>
        <transport_descriptor>
            <transport_id>udp_transport_n1</transport_id>
            <type>UDPv4</type>
            <sendBufferSize>9216</sendBufferSize>
            <receiveBufferSize>9216</receiveBufferSize>
            <non_blocking_send>true</non_blocking_send>
        </transport_descriptor>
    </transport_descriptors>

     <transport_descriptors>
        <transport_descriptor>
            <transport_id>udp_transport_n2</transport_id>
            <type>UDPv4</type>
            <non_blocking_send>false</non_blocking_send>
        </transport_descriptor>
    </transport_descriptors>

    <participant profile_name="n1" id="n1">
        <rtps>
            <userTransports>
                <transport_id>udp_transport_n1</transport_id>
            </userTransports>
            <useBuiltinTransports>false</useBuiltinTransports>
        </rtps>
    </participant>

    <participant profile_name="n2" id="n2">
        <rtps>
            <userTransports>
                <transport_id>udp_transport_n2</transport_id>
            </userTransports>
            <useBuiltinTransports>false</useBuiltinTransports>
        </rtps>
    </participant>
</profiles>
```

Is it possible to perform such selecting profile assignment using existing features of Fast DDS?

**Comment by jparisu** [comment]
This behaviour was supported until ROS2-Eloquent, as the Fast-DDS docs 13.6 said.

Unfortunately, this design has changed with the relase of ROS2-Foxy.
In this new design, the participant is part of the context, and new participants are not created anymore with new nodes.
Hence, the way to set the participant QoS (attributes) is by modifying the profile file by default (env variable FASTRTPS_DEFAULT_PROFILES_FILE) and setting the attribute 'is_default_profile="true"' for the profile you want to use. But this attempt would use this same profile for all new nodes created by this process.

The only way to use different QoS in various nodes is by executing ROS2 in different processes and each of them referencing a different profile file, where the default profile for the participant could be modified.

Please, feel free to reopen the issue in case you have further doubts.
