### ISSUE TITLE
How to get domain topic list?

### ISSUE THREAD

**Issue by reza-ebrahimi** [eProsima/Fast-DDS#1341]
How to get a domain topic list?

**Comment by rsanchez15** [comment]
There is a `DomainParticipant` member function (currently not implemented in Fast DDS) called `get_discovered_topics` that retrieves a list of all the topics that the `DomainParticipant` discovers in the domain. 
This will be implemented in future versions of Fast DDS.

**Comment by reza-ebrahimi** [comment]
Is there any updates here?

**Comment by sven1904** [comment]
more than 4 years later and still no support.
seems to be a far future version of fast dds...

as an alternative (workaround):
how does fastdds_monitor discover the participants/topics within a domain?
