### ISSUE TITLE
Equivalent to idl module keyword in Dynamic Data Types 

### ISSUE THREAD

**Issue by mdnasr** [eProsima/Fast-DDS#1342]
FastDDS generator support `module` keyword in IDL. The generated code is wrapped in C++ namespace. Are there any way to do the same thing using Dynamic Data Types?

## Steps to Reproduce

To clarify, Most ROS IDL use `module` keyword in their IDL

```
module sensor_msgs {
  module msg {
    struct Image {
      uint32 height;
      uint32 width;
    };
  };
};
```

Topic data type of such IDL will be `sensor_msgs::msg::Image` using `myType.getName();`
I want to create equivalent type to this using Dynamic Data Types in C++ or XML, but I couldn't find any API to replicate `module` keyword.

## System information

- Fast-RTPS version: 1.10.x
- OS: Ubuntu 16.04

**Comment by LuisGP** [comment]
Hi @mdnasr,

The `module` concept isn't part of the standard and we haven't implemented it.
You can define the Dynamic Type name to something similar in a C way in its builder: `sensor_msgs__msg__Image`.

What is your use case?

Best regards.

**Comment by EduPonz** [comment]
I'm closing this issue as the question has been solved. Please feel free to comment or reopen at any time.
