### ISSUE TITLE
vs2015 link error [9127]

### ISSUE THREAD

**Issue by senlinli** [eProsima/Fast-DDS#1344]
os:winodws 7 x64
compiler:vs2015 update3

fatal error LNK1120: unresolved externals symbol fastdds::dds::DataReader::get_topicdescription

**Comment by EduPonz** [comment]
Hi @senlinli ,

As you can see in #1347 , `fastdds::dds::DataReader::get_topicdescription` was not being exported, which will cause your linking error when compiling with Visual Studio. It'd be very nice if you could give it a try. The fix will make its way to master soon.
