### ISSUE TITLE
Publish/subscribe padding message payload to be a multiple of 4 [9199]

### ISSUE THREAD

**Issue by lbrunet1982** [eProsima/Fast-DDS#1363]
Hi, I have created a custom data type by by creating a class that overrides TopicDataType and have implemented my own serialization mechanism.  When I send a message of a certain size, the received message is always padded to be a multiple of 4.  For instance, if I publish 6 bytes, I receive 8 (padded with zeroes for the last two bytes).  Is this normal?  I couldn't find reference to it in the documentation.  Is there a way to determine the actual received message length without adding it to the encoding scheme?

Thanks!

**Comment by IkerLuengo** [comment]
Hi, @lbrunet1982,

According to [RTPS specification v2.3](https://www.omg.org/spec/DDSI-RTPS/2.3/PDF), section 9.4.1- Overall Structure:

> The PSM aligns each Submessage on a 32-bit boundary with respect to the start of the Message.

i.e., if a submessage (in this case, `SerializedPayload`) does not end on a 4-byte boundary, it has to be padded to 4-byte for the next submessage to be correctly aligned.

Additionally, the `submessageLength` is defined as the length from the start of the submessage contents to the start of the next submessage (or the end of the message if this is the last submessage). Therefore, the submessage length has to include any padding that has been added.

There is no way of knowing the actual size of the serialized payload minus the padding on the subscriber. Nevertheless, the padding should be irrelevant to the deserialization of the data. Usually serialization and deserialization on the `TopicDataType` is done in such a way that it does not relay in the size of the serialized payload provided by the submessage (at least not beyond some sanity checks like asserting we are not reading data beyond the provided size). e.g., writing the number of elements of variable length collections or the length of strings before the collection/string data itself. In this case, the deserialization can just ignore any padding bytes that have been added.

Please, feel free to reopen if you need some more information regarding this issue.

**Comment by briansoe66** [comment]
@IkerLuengo, in which version of fast-dds was this change made? Or can you tell me where the code is, so I can lookup the git history?

I am interested in protobuf serialization, which requires the number of serialized bytes before padding.

**Comment by EduPonz** [comment]
Hi @briansoe66 ,

There is not associated change, as the answer was more an explanation of what it's normally done. I guess you could use [Fast-DDS-Gen](https://github.com/eProsima/Fast-DDS-gen) to generate some type support (which inherits from `TopicDataType`) and check the code generated there.
