### ISSUE TITLE
State of SHM transport on Windows [9275]

### ISSUE THREAD

**Issue by danrauch** [eProsima/Fast-DDS#1376]
Hi,

is there any public discussion regarding the state of SHM transport on Windows? I searched around but couldn't find any info.
It was deactivated as default in 2.0 some time ago due to some issues - are there any plans to reactivate it?

Thanks!
Daniel

**Comment by MiguelCompany** [comment]
Hi @danrauch 

Reactivating SHM transport as default is something we plan to do really soon (both on master and 2.0.x branch), as most of the issues have been fixed (on #1248 and #1250 and their corresponding backports), so please stay tuned!

**Comment by danrauch** [comment]
Hi Miguel,

that's great news - thanks for the quick reply!

**Comment by MiguelCompany** [comment]
@danrauch Be informed that SHM transport is enabled by default, both on master and 2.0.x.

We will soon release v2.0.2 and v2.1.0, with SHM transport activated by default

**Comment by danrauch** [comment]
Thanks for the info - my question is therefore answered.
