### ISSUE TITLE
`ros2 topic info -v` prints wrong data [9293]

### ISSUE THREAD

**Issue by iuhilnehc-ynos** [eProsima/Fast-DDS#1380]
This bug report originated from https://github.com/ros2/ros2cli/issues/525.

`ros2 topic info -v` prints wrong Nodename, Namespace and QoS profile from ros2 daemon,
NOTE: It seems that `ros2 daemon with rmw_fastrtps_cpp` does not set correct data after receiving data(w) from `a node with rmw_cyclonedds_cpp` because some message ids are optimized in CycloneDDS that not be sent (such as, `PID_DURABILITY` is a default value of `VOLATILE`, `PID_PARTICIPANT_GUID` is sent in data(p) before )

## Expected Behavior

- Node name is `_ros2cli_{pid}`, not `_CREATED_BY_BARE_DDS_APP_`
- Namespace is `/`, not `_CREATED_BY_BARE_DDS_APP_`
- Durability is `RMW_QOS_POLICY_DURABILITY_VOLATILE` (run ros2 with durability(`volatile`) )

such as,
```
Type: std_msgs/msg/String

Publisher count: 1

Node name: _ros2cli_3789
Node namespace: /
Topic type: std_msgs/msg/String
Endpoint type: PUBLISHER
GID: a2.71.10.01.63.3e.45.12.06.a7.78.19.00.00.08.03.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RMW_QOS_POLICY_RELIABILITY_BEST_EFFORT
  Durability: RMW_QOS_POLICY_DURABILITY_VOLATILE
  Lifespan: 9223372036854775807 nanoseconds
  Deadline: 9223372036854775807 nanoseconds
  Liveliness: RMW_QOS_POLICY_LIVELINESS_AUTOMATIC
  Liveliness lease duration: 9223372036854775807 nanoseconds

Subscription count: 0

```

## Current Behavior

```
Type: std_msgs/msg/String

Publisher count: 1

Node name: _CREATED_BY_BARE_DDS_APP_
Node namespace: _CREATED_BY_BARE_DDS_APP_
Topic type: std_msgs/msg/String
Endpoint type: PUBLISHER
GID: a2.71.10.01.63.3e.45.12.06.a7.78.19.00.00.08.03.00.00.00.00.00.00.00.00
QoS profile:
  Reliability: RMW_QOS_POLICY_RELIABILITY_BEST_EFFORT
  Durability: RMW_QOS_POLICY_DURABILITY_TRANSIENT_LOCAL
  Lifespan: 2147483651294967295 nanoseconds
  Deadline: 2147483651294967295 nanoseconds
  Liveliness: RMW_QOS_POLICY_LIVELINESS_AUTOMATIC
  Liveliness lease duration: 2147483651294967295 nanoseconds

Subscription count: 0
```

## Steps to Reproduce

1. run on terminal A
```
$ export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
$ ros2 topic pub /talker1234 --qos-durability volatile  std_msgs/String "data: Hello World volatile" > /dev/null
```
2. run on terminal B
```
$ ros2 daemon stop
$ export RMW_IMPLEMENTATION=rmw_fastrtps_cpp

$ ros2 topic info -v /talker1234
```

## System information

- Fast-RTPS version: 3dcd9ab13c5f7158a8ee460a55ef37d229d5ba08
- OS: Ubuntu 20.04
- Network interfaces: eth0 (192.168.0.61), lo (127.0.0.1)
- ROS2: Foxy

## Additional resources
- Wireshark capture 
package data from CycloneDDS(vendor: 1.16) without `PID_DURABILITY` and `PID_PARTICIPANT_GUID`
![image](https://user-images.githubusercontent.com/64191023/92686117-9c722d00-f36b-11ea-9a97-cdd51eed1b4b.png)

**Comment by MiguelCompany** [comment]
@iuhilnehc-ynos I saw ros2/ros2cli#525 yesterday, and spent some time looking at the code.

Regarding parsing a WriterProxyData object when PID_DURABILITY is not present, I don't think your analysis is correct. Before parsing the CDR data, the object is reset calling it's `clear` method, which will in turn call `m_qos.clear()`, which will call `m_durability.clear()`, which has the following code

https://github.com/eProsima/Fast-DDS/blob/40568fa4784e846f95c461608d43a2b57eaef55b/include/fastdds/dds/core/policy/QosPolicies.hpp#L271-L275

The default constructor of `DurabilityQosPolicy` sets the kind to `VOLATILE` so it should have the correct behavior.

I agree with the part of PID_PARTICIPANT_GUID. I think it should be ignored and be filled up when parsing PID_ENDPOINT_GUID.

**Comment by iuhilnehc-ynos** [comment]
> Before parsing the CDR data, the object is reset calling it's clear method

I didn't check that much before, so we need to continue to find which object and where sets the m_qos.
Actually, I just quickly updated the following source code from
```
WriterQos::WriterQos()
{
    this->m_reliability.kind = RELIABLE_RELIABILITY_QOS;
    this->m_durability.kind = TRANSIENT_LOCAL_DURABILITY_QOS;
}
```
to
```
WriterQos::WriterQos()
{
    this->m_reliability.kind = RELIABLE_RELIABILITY_QOS;
    this->m_durability.kind = VOLATILE_DURABILITY_QOS;
}
```
And then it's working.

**Comment by MiguelCompany** [comment]
@iuhilnehc-ynos I just created #1382 to solve the part related to `PID_PARTICIPANT_GUID`. Tomorrow I will work on the durability issue.

**Comment by iuhilnehc-ynos** [comment]
@MiguelCompany 

```cpp
void WriterQos::clear() {
    m_durability.clear();
    ...
    m_reliability.kind = RELIABLE_RELIABILITY_QOS;
    m_durability.kind = TRANSIENT_LOCAL_DURABILITY_QOS;
}

```

I think it's the problem.

**Comment by iuhilnehc-ynos** [comment]
> I just created #1382 to solve the part related to PID_PARTICIPANT_GUID.

Thank you, I should not combine two problems into one issue.

**Comment by iuhilnehc-ynos** [comment]
There is a tricky code.
```
p.guid.entityId = c_EntityId_RTPSParticipant;
```
After checking with `ros2 topic info -v`, it seems good.

**Comment by fujitatomoya** [comment]
@iuhilnehc-ynos @MiguelCompany 

Just FYI,

> Node name is _ros2cli_{pid}, not _CREATED_BY_BARE_DDS_APP_
> Namespace is /, not _CREATED_BY_BARE_DDS_APP_

i confirmed that above problems are fixed with https://github.com/eProsima/Fast-DDS/pull/1382. (using https://github.com/ros2/ros2/commit/91d8a43ed28edbe04f4ea361c493b19758e35877)

**Comment by fujitatomoya** [comment]
@iuhilnehc-ynos 

i was just catching up with you, but https://github.com/eProsima/Fast-DDS/issues/1380#issuecomment-690340738 makes sense to me.

**Comment by iuhilnehc-ynos** [comment]
@fujitatomoya 

> but #1380 (comment) makes sense to me.

Besides that, we need to care this https://github.com/eProsima/Fast-DDS/issues/1380#issuecomment-690345951 .

WriterQos

- constructor 

   m_durability.kind = TRANSIENT_LOCAL_DURABILITY_QOS

- clean
    m_durability.clear();     //  m_durability will be VOLATILE
    ...
    m_durability.kind = TRANSIENT_LOCAL_DURABILITY_QOS;        // set `TRANSIENT_LOCAL` again

**Comment by iuhilnehc-ynos** [comment]
> i confirmed that above problems are fixed with #1382. (using ros2/ros2@91d8a43)

Actually, I don't like this kind of fix.

**Comment by fujitatomoya** [comment]
> Actually, I don't like this kind of fix.

maybe you could share your thought then? https://github.com/eProsima/Fast-DDS/pull/1382 is still open!

**Comment by iuhilnehc-ynos** [comment]
IMO, m_guid of `ParticipantProxyData` should be used for m_RTPSParticipantKey in `WriterProxyData` as default value, and processing the PID_PARTICIPANT_GUID in `WriterProxyData` should be kept.

```
class ParticipantProxyData;          // Currently, WriterProxyData does not use ParticipantProxyData.

/**
 **@ingroup BUILTIN_MODULE
 */
class WriterProxyData
```

To make use of `PID_ENDPOINT_GUID` to set `m_RTPSParticipantKey` in `WriterProxyData` seems a little strange.

**Comment by MiguelCompany** [comment]
> To make use of `PID_ENDPOINT_GUID` to set `m_RTPSParticipantKey` in `WriterProxyData` seems a little strange.

@iuhilnehc-ynos I think you are right, please see the new solution on #1382 and my explanation on https://github.com/eProsima/Fast-DDS/pull/1382#issuecomment-690937266

**Comment by iuhilnehc-ynos** [comment]
@MiguelCompany 

Use guidPrefix is also good.
![image](https://user-images.githubusercontent.com/64191023/92897569-e59bad00-f44f-11ea-97e9-173a46e66bf6.png)

But actually I really like t use ParticipantProxyData because I have no idea if there will be some extra message which WriterProxyData/ReaderProxyData will need.

**Comment by MiguelCompany** [comment]
@iuhilnehc-ynos We are not talking about the better approach, but the one mentioned in the standard. And what the standard says is that `participant_key` is sent using `PID_PARTICIPANT_GUID`

**Comment by iuhilnehc-ynos** [comment]
> what the standard says is that participant_key is sent using PID_PARTICIPANT_GUID

If so, we should use ParticipantProxyData, because the `PID_PARTICIPANT_GUID` data is only sent in data(p), not data(w) on CycloneDDS. we use `guidPrefix` which is not `PID_PARTICIPANT_GUID` to set `participant_key` in data(w), is it fit the standard?

**Comment by MiguelCompany** [comment]
> because the `PID_PARTICIPANT_GUID` data is only sent in data(p), not data(w) on CycloneDDS

But the standard is saying that for `PublicationBuiltinTopicData` (i.e. data(w)), `PID_PARTICIPANT_GUID` should be sent with the content of `participant_key`

**Comment by iuhilnehc-ynos** [comment]
Sorry, I am not familiar with the source code, maybe there are some limitations.
Please do what you want.

**Comment by fujitatomoya** [comment]
@MiguelCompany 

with https://github.com/eProsima/Fast-DDS/pull/1384, confirm that fixes `Durability` problem. thanks!

**Comment by iuhilnehc-ynos** [comment]
@MiguelCompany 

Thank you. After applying https://github.com/eProsima/Fast-DDS/pull/1384 on the latest branch (2.0.x with c1c29b2a5d4d40446603fd19a235012d56a47aa0), I confirmed that these issues are fixed.

**Comment by fujitatomoya** [comment]
@iuhilnehc-ynos 

i think that you can close this now.

**Comment by iuhilnehc-ynos** [comment]
Thanks for the fix, close it.
