### ISSUE TITLE
Fast-DDS 2.0.x not building on Windows

### ISSUE THREAD

**Issue by hidmic** [eProsima/Fast-DDS#1385]
## Expected Behavior
Fast-DDS 2.0.x build on Windows 10 with:

```
LINK : fatal error LNK1104: cannot open file '$<$<BOOL:debug.obj'
```

See https://ci.ros2.org/view/nightly/job/nightly_win_rel/1688/console#console-section-41 for an instance of this.

## Current Behavior
Fast-DDS 2.0.x fails to build on Windows 10.

## Steps to Reproduce

1. Attempt to build Fast-DDS 2.0.x on Windows 10

## System information

- Fast-DDS version: [2.0.x](https://github.com/eProsima/Fast-DDS/tree/2.0.x)
- OS: Windows 10
- ROS2: [master](https://github.com/ros2/ros2)

## Additional context
The regression was probably introduced by https://github.com/eProsima/Fast-DDS/pull/1267, likely [here](https://github.com/eProsima/Fast-DDS/pull/1267/files#diff-4ca778ba70260365e2be4dad226754ebR401).

**Comment by MiguelCompany** [comment]
@hidmic @sloretz as this has been fixed on #1386 I think this can be closed, and ros2/ros2#1027 can be reverted
