### ISSUE TITLE
Remove ASIO_STANDALONE compile definition from CMakeLists [9824]

### ISSUE THREAD

**Issue by pablorcum** [eProsima/Fast-DDS#1395]
## Expected Behavior
Using compile definition `ASIO_ENABLE_BOOST` should extend the package asio with some Boost functionality according to `asio\asio\include\asio\detail\config.hpp`.

If no ASIO define is set by the user, `asio\asio\include\asio\detail\config.hpp` will define `ASIO_STANDALONE` by default as shown below.
```
#if !defined(ASIO_STANDALONE)
# if !defined(ASIO_ENABLE_BOOST)
#  if (__cplusplus >= 201103)
#   define ASIO_STANDALONE 1
#  elif defined(_MSC_VER) && defined(_MSVC_LANG)
#   if (_MSC_VER >= 1900) && (_MSVC_LANG >= 201103)
#    define ASIO_STANDALONE 1
#   endif // (_MSC_VER >= 1900) && (_MSVC_LANG >= 201103)
#  endif // defined(_MSC_VER) && defined(_MSVC_LANG)
# endif // !defined(ASIO_ENABLE_BOOST)
#endif // !defined(ASIO_STANDALONE)
```

## Current Behavior
`ASIO_STANDALONE` is explicitly defined in `src/cpp/CMakeLists.txt`. This prevents the user from using `ASIO_ENABLE_BOOST` even with explicitly added to the compiler when building. `ASIO_ENABLE_BOOST` will be omitted in this scenario as defined in `config.hpp` even when it may be required in some cases to leverage advanced features from the Boost library.

## Steps to Reproduce
If using CMake, you can add to your toolchain file `set(CMAKE_CXX_FLAGS_INIT "-DASIO_ENABLE_BOOST")`, and the build will succeed with ASIO_STANDALONE although the boost library is not added to the path, because it is not considered at all as shown in the following code extracted from `asio\asio\include\asio\detail\config.hpp`.
```
#if defined(ASIO_STANDALONE)
# define ASIO_DISABLE_BOOST_ARRAY 1
# define ASIO_DISABLE_BOOST_ASSERT 1
# define ASIO_DISABLE_BOOST_BIND 1
# define ASIO_DISABLE_BOOST_CHRONO 1
# define ASIO_DISABLE_BOOST_DATE_TIME 1
# define ASIO_DISABLE_BOOST_LIMITS 1
# define ASIO_DISABLE_BOOST_REGEX 1
# define ASIO_DISABLE_BOOST_STATIC_CONSTANT 1
# define ASIO_DISABLE_BOOST_THROW_EXCEPTION 1
# define ASIO_DISABLE_BOOST_WORKAROUND 1
#else // defined(ASIO_STANDALONE)
# include <boost/config.hpp>
# include <boost/version.hpp>
# define ASIO_HAS_BOOST_CONFIG 1
#endif // defined(ASIO_STANDALONE)
```

## System information
- Fast-RTPS version: v1.8.4
- OS: Windows 10

## Additional context
The goal is defining ASIO_ENABLE_BOOST to enable and leverage POSIX threads for Asio.

**Comment by pablorcum** [comment]
Just noticed that it implies at least ASIO v1.13 according to [this](https://github.com/chriskohlhoff/asio/commit/265e75cdbba739b1b1e3a46b283eaee3b9c60fe8).

**Comment by felixf4xu** [comment]
Thanks, just another additional note that in Ubuntu 20.04, the default `libasio-dev` is 1.12.2-1, any Fast-DDS user in Ubuntu 20.04, `ASIO_STANDALONE` is still needed.

> Just noticed that it implies at least ASIO v1.13 according to [this](https://github.com/chriskohlhoff/asio/commit/265e75cdbba739b1b1e3a46b283eaee3b9c60fe8).
