### ISSUE TITLE
Make Fast-DDS Boost patch portable for non-Linux OS

### ISSUE THREAD

**Issue by pablorcum** [eProsima/Fast-DDS#1451]
The current Fast-DDS Boost patch for shared_memory_object at `thirdparty\boost\include\boost\interprocess\shared_memory_object.hpp` uses the function [fallocate](https://man7.org/linux/man-pages/man2/fallocate.2.html), which is a non-portable, Linux specific system-call. According to [this reference](https://man7.org/linux/man-pages/man2/fallocate.2.html), it could be easily replaced with posix_allocate to improve compatibility with other UNIX-like OS.

## Expected Behavior
Crosscompiling for POSIX capable UNIX-like OS such as QNX. This can be enabled using POSIX calls whenever possible.

## Current Behavior
fallocate is a Linux specific system-call that is not present in non-Linux OS.

## Proposed fix
`fallocate(m_handle, 0, 0, length)`
to
`posix_fallocate(m_handle, 0, length)`

## System information
- Fast-RTPS version: 1a6c3f55e80b620e611aa8be85d7e999b20f104c
- Target OS: QNX

**Comment by MiguelCompany** [comment]
@pablorcum This has been solved both on `master` and `2.0.x`
