### ISSUE TITLE
Calculation of memory_pool_block_size incorrectly uses a function pointer as an integral value.

### ISSUE THREAD

**Issue by mperronqnx** [eProsima/Fast-DDS#1464]
A change was recently committed to the foonathan-memory library (https://github.com/foonathan/memory/commit/35f1010c83517a847ee872488fc3ba6b1411853e) whereby memory_block_stack::implementation_offset was redefined to a constexpr function; previously it was defined as a size_t. The eprosima::fastrtps::memory_pool_block_size() function uses this symbol as if it were an integer. This may lead to incorrect block size calculations for the memory pool.

The erroneous calculation can be found in the foonathan_memory_helpers.hpp header: https://github.com/eProsima/Fast-DDS/blob/f1b8d1ae676fbddd014bdb43a7f8ad3ecc31f28a/include/fastrtps/utils/collections/foonathan_memory_helpers.hpp#L56

## Expected Behavior
No errors when compiling with the -Werror option.

## Current Behavior
Compilation stops with the following warning when the -Werror option is specified:

warning: pointer to a function used in arithmetic [-Wpointer-arith]

Adding an open-close parentheses pair resolves the issue.

## Steps to Reproduce
Setting the -Werror option will cause the compilation to fail when building against the HEAD of foonathan-memory.

## System information
- Target system: QNXNTO, x86_64
- Compiler: GCC 8.3.0 20190222
- SHA of foonathan-memory: bf64e407a98d8482c98687bbfd3379585ec95586
- Fast-RTPS version: v2.0.1
- OS: Ubuntu 18.04.5

**Comment by MiguelCompany** [comment]
@mperronqnx We already have #1457 for this

**Comment by MiguelCompany** [comment]
I've reopened this until a fix for `2.0.x` is in place

**Comment by MiguelCompany** [comment]
I will close this since it should have been fixed by #1469
