### ISSUE TITLE
Segmentation fault caused by sequential Asio calls [9820]

### ISSUE THREAD

**Issue by pablorcum** [eProsima/Fast-DDS#1484]
## Expected Behavior
Run HelloWorldExample from Fast-RTPS together with another application that also uses Asio.

## Current Behavior
As soon as I start the HelloWorldExample with `./HelloWorldExample publisher`, the segmentation fault occurs.

## Steps to Reproduce
The error occurs alongside a simple [eCAL](https://github.com/continental/ecal) instance, which also uses Asio for communication.
1. Download and unzip the eCAL build libraries from [installecallibs.zip](https://github.com/eProsima/Fast-DDS/files/5373403/installecallibs.zip).
2. Download the modified HelloWorldExample from [helloWorld.zip](https://github.com/eProsima/Fast-DDS/files/5373422/helloWorld.zip). I've included the executable and the sources to prove that the modifications are minimal.
3. You may have to add the libraries from (1) to the path. Use `export LD_LIBRARY_PATH=pathToECALLibs:pathToFast-RTPSLibs`.
4. Check with ldd that all libraries required to run HelloWorldExample are available.
5. Execute `./HelloWorldExample publisher`.

## System information
- Fast-RTPS version: v1.8,4 with Asio v1.12.2
- OS: Ubuntu 20.04.1, QNX

## Additional context
Analyzing the core dump looks like an issue with Asio. I tried the exactly same configuration but building Fast-RTPS with Asio v1.13.0 (only one version later than status-quo) and everything works fine. In fact, I tried several versions of Asio, and all of them worked. It looks like the bug was definitely fixed in v1.13.0.

**Comment by pablorcum** [comment]
This can be fixed by setting the flag ASIO_DISABLE_VISIBILITY. It will facilitate parallel independent usage of different Asio sets within the same application. It needs at least Asio v1.13.0 though.

**Comment by felixf4xu** [comment]
> This can be fixed by adding the define `ASIO_DISABLE_VISIBILITY` at `src/cpp/CMakeLists.txt`. It will facilitate parallel independent usage of different Asio sets within the same application. It needs at least Asio v1.13.0 though.

Do you know from which version of `Fast-DDS` is `asio` v1.13.0 used?
