### ISSUE TITLE
libfastrtps build not linking against libatomic in an ARMHF environment

### ISSUE THREAD

**Issue by pbleyer** [eProsima/Fast-DDS#1495]
While attempting to compile Fast-DDS 2.0.1 on a Linux GNU EABIHF environment with GCC 8.3.0 (in particular, Raspberry Pi August 2020 Raspbian distribution), the linking step for libfastrtps fails with undefined atomic type references. Enabling the "atomic" library link for the architecture to the library list in the CMake target_link_libraries() command of src/cpp/CMakeLists.txt file fixes the issue.

**Comment by EduPonz** [comment]
Hi @pbleyer ,

We faced a similar issue (#1262) a couple of months ago, but it seems that you have a simpler and more elegant solution. Would you be so kind as to submit a PR for this?

Thanks for your report!

**Comment by MiguelCompany** [comment]
One thing to take into consideration is that this is platform/compiler/library dependant, so we should only add `-latomic` when needed

**Comment by pbleyer** [comment]
> 
> 
> One thing to take into consideration is that this is platform/compiler/library dependant, so we should only add `-latomic` when needed. It may be interesting to have a look at LLVM's [CheckAtomic](https://github.com/llvm-mirror/llvm/blob/master/cmake/modules/CheckAtomic.cmake)

Agreed. I can force the compiler to complain with a simple C++ program that tries to update a std::atomic variable, I guess in a similar way to the LLVM example you provided:

```
#include <atomic>

int
main(int argc, char **argv)
{
        volatile std::atomic_ullong i(0xcafebabedeadbeeful);
        i += 100;
        return 0;
}
```
```
g++ try_atomic.cpp -o try_atomic
/usr/bin/ld: /tmp/ccD8a1uI.o: in function `std::__atomic_base<unsigned long long>::operator+=(unsigned long long) volatile':
try_atomic.cpp:(.text._ZNVSt13__atomic_baseIyEpLEy[_ZNVSt13__atomic_baseIyEpLEy]+0x28): undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
```
And we could set a CMake BOOL based on the call to try_run() with and without linking with libatomic and then use that in the target_link_libraries() list.

Let me see if it works and I will submit a PR.

**Comment by RFRIEDM** [comment]
Has there been any change of plans to fully support the Pi 4?

**Comment by EduPonz** [comment]
I'm unsure on what you mean by full support. Currently aarch64 is a Tier I platform for Fast DDS so we run all our CI in RaspberryPi 4. Regarding the atomic library, @pbleyer kindly submitted #1503 a couple of months ago, and that features is already in master. #1634 Further extends that work

**Comment by RFRIEDM** [comment]
Excellent thank you for the support! I look forward to using it.

**Comment by EduPonz** [comment]
Glad to hear! Please do report whether the fixes work for you, we're much interested!
