### ISSUE TITLE
Increment operators of ParameterPropertyList_t iterators seem incorrect [9815]

### ISSUE THREAD

**Issue by VladimirVassiliev** [eProsima/Fast-DDS#1530]
The pre- and postfix increment operators of ParameterPropertyList_t iterators seem to be reversed.

## Expected Behavior

The postfix increment operator should return the current value and the prefix one should return the new value.
## Current Behavior

The postfix increment operator returns the new value and the prefix one returns the current value.

## Steps to Reproduce

It looks like it does not cause any problems yet, because the return value is not used.

## System information

- Fast-RTPS version: 
- OS: 
- Network interfaces: 
                      
- ROS2: 
        

## Additional resources
- Wireshark capture 
- XML profiles file

**Comment by JLBuenoLopez-eProsima** [comment]
Thansk for reporting @VladimirVassiliev and sorry for the late reply. I have just issued #3739 that fixes the issue.
