### ISSUE TITLE
Questions regarding KEEP_ALL_HISTORY_QOS [9808]

### ISSUE THREAD

**Issue by pbustos** [eProsima/Fast-DDS#1543]
Hello, I have a few questions related to the reliable multicast transport that we could not figure out in the documentation:

- When using the "publisher_attr.qos.m_lifespan.duration" setting, are invalidated messages cleared even when history is set to KEEP_ALL_HISTORY_QOS? If not, is there a way to get that behavior?

-When a subscriber is removed with removeSubscriber, do publishers remove from the history (configured with KEEP_ALL_HISTORY_QOS) the messages that the subscriber has left unanswered or has not yet received? If not, how do you configure a subscriber disconnect so that publishers are aware of it?

-Does setting KEEP_ALL_HISTORY_QOS on a subscriber delete history messages after ACK?

Thanks!

**Comment by MiguelCompany** [comment]
> * When using the "publisher_attr.qos.m_lifespan.duration" setting, are invalidated messages cleared even when history is set to KEEP_ALL_HISTORY_QOS?

Yes. When the lifespan of a change expires, it is removed from the publisher's history, regardless of the settings of the HISTORY QoS.

> -When a subscriber is removed with removeSubscriber, do publishers remove from the history (configured with KEEP_ALL_HISTORY_QOS) the messages that the subscriber has left unanswered or has not yet received?

When all the subscribers matching the publisher have been removed, changes removal will depend on the DURABILITY QoS.
* When it is VOLATILE, changes will be immediately removed from the publisher's history
* With other values, changes will remain in the publisher's history. For a publisher using KEEP_ALL_HISTORY_QOS, if a change is added later on, it will be kept in the history. The maximum number of changes kept depends on the RESOURCE_LIMITS QoS. When the resource limit is reached, new changes will replace old ones.

> -Does setting KEEP_ALL_HISTORY_QOS on a subscriber delete history messages after ACK?

Changes are only removed from subscribers when taking them (i.e. calling `take`). The difference between KEEP_LAST and KEEP_ALL subscribers is that the latter will discard changes if the resource limit has been reached when they are received, forcing a retransmission from the publisher later on. Changes will only be acknowledged if they have been added to the subscriber's history.

**Comment by pbustos** [comment]
Thank you for the quick answer.

Let me add here the result of a recent test comparing multicast vs unicast in a single machine. The test involves a new distributed graph data structure that is part of a robot architecture. The graph is shared among n processes and being heavily edited by them, generating a flow of 30MB/s that must reach all of them while keeping the graph consistent.

![photo5845895143981429592](https://user-images.githubusercontent.com/6126487/98299037-53c7a080-1fb7-11eb-9081-1435172827e6.jpg)
