### ISSUE TITLE
Breaks building ROS 2 from source

### ISSUE THREAD

**Issue by ThijsRay** [eProsima/Fast-DDS#1556]
Currently, the 2.0.x branch is used in ROS 2. However, the package.xml file has some flaws, This breaks the building of ROS 2 from source.

The following issues seem to be present since 669a400b704b6e70752e559d4a5719d4a36a6296:
* Mismatching brackets in package.xml (fixed in https://github.com/eProsima/Fast-DDS/pull/1554)
* Unknown ROS Foxy dependencies: libgmock-dev

There might be more issues, but currently, it is not possible to build ROS 2 Foxy from source.

**Comment by MiguelCompany** [comment]
@ThijsRay Could you check with #1557 ?

**Comment by brawner** [comment]
Foxy builds seem to be working for ci.ros2.org currently. New PR for unused variable warning at #1558

**Comment by ThijsRay** [comment]
Yes, it looks like it is working again!
