### ISSUE TITLE
Split data into fragments greater than 65 KB for SharedMemTransportDescriptor

### ISSUE THREAD

**Issue by sfod** [eProsima/Fast-DDS#1572]
It's rather a question than a bug.

I'm using SharedMemTransportDescriptor as the only available transport for reader/writer app, and I'm not sure how to fragment data into fragments greater than 65 KB.

Here is an example of how I initialize transport.
```
RTPSParticipantAttributes PParam;
PParam.useBuiltinTransports = false;

auto shm_transport = std::make_shared<SharedMemTransportDescriptor>();
shm_transport->segment_size(1000000);
shm_transport->max_message_size(1000000);
PParam.userTransports.push_back(std::move(shm_transport));
```

When I send a message under 1 MB everything works perfect.
But when I try to send 2 MB message, transfer fails with error "Cannot add DATA submsg to the CDRMessage. Buffer too small".

I found the only way to resolve this issue is to fragment data using `CacheChange_t::setFragmentSize()` method.
The problem is that setFragmentSize takes fragment size as uint16_t variable, so it's not possible to split data into fragments greater than 65 KB.

Here is an example of how I split data.
```
CacheChange_t* ch = mp_writer->new_change([]() -> uint32_t {
            return 1000000;
        }, ALIVE);
// The following line is incorrect as 1000000 will transform into 16960.
// ch->setFragmentSize(1000000);
// This works but fragment size is too low.
ch->setFragmentSize(64000);
mp_history->add_change(ch);
```

So the question is: how to split data into big fragments?

## Expected Behavior
It should be possible to send large data fragments between processes using shared memory.

## Current Behavior
The maximum fragment size is 65 KB.

## System information

- Fast-RTPS version: commit 40568fa4784e846f95c461608d43a2b57eaef55b (tag: v2.0.1)
- OS: Ubuntu 20.04.1 LTS
- Network interfaces: none
- Used transport: shared memory

**Comment by MiguelCompany** [comment]
The shared memory transport is like the rest of the transports. This means that it is responsible for transporting RTPS messages with the format depicted on the [RTPS standard](https://www.omg.org/spec/DDSI-RTPS/About-DDSI-RTPS/). Section 8.3.7.3 specifies the format of the DataFrag submessage. Table 8.36 specifies the fields of that submessage, and field `fragmentSize` has `ushort` type. The description of the field mentions the maximum size explicitly:

> The size of an individual fragment in bytes. The maximum
fragment size equals 64K.

As you can see, there's no room for improvement here.

**Comment by sfod** [comment]
I overlooked that info in standard, now this limitation makes sense.
So, the solution is whenever possible to set `max_message_size` to value that will be greater than a message max length.
Thanks for clarifying that for me.

**Comment by MiguelCompany** [comment]
Correct. If you don't want your data to be fragmented, `max_message_size` should be a bit greater than the maximum value used on the call to `new_change`. Some additional space is required for the RTPS header (20 bytes), one INFO_DST sub-message (16 bytes), one INFO_TS sub-message (12 bytes), and the DATA sub-message header (20 bytes).

Take also into account that `segment_size` should be at least `max_message_size`
