### ISSUE TITLE
Cross Compiler Failed on thirdparty/nlohmann-json 

### ISSUE THREAD

**Issue by baozinihao321** [eProsima/Fast-DDS#1608]
The cross compiler failed when make nlohmann-json
## Expected Behavior

The compiler should finish the task as expected
## Current Behavior

/nfs/john/DDS/Fast-DDS/thirdparty/nlohmann-json/json.hpp:11528:91: internal compiler error: same canonical type node for different types nlohmann::detail::json_reverse_iterator<Base>::base_iterator and std::reverse_iterator<_Iterator>
     explicit json_reverse_iterator(const base_iterator& it) noexcept : base_iterator(it) {}
                                                                                           ^
0x81f515d cp_parser_member_declaration
	/usr1/code/CODE_CCTD_V1R2C00/code/current/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:22625
0x81ccc27 cp_parser_member_specification_opt
	/usr1/code/CODE_CCTD_V1R2C00/code/current/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:22186
0x81ccc27 cp_parser_class_specifier_1
	/usr1/code/CODE_CCTD_V1R2C00/code/current/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:21378
0x81cda0b cp_parser_class_specifier
	/usr1/code/CODE_CCTD_V1R2C00/code/current/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:21614
0x81cda0b cp_parser_type_specifier
	/usr1/code/CODE_CCTD_V1R2C00/code/current/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:15868
0x81e5348 cp_parser_decl_specifier_seq
	/usr1/code/CODE_CCTD_V1R2C00/code/current/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:12788
0x81f32fd cp_parser_single_declaration
	/usr1/code/CODE_CCTD_V1R2C00/code/current/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:25803
0x81f36a8 cp_parser_template_declaration_after_parameters
	/usr1/code/CODE_CCTD_V1R2C00/code/current/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:25498
0x81f408b cp_parser_explicit_template_declaration
	/usr1/code/CODE_CCTD_V1R2C00/code/current/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:25730
0x81f4460 cp_parser_template_declaration_after_export
	/usr1/code/CODE_CCTD_V1R2C00/code/current/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:25748
0x82026e8 cp_parser_declaration
	/usr1/code/CODE_CCTD_V1R2C00/code/current/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:12115
0x8201258 cp_parser_declaration_seq_opt
	/usr1/code/CODE_CCTD_V1R2C00/code/current/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:12045
0x8201691 cp_parser_namespace_body
	/usr1/code/CODE_CCTD_V1R2C00/code/current/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:17649
0x8201691 cp_parser_namespace_definition
	/usr1/code/CODE_CCTD_V1R2C00/code/current/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:17626
0x8202674 cp_parser_declaration
	/usr1/code/CODE_CCTD_V1R2C00/code/current/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:12150
0x8201258 cp_parser_declaration_seq_opt
	/usr1/code/CODE_CCTD_V1R2C00/code/current/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:12045
0x8201691 cp_parser_namespace_body
	/usr1/code/CODE_CCTD_V1R2C00/code/current/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:17649
0x8201691 cp_parser_namespace_definition
	/usr1/code/CODE_CCTD_V1R2C00/code/current/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:17626
0x8202674 cp_parser_declaration
	/usr1/code/CODE_CCTD_V1R2C00/code/current/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:12150
0x8201258 cp_parser_declaration_seq_opt
	/usr1/code/CODE_CCTD_V1R2C00/code/current/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:12045
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.

## Steps to Reproduce

1. Cmake Config
cmake ..  -DCMAKE_INSTALL_PREFIX=~/nfs/john/DDS/Fast-DDS/install/ \
          -DCMAKE_SYSTEM_NAME=Linux \
          -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
          -DCMAKE_C_COMPILER=aarch64-himix100-linux-gcc \
          -DCMAKE_CXX_COMPILER=aarch64-himix100-linux-g++ \
          -DCMAKE_CXX_FLAGS=-fPIC \
          -DCMAKE_C_FLAGS=-fPIC \
          -DNO_TLS=ON \
          -DCOMPILE_EXAMPLES=ON
2.  All Configure Done!

## System information

- Fast-DDS version: 2.1.0
- OS: Ubuntu 12.04.2 LTS
- Cross Compiler: aarch64-himix100-linux-g++ ( gcc version 6.3.0 )

**Comment by EduPonz** [comment]
Hi @baozinihao321 ,

This issue was observed in nlohmann/json#1906 as well almost a year ago. The answer suggests a compiler bug, although I haven't looked into it in detail.

**Comment by baozinihao321** [comment]
> Hi @baozinihao321 ,
> 
> This issue was observed in [nlohmann/json#1906](https://github.com/nlohmann/json/issues/1906) as well almost a year ago. The answer suggests a compiler bug, although I haven't looked into it in detail.

Thanks for a very quick reply! I noticed that issue in nlohmann/json#1906 too, but I can't find a method or trick to get over this bug.
When I used Fast-DDS 2.0.0, it seems that we haven't use this json third-party yet. It looks like a upgrade in rtps database.
So... a little bit confuse now. Could you take a moment to look through this bug again? Thanks .

**Comment by EduPonz** [comment]
Hi @baozinihao321 ,

As you say, the third-party was introduced in v2.0.2 with the newest version of the Discovery Server.

At the moment the official support for aarch64 is limited to Ubuntu 20.04. For cross-compilation we use 
`aarch64-linux-gnu-gcc`, `aarch64-linux-gnu-g++`, `aarch64-linux-gnu-ld`, and `qemu`. It be great if you could share what worked for you so others can follow your process.

Thanks!

**Comment by baozinihao321** [comment]
I tried aarch64-linux-gnu-g++ (gcc version 7.2.0), it worked... 
Then I tried the aarch64-himix100-linux-g++ (gcc version 6.3.0) again after
I commented out the LINE 11528 in json.hpp, it worked as well... (Though I hate to change src code). 
Anyway, Newer Compiler, Fewer Problems...

**Comment by examyes** [comment]
Replace `using base_iterator = std::reverse_iterator<Base>;` with `typedef std::reverse_iterator<Base> base_iterator;` may fix the compiler error.

Anyway, this is a gcc bug.

**Comment by hjes** [comment]
> Replace `using base_iterator = std::reverse_iterator<Base>;` with `typedef std::reverse_iterator<Base> base_iterator;` may fix the compiler error.
> 
> Anyway, this is a gcc bug.

Yes, this should help solve my problem.
