### ISSUE TITLE
Run DDS HelloWorld Example Failed on Foonathan Memory

### ISSUE THREAD

**Issue by baozinihao321** [eProsima/Fast-DDS#1617]
## Expected Behavior

Run DDS Demo Successfully
## Current Behavior

Starting 
 [RTPS_MSG_OUT Error] error: couldn't generate segment_name -> Function init
Subscriber running. Please press enter to stop the Subscriber
[foonathan::memory] Allocator foonathan::memory::memory_pool (at 0x4bd6f8) received invalid size/alignment 56, max supported is 48terminate called after throwing an instance of 'foonathan::memory::bad_node_size'
  what():  allocation node size exceeds supported maximum of allocator
Aborted

## Steps to Reproduce

1. Run DDS Demo on two SBCs (./DDSHelloWorldExample subscriber and ./DDSHelloWorldExample publisher)
2. The Subscriber report allocator memory error

## System information

- Fast-DDS version: 2.1.0
- OS : Linux 4.9.37
- Processor : A53
- Arch : aarch64
- Cross-Compiler : aarch64-himix100-linux-g++ (gcc 6.3.0)
- Foonathan Memory: 0.6.2 (latest) 

## Additional context

Foonathan Cmake Option (-DFOONATHAN_MEMORY_BUILD_TOOLS=OFF)
container_node_sizes_impl.hpp
#define FOONATHAN_MEMORY_NO_NODE_SIZE

## Additional resources
- Wireshark capture 
- XML profiles file

**Comment by baozinihao321** [comment]
Solve this by following steps:
1、Turn on Foonathan Cmake Option (-DFOONATHAN_MEMORY_BUILD_TOOLS=ON)
2、run the debug tool on the Arm platorm
3、copy the generated "container_node_sizes_impl.hpp" to MEMORY_ROOT/include/foonathan/memory/detail
4、change MEMORY_ROOT/src/CMakeLists.txt  (Add header file, comment out Tools Line etc.)
5、rebuild memory (-DFOONATHAN_MEMORY_BUILD_TOOLS=OFF)
6、rebuild FastDDS

**Comment by kk-12138** [comment]
> 
> 
> Solve this by following steps:
> 1、Turn on Foonathan Cmake Option (-DFOONATHAN_MEMORY_BUILD_TOOLS=ON)
> 2、run the debug tool on the Arm platorm
> 3、copy the generated "container_node_sizes_impl.hpp" to MEMORY_ROOT/include/foonathan/memory/detail
> 4、change MEMORY_ROOT/src/CMakeLists.txt (Add header file, comment out Tools Line etc.)
> 5、rebuild memory (-DFOONATHAN_MEMORY_BUILD_TOOLS=OFF)
> 6、rebuild FastDDS

hi, for step 2 & 3, how to run the debug tool to generate the header files? could you give the command？

**Comment by Baren123** [comment]
I'm faced the same problem.Can you tell me how to solve it？Thanks.
