### ISSUE TITLE
How to improve the packet loss rate when transport large data over udp?

### ISSUE THREAD

**Issue by liyue75** [eProsima/Fast-DDS#1625]
Hi, I used test/performance/latency/Latency to get latency of FastDDS. I modified udp address in xml file,  the time-out period passed to wait_for function and the payloads_demands.csv  to let the test work with large data on dual hosts.
  I found there is packet loss when the size of data is big.

## Expected Behavior
The publisher on one host would send 1000 samples, and the subscriber on the other host would recv each sample and then send it back to the pub, then the publisher caculate the latency by  dividing the time interval between sending ahnd receiving of each sample by 2.

## Current Behavior
When using reliable_udp , the result of the test:
Bytes, Samples, mean
512k,        995,    9164us
1024k,      993,   18587us

When using best_effort_udp, the result was:
Bytes, Samples, mean
512k,       985,     6592us
1024k,    965,     12319us 

If there was no loss the value of samples would be 1000. The value of mean is the average latency.

## Steps to Reproduce
1.Change the parameter's value of wait_for in test/performance/latency/LatencyTestPublisher.cpp, line 686: 
data_msg_cv_.wait_for(lock, std::chrono::milliseconds(4)
Change the 4 to 1000, so the large data  transfer does not cause timeout
2. Compile the src and generate the LatencyTest  program.                                
3.Modify the test/performancd/latency/payloads_demands.csv:     524288;1048576;
4.Modify the ip address in test/performance/latency/xml/interprocess_reliable_udp.xml and interporcess_best_effort_udp.xml, 
change the address from 127.0.0.1 to your host LAN IP address.
4. I haven't changed any of the other FastDDS options.
To test reliable udp:
launch "./LatencyTest publisher -s 1000 -f  payloads_demands.csv --xml interprocess_reliable_udp.xml", and on the other host, type "./LatencyTest subscriber -f payloads_demands.csv --xml interprocess_reliable_udp.xml"
To test besteffort udp:
./LatencyTest publisher -s 1000 -f payloads_demands.csv --xml interprocess_best_effort_udp.xml
./LatencyTest subscriber -f payloads_demands.csv --xml interprocess_best_effort_udp.xml

## System information

- Fast-RTPS version: 2.1.0
- OS: Ubuntu 18.04 
-Network: Wired LAN

Here are some questions I want to ask: 
  Are the rate of packet loss of my test normal?
  Why reliable udp also has lost packets? 
  Is there any way to improve the packet loss rate of big data transmitted over UDP?

**Comment by liyue75** [comment]
Hi, I found out what the problem was.
Before, the test was conducted between a physical machine and a virtual machine.
Now, when I run the test on two physical machines, I find that the packet loss is not high at all.
The newresult of 10000 samples is:
reliable udp:
Bytes,Samples,latency
512k, 9997, 5395
1M, 9992, 10177
best_effort udp:
Bytes, Samples, latency
512k, 9995, 5376
1M,    9990, 10142

Maybe there is a problem with my virtual machine network, but Fast-DDS works fine.
I will close this issue.

**Comment by EduPonz** [comment]
Hi @liyue75 , 

That's great to hear! Sorry we didn't get back to you sooner, but we've been on vacation the last few days.
