### ISSUE TITLE
Throughput test's bug

### ISSUE THREAD

**Issue by liyue75** [eProsima/Fast-DDS#1664]
When I keep running test/performance/throughput/ThroughputTest with large payload on dual hosts, segmentation fault will generated on subscriber. And I find the probable cause:
In test/performance/throughput/ThroughputSubscriber.cpp: 
In process_message():
line500 and 501
        delete(**throughput_type_**);
        **throughput_type_** = nullptr;
In onNewDataMessage():
line 114:
if ((last_seq_num_ + 1) < throughput_subscriber_.**throughput_type_**->seqnum)

If the sub recv END command while takeNextData,  it will delete **throughput_type_**, after that  the **throughput_type_** can not be used, this will cause segmetation fault.

So I move 
delete(**throughput_type_**);
**throughput_type_** = nullptr;
these two lines to line 558, 
in this way ,it waits for the data subuscriber matching to be removed before setting the **throughput_type** to null.

## System information

- Fast-RTPS version: v2.1.0
- OS: ubuntu18.04

**Comment by jparisu** [comment]
Hi @liyue75 ,

Thank you for your contribution. The linked PR #10205 fixes this problem.
Your comment has been really helpful finding the issue, but we have solved it using a mutex rather than moving the lines you suggested. This fixes also the dynamic datatype part and keeps the logic as it was.

**Comment by liyue75** [comment]
@jparisu That's good to hear about that.
