### ISSUE TITLE
Unable to use `SharedMemTransport` as the sole transport layer [10450]

### ISSUE THREAD

**Issue by alireza-hosseini** [eProsima/Fast-DDS#1665]
I had issues with setting the `SharedMemTransport` as the only transport layer of my participants, so I tried to replicate it on your `HelloWorldExampleSharedMem` example and I faced the same issue. Basically, if you comment out the line
https://github.com/eProsima/Fast-DDS/blob/b0e119bafc02fd6761ad5cd7c61872c32a008a61/examples/C%2B%2B/HelloWorldExampleSharedMem/HelloWorldPublisher.cpp#L65
which means having shared memory as the only transport layer, the application would get stuck on the creation of the `participant` (https://github.com/eProsima/Fast-DDS/blob/b0e119bafc02fd6761ad5cd7c61872c32a008a61/examples/C%2B%2B/HelloWorldExampleSharedMem/HelloWorldPublisher.cpp#L67).

## Expected Behavior

I should be able to use the shared memory transport layer without dependency on the other transport layers.

## Current Behavior

Application gets stuck on https://github.com/eProsima/Fast-DDS/blob/b0e119bafc02fd6761ad5cd7c61872c32a008a61/examples/C%2B%2B/HelloWorldExampleSharedMem/HelloWorldPublisher.cpp#L67.

## Steps to Reproduce

1. As explained above, in the `HelloWorldExampleSharedMem` example,  comment out the line which is adding the `udp` transport layer to the participant transport layers.
2. Rerun the example
3. Application will get stuck on creation of the participant 

## System information

- Fast-RTPS version: v2.1.0 
- OS: Windows 10 
- Network interfaces: I shouldn't need any network interface in this case 
                      
- ROS2: 
        

## Additional context

 I should mention that due to our project requirements I complied fast-dds and its dependencies with `POSITION_INDEPENDENT_CODE` flag enabled and also `MT` and `MTd` flags instead of `MD` and `MDd`. In case these modifications would cause unexpected behaviors in your library would be great if you let me know.

## Additional resources
- Wireshark capture 
- XML profiles file

**Comment by sfod** [comment]
I've encountered the same problem. I believe that this commit is the reason of the issue: https://github.com/eProsima/Fast-DDS/pull/1181/commits/47adefc48ae7652fb95829e90165459acf0458d8

In the HelloWorld example, the **Subscriber** enables both UDPv4 and SharedMem transports, so the default locators list contains UDP only. The modified **Publisher** has only SharedMem transport enabled. Which leads to inability to communicate.

I reverted this commit, and modified HelloWorld example now works just fine.

What are the reasons behind the mentioned commit? Comment from it is not clear.
>         // For better fault-tolerance reasons, SHM multicast metatraffic is avoided if it is already provided 
>         // by another transport

**Comment by sfod** [comment]
@imontesino Probably my question got lost.
Is there a chance the logic mentioned above could be fixed? I could try to fix it myself, if only I understand the issue that was originally fixed.

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @sfod,

I suggest you look into the DDS API compliant [`HelloWorldExampleSharedMemory`](https://github.com/eProsima/Fast-DDS/tree/master/examples/C%2B%2B/DDS/HelloWorldExampleSharedMem). The old FastRTPS API has been deprecated and it is not longer being given support. In fact, those specific examples that are using the old API are going to be removed from the repository soon. In this other example the Shared Memory Transport is the only one being enabled and, therefore, the only one in use since #2407.

I hope this information is helpful!
