### ISSUE TITLE
catch exception when creating a named_mutex:Function not implemented [10202]

### ISSUE THREAD

**Issue by sky-fire** [eProsima/Fast-DDS#1668]
https://github.com/eProsima/Fast-DDS/blob/b0e119bafc02fd6761ad5cd7c61872c32a008a61/src/cpp/rtps/transport/shared_mem/SharedMemSegment.hpp#L197

**Comment by JLBuenoLopez-eProsima** [comment]
@sky-fire 

Could you provide us more information about this issue?

**Comment by JLBuenoLopez-eProsima** [comment]
Not having enough information about the issue and how to reproduce it, and not having any answer from the opening user, I will proceed and close it. If any user encounters this issue in the future, please fill up the issue template with enough information to reproduce it.
