### ISSUE TITLE
Apply "historyMemoryPolicy" From DDS Layer for Large Message [10208]

### ISSUE THREAD

**Issue by rxdu** [eProsima/Fast-DDS#1674]
Hello, 

I've been trying to use FastDDS to send LaserScan data (using the idl from ROS2 which contains unbounded sequences such as "sequence<float> ranges") and found the subscriber cannot receive messages if the number of points exceeds a certain number. 

After some research, I think the issue was caused by the memory allocation related to this "historyMemoryPolicy". As a reference, I checked the following issue discussions:

[issue 103](https://github.com/eProsima/Fast-DDS/issues/103)
[issue 74](https://github.com/eProsima/Fast-DDS/issues/74)
[issue 1205](https://github.com/eProsima/Fast-DDS/issues/1205)

It seems there are two solutions for this:

1. Use "DYNAMIC" or "PREALLOCATED_WITH_REALLOC" policy 
2. Reserve enough space in the idl, for example, sequence<float, 1000> ranges

I've verified the 2nd solution works. But since I'm using idls generated by ROS2, it's not ideal to manually modify the idl definitions whenever I see this problem. So I tried to use the first solution but I could not get it to work. I don't see a function to set this policy directly from the DDS layer so I tried to create publisher and subscriber with the following XML profile:

```
<?xml version="1.0" encoding="UTF-8"?>
<dds xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
    <profiles>
        <participant profile_name="ros2_participant_profile" is_default_profile="true">
            <rtps>
                <builtin>
                    <readerHistoryMemoryPolicy>PREALLOCATED_WITH_REALLOC</readerHistoryMemoryPolicy>
                    <readerPayloadSize>2048</readerPayloadSize>
                    <writerHistoryMemoryPolicy>PREALLOCATED_WITH_REALLOC</writerHistoryMemoryPolicy>
                    <writerPayloadSize>2048</writerPayloadSize>
                </builtin>
            </rtps>
        </participant>

        <publisher profile_name="ros2_publisher_profile" is_default_profile="true">
            <qos>
                <publishMode>
                    <kind>ASYNCHRONOUS</kind>
                </publishMode>
            </qos>
            <historyMemoryPolicy>PREALLOCATED_WITH_REALLOC</historyMemoryPolicy>
        </publisher>

        <subscriber profile_name="ros2_subscriber_profile" is_default_profile="true">
            <historyMemoryPolicy>PREALLOCATED_WITH_REALLOC</historyMemoryPolicy>
        </subscriber>
    </profiles>
</dds>
```

Since I'm using a lightweight FastDDS wrapper of our company, I cannot copy and paste all relevant code here. But internally it's just using the normal create_xxx_with_profile functions like

```
participant_ =
      DomainParticipantFactory::get_instance()->create_participant_with_profile(
          domain_id_, profile_name);
publisher_ = participant->create_publisher_with_profile(profile);
subscriber_ = participant->create_subscriber_with_profile(profile);
```

I can confirm the participant/publisher/subscriber are created using the above functions during runtime. But it doesn't seem to be making any effect and the receiver still cannot receive messages.

Did I miss any additional configurations? Any suggestions?

Thank you!

**Comment by EduPonz** [comment]
Hi @rxdu ,

First of all, thanks for your report. While we take a closer look into it, you might be interested in setting the policy programatically. You can do so with the [`history_memory_policy`](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/core/policy/eprosimaExtensions.html#memorymanagementpolicy) attribute within the  `RTPSEndpointQos`.

**Comment by rxdu** [comment]
> Hi @rxdu ,
> 
> First of all, thanks for your report. While we take a closer look into it, you might be interested in setting the policy programatically. You can do so with the [`history_memory_policy`](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/core/policy/eprosimaExtensions.html#memorymanagementpolicy) attribute within the `RTPSEndpointQos`.

Thank you for the quick response. I just tried the method you mentioned and it works! I tried to achieve this programmatically earlier but missed this QoS setting API from the documentation.

**Comment by edgarcamilocamacho** [comment]
Hi @rxdu, could you publish the modifications you did to your code to fix it? Please.

**Comment by rxdu** [comment]
The following setup works for me (with similar settings for the subscriber):

```
publisher_ = participant_->create_publisher(
      eprosima::fastdds::dds::PUBLISHER_QOS_DEFAULT, nullptr);
topic_ = participant_->create_topic(
      topic_name, type_name, eprosima::fastdds::dds::TOPIC_QOS_DEFAULT);
DataWriterQos wqos = DATAWRITER_QOS_DEFAULT;
wqos.reliability().kind = RELIABLE_RELIABILITY_QOS;
wqos.durability().kind = TRANSIENT_LOCAL_DURABILITY_QOS;
wqos.endpoint().history_memory_policy =
        eprosima::fastrtps::rtps::PREALLOCATED_WITH_REALLOC_MEMORY_MODE;
writer_ = publisher_->create_datawriter(topic_, wqos, &callbacks_);
```

I did a few more tests and it seems the XML way also works with 
```
publisher_ = participant->create_publisher_with_profile("ros2_publisher_profile");
topic_ = participant_->create_topic(
        topic_name, type_name, eprosima::fastdds::dds::TOPIC_QOS_DEFAULT);
writer_ = publisher_->create_datawriter_with_profile(topic_, "ros2_publisher_profile",
                                                         &callbacks_);
```
Due to my lack of familiarity with the library API and internal implementation, I thought creating the publisher with a profile would be sufficient and didn't create the data writer with the same profile.

As to this API usage matter, wouldn't it make more sense if the topic and date writer construction/destruction is managed internally by the publisher? Conceptually a publisher is a higher-level manager of a data writer and a data writer would always be associated with a topic (according to my understanding).  I know they are different entities with different sets of associated QoS policies but it feels a little strange that I create a publisher with the profile first and then create a writer with the newly created publisher and the same profile again. Is there a case where the publisher and the data writer are created with different profiles?

**Comment by edgarcamilocamacho** [comment]
Thanks @rxdu!, the solution worked for me too. And I am with you about the missing of an "inheritance" of the QoS policies.

**Comment by EduPonz** [comment]
Hi @rxdu @edgarcamilocamacho ,

> Due to my lack of familiarity with the library API and internal implementation, I thought creating the publisher with a profile would be sufficient and didn't create the data writer with the same profile.

Actually, the documentation could do a better job explaining the difference in the profiles. Fast DDS v2.0.0 introduced a DDS specification compliant API (DDS API), while at the same time deprecated the old pub/sub API (which we normally call Fast RTPS API). In your code, you're using the DDS API. However, for back-compatibility reasons, we did not change the XML schema, parser, and profile manager, mainly because ROS 2, to this day, still uses the Fast RTPS API, i.e. the deprecated one. Changing the way XML profiles are managed would have cause a lot of application breaks in ROS 2 that we wanted to avoid. 

What we did then was to create an alias `data_writer` for the `publisher` XML tag. This is because the large majority of the attributes that used to be `PublisherAttributes` are now `DataWriterQos` (the Fast RTPS `Publisher` is the equivalent of the DDS `DataWriter`). In fact, the only `PublisherQos` that can be set using the XML is [PartitionQosPolicy](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/core/policy/standardQosPolicies.html#partitionqospolicy). Internally, all the `publisher`/`data_writer` XML profiles are stored in the same map, so only one with the same name is allowed. In your example you actually wouldn't need to create the publisher from the profile (since you're not setting any partitions), the data writer would suffice. In any case, you could split the the profile in two (if you were to configure partitions), one for the publisher and another one for the data writer, and the create the entities with their corresponding profiles:

```
<publisher profile_name=pub_profile>
    <!-- You can only configure partitions here -->
    ...
</publisher>

<data_writer profile_name=dw_profile>
    <!-- All the DataWriterQos come here -->
    ...
</data_writer>
```
```
publisher_ = participant->create_publisher_with_profile("pub_profile");
topic_ = participant_->create_topic(
        topic_name, type_name, eprosima::fastdds::dds::TOPIC_QOS_DEFAULT);
writer_ = publisher_->create_datawriter_with_profile(topic_, "dw_profile",
                                                         &callbacks_);
```

**Comment by rxdu** [comment]
That makes a lot more sense now. Thank you for the clarification.
