### ISSUE TITLE
Fast-DDS installation failed during ROS2 installation

### ISSUE THREAD

**Issue by KanwalAshraf** [eProsima/Fast-DDS#1676]
During the installation of ROS2 on Raspberry Pi with OS Raspbian the FastDDS installation is failing. The installation was successful when I install only Fast-DDS but the integrated module of ROS2 with FastDDS is not working.

## Current Behavior
The error code is as below:
`--- stderr: fastrtps                                      
In file included from /home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/RTPSParticipantAttributes.h:31,
                 from /home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/dds/core/policy/QosPolicies.hpp:29,
                 from /home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastrtps/qos/QosPolicies.h:23,
                 from /home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/WriterAttributes.h:27,
                 from /home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/writer/RTPSWriter.h:25,
                 from /home/pi/ros2_foxy/src/eProsima/Fast-DDS/src/cpp/rtps/writer/RTPSWriter.cpp:20:
/home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/ServerAttributes.h:72:30: error: expected identifier before numeric constant
     FASTDDS_DEPRECATED_UNTIL(3, "eprosima::fastrtps::rtps:GetEDPPublicationsReader()",
                              ^
/home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/ServerAttributes.h:72:30: error: expected ‘,’ or ‘...’ before numeric constant
/home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/ServerAttributes.h:73:50: error: ISO C++ forbids declaration of ‘FASTDDS_DEPRECATED_UNTIL’ with no type [-fpermissive]
             "Not implemented nor used functions.")
                                                  ^
/home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/ServerAttributes.h:73:50: error: expected ‘;’ at end of member declaration
             "Not implemented nor used functions.")
                                                  ^
                                                   ;/home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/ServerAttributes.h:75:30: error: expected identifier before numeric constant
     FASTDDS_DEPRECATED_UNTIL(3, "eprosima::fastrtps::rtps:GetEDPSubscriptionsWriter()",
                              ^
/home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/ServerAttributes.h:75:30: error: expected ‘,’ or ‘...’ before numeric constant
/home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/ServerAttributes.h:76:50: error: ISO C++ forbids declaration of ‘FASTDDS_DEPRECATED_UNTIL’ with no type [-fpermissive]
             "Not implemented nor used functions.")
                                                  ^
/home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/ServerAttributes.h:76:50: error: expected ‘;’ at end of member declaration
             "Not implemented nor used functions.")
                                                  ^
                                                   ;
/home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/ServerAttributes.h:75:5: error: ‘int eprosima::fastdds::rtps::RemoteServerAttributes::FASTDDS_DEPRECATED_UNTIL(int)’ cannot be overloaded with ‘int eprosima::fastdds::rtps::RemoteServerAttributes::FASTDDS_DEPRECATED_UNTIL(int)’
     FASTDDS_DEPRECATED_UNTIL(3, "eprosima::fastrtps::rtps:GetEDPSubscriptionsWriter()",
/home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/ServerAttributes.h:72:5: note: previous declaration ‘int eprosima::fastdds::rtps::RemoteServerAttributes::FASTDDS_DEPRECATED_UNTIL(int)’
     FASTDDS_DEPRECATED_UNTIL(3, "eprosima::fastrtps::rtps:GetEDPPublicationsReader()",
     ^~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/ServerAttributes.h:79:30: error: expected identifier before numeric constant
     FASTDDS_DEPRECATED_UNTIL(3, "eprosima::fastrtps::rtps:GetEDPPublicationsWriter()",
                              ^
/home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/ServerAttributes.h:79:30: error: expected ‘,’ or ‘...’ before numeric constant
/home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/ServerAttributes.h:80:50: error: ISO C++ forbids declaration of ‘FASTDDS_DEPRECATED_UNTIL’ with no type [-fpermissive]
             "Not implemented nor used functions.")
                                                  ^
/home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/ServerAttributes.h:80:50: error: expected ‘;’ at end of member declaration
             "Not implemented nor used functions.")
                                                  ^
                                                   ;
/home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/ServerAttributes.h:79:5: error: ‘int eprosima::fastdds::rtps::RemoteServerAttributes::FASTDDS_DEPRECATED_UNTIL(int)’ cannot be overloaded with ‘int eprosima::fastdds::rtps::RemoteServerAttributes::FASTDDS_DEPRECATED_UNTIL(int)’
     FASTDDS_DEPRECATED_UNTIL(3, "eprosima::fastrtps::rtps:GetEDPPublicationsWriter()",
     ^~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/ServerAttributes.h:72:5: note: previous declaration ‘int eprosima::fastdds::rtps::RemoteServerAttributes::FASTDDS_DEPRECATED_UNTIL(int)’
     FASTDDS_DEPRECATED_UNTIL(3, "eprosima::fastrtps::rtps:GetEDPPublicationsReader()",
^~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/ServerAttributes.h:82:30: error: expected identifier before numeric constant
     FASTDDS_DEPRECATED_UNTIL(3, "eprosima::fastrtps::rtps:GetEDPSubscriptionsReader()",
                              ^
/home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/ServerAttributes.h:82:30: error: expected ‘,’ or ‘...’ before numeric constant
/home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/ServerAttributes.h:83:50: error: ISO C++ forbids declaration of ‘FASTDDS_DEPRECATED_UNTIL’ with no type [-fpermissive]
             "Not implemented nor used functions.")
                                                  ^
/home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/ServerAttributes.h:83:50: error: expected ‘;’ at end of member declaration
             "Not implemented nor used functions.")
                                                  ^
                                                   ;
/home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/ServerAttributes.h:82:5: error: ‘int eprosima::fastdds::rtps::RemoteServerAttributes::FASTDDS_DEPRECATED_UNTIL(int)’ cannot be overloaded with ‘int eprosima::fastdds::rtps::RemoteServerAttributes::FASTDDS_DEPRECATED_UNTIL(int)’
     FASTDDS_DEPRECATED_UNTIL(3, "eprosima::fastrtps::rtps:GetEDPSubscriptionsReader()",
     ^~~~~~~~~~~~~~~~~~~~~~~~
/home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/ServerAttributes.h:72:5: note: previous declaration ‘int eprosima::fastdds::rtps::RemoteServerAttributes::FASTDDS_DEPRECATED_UNTIL(int)’
     FASTDDS_DEPRECATED_UNTIL(3, "eprosima::fastrtps::rtps:GetEDPPublicationsReader()",
     ^~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [src/cpp/CMakeFiles/fastrtps.dir/build.make:193: src/cpp/CMakeFiles/fastrtps.dir/rtps/writer/RTPSWriter.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:987: src/cpp/CMakeFiles/fastrtps.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
Failed   <<< fastrtps [12.3s, exited with code 2]
   Summary: 42 packages finished [2min 11s]
  1 package failed: fastrtps
  1 package had stderr output: fastrtps
  225 packages not processed`
## System information
Raspberry Pi 4 OS Raspbian 

- Fast-RTPS version: 2.0.x
- OS: Raspbian
- ROS2: ROS2 Foxy

**Comment by EduPonz** [comment]
On the trace I can see
```
/home/pi/ros2_foxy/src/eProsima/Fast-DDS/include/fastdds/rtps/attributes/ServerAttributes.h:72:30: error: expected identifier before numeric constant FASTDDS_DEPRECATED_UNTIL...
```
However, macro `FASTDDS_DEPRECATED_UNTIL` is not present in that file neither on 2.0.x nor on 2.1.x, but on master instead. I suspect that you're not using the appropriate Fast DDS branch on the build, or have some mixed installation getting in your way. Could you double check the Fast DDS branch you're attempting to compile? To speed up the process you could build with `colcon build --packages-up-to fastrtps`

**Comment by KanwalAshraf** [comment]
I tried compilation again with `colcon build --packages-up-to fastrtps` and i see the same error. From ros2.repos, it seems the version is correct
`eProsima/Fast-DDS:
    type: git
    url: https://github.com/eProsima/Fast-DDS.git
    version: 2.0.x`
I can see that in the ServerAttributes.h file the `FASTDDS_DEPRECATED_UNTIL` in the version i'm using and also on the FastDDS repository is as:
`FASTDDS_DEPRECATED_UNTIL(3, "eprosima::fastrtps::rtps:GetEDPPublicationsReader()",
            "Not implemented nor used functions.")`
So I'm not sure what am I doing wrong here.

**Comment by EduPonz** [comment]
Hi @KanwalAshraf ,

Could you please do:

```bash
cd <path_to_workspace>/src/eProsima/Fast-DDS  # Go to Fast DDS repository
git log --oneline -n1  # See branch and commit
git checkout 2.0.x  # Make sure you're in 2.0.x branch
git pull  # Update branch
cd ../../../
colcon build --packages-up-to fastrtps --cmake-clean-cache # Build
```

**Comment by JLBuenoLopez-eProsima** [comment]
I am going to close this issue as no answer has been received in almost a year. Besides, as it has been said, the officially supported branch for ROS 2 Foxy is 2.1.x which does not include the mentioned macros. Consequently, this is not an official and supported installation of ROS 2 Foxy.
