### ISSUE TITLE
Missing fastddsgen and fastddsgen.jar in the eProsima_Fast-DDS-2.1.0-Linux official release [13592]

### ISSUE THREAD

**Issue by lycpaul** [eProsima/Fast-DDS#1677]
I used to use the installation script from the official release to install fastdds but the latest release ([eProsima_Fast-DDS-2.1.0-Linux](https://www.eprosima.com/index.php/component/ars/repository/eprosima-fast-dds/eprosima-fast-dds-2-1-0)) seems only contains ```java/fastrtpsgen``` and missing the ```java/fastddsgen.jar``` and ```java/fastddsgen``` required in the ```install.sh``` so it fails to install the ```fastddsgen``` at the end of the script.

**Comment by edgarcamilocamacho** [comment]
Yes, I found that too. I am using this repo for the generator: https://github.com/eProsima/Fast-DDS-Gen

**Comment by lycpaul** [comment]
It seems that 2.1.0 and 2.0.0 using the same ```fastddsgen``` version, so I just use the one from the 2.0.0 official release and change the last few lines of ```install.sh``` to this:

```
mkdir -p /usr/local/share/fastrtpsgen/java
cp java/fastrtpsgen.jar /usr/local/share/fastrtpsgen/java
cp java/fastrtpsgen /usr/local/bin/
cp -r doc/ /usr/local/share/fastrtps/
```

**Comment by JLBuenoLopez-eProsima** [comment]
I will proceed and close this issue as the later releases have solved this. Also, we have included a step in our release testing that checks that the installer includes Fast DDS-Gen so this issue is not expected to happen in future releases.
