### ISSUE TITLE
Strings not working with map [12537]

### ISSUE THREAD

**Issue by edgarcamilocamacho** [eProsima/Fast-DDS#1689]
When I try to generate the **cxx** and **h** files from the next **idl**:

```
struct AsyncCommand
{
    string app_id;
    string command;
    map<string, double> parameters;
};
```

I get the following error:

```
...
ERROR: Class com.eprosima.idl.parser.typecode.StringTypeCode has no such attribute: size in template context [struct_type if(ctx.anyCdr)_subtemplate anonymous if(!member.annotationNonSerialized)_subtemplate max_serialized_size elseif(typecode.isMapType)_subtemplate map_max_serialized_size]
...
```

But not getting the error when not using string in the map:

```
struct AsyncCommand
{
    string app_id;
    string command;
    map<double, double> parameters;
};
```

Pd:
I also created an issue in the Generator Repository 23 days ago: https://github.com/eProsima/Fast-DDS-Gen/issues/50

**Comment by JLBuenoLopez-eProsima** [comment]
I am going to close this issue as it is related with other repository where this issue was also open (eProsima/Fast-DDS-Gen/#50).
