### ISSUE TITLE
ABI Versioning [10458]

### ISSUE THREAD

**Issue by roehling** [eProsima/Fast-DDS#1722]
I've seen that you carefully document API and ABI breakages, and follow the semantic versioning rules for the project version, which is really helpful. However, the project version only tracks the API compatibility. Any ABI breakage needs to bump the SOVERSION of the shared object.

Currently, the SOVERSION is set to `${PROJECT_VERSION_MAJOR}`, even though ABI breakages do occur more often. This makes it hard to properly package the library for distributions: you either break code that was linked against the older version, or you need to bump the SOVERSION specifically for (e.g.) Debian, which makes it incompatible with the upstream version.

It would be really helpful if you tracked the ABI version independently from the project version. I suggest you start from where you are with a numeric counter that is bumped whenever an incompatible change occurs ([protobuf](https://packages.debian.org/source/sid/protobuf) does it like this). As you're already tracking ABI breakages, this is trivial to implement and gives you the most flexibility.

Some projects prefer to use MAJOR.MINOR as ABI version, changing the SONAME on every minor release. This is useful if you expect to break ABI compatibility very often and do not wish to track this explicitly, but you might change the SONAME needlessly.

**Comment by MiguelCompany** [comment]
PR #1733 is addressing this. The PR has been approved and assigned to milestone v2.3.0. This way we will remember to merge it before the first ABI break to master, as we have stated [here](https://github.com/eProsima/Fast-DDS/pull/1733#issuecomment-773110214).

@roehling We consider this issue to be resolved, but we leave you the decision on when to close it.

**Comment by roehling** [comment]
Thank you! I'll close this issue as it is de facto a duplicate of #1733 now
