### ISSUE TITLE
codecvt template issue with libc++ LLVM implementation [10459]

### ISSUE THREAD

**Issue by asobhy-qnx** [eProsima/Fast-DDS#1724]
https://github.com/eProsima/Fast-DDS/blob/70e2ad09001cbe92eea7bfe66830099b96b6f7d4/src/cpp/utils/string_convert.cpp#L84 This affects the LLVM libc++ library which is being used by clang as well as other compilers such as qcc in QNX. I suggest either including:

`#if defined(__clang__) || defined(__QNXNTO__)`

or making it a bit more general by detecting whether the C++ lib is LLVM libc++ or GNU libstdc++ using:

`#ifndef __GLIBCXX__`

which will include any system using non gnu libc++ which includes the two options above

**Comment by EduPonz** [comment]
Hi @asobhy-qnx ,

Would you be so kind as to submit a PR for the fix?

**Comment by asobhy-qnx** [comment]
will do. Thanks.

**Comment by asobhy-qnx** [comment]
I would like to push the fix to master and 2.1.x
