### ISSUE TITLE
Yocto support for Fast-DDS

### ISSUE THREAD

**Issue by madmax440** [eProsima/Fast-DDS#1754]
Do you have a yocto package support anywhere  i could find and use?

## Expected Behavior
May have yocto meta layer for Fast-DDS

## Current Behavior
No yocto meta layer for Fast-DDS

## System information
Master branch

## Additional context
Projects such as in Automotive tend to use Yocto on the embedded linux and as well like to use Fast-DDS. Would be greatly appreciative if there is an available Yocto package.

Thanks.

**Comment by EduPonz** [comment]
Hi @madmax440 ,

Unfortunately, we do not support any Yocto recipe for Fast DDS. However, there is some work on the ROS 2 community for providing a ROS 2 layer that might interest you. I suppose you could simplify their layer for your needs.
https://discourse.ros.org/t/ros2-yocto-meta-layer/9643
https://github.com/ros-infrastructure/superflore

**Comment by madmax440** [comment]
Thanks Very much. Appreciate it.

**Comment by Muhammad540** [comment]
> Thanks Very much. Appreciate it.

@devendranaga did you manage run fast-dds on yocto ? I dont want to have the entire ROS2 on my embedded platform just to use fast-dds.
