### ISSUE TITLE
Publisher and subscriber nodes don't hear each other if one of them runs in a docker container. [13593]

### ISSUE THREAD

**Issue by wl2776** [eProsima/Fast-DDS#1755]
# The issue
The listener node from standard examples of ROS2 Foxy doesn't hear "hello"s from the talker node from the same examples if one of them runs in a docker container, based on Ubuntu 18.04, and both use FastDDS.

If at least one of nodes is switched to CycloneDDS (host or container, no matter), the issue disappears.

The issue has been reproduced several times on different physical and virtual PCs.

The issue is not observed on the `osrf/ros:foxy-desktop` docker image, based on Ubuntu 20.04, published by OSRF.

# Steps to reproduce

Host: Ubuntu 20.04. 
ROS2 is installed either from sources or from Debian packages. 
The issue is reproduced in both variants.

Container: based on Ubuntu 18.04, ROS2 installed from sources.
Image can be pulled from https://hub.docker.com/repository/docker/wl2776/nvidia-ros
Dockerfile will be attached to this issue.

No additional XML configurations. 

Run container without network isolation (`--net host`). 

```shell
# on host
$ docker run --rm -it --net host nvidia-ros

# in the container
root@lnx:~# env | grep ROS
ROS_DOMAIN_ID=142
ROS_VERSION=2
ROS_LOCALHOST_ONLY=0
ROS_PYTHON_VERSION=3
ROS_DISTRO=foxy
root@lnx:~# ros2 run examples_rclcpp_minimal_publisher publisher_member_function
[INFO] [1613117483.186436651] [minimal_publisher]: Publishing: 'Hello, world! 0'
[INFO] [1613117483.686272509] [minimal_publisher]: Publishing: 'Hello, world! 1'
[INFO] [1613117484.186273691] [minimal_publisher]: Publishing: 'Hello, world! 2'
[INFO] [1613117484.686271888] [minimal_publisher]: Publishing: 'Hello, world! 3'
```

Run subscriber node on the host in another terminal.

```bash
$ source /opt/ros/foxy/setup.zsh && export ROS_DOMAIN_ID=142
$ env | grep ROS
ROS_DISTRO=foxy
ROS_LOCALHOST_ONLY=0
ROS_PYTHON_VERSION=3
ROS_VERSION=2
ROS_DOMAIN_ID=142
$ ros2 run examples_rclcpp_minimal_subscriber subscriber_member_function
```

It doesn't hear anything.

Leave the publisher in the container running, stop the subscriber on the host, switch to CycloneDDS and run it on the host again. 

```bash
$ ros2 run examples_rclcpp_minimal_subscriber subscriber_member_function

^C[INFO] [1613117650.526890658] [rclcpp]: signal_handler(signal_value=2)
$ export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
$ env | grep ^R
ROS_DISTRO=foxy
ROS_LOCALHOST_ONLY=0
ROS_PYTHON_VERSION=3
ROS_VERSION=2
ROS_DOMAIN_ID=142
RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
$ ros2 run examples_rclcpp_minimal_subscriber subscriber_member_function

1613117678.140229 [142] subscriber: using network interface enp0s31f6 (udp/106.xxx.xxx.xxx) selected arbitrarily from: enp0s31f6, docker0
[INFO] [1613117679.686372183] [minimal_subscriber]: I heard: 'Hello, world! 393'
[INFO] [1613117680.186305884] [minimal_subscriber]: I heard: 'Hello, world! 394'
[INFO] [1613117680.686421621] [minimal_subscriber]: I heard: 'Hello, world! 395'
[INFO] [1613117681.186358354] [minimal_subscriber]: I heard: 'Hello, world! 396'
```

Stop the subscriber on the host, switch back to FastDDS and run it on the host again

```bash 
[INFO] [1613117681.186358354] [minimal_subscriber]: I heard: 'Hello, world! 396'
^C[INFO] [1613117681.366692228] [rclcpp]: signal_handler(signal_value=2)
$ unset RMW_IMPLEMENTATION
$ env | grep ^R
ROS_DISTRO=foxy
ROS_LOCALHOST_ONLY=0
ROS_PYTHON_VERSION=3
ROS_VERSION=2
ROS_DOMAIN_ID=142
$ ros2 run examples_rclcpp_minimal_subscriber subscriber_member_function
```

The subscriber again doesn't hear anything

Stop the publisher in the container, switch to CycloneDDS and run it in the container again.

```bash
^C[INFO] [1613117842.463629626] [rclcpp]: signal_handler(signal_value=2)
root@lnx:~# export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
root@lnx:~# env | grep ^R
ROS_DOMAIN_ID=142
ROS_VERSION=2
ROS_LOCALHOST_ONLY=0
ROS_PYTHON_VERSION=3
RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
ROS_DISTRO=foxy
root@lnx:~# ros2 run examples_rclcpp_minimal_publisher publisher_member_function
1613117947.691213 [142] publisher_: using network interface enp0s31f6 (udp/106.xxx.xxx.xxx) selected arbitrarily from: enp0s31f6, docker0
[INFO] [1613117948.200518662] [minimal_publisher]: Publishing: 'Hello, world! 0'
[INFO] [1613117948.700400226] [minimal_publisher]: Publishing: 'Hello, world! 1'
[INFO] [1613117949.200452826] [minimal_publisher]: Publishing: 'Hello, world! 2'
[INFO] [1613117949.700449752] [minimal_publisher]: Publishing: 'Hello, world! 3'
[INFO] [1613117950.200470917] [minimal_publisher]: Publishing: 'Hello, world! 4'

```

And the subscriber in the host writes that it has heard "Hello world"

Same issue reproduces if I swap subscriber and publisher and run subscriber in the container, and publisher on the host.

# Additional details.

Thorough investigation of the issue is provided in this question https://answers.ros.org/question/370595/ros2-foxy-nodes-cant-communicate-through-docker-container-border/
In short: traffic, produced by the publisher in the container is seen on the host by `tcpdump` or `netcat`. Wireshark successfully parses packets, saved by tcpdump, as valid RTPS packets.

I've also tried launching another container from the same image - again, no "I've heard hellos".

I've also tried running a container from the ROS2 image, published by OSRF (https://hub.docker.com/layers/osrf/ros/foxy-desktop/). And here participants have heard each other.

_Originally posted by @wl2776 in https://github.com/eProsima/Fast-DDS/issues/1698#issuecomment-777565621_

According to comment from @richiware, 

> The last releases of Fast-DDS come with SharedMemory transport by default. Using `--net=host` implies both DDS participants believe they are in the same machine and they try to communicate using SharedMemory instead of UDP. We will implement a mechanism to detect this kind of situation.

**Comment by wl2776** [comment]
Attaching Dockerfile: 

[Dockerfile.txt](https://github.com/eProsima/Fast-DDS/files/5970586/Dockerfile.txt)

Content of file ros2_entrypoint.sh, referenced in it:

```bash
#!/bin/bash -e

# setup ros2 environment
source "/opt/ros/foxy/setup.bash"
export ROS_DOMAIN_ID=142
exec "$@"
```

**Comment by erd3muysal** [comment]
Having same trouble in Nvidia enabled Docker container build via following Dockerfile;

```
FROM osrf/ros:foxy-desktop

# nvidia-container-runtime
ENV NVIDIA_VISIBLE_DEVICES \
    ${NVIDIA_VISIBLE_DEVICES:-all}
ENV NVIDIA_DRIVER_CAPABILITIES \
    ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics

```
Running the Docker image via following bash scrip;

```
#!/usr/bin/env bash

XAUTH=/tmp/.docker.xauth
touch $XAUTH
xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -

if [ ! -f $XAUTH ]
then
    xauth_list=$(xauth nlist :0 | sed -e 's/^..../ffff/')
    if [ ! -z "$xauth_list" ]
    then
        echo $xauth_list | xauth -f $XAUTH nmerge -
    else
        touch $XAUTH
    fi
    chmod a+r $XAUTH
fi

docker run -it \
    --env="DISPLAY=$DISPLAY" \
    --env="QT_X11_NO_MITSHM=1" \
    --env="XAUTHORITY=$XAUTH" \
    --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw" \
    --volume="$XAUTH:$XAUTH" \
    --volume="/home/ubuntu/.ros:/root/.ros" \
    --runtime=nvidia \
    --network=host \
    --name=ros_nvida \
    --privileged \
    ros-nvidia \
    bash
```

Within the first terminal in Docker container:
```
root@neuromancer:~/.ros/ws# env | grep ROS
ROS_VERSION=2
ROS_PYTHON_VERSION=3
ROS_DOMAIN_ID=101
ROS_LOCALHOST_ONLY=0
ROS_DISTRO=foxy

root@neuromancer:~/.ros/ws# ros2 topic pub --rate 0.5 /dolly/cmd_vel geometry_msgs/msg/Twist "{linear: {x: 2.0, y: 0.0, z: 0.0}, angular: {x: 0.0, y: 0.0, z: 1.8}}"
publisher: beginning loop
publishing #1: geometry_msgs.msg.Twist(linear=geometry_msgs.msg.Vector3(x=2.0, y=0.0, z=0.0), angular=geometry_msgs.msg.Vector3(x=0.0, y=0.0, z=1.8))

publishing #2: geometry_msgs.msg.Twist(linear=geometry_msgs.msg.Vector3(x=2.0, y=0.0, z=0.0), angular=geometry_msgs.msg.Vector3(x=0.0, y=0.0, z=1.8))

publishing #3: geometry_msgs.msg.Twist(linear=geometry_msgs.msg.Vector3(x=2.0, y=0.0, z=0.0), angular=geometry_msgs.msg.Vector3(x=0.0, y=0.0, z=1.8))
```
Within the second terminal in the Docker container;
```
root@neuromancer:~/.ros/ws# env | grep ROS
ROS_VERSION=2
ROS_PYTHON_VERSION=3
ROS_DOMAIN_ID=101
ROS_LOCALHOST_ONLY=0
ROS_DISTRO=foxy

root@neuromancer:~/.ros/ws# ros2 topic echo /dolly/cmd_vel
linear:
  x: 0.0
  y: 0.0
  z: 0.0
angular:
  x: 0.0
  y: 0.0
  z: 0.0
---
linear:
  x: 0.0
  y: 0.0
  z: 0.0
angular:
  x: 0.0
  y: 0.0
  z: 0.0
---
linear:
  x: 0.0
  y: 0.0
  z: 0.0
angular:
  x: 0.0
  y: 0.0
  z: 0.0
---
```

**Comment by JLBuenoLopez-eProsima** [comment]
Limitations to the default SHM transport are known when using multi-user environments and docker containers due to permissions and the manner that Fast DDS considers that a process is running in the same host. Probably disabling the SHM transport and using an UDP transport is enough to solve this problem as explained in #3575. I am going to close this issue because the corresponding ticket is already created in the Ideas discussion forum, #3569, where enhancements and feature requests are handled as per Fast DDS Contributing guidelines.
