### ISSUE TITLE
posix_fallocate does not work on shared memory on QNX

### ISSUE THREAD

**Issue by asobhy-qnx** [eProsima/Fast-DDS#1765]
https://github.com/eProsima/Fast-DDS/blob/0149608645c53a563472f4cddd42d8980e38aa31/thirdparty/boost/include/boost/interprocess/shared_memory_object.hpp#L399

Is there a reason posix_fallocate() is used instead of ftruncate()? posix_fallocate returns an error code: "The fd argument doesn't refer to a regular file." which is due to that the file is a shared memory object and not an actual file.

Is there any drawbacks of using ftruncate instead?

**Comment by MiguelCompany** [comment]
@asobhy-qnx The reason why `ftruncate` may cause malfunction on some systems is explained [here](https://github.com/eProsima/Fast-DDS/pull/1248#issue-427765367)

If we can ensure that `ftruncate` fails on QNX if `length` bytes cannot be allocated, then I guess we can wrap [this line](https://github.com/eProsima/Fast-DDS/blob/0149608645c53a563472f4cddd42d8980e38aa31/thirdparty/boost/include/boostconfig.hpp#L21) inside an `#if !defined(__QNXNTO__)`

**Comment by asobhy-qnx** [comment]
ftruncate will fail when there is no more physical memory.

**Comment by MiguelCompany** [comment]
@asobhy-qnx PR #1773 should fix this issue. Please check on your side.

**Comment by asobhy-qnx** [comment]
Yes I tested it and works, Thank you.

**Comment by MiguelCompany** [comment]
@asobhy-qnx The patch is on master, 2.2.x, 2.1.x and 2.2.x
