### ISSUE TITLE
Always print "Cannot get MAC addresses. Failing back to IP based ID", when run fastdds demo on QNX7+ArmV8 target board [10882]

### ISSUE THREAD

**Issue by liutiegang** [eProsima/Fast-DDS#1777]
Always print "Cannot get MAC addresses. Failing back to IP based ID", when run fastdds demo on QNX7+ArmV8 target board
Seems this print line "Cannot get MAC addresses. Failing back to IP based ID" has no effect on running fastdds demo.

Could anyone please give some help on how to remove this print line?

Thanks.

**Comment by IkerLuengo** [comment]
Some of the features of FastDDS need to use a host-specific UID for applications running on the same host to know they are indeed running on the same host. We try to get the system's MAC addresses to generate this UID. Unfortunately, retrieving the MAC addresses requires very platform specific code, and we have done it only for the supported platforms. For all remaining platforms, the GUID generation falls back to using the system's IP addresses, which can be retrieved in a more standard way, at least for POSIX platforms.

Most of the time there is no difference between both approaches, and the print is there just as a warning to be aware that IP addresses are being used to get the host UID. This can be relevant in certain deployments where FastDDS is running inside containers, depending on the network interface configuration.

The method to blame is [here](https://github.com/eProsima/Fast-DDS/blob/42eab30e034e4b6db823fe7b19944e49230d5640/src/cpp/utils/IPFinder.cpp#L327). We would need support from the QNX community to add an implementation that works on that platform. We are also considering moving the print line to a warning log.

**Comment by IkerLuengo** [comment]
@liutiegang can you please try with branch [bugfix/mac-address-qnx](https://github.com/eProsima/Fast-DDS/tree/bugfix/mac-address-qnx)?

It is just a try adding platforms that define `__QNXNTO__` to the same MAC-retrieving algorithm as the ones defining `__linux__`. We don't know if it will work, but it's worth a shot.

**Comment by liutiegang** [comment]
Hi, I had a short time to try it, but I must change the implementation of IPFinder::getAllMACAddress for QNX OS

The new implementation is following:
bool IPFinder::getAllMACAddress(
        std::vector<info_MAC>* macs)
{
    struct ifaddrs *ifap, *ifaptr;
    unsigned char *ptr;
    if (getifaddrs(&ifap) == 0) {
        for(ifaptr = ifap; ifaptr != NULL; ifaptr = (ifaptr)->ifa_next) {

            if (((ifaptr)->ifa_addr)->sa_family == AF_LINK) {
                ptr = (unsigned char *)LLADDR((struct sockaddr_dl *)(ifaptr)->ifa_addr);
            
		info_MAC mac;
           	memcpy(mac.address, ptr, 6);

	    	if (std::find(macs->begin(), macs->end(), mac) == macs->end())
	    	{
	        	macs->push_back(mac);
	    	}

                printf("%s: %02x:%02x:%02x:%02x:%02x:%02xn",
                                    (ifaptr)->ifa_name,
                                    *ptr, *(ptr+1), *(ptr+2), *(ptr+3), *(ptr+4), *(ptr+5));
            }

        }
        freeifaddrs(ifap);
        return true;
    } else {
        return false;
    }   
}

Thanks.

**Comment by asobhy-qnx** [comment]
Here is another similar implementation. The only difference is that I check that the ip address list already found from getip() and I only add the mac address for that corresponds to an ip address in the list of ips. I do not know if it makes a difference but this seems to be as close as possible to the other implementations for the other OSes.
```
bool IPFinder::getAllMACAddress(
        std::vector<info_MAC>* macs)
{
    struct ifaddrs *ifaphead;
    struct ifaddrs *ifap;

    if (getifaddrs(&ifaphead) != 0)
    {
        printf("get_if_name: getifaddrs() failed");
        return false;
    }

    struct sockaddr_dl *sdl = NULL;

    std::vector<IPFinder::info_IP> ips;
    IPFinder::getIPs(&ips);

    for (auto& ip : ips){

        for (ifap = ifaphead; ifap; ifap = ifap->ifa_next)
        {
            if ((ifap->ifa_addr->sa_family == AF_LINK))
            {
                if (strcmp(ifap->ifa_name,ip.dev.c_str()) == 0)
                {
                    sdl = (struct sockaddr_dl *)ifap->ifa_addr;
                    if (sdl)
                    {
                        info_MAC mac;
                        memcpy(mac.address, LLADDR(sdl), sdl->sdl_alen);
                        if (std::find(macs->begin(), macs->end(), mac) == macs->end())
                        {
                            macs->push_back(mac);
                        }
                    }
                }
            }
        }
    }

    if(ifaphead)
    {
        freeifaddrs(ifaphead);
    }

    return true;
}
```

**Comment by IkerLuengo** [comment]
@liutiegang and @asobhy-qnx , thank you for your feedback.

We have added the implementation for QNX in pull request #1821.
