### ISSUE TITLE
For data-sharing delivery, spend much time (more than 10s) receiving messages if subscriber is terminated and restarted

### ISSUE THREAD

**Issue by Barry-Xu-2018** [eProsima/Fast-DDS#1783]
Test case:

1. Start a publisher in terminal A
2. Start a subscriber in terminal B
3. Terminal subscriber in terminal B
4. restart a subscriber in terminal B. And check received messages.

Qos Configuration: BEST_EFFORT_RELIABILITY_QOS, depth=10

## Expected Behavior
The subscriber can be restarted and receive messages from the publisher soon.

## Current Behavior
The subscriber is restarted and messages can be received after more than 10s

## Steps to Reproduce
1. Start a publisher in terminal A
2. Start a subscriber in terminal B
3. Terminal subscriber in terminal B
4. restart a subscriber in terminal B and check output received message 

You can use this test program which is modified based on the example `HelloWorldExampleDataSharing`. https://github.com/Barry-Xu-2018/Fast-DDS/commits/topic-shared-memory-test. 
1. Execute `./DDSHelloWorldExampleDataSharing -t publisher -c 10000` in terminal A
2. Execute `./DDSHelloWorldExampleDataSharing -t subscriber` in terminal B
3. In terminal B, do ctl+c to termiante subscriber
4. Re-execute `./DDSHelloWorldExampleDataSharing -t subscriber` in terminal B
5. Check output in terminal B. 

## System information

- Fast-RTPS version:  v2.2.0
- OS: ubuntu 20.04

**Comment by IkerLuengo** [comment]
This issue and #1782 share the same cause: the publisher is not aware of the terminating subscriber until the liveliness mechanism kicks in. There is a deeper analysis on #1782. I'll close this in favor of the other one.
