### ISSUE TITLE
no QNX implementation for getALLMACAddress

### ISSUE THREAD

**Issue by asobhy-qnx** [eProsima/Fast-DDS#1791]
Need to add an implementation for QNX for getALLMACAddress.

Another issue was discovered for detecting the mac address when testing master branch:

Cannot get MAC addresses. Failing back to IP based ID
1970-01-01 03:02:45.699 [RTPS_MSG_OUT Error] error: couldn't generate segment_name -> Function init
The issue is in the implementation of getAllMACAddress(). Even the Linux implementation does not work because ifr.ifr_hwaddr and SIOCGIFHWADDR are not in the QNX implementation of ioclt and struct ifreq

Here is an implementation for getAllMACAddress()

```
bool IPFinder::getAllMACAddress(
        std::vector<info_MAC>* macs)
{
    struct ifaddrs *ifaphead;
    struct ifaddrs *ifap;

    if (getifaddrs(&ifaphead) != 0)
    {
        printf("get_if_name: getifaddrs() failed");
        return false;
    }

    struct sockaddr_dl *sdl = NULL;

    std::vector<IPFinder::info_IP> ips;
    IPFinder::getIPs(&ips);

    for (auto& ip : ips){

        for (ifap = ifaphead; ifap; ifap = ifap->ifa_next)
        {
            if ((ifap->ifa_addr->sa_family == AF_LINK))
            {
                if (strcmp(ifap->ifa_name,ip.dev.c_str()) == 0)
                {
                    sdl = (struct sockaddr_dl *)ifap->ifa_addr;
                    if (sdl)
                    {
                        info_MAC mac;
                        memcpy(mac.address, LLADDR(sdl), sdl->sdl_alen);
                        if (std::find(macs->begin(), macs->end(), mac) == macs->end())
                        {
                            macs->push_back(mac);
                        }
                    }
                }
            }
        }
    }

    if(ifaphead)
    {
        freeifaddrs(ifaphead);
    }

    return true;
}
```

**Comment by asobhy-qnx** [comment]
duplicates #1777  closing.

**Comment by condor21** [comment]
I recently faced the same issue with ros2 installation on qnx system, however it seems functionally fine in spite of this error. Is there any possible influence on the ROS or DDS functionality? If it is not proper place to ask the question, I will remove it.
