### ISSUE TITLE
failed to build HelloWorldExample

### ISSUE THREAD

**Issue by simon13579** [eProsima/Fast-DDS#1808]
Hello,

Today I follow the readme and use "Colcon Installation" method, everything looks good, just a stderr is shown during the installation of foonathan_memory_vendor, but it looks finished anyway.
![Screenshot from 2021-03-05 21-51-18](https://user-images.githubusercontent.com/38149116/110198111-1b63a080-7e8b-11eb-9e5f-a3e36e30f852.png)

But when I try to build the HelloWorldExample, it reports the below error:
![Screenshot from 2021-03-05 22-51-02](https://user-images.githubusercontent.com/38149116/110198224-df7d0b00-7e8b-11eb-9ffd-89bde72eb6cb.png)

My system is Ubuntu 18.04.
Thanks!

Best Regards,
Simon

**Comment by edgarcamilocamacho** [comment]
Try to do the following:

``` bash
$ cd ~/Dev/fastdds_ws
$ source install/setup.bash
```

Using the same terminal, go to the HelloWorld folder and do `cmake ..`

If you build using colcon and don't install it in your system, you always must run `setup.bash` before building your projects.

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @simon13579,

Besides the solution in the previous comment (thanks @edgarcamilocamacho!), you can also build the examples using colcon enabling the corresponding CMake option:

```
colcon build --packages-select fastrtps --cmake-args -DCOMPILE_EXAMPLES
```

There is also a CMake option (`-DINSTALL_EXAMPLES`) that also installs them in the install folder of your colcon workspace. For more information about these options and other building options you may be interested in, please refer to our [documentation](https://fast-dds.docs.eprosima.com/en/latest/installation/configuration/cmake_options.html#cmake-options).

**Comment by simon13579** [comment]
Hi @edgarcamilocamacho @JLBuenoLopez-eProsima,

It works, thanks!
