### ISSUE TITLE
Compilibility of eProsima FastDDS and RTI Context DDS [10768]

### ISSUE THREAD

**Issue by ilikecola** [eProsima/Fast-DDS#1809]
I used eProsima FastDDS 2.2.0 and RTI Context DDS 6.0.1 for some demo example (both using out-of-box auto-generator),but the error below occurred. 

COMMENDSrWriterService_assertRemoteReader:Discovered remote reader with GUID 0X10F44B6,0XA8426118,0X1000000,0X200C7 using a non-addressable locator.
This can occur if the transport is not installed and/or enabled in the local participant.
See https://community.rti.com/kb/what-does-cant-reach-locator-error-message-mean for additional info.
can't reach: locator: 16://5544:B600:0000:0000:0000:0000:0000:0000:7412

and

"PRESPsReaderQueue_storeSampleData:deserialize sample error" which sometimes shows "invalid enumerator 0"

possible enumeration is:
enum TimeAccuracyKind {
                @value(14)                 TimeAccuracyKind_T2,
                @value(10)                 TimeAccuracyKind_T1,
                @value(16)                 TimeAccuracyKind_T3,
                @value(18)                 TimeAccuracyKind_T4,
                @value(20)                 TimeAccuracyKind_T5,
                @value(31)                 TimeAccuracyKind_UNDEFINED,
                @value(7)                 TimeAccuracyKind_T0

Thanks!

**Comment by ilikecola** [comment]
After digging into code and contacting with RTI, the first question is no solution, because there is no DDS-TCP standard launched, so it is impossible to be compatible for now.

And second, it's because fastdds code generator does not implement @value at enumeration, but it has api for getting value already.
I am working on it.

**Comment by JLBuenoLopez-eProsima** [comment]
Sorry for the late reply, @ilikecola,

First of all we would need some more information to be able to reproduce the issue in our side. Could you provide some detailed instructions about what demo you run and the steps you took?

**Comment by JLBuenoLopez-eProsima** [comment]
I am going to close this issue due to inactivity. More information is required and no answer has been received in the last month (see [CONTRIBUTING](https://github.com/eProsima/Fast-DDS/blob/master/CONTRIBUTING.md#issues)). Feel free to reopen providing the required information, though opening a new ticket using the issue template is advisable.
