### ISSUE TITLE
Segmentation fault in RTPSDomainImpl::find_local_reader [10842]

### ISSUE THREAD

**Issue by AtsushiMorinaga** [eProsima/Fast-DDS#1819]
# Segmentation fault in RTPSDomainImpl::find_local_reader

Callstack: 

```
Stack trace (most recent call last) in thread 29:
#10   Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#9    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f4a124874ce, in clone
#8    Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7f4a128bafa2, in 
#7    Object "/usr/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f4a127a7b2e, in 
#6    Object "/usr/local/lib/libfastrtps.so.0", at 0x7f4a12b64a26, in eprosima::fastrtps::rtps::ResourceEvent::event_service()
#5    Object "/usr/local/lib/libfastrtps.so.0", at 0x7f4a12b6452b, in eprosima::fastrtps::rtps::ResourceEvent::do_timer_actions()
#4    Object "/usr/local/lib/libfastrtps.so.0", at 0x7f4a12b65a3f, in eprosima::fastrtps::rtps::TimedEventImpl::trigger(std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >)
#3    Object "/usr/local/lib/libfastrtps.so.0", at 0x7f4a12b7ca64, in 
#2    Object "/usr/local/lib/libfastrtps.so.0", at 0x7f4a12b72bc3, in eprosima::fastrtps::rtps::StatefulWriter::intraprocess_heartbeat(eprosima::fastrtps::rtps::ReaderProxy*, bool)
#1    Object "/usr/local/lib/libfastrtps.so.0", at 0x7f4a12bff2cb, in eprosima::fastrtps::rtps::RTPSDomainImpl::find_local_reader(eprosima::fastrtps::rtps::GUID_t const&)
#0    Object "/usr/local/lib/libfastrtps.so.0", at 0x7f4a12bf4fb7, in eprosima::fastrtps::rtps::RTPSParticipantImpl::find_local_reader(eprosima::fastrtps::rtps::GUID_t const&)
Segmentation fault (Address not mapped to object [0x10])
``` 

RTPSDomainImpl::find_local_reader does not acquire the participant mutex lock.
`m_allReaderList` may be modified by other contexts while processing the for loop. 

```c++
RTPSReader* RTPSParticipantImpl::find_local_reader(
        const GUID_t& reader_guid)
{
    // As this is only called from RTPSDomainImpl::find_local_reader, and it has
    // the domain mutex taken, there is no need to take the participant mutex
    // std::lock_guard<std::recursive_mutex> guard(*mp_mutex);
    for (auto reader : m_allReaderList)
    {
        if (reader->getGuid() == reader_guid)
        {
            return reader;
        }
    }

 

    return nullptr;
}
```

Does the domain mutex protect `m_allReaderList`?

## Expected Behavior

No crash

## Current Behavior

Rarely crash

## Steps to Reproduce

1. Run multiple participants and read/write some data.
2. Heartbeat event and matching event occur at the same time?

Sorry, I'm not sure.

## System information

Fast-RTPS version: 2.2.0  
OS: Debian 10

**Comment by fujitatomoya** [comment]
@AtsushiMorinaga 

although you don't have concrete reproducible method, could you elaborate the behavior of your application to meet this crash stack a little bit?

- when this problem happens? only startup time for the application? or after long running, this problem suddenly happens?
- in the participant, multiple publisher and subscribers?
- how often does it create/destroy publisher and subscribers?

> m_allReaderList may be modified by other contexts

that could be only explanation, i guess. (if possible, I'd like to see the debug symbols.)

https://github.com/eProsima/Fast-DDS/blob/bf1ca5546725ec8dbe173b6fd98200bc16229655/src/cpp/rtps/participant/RTPSParticipantImpl.cpp#L978-L980

as far as i see, i wonder this covers the following...

https://github.com/eProsima/Fast-DDS/blob/bf1ca5546725ec8dbe173b6fd98200bc16229655/src/cpp/rtps/participant/RTPSParticipantImpl.cpp#L790

**Comment by MiguelCompany** [comment]
@AtsushiMorinaga @fujitatomoya I think there is a bug here. Adding something to `m_allReaderList` should be protected by the domain mutex, and as far as I can tell it doesn't seem to be that way.

I'm currently testing a hotfix. Will keep you informed.

**Comment by MiguelCompany** [comment]
@AtsushiMorinaga @fujitatomoya PR #1823 should fix this issue. I thought [this test]() should have caught this bug, but it seems it is not strong enough.

Can you think of a better way to test this? I would like to add such a test to the PR if possible.

**Comment by AtsushiMorinaga** [comment]
Thanks!
I think it is very difficult to cause this intentionally. I couldn't come up with a better way :pensive:

**Comment by fujitatomoya** [comment]
> Can you think of a better way to test this? I would like to add such a test to the PR if possible.

I believe this test makes sense, albeit not sure if specific time window to hit this race condition can be simulated.
