### ISSUE TITLE
How to use the latest version of Fast DDS as middleware on ROS 2 Eloquent?

### ISSUE THREAD

**Issue by liyue75** [eProsima/Fast-DDS#1833]
I am using ros2_eloquent, its default middleware is FastDDS, and the version is FastRTPSv1.9.3.   
The latest version of FastDDS has been updated to version 2.2.0. I was wondering if I could use version 2.2.0 for Eloquent as its middleware?    
How to do this? Do I need to modify RMW_FASTRTPS_CPP, add FastDDSv2.2.0's src and compile ros2 again?

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @liyue75,

We tried recently just this. Just follow the steps below and you should be able to update to the latest Fast DDS version working with ROS 2 Eloquent.

1. Follow the instructions provided by ROS 2 to [build ROS 2 Eloquent from sources](https://index.ros.org/doc/ros2/Installation/Eloquent/Linux-Development-Setup/). Before running the step [Build the code in the workspace](https://index.ros.org/doc/ros2/Installation/Eloquent/Linux-Development-Setup/#build-the-code-in-the-workspace), the next changes should be done in the following repositories.
2. Fast DDS: checkout v2.2.0 branch

```
cd [ROS 2 Eloquent workspace]/src/eProsima/Fast-DDS
git fetch
git checkout v2.2.0
```

3. It is advisable to also update to the latest version of Fast CDR

```
cd [ROS 2 Eloquent workspace]/src/eProsima/Fast-DDS
git fetch
git checkout v1.0.20
```

4. RMW FastRTPS: there is an API break between the newest releases of Fast DDS and the release being used in ROS 2 Eloquent. The `fastdds_api_break_eloquent.patch` patch below should be applied (Please, pay attention that I have to add the extension `.txt` to upload the file here):

[fastdds_api_break_eloquent.patch](https://github.com/eProsima/Fast-DDS/files/6148195/fastdds_api_break_eloquent.patch.txt)

```
cd [ROS 2 Eloquent workspace]/src/ros2/rmw_fastrtps
git apply fastdds_api_break_eloquent.patch
```

5. Proceed with ROS 2 Eloquent build from sources instructions.

We have just made some basic testing and it seems to work correctly. Please, let us known if you run into any issue.

**Comment by liyue75** [comment]
@JLBuenoLopez-eProsima Thank you, it works. 
If I meet problems later, I will open a new issue.
