### ISSUE TITLE
src\cpp\utils\IPFinder.cpp not compiling for QNX due to include of wrong header

### ISSUE THREAD

**Issue by pablorcum** [eProsima/Fast-DDS#1840]
This issue is related to #1777. The implementation is right but in line 52 the included header is wrong. See below.

## Expected Behavior
Insert:
`#include <net/if_dl.h>
`
## Current Behavior
Replace:
`#include <sys/types.h>
`
## System information
- Fast-RTPS version: 60efaa53805c1909bd0156f034705fe5d0bb071c
- OS: QNX v7.1

**Comment by MiguelCompany** [comment]
@pablorcum Would you mind doing the change yourself and opening a PR?

**Comment by pablorcum** [comment]
It is a bit complicated for me at the time to submit the change. Please feel free to eventually commit it yourself.

**Comment by MiguelCompany** [comment]
Closing via #1843
