### ISSUE TITLE
Issue with Creating Demo HelloWorld Application [13596]

### ISSUE THREAD

**Issue by vectorSigma54** [eProsima/Fast-DDS#1854]
Hi guys ! I am new to DDS/RTPS protocols and was trying to get started with using Fast DDS by building the example listed [here](https://fast-dds.docs.eprosima.com/en/latest/fastdds/getting_started/simple_app/simple_app.html#write-the-fast-dds-publisher).
But for some reason, the publisher and subscribers are not interacting with each other.
![Screenshot (19)](https://user-images.githubusercontent.com/81268425/112229200-8ae1da00-8c58-11eb-8e20-f8e04b598aea.png)
**PUBLISHER**
![Screenshot (20)](https://user-images.githubusercontent.com/81268425/112229205-8e756100-8c58-11eb-8fac-a2d2125e28ca.png)
**SUBSCRIBER**
I am not sure how I am supposed to proceed with this.
Currently am using the latest version of Fast-DDS and Ubuntu 20.04 (WSL)

**Comment by JLBuenoLopez-eProsima** [comment]
Sorry for the late reply, @vectorSigma54 

I do not see why it is not working. Maybe it has something to do with the [SharedMemoryTransport](https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/shared_memory/shared_memory.html) that it is enable by deafult in the latest releases of Fast DDS. This means that if Fast DDS detects that both applications are running in the same host, it will use this transport layer. You can disable SHM and leave only UDP transport layer following the instructions in [this comment](https://github.com/eProsima/Fast-DDS/issues/1750#issuecomment-777348328) in case there is some issue preventing shared memory in your host.

I also suggest trying the [HelloWorldExample](https://github.com/eProsima/Fast-DDS/tree/master/examples/C%2B%2B/DDS/HelloWorldExample) included in the repository.

**Comment by JLBuenoLopez-eProsima** [comment]
I am going to close this issue due to inactivity, as no answer has been received in the last month. @vectorSigma54, feel free to reopen if you still need help. Also, I would like to clarify that the code of the example is run in the documentation test suite, so the code is functional.
