### ISSUE TITLE
Support for C#?

### ISSUE THREAD

**Issue by ChuiVanfleet** [eProsima/Fast-DDS#1861]
Forgive me if this is the wrong place to ask this...

What would it take to get C# language support for fastrtps? How much work would that require?

Depending on the size and amount of work, we may have some bandwidth/budget to add this.

Thanks!

**Comment by EduPonz** [comment]
Hi @ChuiVanfleet ,

The best approach would be to write an email describing your use case / needs evaluation.support@eprosima.com. That way, the sales team can assist you directly.

I'll go ahead and close the issue. We'll be waiting for your email.
Thanks for your interest!
