### ISSUE TITLE
LivelinessManager remove writer issue [11017]

### ISSUE THREAD

**Issue by fenggaobj** [eProsima/Fast-DDS#1871]
Hi, I'am working on fastrtps 2.0.x version.

Maybe I found an issue in LivelinessManager.cpp.
In function "LivelinessManager::remove_writer",  the "writer"  will pointer the last object of the vector after calling "writers_.remove(writer)" ,   maybe the removing writer is not the last,  the result is it will notify the wrong guid writer(the remove opertion makes the iterator points to the last object in the vector) in the "writers_" vector by calling "callback_".

Should we put the "writers_.remove(writer)" after calling "callback_"  ?

Thanks a lot.

**Comment by MiguelCompany** [comment]
> Maybe I found an issue in LivelinessManager.cpp.
> In function "LivelinessManager::remove_writer", the "writer" will pointer the last object of the vector after calling "writers_.remove(writer)" , maybe the removing writer is not the last, the result is it will notify the wrong guid writer(the remove opertion makes the iterator points to the last object in the vector) in the "writers_" vector by calling "callback_".

Thank you very much for this analysis, I think you are right.

> Should we put the "writers_.remove(writer)" after calling "callback_" ?


The order should be preserved (i.e. writer removed before callback), but we can use the input arguments instead of accessing the `writer`, as we already checked they are equal above.

This is what I have done on #1782

**Comment by fenggaobj** [comment]
Thank you for the quick reply,  I will use  "input arguments" to callback and retry it.

**Comment by MiguelCompany** [comment]
This should have been fixed by #1872. Closing the issue.
