### ISSUE TITLE
Fast-DDS started before network interfaces

### ISSUE THREAD

**Issue by alsora** [eProsima/Fast-DDS#1880]
Hi, I'm running a ROS 2 application that uses Fast-DDS v2.0.2.
The application is started by a daemon script when the system boots up.

I noticed that sometimes the application starts sooner than all the network interfaces have been started and this results in ROS messages not being published on those interfaces that were not available at startup.

Is there a way to configure Fast-DDS such that it uses new network interfaces that were not available at the beginning?
I'm currently using a default Fast-DDS configuration.

Thank you

**Comment by MiguelCompany** [comment]
This is not currently possible. It was already reported in #664, where a change to the sources is suggested. That change will only work if your network interfaces have a fixed IP address assigned.

If you know the number of interfaces in advance, you could make your application wait for the interfaces to be ready using [this method](https://github.com/eProsima/Fast-DDS/blob/969bdfa055f48d28acede134d0333b2b0b045e2f/include/fastrtps/utils/IPFinder.h#L71)

**Comment by alsora** [comment]
Ok, thank you for the answer!
