### ISSUE TITLE
How to sniff the traffic of fast-DDS if the transport layer is using Shared Memory? [11135]

### ISSUE THREAD

**Issue by carlstand** [eProsima/Fast-DDS#1890]

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @carlstand,

You can use `rtps_dump_file_` member in the Shared Memory Transport Descriptor. This member contains the full path to a file and if it is not empty, the shared memory traffic is traced in that file (please refer to our [documentation](https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/shared_memory/shared_memory.html#sharedmemtransportdescriptor) for more information). You can set this variable either by code or an [XML configuration file](https://fast-dds.docs.eprosima.com/en/latest/fastdds/xml_configuration/transports.html#transport-descriptors).

The output file can be opened with Wireshark with the `Import from Hex Dump` option with `Raw IPv4` encapsulation type.

Please, be aware that this option only captures the traffic going through the Shared Memory transport. If you are using intraprocess, Data Sharing or Zero Copy, there is no tool implemented currently that allows the capture of the data being exchanged.

**Comment by JLBuenoLopez-eProsima** [comment]
I will close this issue as it has already been answered. Please, feel free to reopen it if you need some more help.
