### ISSUE TITLE
Data sharing should be disabled in LatencyTest benchmark without --data_sharing flag

### ISSUE THREAD

**Issue by JakubSosnovec** [eProsima/Fast-DDS#1898]
When no XML profile is passed to the LatencyTest benchmark, data sharing policy is set to automatic by default. This will mean that data sharing is enabled regardless whether the --data_sharing command line flag is passed to the program or not.

## Expected Behavior
Data sharing policy should be disabled when --data_sharing command line flag is not passed.

## Current Behavior
Data sharing policy is automatic (and thus enabled) even if --data_sharing command line flag is not passed.

## Steps to Reproduce
1. Run LatencyTest publisher and subscriber on the same device (to benchmark shared memory transport).
2. Try with passing --data_sharing flag.
3. Try without passsing --data_sharing flag.
4. Observe that the performance results are the same.

## Suggested fix
Explicitly set the DataSharingQosPolicy to "off" whenever the command line flag is not passed in. Could be done here: https://github.com/eProsima/Fast-DDS/blob/master/test/performance/latency/LatencyTestPublisher.cpp#L274 and https://github.com/eProsima/Fast-DDS/blob/master/test/performance/latency/LatencyTestSubscriber.cpp#L226

**Comment by MiguelCompany** [comment]
@JakubSosnovec Would you mind doing the changes yourself and submitting a PR?
