### ISSUE TITLE
New tag on the 2.3.x branch for ROS 2 Rolling [13604]

### ISSUE THREAD

**Issue by clalancette** [eProsima/Fast-DDS#1910]
It looks like there are a few fixes on the 2.3.x branch that are not yet tagged.  Could we please have a new tag on that branch so we can release those fixes into the binary Debian packages?  Thank you.

**Comment by EduPonz** [comment]
Hi @clalancette ,

We have merged two new fixes today. I've create the tag https://github.com/eProsima/Fast-DDS/tree/v2.3.0-1 for you. Thanks!

**Comment by clalancette** [comment]
Is there any chance this can be v2.3.1?  We can make a release with that other tag, but it is a bit difficult for us (since to our tools, it is effectively the same release number as the v2.3.0 tag).

**Comment by EduPonz** [comment]
Hi @clalancette ,

The thing is that v2.3.1 would mean a whole release process for us, and it's something that we have not planned until the 2nd week of May. Would a v2.3.0.1 be ok for you? Or do you just take up to micro version? 
We're already out for the day, but can discuss the possibility internally tomorrow, even have a chat with you at the end of our day if needed.

**Comment by clalancette** [comment]
Just to explain a few things about our versioning and release requirements:

1. Our tools currently really only understand X.Y.Z; everything else is a custom release.  So a v2.3.0.1 tag wouldn't really help with the current problem.
2. Because of the above, we probably won't do a new release with the v2.3.0-1 tag.
3. But it is fine for us not to have a tag for the latest code right now.  It just means that we won't be testing the latest code when we test our Debian packages.  There do look to be a few fixes between v2.3.0 and the latest that might be important, but we can go ahead without them.
4. We do appreciate a new release, but the 2nd week of May is going to be too late to get it into Galactic for release day.  We'll be deep into freeze at that point, and only critical bugfixes will be landing.  There are two options there: 1. Do a Fast-DDS release the last week of April (April 26-April 30), or 2. Do a Fast-DDS update for the first Galactic patch release.  Either should work, so it is up to you which way you want to go.  If you do decide to make a release the last week of April, then we'll need to have a tag no later than midnight Pacific time on April 29th, so we can re-bloom the package.

Let me know if this all makes sense to you.

**Comment by MiguelCompany** [comment]
@clalancette I have created v2.3.01, which I think is compatible with the X.Y.Z policy. We do prefer to have those bugfixes in as soon as possible, but spending resources in release testing when we are planning to do that in the near future seems a waste of time.

**Comment by EduPonz** [comment]
Hi @clalancette ,

I just wanted to let you know that we just released [Fast DDS v2.3.1](https://github.com/eProsima/Fast-DDS/releases/tag/v2.3.1)

> 4\. If you do decide to make a release the last week of April, then we'll need to have a tag no later than midnight Pacific time on April 29th, so we can re-bloom the package.

Is there anything we need to do on our side to have this tag included in ROS 2 Galactic release?

Thanks!

**Comment by MiguelCompany** [comment]
@clalancette I hope you didn't miss yesterday's comment from @EduPonz

**Comment by clalancette** [comment]
Apologies, I forgot about it today.  I'll work with some people and get CI and a release queued up early next week.

**Comment by EduPonz** [comment]
Hey, that's awesome! Don't worry about it, we know you guys have a lot on your plate. Just let us know if there's something we can do to help.

**Comment by MiguelCompany** [comment]
@clalancette Friendly ping

**Comment by JLBuenoLopez-eProsima** [comment]
I will proceed and close the issue as it was required for a specific ROS 2 Rolling release. Also, ROS 2 Rolling should be updated to use a more current branch to benefit from the latest features included in Fast DDS.
