### ISSUE TITLE
Why I cannot build the foonathan_memory_vendor successfully?

### ISSUE THREAD

**Issue by zijian1998** [eProsima/Fast-DDS#1913]
I tried to install the Fast-DDS with the help of [tutorial](https://fast-dds.docs.eprosima.com/en/latest/installation/sources/sources_linux.html). And I was failed when I 'colcon build' the foonathan_memory_vendor.
I built it on the "Ubuntu 20.04" OS.And the error was happened after I typed the` colcon build`.
The stderr.log is as following.

> Cloning into 'foo_mem-ext'...
> Note: switching to 'c619113'.
> 
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by switching back to a branch.
> 
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -c with the switch command. Example:
> 
>   git switch -c <new-branch-name>
> 
> Or undo this operation with:
> 
>   git switch -
> 
> Turn off this advice by setting config variable advice.detachedHead to false
> 
> HEAD is now at c619113 Whitespace clean up (#70)
> Submodule 'cmake/comp' (https://github.com/foonathan/compatibility.git) registered for path 'cmake/comp'
> Cloning into '/home/wzj/Fast-DDS/build/foonathan_memory_vendor/foo_mem-ext-prefix/src/foo_mem-ext/cmake/comp'...
> CMake Error at cmake/comp/comp_base.cmake:288 (message):
>   error downloading feature file cpp11_lib/max_align_t.cmake: "Failure when
>   receiving data from the peer".  Check spelling of feature.
> 
>     Trying 185.199.108.133:443...
> 
>   TCP_NODELAY set
> 
>   Connected to raw.githubusercontent.com (185.199.108.133) port 443 (#0)
> 
>   ALPN, offering h2
> 
>   ALPN, offering http/1.1
> 
>   successfully set certificate verify locations:
> 
>     CAfile: /etc/ssl/certs/ca-certificates.crt
>     CApath: /etc/ssl/certs
> 
>   [5 bytes data]
> 
>   TLSv1.3 (OUT), TLS handshake, Client hello (1):
> 
>   [512 bytes data]
> 
>   [5 bytes data]
> 
>   TLSv1.3 (IN), TLS handshake, Server hello (2):
> 
>   [122 bytes data]
> 
>   [5 bytes data]
> 
>   [5 bytes data]
> 
>   [1 bytes data]
> 
>   TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
> 
>   [19 bytes data]
> 
>   [5 bytes data]
> 
>   [1 bytes data]
> 
>   TLSv1.3 (IN), TLS handshake, Certificate (11):
> 
>   [3067 bytes data]
> 
>   [5 bytes data]
> 
>   [1 bytes data]
> 
>   TLSv1.3 (IN), TLS handshake, CERT verify (15):
> 
>   [264 bytes data]
> 
>   [5 bytes data]
> 
>   [1 bytes data]
> 
>   TLSv1.3 (IN), TLS handshake, Finished (20):
> 
>   [52 bytes data]
> 
>   [5 bytes data]
> 
>   TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
> 
>   [1 bytes data]
> 
>   [5 bytes data]
> 
>   [1 bytes data]
> 
>   TLSv1.3 (OUT), TLS handshake, Finished (20):
> 
>   [52 bytes data]
> 
>   SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
> 
>   ALPN, server accepted to use h2
> 
>   Server certificate:
> 
>    subject: C=US; ST=California; L=San Francisco; O=GitHub, Inc.; CN=www.github.com
>    start date: May  6 00:00:00 2020 GMT
>    expire date: Apr 14 12:00:00 2022 GMT
>    subjectAltName: host "raw.githubusercontent.com" matched cert's "*.githubusercontent.com"
>    issuer: C=US; O=DigiCert Inc; OU=www.digicert.com; CN=DigiCert SHA2 High Assurance Server CA
>    SSL certificate verify ok.
> 
>   Using HTTP2, server supports multi-use
> 
>   Connection state changed (HTTP/2 confirmed)
> 
>   Copying HTTP/2 data in stream buffer to connection buffer after upgrade:
>   len=0
> 
>   [5 bytes data]
> 
>   [1 bytes data]
> 
>   [5 bytes data]
> 
>   [1 bytes data]
> 
>   [5 bytes data]
> 
>   [1 bytes data]
> 
>   Using Stream ID: 1 (easy handle 0x560b1d2f63c0)
> 
>   [5 bytes data]
> 
>   [1 bytes data]
> 
>   GET /foonathan/compatibility/master/cpp11_lib/max_align_t.cmake HTTP/2
> 
> 
>   Host: raw.githubusercontent.com
> 
> 
>   user-agent: curl/7.66.0
> 
> 
>   accept: */*
> 
> 
>   
> 
> 
>   [5 bytes data]
> 
>   [1 bytes data]
> 
>   TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
> 
>   [193 bytes data]
> 
>   OpenSSL SSL_read: Connection reset by peer, errno 104
> 
>   Failed receiving HTTP2 data
> 
>   [5 bytes data]
> 
>   [1 bytes data]
> 
>   OpenSSL SSL_write: Broken pipe, errno 32
> 
>   Failed sending HTTP2 data
> 
>   Connection #0 to host raw.githubusercontent.com left intact
> 
> Call Stack (most recent call first):
>   cmake/comp/comp_base.cmake:347 (_comp_fetch_feature)
>   cmake/comp/comp_base.cmake:369 (_comp_handle_feature)
>   cmake/compatibility.cmake:13 (comp_target_features)
>   CMakeLists.txt:50 (include)
> 
> 
> make[2]: *** [CMakeFiles/foo_mem-ext.dir/build.make:108: foo_mem-ext-prefix/src/foo_mem-ext-stamp/foo_mem-ext-configure] Error 1
> make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/foo_mem-ext.dir/all] Error 2
> make: *** [Makefile:130: all] Error 2

It seems that my question is the same as the [#801](https://github.com/eProsima/Fast-DDS/issues/801). So I follow the comment , delete the build directory and try again. I tried 10 times at least, but nothing changed. 
Does anyone know where it's going wrong? Thanks.

**Comment by MiguelCompany** [comment]
It seems the connection to github when getting dependencies is being closed. Could you check the result of `wget https://raw.githubusercontent.com/foonathan/compatibility/master/cpp11_lib/max_align_t.cmake` ?

**Comment by zijian1998** [comment]
Yeah, I could get it.

> ~/Fast-DDS$ wget https://raw.githubusercontent.com/foonathan/compatibility/master/cpp11_lib/max_align_t.cmake
> --2021-04-13 20:31:28--  https://raw.githubusercontent.com/foonathan/compatibility/master/cpp11_lib/max_align_t.cmake
> Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
> Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 992 [text/plain]
> Saving to: ‘max_align_t.cmake’
> 
> max_align_t.cmake   100%[===================>]     992  --.-KB/s    in 0s      
> 
> 2021-04-13 20:31:29 (19.6 MB/s) - ‘max_align_t.cmake’ saved [992/992]

**Comment by zijian1998** [comment]
So,what should I do next to finish the tutorial?Can this cmake file help me to finish the build?

**Comment by lovetianer** [comment]
try change source list , maybe helpful

**Comment by MiguelCompany** [comment]
This is surely not a problem of Fast DDS, but a connectivity issue with github.
