### ISSUE TITLE
can't reconnect to the discovery server, resulting in lot of CLOSE_WAIT connections [13605]

### ISSUE THREAD

**Issue by yuraSomatic** [eProsima/Fast-DDS#1914]
## Current Behavior
2 ros nodes:
1 remote discovery server with public or local ip 1 
1 remote client with public or local ip 2 
Using FASTRTPS_DEFAULT_PROFILES_FILE for xml config setup (all configs from #1790)

1) start nodes, all working good
2) restart client node with same xml config. Restarted node can't communicate with other possible nodes (discovery server too)
3) if I restart this node again, with different `<transport_descriptor> <listening_ports> <port>` number - all working good
Restarting this node lot of times with different port numbers resulting in lot of CLOSE_WAIT connections on both (remote 1 and remote 2 sides). And new, different node, started with one of ports, used before wiht restarted node - can't communicate with other nodes. After restarting discovery server all CLOSE_WAIT connections cleared and i can use all ports again.
4) this happens with remotes in wan and lan scenarios, but not on localhost

## Expected Behavior
- All noodes should be able to communicate with restarted client node with no need to restart discovery server node or specifying new `<transport_descriptor> <listening_ports> <port>` number in client's xml config.
- Also it would be great to automaticly assign available port number to new client, without need to specify different port numbers for each client, resulting in redundant config files.

## System information
ros2 foxy default dds, ubuntu 20.04

**Comment by yuraSomatic** [comment]
Localhost reconnection works only with wan ip server, client configs

**Comment by JLBuenoLopez-eProsima** [comment]
Sorry for the late reply @yuraSomatic,

This issue seems related to #966. There are some issues when closing TCP connections and we are working on solving them.

**Comment by JLBuenoLopez-eProsima** [comment]
@yuraSomatic,

This issue might have been solved by #2470 which has been backported to the [currently supported releases](https://github.com/eProsima/Fast-DDS/blob/master/RELEASE_SUPPORT.md#release-support). Would you mind checking and if the issue has been solved close the issue?

**Comment by yuraSomatic** [comment]
Sorry, I can't. We preferred ZMQ over ros2 with DDS.

**Comment by yejw5** [comment]
@JLBuenoLopez-eProsima Before this issue fixed, could the vast CLOSE_WAIT sockets cause clients with new port connecting to server failed?

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @yejw5,

Before #2470 there were several issues related with the Discovery Server reconnection and the closing of TCP sockets, so I suggest you use one of the Fast DDS releases that have the patch included (releases `v2.6.0`, `v2.5.1`, `v2.4.2` or branches `2.1.x`, `2.3.x`)

**Comment by yejw5** [comment]
> Hi @yejw5,
> 
> Before #2470 there were several issues related with the Discovery Server reconnection and the closing of TCP sockets, so I suggest you use one of the Fast DDS releases that have the patch included (releases `v2.6.0`, `v2.5.1`, `v2.4.2` or branches `2.1.x`, `2.3.x`)

Thanks~
