### ISSUE TITLE
[11212] FOONATHAN_MEMORY_ASSERT(no_nodes > 0) in ProxyHashTable<eprosima::fastrtps::rtps::ReaderProxyData>::ProxyHashTable after update

### ISSUE THREAD

**Issue by ma30002000** [eProsima/Fast-DDS#1917]
After updating from FastRTPS 1.10.0 (works) to FastDDS 2.3.0 I run into the assertion

`FOONATHAN_MEMORY_ASSERT(no_nodes > 0)`

evaluated at foonathan::memory::detail::free_memory_list::insert_impl every time
when trying to create a participant, i.e. I cannot use FastDDS at all:

```
foonathan::memory::detail::free_memory_list::insert_impl 0x0000563012d7f7e0
foonathan::memory::detail::free_memory_list::insert 0x0000563012d7f428
foonathan::memory::memory_pool<foonathan::memory::node_pool, foonathan::memory::detail::lowlevel_allocator<foonathan::memory::detail::heap_allocator_impl> >::allocate_block 0x0000563012d868cf
foonathan::memory::memory_pool<foonathan::memory::node_pool, foonathan::memory::detail::lowlevel_allocator<foonathan::memory::detail::heap_allocator_impl> >::memory_pool<>(unsigned long, unsigned long) memory_pool.hpp:69
eprosima::fastrtps::rtps::detail::node_segregator<32ul, foonathan::memory::detail::lowlevel_allocator<foonathan::memory::detail::heap_allocator_impl> >::node_segregator ProxyHashTables.hpp:55
eprosima::fastrtps::rtps::detail::binary_node_segregator<32ul, foonathan::memory::detail::lowlevel_allocator<foonathan::memory::detail::new_allocator_impl> >::binary_node_segregator ProxyHashTables.hpp:127
eprosima::fastrtps::rtps::ProxyHashTable<eprosima::fastrtps::rtps::ReaderProxyData>::ProxyHashTable ProxyHashTables.hpp:173
eprosima::fastrtps::rtps::ParticipantProxyData::ParticipantProxyData ParticipantProxyData.cpp:67
eprosima::fastrtps::rtps::PDPListener::PDPListener PDPListener.cpp:48
eprosima::fastrtps::rtps::PDPSimple::createPDPEndpoints PDPSimple.cpp:266
eprosima::fastrtps::rtps::PDP::initPDP PDP.cpp:359
eprosima::fastrtps::rtps::PDPSimple::init PDPSimple.cpp:120
eprosima::fastrtps::rtps::BuiltinProtocols::initBuiltinProtocols BuiltinProtocols.cpp:126
eprosima::fastrtps::rtps::RTPSParticipantImpl::enable RTPSParticipantImpl.cpp:402
eprosima::fastrtps::rtps::RTPSParticipant::enable RTPSParticipant.cpp:170
eprosima::fastrtps::Domain::createParticipant Domain.cpp:205
main main.cpp:162
__libc_start_main 0x00007fe1d765fcb2
_start 0x000056301119302e
```

The code that performs the assertion looks like this:

```
char* ordered_free_memory_list::insert_impl(void* mem, std::size_t size) FOONATHAN_NOEXCEPT
{
    auto actual_size = node_size_ + 2 * fence_size();
    auto no_nodes    = size / actual_size;
    FOONATHAN_MEMORY_ASSERT(no_nodes > 0);
    [...]
```
    
For FastDDS 2.3.0, the following values are set:
size = 64
node_size = 32
debug_fence_size = 8 -> fence_size() = 32
-> actual_size = 96

For (working) FastRTPS 1.10.0 I get a very similar callstack:
```
foonathan::memory::detail::free_memory_list::insert_impl 0x00005574b6737b76
foonathan::memory::detail::free_memory_list::insert 0x00005574b67377e4
foonathan::memory::memory_pool<foonathan::memory::node_pool, foonathan::memory::detail::lowlevel_allocator<foonathan::memory::detail::heap_allocator_impl> >::allocate_block memory_pool.hpp:226
foonathan::memory::memory_pool<foonathan::memory::node_pool, foonathan::memory::detail::lowlevel_allocator<foonathan::memory::detail::heap_allocator_impl> >::memory_pool<>(unsigned long, unsigned long) memory_pool.hpp:69
eprosima::fastrtps::rtps::detail::node_segregator<32ul, foonathan::memory::detail::lowlevel_allocator<foonathan::memory::detail::heap_allocator_impl> >::node_segregator ProxyHashTables.hpp:60
eprosima::fastrtps::rtps::detail::binary_node_segregator<32ul, foonathan::memory::detail::lowlevel_allocator<foonathan::memory::detail::new_allocator_impl> >::binary_node_segregator ProxyHashTables.hpp:132
eprosima::fastrtps::rtps::ProxyHashTable<eprosima::fastrtps::rtps::ReaderProxyData>::ProxyHashTable ProxyHashTables.hpp:178
eprosima::fastrtps::rtps::ParticipantProxyData::ParticipantProxyData ParticipantProxyData.cpp:61
eprosima::fastrtps::rtps::PDPListener::PDPListener PDPListener.cpp:47
eprosima::fastrtps::rtps::PDPSimple::createPDPEndpoints PDPSimple.cpp:261
eprosima::fastrtps::rtps::PDP::initPDP PDP.cpp:332
eprosima::fastrtps::rtps::PDPSimple::init PDPSimple.cpp:119
eprosima::fastrtps::rtps::BuiltinProtocols::initBuiltinProtocols BuiltinProtocols.cpp:122
eprosima::fastrtps::rtps::RTPSParticipantImpl::enable RTPSParticipantImpl.cpp:384
eprosima::fastrtps::rtps::RTPSDomain::createParticipant RTPSDomain.cpp:197
eprosima::fastrtps::Domain::createParticipant Domain.cpp:168
main main.cpp:162
__libc_start_main 0x00007f2cd323ccb2
_start 0x00005574b4cd702e
```

However with a larger size:
size = 96
node_size = 32
debug_fence_size = 8 -> fence_size() = 32
-> actual_size = 96

So for some reason the "shrinking" of the allocated data structure seems no longer to be compatible with my free_memory_list apparently (at least on my platform/setting)

## Expected Behavior
Assertion passes

## Current Behavior
Assertion fails

## Steps to Reproduce
Call createParticipant()

## System information
Linux x64, (Ubuntu 20.10), gcc 10.2.0, nonoptimized debug build
FastRTSP/FastDDS versions 1.10.0(works), 2.3.0 (assertion thrown)
foonathan-memory 0.6.2 (same with 0.7)
boost 1.73.0
fastcdr 1.0.15
openssl 1.1.1c
tinyxml2 8.0.0

## Additional resources
- Wireshark capture 
- XML profiles file

**Comment by PFrieling** [comment]
I am having a similar experience. I previously used the Fast-DDS 2.2.0 binaries and yesterday tried to get Fast-DDS 2.3.0 running from sources on Windows 10. Somehow my executables, linked with version 2.3, crashed on start. Today i tried to use my previous projects, linked with Fast-DDS 2.2.0 and got the following issue:

If i execute the HelloWorldExample once (as a publisher), the program creates a participant and waits for subscribers. At the second execution (to create the subscriber node), the code freezes at Domain::createParticipant(PParam). If i quit the publisher, i get the following warnings:

> [foonathan::memory] Allocator foonathan::memory::new_allocator (at 0000000000000000) leaked 1024 bytes.
> [foonathan::memory] Allocator foonathan::memory::heap_allocator (at 0000000000000000) leaked 5040 bytes.

I have tested the following things:
1. I can run the same executable on another machine with fastcdr-1.0.dll, fastcdrd-1.0.dll, fastrtps-2.2.dll, fastrtpsd-2.2.dll, libcrypto-1_1-x64.dll and libssl-1_1-x64.dll and have no issues.
2. Similar, if i login as another user onto my machine, the HelloWorldExample works fine.
3. I can create a publisher on my machine and a subscriber on another machine, no issues.
4. If i switch to UDPv4 transport, the HelloWorldExample works on my machine.

**Comment by MiguelCompany** [comment]
@ma30002000 Could you please check that #1918 fixes your issue?

**Comment by ma30002000** [comment]
I will check but earliest tomorrow.

**Comment by ma30002000** [comment]
Ok, I can confirm that #1918 fixes my issue. Will this be part of the next release?

**Comment by MiguelCompany** [comment]
> Will this be part of the next release?

Definetely.
