### ISSUE TITLE
Does a vector in IDL file have a default maximun number of elements?

### ISSUE THREAD

**Issue by liyue75** [eProsima/Fast-DDS#1925]
I use fastddsgen to generate source files from an IDL file, my IDL file:
```
struct Msg {
sequence<octet> vector;
};
```
In my publisher program, I have a structer `Msg my_msg`, if I set the vector size to 200
```
my_msg.vector.resize(200);
std::vector<uint8_t> tmp(200);
my_msg.msg(tmp);
```
the program works well, the subscriber can receive my_msg, but if I set the vector size to 500:
```
my_msg.vector.resize(500);
std::vector<uint8_t> tmp(500);
my_msg.msg(tmp);
```
This time, the subscriber can not receive my_msg.

If I want to store a image which size is about 1 MB in a vector, then send the vector using fastdds, What should I do?
Does it have anything to do with fastcdr? How to set fastcdr?

## System information

- Fast-RTPS version: fastrtps:v2.3.0
- OS: Ubuntu18.04

**Comment by mtheall** [comment]
The default vector limit is 100 elements.

You can manually specify the limit (for example 1000) like this:
```
struct Msg {
sequence<octet, 1000> vector;
};
```

**Comment by liyue75** [comment]
@mtheall Yes, it works. Thank you.
