### ISSUE TITLE
WLP and WLPListener intra-process deadlock issue [13640]

### ISSUE THREAD

**Issue by fenggaobj** [eProsima/Fast-DDS#1950]
In WLP.cpp file in 2.0.x branch,  the "add_local_writer" and "remove_local_writer" api use the PDP's recursive_mutex.

For example:

> bool WLP::add_local_writer(
>         RTPSWriter* W,
>         const WriterQos& wqos)
> {
>     std::lock_guard\<std::recursive_mutex\> guard(*mp_builtinProtocols->mp_PDP->getMutex());
>     logInfo(RTPS_LIVELINESS, W->getGuid().entityId << " to Liveliness Protocol");
> 
> ...................................
> 

 I'm a bit confused why WLP does not create the recursive_mutex of its own?   it does not use the object from high level  in the api above.  Or want to protect the StatefulWriter parameter passed in "add_local_writer"  ?

Maybe WLP and WLPListener using the PDP's recursive_mutex at the same time will lead to ABBA deadlock in intraprocess liveliness report and assert.

**Comment by fenggaobj** [comment]
**In the same process**, there are 2 partitions(A and B), they announce the liveliness to each other at the same time.
The stack of the liveliness threads:

> ResourceEvent thread 1: WLP(hold partition A PDP recursive_mutex)->WriterHistory->StatefulWriter->ReaderProxy->ReaderLocator(found the  partition B' reader intraprocess)->StatefulReader->WLPListener(waiting partition B PDP recursive_mutex hold by WLP in thread 2)
> 
> ResourceEvent thread 2: WLP(hold partition B PDP recursive_mutex)->WriterHistory->StatefulWriter->ReaderProxy->ReaderLocator(found the  partition A' reader intraprocess)->StatefulReader->WLPListener(waiting partition A PDP recursive_mutex  hold by WLP in thread 1)

Maybe the two WLPs "send_liveliness_message" to each other in the same process, leads to the two WLPListeners wait PDP'recursive_mutex in another thread, the ABBA deadlock.

**Comment by MiguelCompany** [comment]
@fenggaobj  I've taken a quick look, and I do think there may be an issue. I still have to take a closer look, because I think the solution may involve other places in the code. I will try to allocate some time for it tomorrow.

**Comment by advancenOO** [comment]
I am wondering if we can change the order of PDP lock, from ABBA to ABAB.
Something like:

    // in Participant A, now we want PDP_B's lock
    bool WLP::add_local_writer() {
        if (A.guid < B.guid) {
            PDP_B->lock();
        } else {
            PDP_A->unlock();
            PDP_B->lock();
            PDP_A->lock();
        }
    }

But I guess the gap between PDP_A.unlock and PDP_A.lock is dangerous.

**Comment by fenggaobj** [comment]
@MiguelCompany Ping...  Any feedback and plan 
to fix the issue pls let me know.

**Comment by JLBuenoLopez-eProsima** [comment]
@fenggaobj,

Currently efforts to fix several issues reported by ThreadSanitizer are being made. Also, Fast DDS 2.0.x has reached [end of life](https://github.com/eProsima/Fast-DDS/blob/master/RELEASE_SUPPORT.md#release-support). Consequently I am going to close this issue as the branch is no longer supported, knowing that efforts are being made to solve this multithreading issues.
