### ISSUE TITLE
get_discovered_topics implementation

### ISSUE THREAD

**Issue by nickblockFB** [eProsima/Fast-DDS#1985]
We'd like to implement this function. We propose creating a "meta-topic" channel where we publish information about the other topics, then subscribers can subscribe to this channel to receive information about what topics are currently being published. Do you think this is a good idea? Do you have any advice about how to implement this?

**Comment by nickblockFB** [comment]
Having looked a little more at it, I dont think i need this meta topic. How would i enumerate the topics currently published?

**Comment by MiguelCompany** [comment]
You could set a [DomainParticipantListener](https://fast-dds.docs.eprosima.com/en/v2.3.2/fastdds/api_reference/dds_pim/domain/domainparticipantlistener.html), to your domain participant, and process the information received when `on_publisher_discovery` gets called.

**Comment by nickblockFB** [comment]
Thanks @MiguelCompany that sounds good.
