### ISSUE TITLE
createparticipant  crash

### ISSUE THREAD

**Issue by libfsw** [eProsima/Fast-DDS#1990]
When I call createparticipant, the program crashes

## System information

- Fast-RTPS version: 2.3.0，x86，vs2017
- 
- OS: win10
- Network interfaces: 
                      no  specified
- ROS2:

**Comment by MiguelCompany** [comment]
@libfsw As this mentions `x86`, I guess it may have been solved by #1982. Could you check if building against the current `2.3.x` branch solves your issue?
