### ISSUE TITLE
SQLite conflict [11751]

### ISSUE THREAD

**Issue by mtheall** [eProsima/Fast-DDS#1994]
My application uses Fast-DDS and Qt. It is accessing a SQLite database via Qt, which uses the system-installed libsqlite3.so. There are symbol conflicts where some symbols are resolved to libsqlite3.so and some symbols are resolved to libfastrtps.so, and in a few situations causes my application to crash, presumably due to an ABI mismatch.

## Expected Behavior
Configure Fast-DDS to build using the system-installed or user-provided sqlite3 shared library. Another option would be the ability to configure the embedded sqlite3 to have all hidden symbols.

## Current Behavior
Can only disable or enable sqlite3 support for persistence. Enabled always uses an embedded sqlite3.

## Steps to Reproduce
I don't have a simplified use-case (yet) but here is a sample stack trace:
```
received signal SIGSEGV, Segmentation fault.
__memmove_avx_unaligned_erms () from /lib64/libc.so.6
sqlite3_str_vappendf () from /lib64/libfastrtps.so.2.3
sqlite3_str_appendf () from /lib64/libfastrtps.so.2.3
sqlite3VdbeMemStringify.lto_priv.0 () from /lib64/libfastrtps.so.2.3
valueToText.lto_priv.0 () from /lib64/libfastrtps.so.2.3
columnName () from /lib64/libsqlite3.so.0
QSQLiteResultPrivate::initColumns from /usr/lib64/qt5/plugins/sqldrivers/libqsqlite.so

## System information
The problem has been observed on the following:
Fedora 34
Ubuntu 20.04

- Fast-RTPS version: Fast-DDS 2.3.2
- OS: Fedora 34, Ubuntu 20.04
- Network interfaces: N/A
- ROS2: N/A, using Fast-DDS directly

## Additional context
N/A

## Additional resources
N/A

**Comment by MiguelCompany** [comment]
@mtheall See #1998 for a possible fix

**Comment by mtheall** [comment]
This does appear to fix the issue. My app doesn't crash where it used to, and all the sqlite3 symbols symbols in libfastrtps.so are now "t" (local) where many were "T" (exported) before.

Thanks
