### ISSUE TITLE
Question: Have a DDS Publisher communicate with a ROS2 subscriber

### ISSUE THREAD

**Issue by arshPratap** [eProsima/Fast-DDS#1995]
I am new to using Fast DDS and had read the docs for eProsima Fast DDS and was wondering how we could setup a communication link between a ROS2 node(subscriber) and a native DDS publisher

To work on this task I have used a simple IDL for the DDS Publisher
```
struct Num {
  int64 num;   
};
```
and used a custom .msg for ROS2 Subscriber
```
int64 num
```
## Expected Behavior

I was expecting for the ros2 subscriber to listen in on the proper topic and print the "I heard " message.
## Current Behavior

The DDS Publisher and the ROS subscriber are for some reason are not able to recognize each other.Their domain IDs are 0.
## Steps to Reproduce

1. Create a custom Num msg for ROS2 (as described [here](http://docs.ros.org.ros.informatik.uni-freiburg.de/en/foxy/Tutorials/Custom-ROS2-Interfaces.html))
2. Create the corresponding ROS2(cpp) subscriber
3. Create a IDL (as described above) and generate the necessary files through FastDDS Gen 
4. Create a DDS Publisher
5. Run the DDS Publisher and the ROS2 subscriber 
## System information

- Fast-RTPS version: Fast -DDS 2.3.0
- OS:Ubuntu 20.04
- ROS2: Foxy
## Additional context

I have already tested examples of FAST-DDS (pub/sub) and they seem to work fine and so do the ROS2-foxy pub/sub.Its only when I am trying on for a 'hybrid' pub/sub combinations that I find this issue.

**Comment by MiguelCompany** [comment]
@arshPratap You may want to pass `-typeros2` [option](https://fast-dds.docs.eprosima.com/en/latest/fastddsgen/usage/usage.html#supported-options)

**Comment by arshPratap** [comment]
@MiguelCompany thanks for the reply..but using the typeros2 option resulted in the same result.(For some reason ..pub and sub not able to communicate). Further help would really be appreciated

**Comment by MiguelCompany** [comment]
@arshPratap You may also need to look at [Mapping of ROS 2 Topic and Service Names to DDS Concepts](https://design.ros2.org/articles/topic_and_service_names.html#mapping-of-ros-2-topic-and-service-names-to-dds-concepts), where you will find that, by default, ROS 2 topic `/foo` is mapped to DDS `rt/foo`

**Comment by arshPratap** [comment]
@MiguelCompany  thanks for the reply but still no luck..had ros2 topic named as "topic" and changed the topic in DDS publisher to "rttopic"as suggested by the above link but still no luck..
ROS2 sub
```
#include <memory>

#include "rclcpp/rclcpp.hpp"
#include "custom_interace/msg/num.hpp"     
using std::placeholders::_1;

class MinimalSubscriber : public rclcpp::Node
{
public:
  MinimalSubscriber()
  : Node("minimal_subscriber")
  {
    subscription_ = this->create_subscription<custom_interace::msg::Num>(          
      "topic", 10, std::bind(&MinimalSubscriber::topic_callback, this, _1));
  }

private:
  void topic_callback(const custom_interace::msg::Num::SharedPtr msg) const       
  {
    RCLCPP_INFO(this->get_logger(), "I heard: '%d'", msg->num);             
  }
  rclcpp::Subscription<custom_interace::msg::Num>::SharedPtr subscription_;       
};

int main(int argc, char * argv[])
{
  rclcpp::init(argc, argv);
  rclcpp::spin(std::make_shared<MinimalSubscriber>());
  rclcpp::shutdown();
  return 0;
}
```
Publisher init() function for DDS Pub
```
//!Initialize the publisher
    bool init()
    {
        
        num_.num(5);

        DomainParticipantQos participantQos;
        participantQos.name("Participant_publisher");
        participant_ = DomainParticipantFactory::get_instance()->create_participant(0, participantQos);

        if (participant_ == nullptr)
        {
            return false;
        }

        // Register the Type
        type_.register_type(participant_);

        // Create the publications Topic
        topic_ = participant_->create_topic("rttopic", "Num", TOPIC_QOS_DEFAULT);

        if (topic_ == nullptr)
        {
            return false;
        }

        // Create the Publisher
        publisher_ = participant_->create_publisher(PUBLISHER_QOS_DEFAULT, nullptr);

        if (publisher_ == nullptr)
        {
            return false;
        }

        // Create the DataWriter
        writer_ = publisher_->create_datawriter(topic_, DATAWRITER_QOS_DEFAULT, &listener_);

        if (writer_ == nullptr)
        {
            return false;
        }
        return true;
    }
```
@MiguelCompany would be great if you could help here.Thanks

**Comment by MiguelCompany** [comment]
@arshPratap Use `rt/topic` instead of `rttopic`

**Comment by arshPratap** [comment]
@MiguelCompany  thanks a lot for this..I was able to solve this

For anyone having the same issue follow these 

- Try using eProsima's [integration services](https://integration-service.docs.eprosima.com/en/latest/examples/different_protocols/pubsub/dds-ros2.html) 
- If you still want to connect with ros2 without the integration services then please read [this ](https://gist.github.com/EduPonz/bea0edf3e1ac366560eff62cceb5ddf9)
- change topicname from ```topic``` to ```rt/topic```(on dds end only)

**Comment by arshPratap** [comment]
Closing this..since this issue was resolved
