### ISSUE TITLE
An error occurred while executing fastddsgen.bat in Win10

### ISSUE THREAD

**Issue by wanfenglinhai** [eProsima/Fast-DDS#2017]
Hi develop team,

Recently I've been working on this, and I came to meet this NullPointerException while executing fastddsgen.bat. It gave me this error:

This is how I run this command, just follow the guideline: fastddsgen.bat -example CMake HelloWorld.idl

Loading templates...
Processing the file HelloWorld.idl...
ERROR<callPreprocessor>: Cannot execute the preprocessor. Reason: Cannot run program "cl.exe": CreateProcess error=2, ϵͳ▒Ҳ▒▒▒ָ▒▒▒▒▒ļ▒▒▒
Exception in thread "main" java.lang.NullPointerException
        at com.eprosima.fastdds.fastddsgen.execute(fastddsgen.java:343)
        at com.eprosima.fastdds.fastddsgen.main(fastddsgen.java:1207)

Could you please tell me how to fix this problem or it may be fixed by you guys?
Underneath is my demo of FastDDS in Win10, hope this could help.
![FastDDS issue](https://user-images.githubusercontent.com/57255196/122876817-84065880-d368-11eb-896b-0c0bfd34776e.png)

BTW, I want to run FastDDS within Android application, could you provide us some guidance of how to implement FastDDS in Android?

Really appreciate your efforts in developing FastDDS, thx a lot.

**Comment by MiguelCompany** [comment]
@wanfenglinhai See eProsima/Fast-DDS-Gen#59 for an explanation and solution to your problem

**Comment by MiguelCompany** [comment]
Closing after confirmation of OP [here](https://github.com/eProsima/Fast-DDS-Gen/issues/59#issuecomment-866633940) that the problem has been solved.
