### ISSUE TITLE
FastDDS Discovery Server does not work locally without a network connection [13652]

### ISSUE THREAD

**Issue by ralph-lange** [eProsima/Fast-DDS#2031]
## Bug report

**Required Info:**

- Operating System: Ubuntu 20.04
- ROS Distro: Galactic
- Installation type: Binaries
- Version or commit hash: 5.0.0-2 (release version of ros-galactic-rmw-fastrtps-cpp)

#### Steps to reproduce issue
- Disable all network connections (unplug Ethernet, turn off WiFi)
- Source the ROS Galactic installation
- Invoke `fastdds discovery -i 0` on a console (cf. https://fast-dds.docs.eprosima.com/en/latest/fastdds/ros2/discovery_server/ros2_discovery_server.html#setup-discovery-server)

#### Expected behavior
Discovery server should start up or give a meaningful error message that at least one network connection is required.

#### Actual behavior
The command stops immediately with output
```
[PARTICIPANT ERROR] Problem creating RTPSParticipant -> Function createParticipant
fastdds discovery <discovery-args>

1
 fast-discovery-server tool not found!
```
... which suggests an incomplete installation, which is not true.

#### Additional information
The same error occurs on Foxy and Rolling. If the computer has a network connection (WiFi, Ethernet), then the whole demo in Section 16.2.3 from https://fast-dds.docs.eprosima.com/en/latest/fastdds/ros2/discovery_server/ros2_discovery_server.html#run-the-demo runs smoothly.

**Comment by ralph-lange** [comment]
Moved from https://github.com/ros2/rmw_fastrtps/issues/545.

**Comment by aditya2592** [comment]
Hi @ralph-lange, I have been struggling with the right approach for discovery on localhost and I am not sure what the right solution is. But in mind, there shouldn't be any need to use discovery server on localhost because there is no limitation of traffic on the loopback interface? Even if there is, can't shared memory be used for discovery traffic? 

Despite this we saw issues where ROS services weren't discover-able without the discovery server on localhost.

**Comment by ralph-lange** [comment]
You're right, there is no need for the discovery server in the setup described above. Therefore, a meaningful error message would be sufficient for me.

I observed the problem in a use-case that is probably not so rare: I was working with a colleague in parallel on the same robot and recorded some topics in bag files. To not interfere with the live system when replaying the bag files, I disconnected from the network and ran into the issue described above.

**Comment by Mario-DL** [comment]
Hi @ralph-lange,
Sorry for the delay in the response and thanks for the report. 
You are right, a meaningful message should be shown in that case. The log message was introduced in #2396. Please check if that solved the issue and feel free to reopen the 
ticket if the issue still persists.

@aditya2592 thanks for the contribution.

**Comment by ralph-lange** [comment]
LGTM. Thank you @aditya2592 and @Mario-DL.
