### ISSUE TITLE
How to define topic profile in XML file? [11917]

### ISSUE THREAD

**Issue by liyue75** [eProsima/Fast-DDS#2032]
When I use DDS API.
I find
![image](https://user-images.githubusercontent.com/53389739/124057977-1094d300-da5b-11eb-92bf-ac3a48b59ea3.png)
![image](https://user-images.githubusercontent.com/53389739/124058017-286c5700-da5b-11eb-8d97-95bfd3e10b4d.png)
But I do not know how to add a topic profile in XML.
The only profiles I can add are:
![image](https://user-images.githubusercontent.com/53389739/124058168-6c5f5c00-da5b-11eb-8025-d67003735a8a.png)
There is no **topic profile**

**Comment by MiguelCompany** [comment]
This has already been explained on [#1369(comment)](https://github.com/eProsima/Fast-DDS/issues/1369#issuecomment-687273698).

The documentation is being updated on eProsima/Fast-DDS-docs#191

**Comment by liyue75** [comment]
@MiguelCompany 
Thank you for your quick reply. Now I know how to add topic profile.
But I have one more question:
Why can not read **topic name** and **data type** from topic profile when using `create_topic_with_profile`? I have to explicit topic/type name as input arguments when calling `create_topic_with_profile`.
In order to re-map topic/type name easily through modify XML file without changing code.
I have to add this in my code to get topic/type name from topic profile
```
eprosima::fastrtps::TopicAttributes tp_attr;
eprosima::fastrtps::xmlparser::XMLProfileManager::fillTopicAttributes("topic_profile", tp_attr);
topic_ = participant_->create_topic_with_profile(tp_attr.getTopicName().to_string(),
                                                                    tp_attr.getTopicDataType().to_string(),
                                                                     "topic_profile");
```
I think if there is an API like this, it reads topic/type name from profile automatically:
```
topic_ = participant_->create_topic_with_profile("topic_profile");
```
It will be more convenient to use.
