### ISSUE TITLE
Information : Fast-DDS 2.3.2 is now part of Conan Center 

### ISSUE THREAD

**Issue by dotChris90** [eProsima/Fast-DDS#2045]
Hello guys, 

just wanted to inform you that your library is now part of the conan center (conan is dependency manager for C++) see --> https://conan.io/center/fast-dds by PR https://github.com/conan-io/conan-center-index/pull/5968 and i want to ask if you guys are fine with this? 

I know you guys have a strong focus on ROS and so but in my honest opinion CONAN is a great way of easily deploy SW to different targets (embedded linux, linux servers, MAC OS, Windows etc.) . 
I hope you do not mind Fast-DDS in a "package manager registry" and if you dont mind i would from time to time also updates the package to newer versions (according to your releases). 

And thanks for developing Fast-DDS - it's the truly most complete DDS implementation (including RPC) i saw so far ;)

**Comment by MiguelCompany** [comment]
Hey @dotChris90! We don't mind at all!

We do think is great to have Fast DDS on one or more package manager registries. It is already part of [conda-forge](https://anaconda.org/conda-forge/fast-dds).

Thank you so much for your contribution (and the compliments)!

**Comment by dotChris90** [comment]
@MiguelCompany  :) thanks - plus there exist simple too few good DDS implementations out there. I close the issue since you are now informed and please go on shaping this awesome library! have a great week

**Comment by pravinbdeore** [comment]
Can you please provide document for how to use Conan ?
