### ISSUE TITLE
Failing to build on Android [12010]

### ISSUE THREAD

**Issue by ivanpauno** [eProsima/Fast-DDS#2055]
## Expected Behavior

Does build on Android.

## Current Behavior

Does not build on Android.

## Steps to Reproduce

We're trying to crosscompile the ros2 core for Android.
Github workflow: https://github.com/ros2-java/ros2_java/blob/ebd8c4fea857528f77786508d52ae7519621c5d3/.github/workflows/build_and_test.yml#L95
The steps to reproduce locally are the same that the ones in the workflow.

## System information

- Fast-RTPS version: 2.3.x
- OS: Host Ubuntu 20.04, target Android
- Network interfaces: N/A
                      
- ROS2: N/A
        

## Additional context

This is probably an user mistake.
We're currently setting the THIRDPARTY cmake option to ON.
The error is:

```
/home/runner/work/ros2_java/ros2_java/ros2_java_ws/src/eProsima/Fast-DDS/src/cpp/utils/IPFinder.cpp:165:9: error: use of undeclared identifier 'getifaddrs'; did you mean 'ifaddrs'?
    if (getifaddrs(&ifaddr) == -1)
        ^
/home/runner/work/ros2_java/ros2_java/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/ifaddrs.h:45:8: note: 'ifaddrs' declared here
struct ifaddrs {
       ^
/home/runner/work/ros2_java/ros2_java/ros2_java_ws/src/eProsima/Fast-DDS/src/cpp/utils/IPFinder.cpp:223:5: error: use of undeclared identifier 'freeifaddrs'
    freeifaddrs(ifaddr);
```

Is `THIRDPARTY=ON` enough to make sure `android-ifaddrs` is being built?

**Comment by MiguelCompany** [comment]
@ivanpauno Both `THIRDPARTY=ON` and `ANDROID=ON` should be present.

Looking at the yaml file, I'm not sure if `ANDROID=ON` would be set by `CMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake`

**Comment by ivanpauno** [comment]
@MiguelCompany thanks for the fast reply.

I have added the `ANDROID=ON` flag (https://github.com/ros2-java/ros2_java/pull/187/commits/3b979f50a285a2913052b4850a728dfddb7192ff), but it still fails with the same error.
You can check the workflow logs here https://github.com/ros2-java/ros2_java/pull/187/checks?check_run_id=3010347277.

**Comment by MiguelCompany** [comment]
🤔 I see the submodule part is working

```
Submodule 'thirdparty/android-ifaddrs' (https://github.com/michalsrb/android-ifaddrs.git) registered for path 'thirdparty/android-ifaddrs'
Cloning into '/home/runner/work/ros2_java/ros2_java/ros2_java_ws/src/eProsima/Fast-DDS/thirdparty/android-ifaddrs'...
```

But then the header is taken from the NDK

```
/home/runner/work/ros2_java/ros2_java/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/ifaddrs.h:45:8: note: 'ifaddrs' declared here
```

We're adding the include directory [here](https://github.com/eProsima/Fast-DDS/blob/dc19fe31a9ace7e0de8ed178f7891050e5a35d39/src/cpp/CMakeLists.txt#L440) so I don't know why the one from the NDK is being taken.

**Comment by MiguelCompany** [comment]
@ivanpauno Could you add `-DCMAKE_VERBOSE_MAKEFILE=ON` so we can check the actual g++ invocation. This will show the list of include folders being searched.

**Comment by MiguelCompany** [comment]
@ivanpauno I could reproduce this locally and found a solution

It seems the third party is not being used, as the header is found on the system.

You can force the third parties to be used, either globally with `-DTHIRDPARTY=FORCE`, or specifically (in this case with `-DTHIRDPARTY=ON -DTHIRDPARTY_android-ifaddrs=FORCE`).

I checked both the global and the specific one, and both worked in my case.

**Comment by ivanpauno** [comment]
That worked, thanks for the help @MiguelCompany !!
