### ISSUE TITLE
Reader can't receive past data when matched again [12126]

### ISSUE THREAD

**Issue by WataruToishita** [eProsima/Fast-DDS#2065]
The reader can receive samples normally after the 1st matching.
But when matched again, the reader can't receive the samples that had already received.

The QoS we are using is follow. 

Participant QoS
- leaseDuration: 3sec
- leaseDuration_announcementperiod: 1sec

Writer, Reader QoS
- KEEP_LAST_HISTORY_QOS
- RELIABLE_RELIABILITY_QOS
- TRANSIENT_LOCAL_DURABILITY_QOS

## Expected Behavior
The reader can receive the samples that had already received when matched again.

## Current Behavior
The reader can not receive the samples that had already received. It can receive only new samples.

## Steps to Reproduce
1. Setup the system and networks: PC A ---(LAN cable)--- Hub ---(LAN cable)--- PC B
2. Run the Participant(writer) on PC A. The writer write some samples.
3. Run the Participant(reader) on PC B. The reader receives above samples.
4. Disconnect the PC B from network and wait at least 3 seconds (=leaseDuration time). The participants detect drop each other on PC A and B.
5. Reconnect the PC B to the network. 
6. The participants discover each other and the reader matched to the writer . But the reader can not receive the samples that had received at step 3.

## System information
- Fast-RTPS version: 2.2.0
- OS: Ubuntu 18.04.5
- Network interfaces: PC A: eth0 (192.168.100.1), PC B: eth0 (192.168.100.2)

**Comment by fujitatomoya** [comment]
@MiguelCompany 

this is what we talked offline. tried to use Participant QoS but it does not work as expected. any clue?

**Comment by MiguelCompany** [comment]
@fujitatomoya I checked the internal design documents, and I was mistaken. The behavior depicted here is how it is designed to work.

Apart from keeping the old samples on the application, the only other option I see is to detect there was a participant drop by checking `DROPPED_PARTICIPANT` on a [participant listener](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/domain/domainParticipantListener/domainParticipantListener.html), and in that case, remove the reader and create it again.

**Comment by fujitatomoya** [comment]
@MiguelCompany thanks for the update. okay, but how we can configure the criteria that indicates participant is dropped? is there any configuration such as duration to set?

**Comment by MiguelCompany** [comment]
@fujitatomoya The way you already did. Using `leaseDuration` on the participant qos.

**Comment by fujitatomoya** [comment]
@MiguelCompany 

> The way you already did. Using leaseDuration on the participant qos.

and this does not work to receive the messages in the past either...we will confirm the application code.

**Comment by WataruToishita** [comment]
I attached the example code to reproduce. The base code is [HelloWorldExample](https://github.com/eProsima/Fast-DDS/tree/master/examples/C%2B%2B/DDS/HelloWorldExample).

You can reproduce by following steps. (Of course you can use docker container instead of PC.)

1. ./DDSHelloWorldExample publisher on PC A
2. ./DDSHelloWorldExample subscriber on PC B
3. Disconnect the PC B from network and wait at least 3 seconds.
4. Reconnect the PC B to the network.

 
 [HelloWorldExample.zip](https://github.com/eProsima/Fast-DDS/files/6846189/HelloWorldExample.zip)

**Comment by MiguelCompany** [comment]
@WataruToishita I will update your example and report back tomorrow

**Comment by fujitatomoya** [comment]
@Barry-Xu-2018 can you also keep your eyes on this? thanks!

**Comment by Barry-Xu-2018** [comment]
> can you also keep your eyes on this? thanks!

Okay.  
I will confirm this problem is resolved after change `leaseDuration` in my environment.

**Comment by MiguelCompany** [comment]
@WataruToishita @fujitatomoya @Barry-Xu-2018

I achieved the desired behavior following the suggestions in my previous [comment](https://github.com/eProsima/Fast-DDS/issues/2065#issuecomment-881355396), i.e. manually deleting and creating the reader when a participant drop is detected.

I attach the full example, and also show the diff from your original code, so the important bits are highligted.

[HelloWorldExample.zip](https://github.com/eProsima/Fast-DDS/files/6852955/HelloWorldExample.zip)

```diff
diff original/HelloWorldExample/HelloWorldSubscriber.cpp HelloWorldExample/HelloWorldSubscriber.cpp
48c48
<     participant_ = DomainParticipantFactory::get_instance()->create_participant(0, pqos);
---
>     participant_ = DomainParticipantFactory::get_instance()->create_participant(0, pqos, &participant_listener_, StatusMask::none());
149a150,165
>
>         // Recreate reader in case of participant drop
>         if (participant_listener_.participant_has_been_dropped)
>         {
>             participant_listener_.participant_has_been_dropped = false;
>             if (reader_ != nullptr)
>             {
>                 subscriber_->delete_datareader(reader_);
>             }
>
>             DataReaderQos rqos = DATAREADER_QOS_DEFAULT;
>             rqos.history().kind = KEEP_ALL_HISTORY_QOS;
>             rqos.reliability().kind = RELIABLE_RELIABILITY_QOS;
>             rqos.durability().kind = TRANSIENT_LOCAL_DURABILITY_QOS;
>             reader_ = subscriber_->create_datareader(topic_, rqos, &listener_);
>         }
diff original/HelloWorldExample/HelloWorldSubscriber.h HelloWorldExample/HelloWorldSubscriber.h
25a26
> #include <fastdds/dds/domain/DomainParticipantListener.hpp>
58a60,77
>
>     class ParticipantListener : public eprosima::fastdds::dds::DomainParticipantListener
>     {
>     public:
>
>         void on_participant_discovery(
>             eprosima::fastdds::dds::DomainParticipant* /* participant */,
>             eprosima::fastrtps::rtps::ParticipantDiscoveryInfo&& info) override
>         {
>             if (eprosima::fastrtps::rtps::ParticipantDiscoveryInfo::DROPPED_PARTICIPANT == info.status)
>             {
>                 participant_has_been_dropped = true;
>             }
>         }
>
>         bool participant_has_been_dropped = false;
>
>     } participant_listener_;
```

**Comment by Barry-Xu-2018** [comment]
@MiguelCompany  

Thanks.  
As user, we need to set callback of DomainParticipantListener to re-create reader.

**Comment by MiguelCompany** [comment]
@Barry-Xu-2018 Correct

**Comment by fujitatomoya** [comment]
@MiguelCompany Ah, okay that is user responsibility. i was mistaken. thanks for the help.

@WataruToishita after all, do you have any more comments or question on this?

**Comment by WataruToishita** [comment]
@MiguelCompany Thanks for the help! I understand that our app needs to re-create readers when detects the participant drop.
@fujitatomoya @Barry-Xu-2018 Thank you for your support. I'll try to redesign our app based on the approach.
