### ISSUE TITLE
Polymorph Data Structures

### ISSUE THREAD

**Issue by tobi4321** [eProsima/Fast-DDS#2073]
I have a scenario with different signal types. All signals have a base type called ComObject. The specific types are for example Increment or Trigger. Is it possible to send the different Objects of Increment and Trigger over the same topic? The idl generation can add the inheritance but for polymorphic classes, the base class should have a virtual function. This is not possible at the moment.
Is there a better solution for my scenario?

**Comment by MiguelCompany** [comment]
I think the only possible way would be using a union. The type will be serialized taking the discriminator into account.

**Comment by tobi4321** [comment]
Alright, i will try that. Thanks!
