### ISSUE TITLE
Implementation of TransportPriorityQosPolicy

### ISSUE THREAD

**Issue by tobi4321** [eProsima/Fast-DDS#2081]
When will the TransportPriorityQosPolicy be implemented? Is it planned for the next releases?

**Comment by EduPonz** [comment]
Hi @tobi4321 ,

Unfortunately, `TransportPriorityQosPolicy` is not part of the roadmap presently, so I cannot give you a specific timeline on it. However, there exists the possibility of funding a feature accerleration if this is something you need implemented ASAP. For that, you can write an email to evaluation.support@eprosima.com to start the conversation.

In any case, thanks for your inquiry and your interest in the product!
