### ISSUE TITLE
Multicast usage

### ISSUE THREAD

**Issue by Benatti1991** [eProsima/Fast-DDS#2091]
I am experiencing performance issues in a peer-to-peer application on a cluster computer when running between ethernet-connected nodes (communication between processes on a single node is fine).
Reading through the documentation I found under "6.28.4 Topics with many subscribers" that multicast would probably solve my problems.  
For the PARTECIPANT, I changed 
`qos.wire_protocol().builtin.initialPeersList.push_back(locator);`
to 
`qos.wire_protocol().default_multicast_locator_list.push_back(locator);`
The partecipants still find each other but the reader fails if not on the same machine. Therefore, I tried to change the DataReader qos as in https://fast-rtps.docs.eprosima.com/_/downloads/en/latest/pdf/ 6.28.4, and the only result was that now it fails also locally.
To change the reader I tried both a simple snippet, just to make it work on my local machine:
```
Locator_t new_multicast_locator;
IPLocator::setIPv4(new_multicast_locator, "127.0.0.1");
new_multicast_locator.port = 7400;
qos.endpoint().multicast_locator_list.push_back(new_multicast_locator);
```
And, on the cluster, to pass al the participant locators:
```
DataReaderQos qos;
auto plist = m_participant->get_qos().wire_protocol().default_multicast_locator_list;
    if (!plist.empty()) {
        for (auto peer : plist) {
            qos.endpoint().multicast_locator_list.push_back(peer);
        }
    }
```
None of the above worked. 
Thanks,
Simon

PS: From my understanding I should NOT change the DataWriter to use multicast, correct?

**Comment by MiguelCompany** [comment]
@Benatti1991
First, you shouldn't need to change the participant qos.
Second, just set a multicast locator using a multicast IP address. Using the one depicted on the documentation (`239.255.0.4`) would do fine.

**Comment by Benatti1991** [comment]
@MiguelCompany  shouldn't the IP on the multicast locator be the IP of the machine my reader is subscribed to?
Simon

**Comment by MiguelCompany** [comment]
@Benatti1991 No. The advantage of multicast is that all readers will be listening on the same multicast address. This way, when the writer needs to send data, it will do it with a single call to the OS, and the network takes care of delivering the packet to all the hosts listening on that multicast address.

**Comment by Benatti1991** [comment]
Thanks Miguel, sorry for the stupid question I didn't know about multicast principles before! 
Simone
