### ISSUE TITLE
Nebula VPN unexpected behaviour

### ISSUE THREAD

**Issue by maxikrie** [eProsima/Fast-DDS#2098]
Hello,

I am currently investigating Nebula VPN in combination with Fast-DDS for DDS communication over the internet (I would like to avoid TCP communication accompanied by the need of firewall configuration - Nebula VPN seems to circumvent this nicely as far as I can tell and also is a Mesh VPN so should find the fastest route between nodes without having to go through a central point such as OpenVPN). 

I have set up Nebula VPN between two machines connected on a home network over Ethernet, where the second machine can also connect to the internet through a second totally unrelated WiFi hotspot. Both machines can ping each other on the VPN either when they are connected through Ethernet, but also when the second machine only uses the secondary WiFi hotspot verifying the VPN.

Now when both machines are connected on the home network through Ethernet, I can run the ShapesDemo successfully (I am not sure which route is taken for data exchange - it could be either the home network or the VPN). When I disconnect Ethernet on the second machine, which is now connected to the internet through the WiFi hotspot, the machine still receives data on the ShapesDemo instance for about 20s verifying that somehow for some time data makes it through the VPN. After that I also see on the first machine that the publisher removed the sub.

If both machines were never connected through Ethernet, but both are connected to the internet (first machine through my home network, second machine through WiFi hotspot), both run Nebula VPN and can ping each other, I never receive any data when running the ShapesDemo on both machines.

Does this make sense to you? It seems that at least in the first case it somehow works verifying my approach in principle..

Many thanks!
Max

**Comment by MiguelCompany** [comment]
This is usually related with the participant announcements, which will always use multicast. VPNs usually disable multicast.

Even if multicast is enabled, you may need to configure the [UDP transport](https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/udp/udp.html#udp-transport) to set a TTL higher than the default one, as the multicast datagrams will need several hops from one host to the other.

**Comment by maxikrie** [comment]
Thank you for the explanation! I quickly tried simple multicast on Nebula VPN and I couldn't get it working immediately, maybe this is the issue indeed.

Would a discovery server solve this problem or are there other issues I will likely encounter when employing a VPN?

**Comment by maxikrie** [comment]
@MiguelCompany Could you briefly share an insight on my follow question?

Thank you for your time!

**Comment by EduPonz** [comment]
Hi @maxikrie ,

@MiguelCompany is currently on vacation but I'll try to pitch in. As Miguel said, multicast usually requieres some configuration to work over VPN. However, Fast DDS provides alternatives for this:

* If all the participants in the network are known before hand, you could disable multicast completely and configure the initial peers of every participant: [Disable multicast disovery](https://fast-dds.docs.eprosima.com/en/latest/fastdds/use_cases/wifi/disable_multicast.html#disabling-multicast-discovery)
* If the network topology is not known or may change on run-time, then [Discovery Server](https://fast-dds.docs.eprosima.com/en/latest/fastdds/discovery/discovery_server.html) is the way to go. Not only does it avoid multicast completely, but it also reduces discovery related packets by up to a 90% reduction, which might be interesting for VPN tunnels. You can find some examples [here](https://fast-dds.docs.eprosima.com/en/latest/fastdds/use_cases/wifi/discovery_server_use_case.html)

> Would a discovery server solve this problem or are there other issues I will likely encounter when employing a VPN?

We have successfully set up communication over VPN in the past, although not with Nebula specifically, but I do not foresee many differences between VPNs.

**Comment by maxikrie** [comment]
Perfect, thanks!
