### ISSUE TITLE
Fast DDS Subscriber "Failed init_port"

### ISSUE THREAD

**Issue by wrgtri** [eProsima/Fast-DDS#2099]
## Expected Behavior
Running 
```
DomainParticipantQos pqos;
participant_ = DomainParticipantFactory::get_instance()->create_participant(0, pqos);
```
should run without errors.

## Current Behavior
When `participant_ = DomainParticipantFactory::get_instance()->create_participant(0, pqos);` is called (specifically `create_participant()`, the following error is produced 
```
2021-07-28 12:49:37.829 [RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7412: open_and_lock_file failed -> Function open_port_internal
2021-07-28 12:49:37.831 [RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7413: open_and_lock_file failed -> Function open_port_internal
```

## Additional context
I have set up an outside application to receive Fast DDS messages from ROS2. I have been able to test that I can receive ros2 topic messages in a simple outside fast dds subscriber (generated using `fastddsgen -example CMake MyMsg.idl`).

Now I am trying to incorporate the Fast DDS subscriber code into another application. However, the above error is produced in the MyMsgSubscriber.cxx (created using fastddsgen command above), in MyMsgSubsriber::init(), line `participant_ = DomainParticipantFactory::get_instance()->create_participant(0, pqos);`. Why is this error occurring? Thank you

## System information
- Fast-DDS version: 2.3.0
- OS: Ubuntu 20.04
- ROS2: Foxy

**Comment by MiguelCompany** [comment]
Hi @wrgtri 

Could you check if running `fastdds shm clean` solves your issue?

**Comment by wrgtri** [comment]
> Could you check if running `fastdds shm clean` solves your issue?

Hi @MiguelCompany 
Unfortunately that did not work. I ran that command and got 
```
0 ports in use
0 segments in use
2 zombie ports cleaned
1 zombie segments cleaned
```
But when I rerun the ros2 publisher and then the fastdds subscriber, I get the same error again in whichever was run second.

**Comment by wrgtri** [comment]
Error was caused by having two installations of FastDDS, one that came with ROS2 and another that I installed. My programs were then calling alternate versions, so they were "stepping on each other's toes." Solution was to uninstall the extra one and have both use the FastDDS that comes with ROS2.
