### ISSUE TITLE
DataWriter::get_type() missing an impl - but impl present in DataWriterImpl.hpp [12283]

### ISSUE THREAD

**Issue by mcelhennyi** [eProsima/Fast-DDS#2100]
It seems the get_type call in the DataWriter class is missing its impl call. 

[Here](https://github.com/eProsima/Fast-DDS/blob/master/src/cpp/fastdds/publisher/DataWriter.cpp) you see no implementation for the get_type() function found [here.](https://github.com/eProsima/Fast-DDS/blob/c0d4d18c19b43dd321aca28526fac32127eb7d87/include/fastdds/dds/publisher/DataWriter.hpp#L303)

## Expected Behavior
[DataWriter.get_type() ]( https://github.com/eProsima/Fast-DDS/blob/master/src/cpp/fastdds/publisher/DataWriter.hpp) should call into [DataWriterImpl.get_type()]( https://github.com/eProsima/Fast-DDS/blob/master/src/cpp/fastdds/publisher/DataWriterImpl.hpp)

## Current Behavior
undefined symbol at runtime

**Comment by EduPonz** [comment]
Hi @mcelhennyi ,

Thanks for your report! I've submited #2101 to fix this. It'd be released in Fast DDS v2.4.0 in the second half of September 2021
