### ISSUE TITLE
No data received on SubscriberListener when custom topic discovery listener is registered at participant

### ISSUE THREAD

**Issue by ma30002000** [eProsima/Fast-DDS#2106]
Using 
*   fastdds 2.3.2
*   fastcdr 1.0.15
*   foonathan_memory 0.7.1

When creating a participant via DomainParticipantFactory::create_participant(), and specifying a custom listener for topic discovery derived from DomainParticipantListener, subscribers created via DomainParticipant::create_subscriber() and Subscriber::create_datareader() with data listeners derived from SubscriberListener, SubscriberListener::on_data_available no longer gets called at all on th esubscriber listener. If not specifying the custom listener for topic discovery, everything works.

When stepping into the code, it seems that the following code paths change:

```
void DataReaderImpl::InnerDataReaderListener::onNewCacheChangeAdded(
        RTPSReader* /*reader*/,
        const CacheChange_t* const change_in)
{
    if (data_reader_->on_new_cache_change_added(change_in))
    {
        //First check if we can handle with on_data_on_readers
        SubscriberListener* subscriber_listener =
                data_reader_->subscriber_->get_listener_for(StatusMask::data_on_readers());
        if (subscriber_listener != nullptr)
        {
            subscriber_listener->on_data_on_readers(data_reader_->subscriber_->user_subscriber_);
        }
        else
        {
            // If not, try with on_data_available
            DataReaderListener* listener = data_reader_->get_listener_for(StatusMask::data_available());
            if (listener != nullptr)
            {
                listener->on_data_available(data_reader_->user_datareader_);
            }
        }
    }
}
```

When a custom DomainParticipantListener is registered, the first check is true, thus calling
`subscriber_listener->on_data_on_readers(data_reader_->subscriber_->user_subscriber_);`
which basically call the empty method SubscriberListener::on_data_on_readers (SubscriberListener is a base class of 
DomainParticipantListener and thus the custom discovery listener).

In case no custom DomainParticipantListener is registered, the first check is false, triggering the callback of
`listener->on_data_available(data_reader_->user_datareader_);`
which is the registered SubscriberListener.

**Comment by MiguelCompany** [comment]
Already answered [here](https://github.com/eProsima/Fast-DDS/issues/1902#issuecomment-815851977)

**Comment by ma30002000** [comment]
Thank you for the fast reply, I can confirm that the comments of #1902 address my issue. However, shouldn't https://fast-dds.docs.eprosima.com/en/latest/fastdds/discovery/disc_callbacks.html be adapted to include StatusMask::none() ? When following the instructions one would not expect that the participant cannot serve subscribers anymore

**Comment by MiguelCompany** [comment]
@ma30002000 You are right. Would you mind opening an issue on [the docs repo](https://github.com/eProsima/Fast-DDS-docs) ?

**Comment by ma30002000** [comment]
Ok, I created the documentation ticket. Does it make sense to warn the developer programmatically when calling create_subscriber on a participant with a custom listener and the respective StatusMask? It took me quite some time to track down my mishandling of the API...

**Comment by EduPonz** [comment]
Hi @ma30002000 ,

We do not think we should warn the user programmatically, as this behaviour is completely intended. We we must do is documenting it properly. I'm closing this ticket, leaving https://github.com/eProsima/Fast-DDS-docs/issues/277 until we solve it. Thanks!
