### ISSUE TITLE
Best method for debugging a writer?

### ISSUE THREAD

**Issue by mcelhennyi** [eProsima/Fast-DDS#2109]
I have setup my reader and writer to be dynamically setup. When I send a internal message to my dds module it constructs a writer on the fly, similarly when I get notified on my reader side of a new writer I construct a reader on the fly.

I have the on the fly part working from the looks of it, but when I write I get a false back. I have debugged the various pieces and I do not see anything out of the ordinary.

**Is there a way for me to figure out the issue with the writer after it fails? Some sort of error return other than true/false?**

Here are some clips from what I have, I unfortunately cannot share all of it.

```
// Create the DDS pariticipant
fastdds::dds::DomainParticipantQos pqos;
_participant = fastdds::dds::DomainParticipantFactory::get_instance()->create_participant(
        _config.domainId,
        pqos,
        this,
        fastdds::dds::StatusMask::none()
);

// Setup our publisher
_publisher = _participant->create_publisher(fastdds::dds::PUBLISHER_QOS_DEFAULT, nullptr);

// Setup the subscriber
_subscriber = _participant->create_subscriber(fastdds::dds::SUBSCRIBER_QOS_DEFAULT, nullptr);

// Loop over all types and register them
for(auto &iter: Messaging::DDS::ddsTypeToPubSubTypeFactory)
{
    auto pubSubTypeObj = iter.second(); // Creates a NEW pointer

    // Register all the types - this allows for mapping from type name (struct name) to struct upon reception
    _participant->register_type(
        fastdds::dds::TypeSupport(pubSubTypeObj /* Takes ownership (shared Ptr) */),
        iter.first
    );
}
```

```
static std::unordered_map<DDS_TYPE, std::function<eprosima::fastdds::dds::TopicDataType*()>> ddsTypeToPubSubTypeFactory = {
        {"PointCloud", constructPubSubType<PointCloudPubSubType>},
};
```
`constructPubSubType` just returns `new T()`

Both sides run this exact code. 

When a new writer is created it looks like this:
```
auto writer = new WriterStruct();
writer->listener = new Modules::DDS::DataWriterListener();
writer->topic = _participant->create_topic(
        outBoundMsg->getTopic(),
        messageType,
        fastdds::dds::TOPIC_QOS_DEFAULT
);
writer->writer = _publisher->create_datawriter(
        writer->topic,
        fastdds::dds::DATAWRITER_QOS_DEFAULT,
        writer->listener
);

// Enable it?
auto ret = writer->writer->enable();
if(ret != ReturnCode_t::RETCODE_OK)
{
    SPDLOG_ERROR(getModuleTag() + "Failed to enable the writer: {}", ret());
}
```

And a new reader:
```
// Setup a new subscriber
auto readerStruct = new ReaderStruct();
readerStruct->type = type;
readerStruct->topic = _participant->create_topic(
        topic,
        type,
        fastdds::dds::TOPIC_QOS_DEFAULT
);
readerStruct->listener = new DDS::DataReaderListener(
        internalId,
        type,

        // Used to publish out PAs when DDS messages are received
        [&](const ProtocolAbstractionPtr &inboundMsg)
        {
            sendInboundPAMessage(inboundMsg);
        }
);
readerStruct->reader = _subscriber->create_datareader(
        readerStruct->topic,
        fastdds::dds::DATAREADER_QOS_DEFAULT,
        readerStruct->listener
);

auto ret = readerStruct->reader->enable();
if (ret != ReturnCode_t::RETCODE_OK)
{
    SPDLOG_ERROR(getModuleTag() + "Failed to enable reader for type {} on topic {}.",
                 type, topic);
}
```

Lastly, I am only writing when I know there is a match. 

I also saw this https://github.com/eProsima/Fast-DDS/issues/1902 and tried to use that as guidance, but I still have the similar no receive issue when using none().

**Comment by EduPonz** [comment]
Hi @mcelhennyi ,

First of all, you do not need to enable writers or readers. It does not hurt, but it's not needed.

Secondly, you could use [this](https://fast-dds.docs.eprosima.com/en/latest/fastdds/api_reference/dds_pim/publisher/datawriter.html#_CPPv4N8eprosima7fastdds3dds10DataWriter5writeEPvRK16InstanceHandle_t) version of the `write` method, which returns a `ReturnCode_t`; you can pass `HANDLE_NIL` as `InstanceHandle_t` there.

Furthermore, you can [enable warning logs](https://fast-dds.docs.eprosima.com/en/latest/fastdds/logging/logging_configuration.html#verbosity-level) to check whether something strange is happening
