### ISSUE TITLE
Question: std::vector "readers_" mutex issue in WLP [13675]

### ISSUE THREAD

**Issue by fenggaobj** [eProsima/Fast-DDS#2110]
Hi
I'am working on fastrtps 2.0.x version. 
There are 3 functions (add_local_reader/remove_local_reader/sub_liveliness_changed) using std::vector "readers_"  in WLP.cpp.
But I can only find "mp_mutex" in “add_local_reader” to protect "readers_".
Should "remove_local_reader" and "sub_liveliness_changed" also protect  "readers_" with"mp_mutex"?  If the multi-threads handle the request at the same time, maybe it will crash.

Thanks a lot.

**Comment by MiguelCompany** [comment]
I do agree that `remove_local_reader` should be using the mutex. Not completely sure of `sub_liveliness_changed`, due to possible ABBAs. What do you think, @richiware?

**Comment by richiware** [comment]
In both cases `readers_` must be protected. But in the case of `sub_liveliness_changed` we have to take care of the order taking `PDP::mutex` and `LivelinessManager::mutex` as @MiguelCompany  suggested.

**Comment by fenggaobj** [comment]
Thanks for your quick reply.  

I just encounter the issue of "sub_liveliness_changed",  the pointer of  "reader" in the following code is exceptional,  i guess the object of reader pointing is changed  because of missing the protection.

`    for (RTPSReader* reader : readers_)
    {
        if (reader->liveliness_kind_ == kind &&
                reader->liveliness_lease_duration_ == lease_duration)
        {
            if (reader->matched_writer_is_matched(writer))
            {
                update_liveliness_changed_status(
                    writer,
                    reader,
                    alive_change,
                    not_alive_change);
            }
        }
    }`

Could you help to give other suggestion to fix the "sub_liveliness_changed"  issue and the ABBAs (it's indeed difficult to fix the ABBAs)?

**Comment by JLBuenoLopez-eProsima** [comment]
Sorry @fenggaobj,

Fast DDS 2.0.x has reached [end of life](https://github.com/eProsima/Fast-DDS/blob/master/RELEASE_SUPPORT.md#release-support). Also, efforts to fix multithreading issues reported by ThreadSanitizer are being made. Consequently, I am going to close this issue as the version is no longer supported and because it is expected to be fixed soon.
