### ISSUE TITLE
Communication between two computers cannot be achieved using HelloWorldExampleTCP

### ISSUE THREAD

**Issue by XiaomuWang** [eProsima/Fast-DDS#2116]
Hi! I am using fastrtps' HelloWorldExampleTCP to be unable to achieve communication between the two machines, and the following error appears, how can I achieve the communication between the two machines?

**Comment by XiaomuWang** [comment]
![a541366c61833b3e75626651153aac0](https://user-images.githubusercontent.com/46257486/128295329-4741dabd-f6ac-441a-aad4-76f6279f0306.png)

**Comment by XiaomuWang** [comment]
![618b28cd1d31bccf3e5b8736ddd9579](https://user-images.githubusercontent.com/46257486/128295595-e61b8e2d-c240-4c0f-90aa-5c33ff27560f.png)

**Comment by XiaomuWang** [comment]
I run directly on two hosts

**Comment by richiware** [comment]
Using TCP transport one application has to take the server role and the other one the client role. In case of `HelloWorldExampleTCP`, it is the publisher who takes the sever role. Executing the publisher you have to specify its public IP with the `-a` option. If both applications are in the same local network, you can specify the local IP of the system hosting the publisher application. If there are in different networks, the publisher application has to specify the public IP (and the router has to be configured to redirect TCP connections).

In the other hand, the subscriber (as client role) needs to know where is the server. Then executing the subscriber you have to specify the public IP of the publisher, the local IP of the system hosting the publisher application.

I hope this helps you.

**Comment by EduPonz** [comment]
To complement @richiware 's answer, Fast DDS documentation provides [some explanation](https://fast-dds.docs.eprosima.com/en/latest/fastdds/transport/tcp/tcp.html#wan-or-internet-communication-over-tcpv4) on how to communicate between LANs over TCPv4. Mind that the specifics on how to configure routers to achieve such communication are not addressed there.

**Comment by XiaomuWang** [comment]
Thanks！I have resolved.

**Comment by XiaomuWang** [comment]
Thanks！I have resolved.
