### ISSUE TITLE
LivelinessManager "writers_" vector reallocation issue [12361]

### ISSUE THREAD

**Issue by fenggaobj** [eProsima/Fast-DDS#2129]
Hi
Maybe there is an issue in LivelinessManager.cpp(2.0.x version) about "writers_" vector.  

As we know that the std::vector will reallocation when the new item is added and the contiguous vector space is not enough at the same time, the new heap address will be filled with all the items, the old heap will be destroyed.
The issue is that the std::iterator pointer(for example: "timer_owner_" in LivelinessManager) will be invalidated if the std::iterator pointer is pointing to one of them before reallocating, caused by the address is destroyed by reallocation.

Although it's an extreme case, we indeed encounted the issue.
My suggestion for fixing the issue is to add checking methods to change the std::iterator pointer when add new item added(for example: LivelinessManager::add_writer).
Could you pls confirm whether my suggestion is right,  and if not right,  pls give fix method.

Thanks a lot.

**Comment by EduPonz** [comment]
Hi @fenggaobj ,

Thanks for the great catch! We have submitted #2141 to fix the issue, it'll get merged today.
