### ISSUE TITLE
How to cross-compile FastDDS to arm linux [13676]

### ISSUE THREAD

**Issue by 263868161** [eProsima/Fast-DDS#2132]
How to cross-compile FastDDS to arm linux

**Comment by EduPonz** [comment]
Hi @263868161 ,

You can take a look at [this project](https://sourceforge.net/projects/raspberry-pi-cross-compilers/).

The first thing you'd need it a toolchain; something on the lines of:
```cmake
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_C_COMPILER arm-linux-gnueabihf-gcc)
set(CMAKE_CXX_COMPILER arm-linux-gnueabihf-g++)
set(CMAKE_CROSSCOMPILING_EMULATOR /usr/bin/qemu-arm)

list(APPEND CMAKE_FIND_ROOT_PATH ${PROJECT_BINARY_DIR}/temp_install)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
```

You'd see that this file cross-compiles using `qemu-arm` emulator, you you'd need to install that, alongside some other tools:

```docker
apt update
apt install -y build-essential cmake qemu-user
```

Then, you'd need to build Fast DDS dependencies first, followed by Fast DDS itself. You can do this using CMake. Given a `${BUILD_TYPE}`, and an `${INSTALL_DIR}`, you can sue the following CMake options in each of the projects:

###### Foonathan-memory flags

```
-DCMAKE_TOOLCHAIN_FILE=/opt/xcompiler/toolchain.cmake
-DCMAKE_BUILD_TYPE=${BUILD_TYPE}
-DBUILD_SHARED_LIBS=OFF
-DFOONATHAN_MEMORY_BUILD_TOOLS=ON
-DCMAKE_POSITION_INDEPENDENT_CODE=ON
-DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}"
```

###### tinyxml2 flags

```
-DCMAKE_TOOLCHAIN_FILE=/opt/xcompiler/toolchain.cmake
-DCMAKE_BUILD_TYPE=${BUILD_TYPE}
-DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}"
```

###### Fast CDR flags

```
-DCMAKE_TOOLCHAIN_FILE=/opt/xcompiler/toolchain.cmake
-DBUILD_SHARED_LIBS=ON
-DCMAKE_BUILD_TYPE=${BUILD_TYPE}
-DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}"
```

###### Fast DDS flags

```
-DCMAKE_TOOLCHAIN_FILE=/opt/xcompiler/toolchain.cmake
-DCMAKE_BUILD_TYPE=${BUILD_TYPE}
-DTHIRDPARTY=ON
-Dfoonathan_memory_DIR=${INSTALL_DIR}/lib/foonathan_memory/cmake
-Dtinyxml2_DIR=${INSTALL_DIR}/lib/cmake/tinyxml2
-Dfastcdr_DIR=${INSTALL_DIR}/lib/cmake/fastcdr
-DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}"
```

Hope that help!

**Comment by tparys** [comment]
If you're running Ubuntu, perhaps this is helpful? ... [https://launchpad.net/~tparys/+archive/ubuntu/fastdds](https://launchpad.net/~tparys/+archive/ubuntu/fastdds)

**Comment by JLBuenoLopez-eProsima** [comment]
I am going to close this issue due to inactivity. @263868161, feel free to reopen it if you are still having issues, but consider moving it to the Unofficial Support discussion forum according to our [CONTRIBUTING guidelines](https://github.com/eProsima/Fast-DDS/blob/master/CONTRIBUTING.md#unofficial-support).
