### ISSUE TITLE
on_data_available never called when Publisher uses RTI Connext DDS [12364]

### ISSUE THREAD

**Issue by Benatti1991** [eProsima/Fast-DDS#2139]
When the same subscriber listens to the same topic (based on the same .idl file definition) on FastDDS everything works fine.

## Expected Behavior
In principle it should behave just the same with the RTI version

## Current Behavior
If the publisher uses RTI DDS implementation, the _on_data_available_  method is never called. 

## Steps to Reproduce
I am using a slightly modified version of the hello world program that I changed to accommodate a custom message

## System information
Tried on different system, even with publisher and subscriber on the same machine

Thanks,
Simon

**Comment by EduPonz** [comment]
Hi @Benatti1991 ,

Could you provide some information about the type (the IDL would be ideal) and the versions of RTI Connext and Fast DDS you are using?

**Comment by Benatti1991** [comment]
Hi,
the RTI Connext version is 6.0.1, the fastDDS both 2.3.0 and 2.3.3 behaved the same way.
Please find the idl message definition below (the same file is used for both  participants)
Simone

`
struct TypeInt {
	sequence<long,256> data;
	long eid;
};

struct TypeFloat {
	sequence<float,256> data;
	long eid;
};

struct TypeDouble {
	sequence<double,256> data;
	long eid;
};

struct TypeShort {
	sequence<short,256> data;
	long eid;
};

struct TypeChar {
	string<512> data;
	long eid;
};



struct Vec3 {
	double x;
	double y;
	double z;
};

struct Quat {
	double e0;
	double e1;
	double e2;
	double e3;
};


struct Pose {
  Vec3 position;
  Quat rotation;
  
  Vec3 position_dt;
  Quat rotation_dt;
  
  Vec3 position_dtdt;
  Quat rotation_dtdt;
};



struct Vehicle {
	unsigned long	id;
	unsigned long type;
	Pose body;
	sequence<Pose,18> tires;
	unsigned long light_state;
};

struct Clock {
	unsigned long long secondsSinceEpoch;
	unsigned long nanoseconds;
};

struct VehicleSet {
	Clock sample_time;
	sequence<Vehicle,1024> data;
};
`

**Comment by richiware** [comment]
Which version of *fast-dds-gen* do you use to generate the source code from your IDL files? This [PR](https://github.com/eProsima/Fast-DDS-Gen/pull/57) fixed an error with alignment that produces no communication with RTI in some cases. Can you regenerate again the source code from IDL files with latest version of *fast-dds-gen*?

**Comment by Benatti1991** [comment]
@richiware I updated the generated code with fastddsgen v 2.0.1 (I didn't have a compiled 2.0.2 at hand but 2.0.1 should have the PR with that bug fix). It didn't solve the issue. The other side (RTI Connext) changed slightly their QoS and now I get the data only ONCE, then complete silence. Here is my QoS:

```
DataReaderQos qos;
qos.reliability().kind = RELIABLE_RELIABILITY_QOS;
qos.durability().kind = TRANSIENT_LOCAL_DURABILITY_QOS;
qos.endpoint().history_memory_policy = PREALLOCATED_WITH_REALLOC_MEMORY_MODE;
qos.history().kind = KEEP_LAST_HISTORY_QOS;
```
And here's the RTI QoS:
![QoS](https://user-images.githubusercontent.com/35219794/129283407-06282287-cc0b-46f9-af28-9fe777565a5b.png)

**Comment by richiware** [comment]
could you provide us a Wireshark capture of the network communications?

**Comment by JLBuenoLopez-eProsima** [comment]
I am going to close this issue due to inactivity. More information was required and no answer has been received in the last few months (see [CONTRIBUTING](https://github.com/eProsima/Fast-DDS/blob/master/CONTRIBUTING.md#issues)). Feel free to reopen providing the required information or a way to reproduce the issue at our side.
