### ISSUE TITLE
Problems encountered when using TCP to transfer large data [13688]

### ISSUE THREAD

**Issue by XiaomuWang** [eProsima/Fast-DDS#2165]
I used https://github.com/eProsima/Fast-DDS/tree/master/examples/C%2B%2B/HelloWorldExampleTCP of code to reads a large string and realize communication between two computers. But after my data communication for a period of time, an error occurred as shown in the figure below. What is wrong?
This is my test code: https://github.com/XiaomuWang/bigdataTest.git
My test data is in code of: build/1624329432.606174.string
The data size is about 504k.
Environment：
  ubuntu:18.04 
  fastdds:2.3.0

**Comment by XiaomuWang** [comment]
![091f015f48d5b413f6b444dca45b97b](https://user-images.githubusercontent.com/46257486/130594452-f5eb7ea9-7728-43c7-ab64-93b056ea5798.png)
[](url)

**Comment by XiaomuWang** [comment]
I used the following two solutions for this:

1. Use "DYNAMIC" or "PREALLOCATED_WITH_REALLOC" policy
2. Reserve enough space in the idl, for example, string<1000000> message

But did not solve the problem.

**Comment by XiaomuWang** [comment]
![image](https://user-images.githubusercontent.com/46257486/130775522-82fb1d2a-ae73-4231-aabb-d38e37143e5f.png)

**Comment by XiaomuWang** [comment]
![a12d858592589a4f805e06e328a0450](https://user-images.githubusercontent.com/46257486/131276466-52304744-fdf2-4ce1-9496-f44f323eb696.png)
The publisher is shown as "Publisher matched".But no longer send messages to subscribers

**Comment by XiaomuWang** [comment]
Question 1: The publisher is shown as "Publisher matched". As shown in the figure above. But no longer send messages to subscribers

**Comment by XiaomuWang** [comment]
![image](https://user-images.githubusercontent.com/46257486/131276725-5184e3ac-a05f-4f5c-b661-c7eb4d8dcee7.png)

**Comment by XiaomuWang** [comment]
Question 2: The subscriber has an error as "[RTCP_MSG_IN Error] Bad RTCP header identifier,closing connection", as shown in the picture above.

**Comment by XiaomuWang** [comment]
Note: These problems only happen occasionally, but once they occur, normal communication cannot be achieved.

**Comment by EduPonz** [comment]
Hi @XiaomuWang ,

This should have been corrected in #1957 , which is present in v2.3.0 onward. Could you please try upgrading Fast DDS?

**Comment by JLBuenoLopez-eProsima** [comment]
I am going to close this issue due to inactivity. A fix was proposed several months ago and no answer has been received.
