### ISSUE TITLE
UDPV4Transport stuck after lock/unlock device on IOS [3096]

### ISSUE THREAD

**Issue by realdream** [eProsima/Fast-DDS#218]
Hi! I'm working on porting ROS2 with FastRTPS on IOS.
While I found an issue that the UDPV4Transport stuck after lock/unlock ios device.
After turn on `INTERNAL_DEBUG`&`DEBUG` in CMakeList.txt  and call `Log::SetVerbosity(Log::Info)` 
I got debug msgs like this
```bash
[PUBLISHER Info] Writing new data -> Function write
[RTPS_WRITER Info] Creating new change -> Function new_change
[RTPS_WRITER Info] Change 47 to be removed. -> Function change_removed_by_history
[RTPS_HISTORY Info] Change 57 added with 25 bytes -> Function add_change
[RTPS_WRITER Info] No reader proxy to add change. -> Function unsent_change_added_to_history
[RTPS_MSG_IN Info] Error while listening to socket... -> Function operator()
[RTPS_MSG_IN Info] Error while listening to socket... -> Function operator()
[RTPS_MSG_IN Info] Error while listening to socket... -> Function operator()
[RTPS_MSG_IN Info] Error while listening to socket... -> Function operator()
[RTPS_MSG_IN Info] Error while listening to socket... -> Function operator()
[RTPS_MSG_IN Info] Error while listening to socket... -> Function operator()
```
It seems like IOS will destroy socket when turn off the screen. # #

**Comment by JLBuenoLopez-eProsima** [comment]
IOS is not an [officially supported OS](https://github.com/eProsima/Fast-DDS/blob/master/PLATFORM_SUPPORT.md#platform-support). Consequently, I am going to proceed and close this issue. If you are interested on having official support for IOS, please feel free to contact our [support team](https://github.com/eProsima/Fast-DDS#getting-help).
