### ISSUE TITLE
Creating dynamic types from IDL (Fast-DDS gen)

### ISSUE THREAD

**Issue by davidhjp01** [eProsima/Fast-DDS#2198]
Hello, I am trying to create a dynamic type data based on the data-type generated from FastDDSgen.
Is this possible? For example, on a publisher app we send datatype `HelloWorld`, which is generated from fastddsgen, and on a subscriber side, detect this datatype using DomainParticipant's `on_type_discovery` or `on_type_information_received`. It seems I am unable to achieve this even I use `-typeobject` option in FastDDSGen.

According to [here](https://github.com/eProsima/xtypes/issues/82#issuecomment-785089279),  DomainParticipant's `on_type_discovery` or `on_type_information_received` listeners are only executed when it receives/discovers FastDDS's DynamicTypes.

How can I create a new data type (for example it is sent by some other DDS library) that is unknown?

**Comment by davidhjp01** [comment]
By the way, the generated `XXXTypeObject.cpp` has `registerXXXTypes()` which only has
```
TypeObjectFactory *factory = TypeObjectFactory::get_instance();
```
According to the FastDDS [doc](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dynamic_types/discovery.html?highlight=TypeIdentifier#fast-dds-gen), the types are registered itself to TypeObjectFactory upon their creation. I see `registerXXXTypes()` is called in the constructors of the custom types when `-typeobject` is given to fastddsgen. But the above code is enough to register types?

**Comment by davidhjp01** [comment]
@fwr-ml I managed to trigger `on_type_discovery` by manually running `TypeObjectFactory::get_instance()->add_type_object()`. But it seems if IDL file contains `@Key` annotation creating a `CompleteTypeObject` via `GetXXXObject(true)` results in segmentation fault. If i remove `@Key`, DomainParticipant is able to trigger `on_type_discovery`.

**Comment by davidhjp01** [comment]
Doesn't seems so I cannot find GetKeyIdentifier in any of the generated codes.

**Comment by fwr-ml** [comment]
Still just speculating, but who defined the annotation "Key" (in the IDL file)? Maybe they meant "key"?

**Comment by davidhjp01** [comment]
I can confirm `GetXXXObject(true)` does not give seg fault when I use `@key` (small k). So i guess small 'k' is the correct syntax? I am not sure why using `@key` gave me an issue, it was quite some time ago I do not recall exactly. But I think [doc](https://fast-dds.docs.eprosima.com/en/latest/fastddsgen/dataTypes/dataTypes.html?highlight=annotation#data-types-with-a-key) should be updated or at least FastDDSgen should throw an error when `@Key` is wrong syntax?

**Comment by fwr-ml** [comment]
As I understand it one can define one's own annotations in IDL. "key" is builtin (prescribed by the standard), "Key" would have been custom but then would have to be defined and registered just like your other stuff.

**Comment by davidhjp01** [comment]
@fwr-ml I remember what happened when I used `@key` annotation -- `DataReader::read_next_sample` gives return code 11 (RETCODE_NO_DATA) when I use this annotation. Any idea why this is happening?

**Comment by fwr-ml** [comment]
With my project I haven't gotten to actually reading data, yet. So again I'm just guessing.
There's no sample to read or no proper key set in the sample. The combination of key members of a type are to identify a sample, i.e. the combination of their values should be different in each sample. For types that just have one key member, that member surely needs to be set in each sample. Types with multiple key members may need each and every key member set to a proper value, but I don't know.

**Comment by davidhjp01** [comment]
I found that the key annotation issue is mentioned in https://github.com/eProsima/Fast-DDS/issues/2064 and fixed in https://github.com/eProsima/Fast-DDS-Gen/pull/61. But there is an issue with fastddsgen for creating TypeObject/identity when I use capital `@Key`. When I use `@key` the program runs but the subscriber receives `RETCODE_NO_DATA`.

**Comment by davidhjp01** [comment]
It seems TypeObjectFactory does not initialise builtin `@Key` annotation with captical K properly. By manually adding this, I could bypass the crash. But still a subcriber gets `RETCODE_NO_DATA` when a publisher sends dynamic data with `@Key` annotation.

**Comment by davidhjp01** [comment]
Creating a new issue with the current problem

**Comment by jiapei100** [comment]
> By the way, the generated `XXXTypeObject.cpp` has `registerXXXTypes()` which only has
> 
> ```
> TypeObjectFactory *factory = TypeObjectFactory::get_instance();
> ```
> 
> According to the FastDDS [doc](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dynamic_types/discovery.html?highlight=TypeIdentifier#fast-dds-gen), the types are registered itself to TypeObjectFactory upon their creation. I see `registerXXXTypes()` is called in the constructors of the custom types when `-typeobject` is given to fastddsgen. But the above code is enough to register types?

It looks `TypeObjectFactory` is now gone... Not in **Fast-DDS** any more?
