### ISSUE TITLE
A subscriber receives RETCODE_NO_DATA with dynamic topic type with @key or @Key [13696]

### ISSUE THREAD

**Issue by davidhjp01** [eProsima/Fast-DDS#2215]
A subscriber receives return code `RETCODE_NO_DATA` when a publisher sends a data created using `DynamicTypeBuilderFactory` with `@Key` or `@key` annotation.

## Expected Behavior

A subscriber receives a data sent by a publisher

## Current Behavior

A subscriber's listener function `on_data_available` is invoked for each data sent by publisher but `read_next_sample` returns `RETCODE_NO_DATA`

## Steps to Reproduce

1. Create .cxx and .h files from .idl (contains a struct with`@key` annotation for one or more of its members) using fastddsgen with -typeobject argument
2. Initialise type object/identifier using GetXXXItentifier(true) and GetXXXObject(true).
3. Register the  dynamictype object created by TypeObjectFactory::get_instance()->build_dynamic_type().
4. Create a topic that uses the registered dynamic type object.
5. Create publishers and subscribers with listeners
6. Create dynamic data using DynamicTypeBuilderFactory
7. Publish data and observe the return code in the subscriber's listener

## System information

Intel i9-10885H 32GB RAM

- Fast-RTPS version:  2.3.3
- OS:  Windows 10
- Network interfaces: 
                      
Not specified, uses simple discovery mechanism
- ROS2: 
        

## Additional resources
- Wireshark capture 
- XML profiles file

**Comment by torbre** [comment]
It would be great if someone in the fast-dds team could look into this issue.

**Comment by richiware** [comment]
Sorry for the inconveniences @davidhjp01 .

If you are using `DynamicTypeBuilderFactory` to requesting a new `DynamicType` from a registered `TypeObject`, as @MiguelCompany suggested, PR #2262 should fix your problem. Would you mind to test your source code against that branch?

Thanks

**Comment by JesusPoderoso** [comment]
I am closing this issue, as it seems that #2316 fixed it, as @davidhjp01 said in [this comment](https://github.com/eProsima/Fast-DDS/issues/2306#issuecomment-970328683) in #2306.
