### ISSUE TITLE
Can use "memory" instead of "foonathan_memory_vendor" under arm?

### ISSUE THREAD

**Issue by chenzhengxi** [eProsima/Fast-DDS#2218]
Can use "memory" instead of "foonathan_memory_vendor" under arm?

**Comment by MiguelCompany** [comment]
Yes. As explained [here](https://github.com/eProsima/Fast-DDS/issues/2151#issuecomment-908981335), you can first install [this library](github.com/foonathan/memory) before building Fast DDS, and the one installed will be used.

**Comment by chenzhengxi** [comment]
thanks
