### ISSUE TITLE
Excessive CPU usage on Mac using Shared Memory [12607]

### ISSUE THREAD

**Issue by smnogar** [eProsima/Fast-DDS#2237]
## Expected Behavior

I am running micrortps_agent as part of the package [px4_ros_com](https://github.com/PX4/px4_ros_com). Its job is to forward micrortps messages from the [PX4 flight control software](https://github.com/PX4/PX4-Autopilot) into FastDDS to be used by ROS2. When using shared memory, its CPU utilization is 300-700% cpu usage, but when disabling shared memory and just using UDP, its utilization is ~40%. Even this 40% number is likely too high, as these are relatively small messages at low rates ~200 Hz or so. 

It seems this is related to boost using a busy wait process on the Mac. Here is a screenshot of the Mac time profiler for the shared memory case.

<img width="1917" alt="Screen Shot 2021-09-28 at 10 39 20 AM" src="https://user-images.githubusercontent.com/17053792/135129946-d9059985-a78a-47e0-8379-557a96f8f524.png">

If there is a good fastdds performance test for measuring/comparing sustained CPU usage, I'd be happy to test it out.

## Steps to Reproduce
1. PX4 ROS2 tutorial is at https://docs.px4.io/master/en/ros/ros2_comm.html

## System information

- Fast-RTPS version: 2.3.3
- OS: macOS 11.6 Big Sur
- ROS2: Galactic
- PX4 v1.12

**Comment by smnogar** [comment]
@JLBuenoLopez-eProsima Can confirm this is still an issue on the latest master branch. On some operating systems (like macOS) Boost's "lock_to_wait" function is a busy wait, driving up CPU usage.

**Comment by JesusPoderoso** [comment]
Hi @smnogar 
Shared Memory transport has been refactor to improve its performance in the [latest released versions of Fast DDS](https://fast-dds.docs.eprosima.com/en/v2.11.2/notes/notes.html#previous-versions).
Could you check if this issue is still happening in Fast DDS v2.11.2?

**Comment by smnogar** [comment]
Gave this a try. Without digging too deep, I'm not seeing much of a performance difference between 2.6 and 2.11.2. However, I've since upgraded to a M2 (arm64) based Mac, and performance is much better. Since I'm guessing Mac x86 performance isn't much of a priority these days, I'll go ahead and close this.
