### ISSUE TITLE
fast-discovery-server: support running on the background (nohub)

### ISSUE THREAD

**Issue by mobangjack** [eProsima/Fast-DDS#2271]
fast-discovery-server uses cin.ignore() for termination, resulting in "nohub" abnormal. The following command terminates immediately after key pressing:
fast-discovery-server -i 0 -l 127.0.0.1 &

**Comment by mobangjack** [comment]
I’m using ros foxy. I noticed that the problem was solved in the master branch. Thanks a lot.

**Comment by MiguelCompany** [comment]
@mobangjack Since ROS 2 Foxy already has Fast DDS 2.1.1, and I have locally checked this, I will go ahead and close this issue.

Feel free to reopen if it is not working on your side
