### ISSUE TITLE
No script output when installing with Colcon [13701]

### ISSUE THREAD

**Issue by ghostravenstorm** [eProsima/Fast-DDS#2275]
No script output when installing with Colcon

## Expected Behavior
After building with Colcon and running `setup.sh` I should see an output that the operation was successful

## Current Behavior
`setup.sh` logs no output and cmake can't find fastcdr dependencies when installing FastDDS

## Steps to Reproduce
1. Follow Colcon install method instructions.
2. Go to `install` directory and run a setup script
3. Observe no script output

## System information

- Fast-RTPS version:  latest branch
- OS: Ubuntu 21.04
- Network interfaces: 
                      

## Additional context
The install setup for foonathan and fastcdr appear to be missing after colcon build. I assumed install was sutomatic and silent.

```
ghost@Faraday-VM:~/Workspace/fastdds_ws/install$ ls
COLCON_IGNORE  fastrtps                 local_setup.bash  local_setup.sh            _local_setup_util_sh.py  setup.bash  setup.sh
fastcdr        foonathan_memory_vendor  local_setup.ps1   _local_setup_util_ps1.py  local_setup.zsh          setup.ps1   setup.zsh
ghost@Faraday-VM:~/Workspace/fastdds_ws/install$ sh setup.sh
ghost@Faraday-VM:~/Workspace/fastdds_ws/install$ 
```
No script output or feedback.

```
ghost@Faraday-VM:~/Workspace/Fast-DDS/build$ cmake ..
-- Version: 2.4.0

CMake Error at cmake/common/eprosima_libraries.cmake:132 (message):
  fastcdr package NOT found

Call Stack (most recent call first):
  CMakeLists.txt:143 (eprosima_find_package)


-- Configuring incomplete, errors occurred!
See also "/home/ghost/Workspace/Fast-DDS/build/CMakeFiles/CMakeOutput.log".
```

**Comment by MiguelCompany** [comment]
@ghostravenstorm The setup scripts are a colcon artifact. They never produce output, and are designed to be sourced (i.e. `source setup.bash`).

They are designed to work with colcon but they are not designed to work with pure cmake.
This means they will not update `CMAKE_PREFIX_PATH`.
In order for executables to work, they do update `LD_LIBRARY_PATH`.

**Comment by JLBuenoLopez-eProsima** [comment]
I am going to close this issue as no feedback from the user has been received. @ghostravenstorm, feel free to reopen if you think there is still something to be discussed.
