### ISSUE TITLE
Problems with transferring big data using DDShelloWorld dexampleTCP on two computers

### ISSUE THREAD

**Issue by XiaomuWang** [eProsima/Fast-DDS#2279]
I want to use DDS to transfer 700K data. I use HelloWorldExampleTCP code to transfer sequence types, and I find that as the data gets bigger and bigger, the transfer gets slower and slower until it finally stops, where should I optimize？Or is there anything I need to configure?Or is there a similar example tutorial for transferring big data between two computers？

For your convenience, I have tested on our TCP demo( [code](https://github.com/XiaomuWang/HelloWorldExampleTCPBigSeq) ), and the result is the same. After printing Subscriber matched, issue and acceptance will be stopped, but after acceptance is stopped, the publisher will continue to issue data. Is it because the amount of data is too large and exceeds the performance of FAST DDS?

Publisher side:
![447949027aff7426ba28a391f36c09e](https://user-images.githubusercontent.com/46257486/137871874-10c5a7fa-0db6-4199-afb3-92d620219d70.png)

Subscriber side:
![699d4c5f3770abbbfd2213639135323](https://user-images.githubusercontent.com/46257486/137871875-9e624d9b-3c4c-4d97-8608-77df2efffcb8.png)

## Steps to Reproduce
I just did the following:
1. The accepted data have been modified, such as：https://github.com/XiaomuWang/HelloWorldExampleTCPBigSeq/blob/b13b26f497d7838f6b472db27847bf7f08616ca9/HelloWorldPublisher.cpp#L53
2. Add historyMemoryPolicy，as:
https://github.com/XiaomuWang/HelloWorldExampleTCPBigSeq/blob/b13b26f497d7838f6b472db27847bf7f08616ca9/HelloWorldPublisher.cpp#L117
3. Modified IDL and generated it again.

## Current Behavior
Data sending and receiving at 700K is slow

## System information
fast dds version:2.3.0
ubuntu:18.04

## Expected Behavior
Can transfer **1634198239.994264.string** in build folder

**Comment by jparisu** [comment]
Duplicate thread: #2225
