### ISSUE TITLE
PID parsing needs vendor check(Shapedemo) [13702]

### ISSUE THREAD

**Issue by YoungJin-gurum** [eProsima/Fast-DDS#2285]
## Expected Behavior

The Shape demo of Fast-DDSs and the shape demo of Gurumdds should communicate normally.
## Current Behavior

communicate not normally.
## Steps to Reproduce

1. Run Shapedemo both of Fast-DDS and Gurumdds.
2. Gurum shape pub & Fast shape sub 
3. Or, Gurum shape sub & Fast shape pub

## System information

- Fast-RTPS version:  v2.4.0
- OS:  Ubuntu 20.04
- Network interfaces:  local(127.0.0.1)
                       
- ROS2: 
        

## Additional context

As RTPS specification, the 8000 series of PID is the area of use by each vendor.
https://github.com/eProsima/Fast-DDS/blob/d5f3559fbf91740865943237d5b0c2057e2b05af/include/fastdds/dds/core/policy/ParameterTypes.hpp#L127
Since gurumdds also uses number 8005, it seems necessary to check the vendor so that there is no problem in communication.
## Additional resources
- Wireshark capture 
- XML profiles file

**Comment by Mario-DL** [comment]
Hi @YoungJin-gurum,
Thanks for the report. It would  be nice it you could provide via e-mail the gurum DDS app so that we can reproduce it as it may be already fixed in a newer version. Also, I think you missed attaching the additional resources.
