### ISSUE TITLE
A reader receives RETCODE_NO_DATA with keyed topics when the value of the key is zero [12862]

### ISSUE THREAD

**Issue by WataruToishita** [eProsima/Fast-DDS#2306]
A reader receives RETCODE_NO_DATA with keyed topics.

1. Define a data type with a key like this:
struct sample{
    octet index;
    @Key octet key_value;
};
1. A writer write a sample with key_value = 0.
1. A reader call take_next_sample() to get the sample, but it returns RETCODE_NO_DATA.

This symptom occurs only when key_value = 0.

## Expected Behavior
A reader receives RETCODE_OK regardless of key_value.

## Current Behavior
A reader receives RETCODE_NO_DATA only when key_value = 0.

## Steps to Reproduce
1. Edit this [example](https://github.com/eProsima/Fast-DDS/blob/master/examples/C%2B%2B/DDS/Keys/keys.cpp#L408) and build. 
From `my_sample.key_value(i + 1); ` to `my_sample.key_value(i + 0);`
2. Run example (./Keys publisher)
3. Run example (./Keys subscriber)
4. Received samples with key_value!=0 will be printed in console.

## System information
- OS: Ubuntu 18.04.5
- Fast-RTPS version: 
V2.4.0: This symptom occurs.
V2.3.0: This symptom occurs.
V2.2.0: No Problem

**Comment by fujitatomoya** [comment]
CC: @Barry-Xu-2018 @iuhilnehc-ynos (This problem is originally come from one of our division.)

**Comment by Barry-Xu-2018** [comment]
After quickly checking, I found

While `key_value` is 0, an invalid `InstanceHandle_t` is created. 
https://github.com/eProsima/Fast-DDS/blob/5fc0d6c0331d663a44bcb3954e238ef78166bc33/examples/C%2B%2B/Keys/sample.idl#L1-L4
 

While key_value is 0, the value of `InstanceHandle_t`  is `0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0`. 
https://github.com/eProsima/Fast-DDS/blob/5fc0d6c0331d663a44bcb3954e238ef78166bc33/include/fastdds/rtps/common/InstanceHandle.h#L34-L37


If each value is 0, it is considered to be undefined.
https://github.com/eProsima/Fast-DDS/blob/5fc0d6c0331d663a44bcb3954e238ef78166bc33/include/fastdds/rtps/common/InstanceHandle.h#L107-L121

Get warning while creating new_change.
https://github.com/eProsima/Fast-DDS/blob/6b55651b6edfaf0a201fce26e1861ceef84696a4/src/cpp/rtps/writer/RTPSWriter.cpp#L218-L221

InstanceHandle_t is created by the below code, which is produced by `fastcdrgen` tool.   
So need to consider this special case while creating `InstanceHandle_t`
https://github.com/eProsima/Fast-DDS/blob/5fc0d6c0331d663a44bcb3954e238ef78166bc33/examples/C%2B%2B/Keys/samplePubSubTypes.cxx#L110-L132

**Comment by davidhjp01** [comment]
Hello, I posted related comments previously, just in case if it can help to resolve this issue:
https://github.com/eProsima/Fast-DDS/issues/2215#issuecomment-952037666

**Comment by MiguelCompany** [comment]
@WataruToishita @fujitatomoya @davidhjp01 Please check if #2316 solves your issues.

**Comment by fujitatomoya** [comment]
@Barry-Xu-2018 could you try that out if the problem can be solved?

**Comment by WataruToishita** [comment]
Hi @MiguelCompany,
I have verified https://github.com/eProsima/Fast-DDS/pull/2316 and it solves this issue. Thank you!!

**Comment by Barry-Xu-2018** [comment]
>@Barry-Xu-2018  could you try that out if the problem can be solved. 

After checking, #2316 can fix this problem.

**Comment by davidhjp01** [comment]
> 
> 
> @WataruToishita @fujitatomoya @davidhjp01 Please check if #2316 solves your issues.

Seems it works on our side as well.

**Comment by fujitatomoya** [comment]
@MiguelCompany we've done double check on this issue can be solved by https://github.com/eProsima/Fast-DDS/pull/2316. please close this issue once https://github.com/eProsima/Fast-DDS/pull/2316 is merged. appreciate it 👍
