### ISSUE TITLE
Do "create_publisher_with_profile" and "create_subscriber_with_profile" actually support XML config? [12869]

### ISSUE THREAD

**Issue by zongyaojin** [eProsima/Fast-DDS#2308]
I noticed that in the `DomainParticipantImpl.hpp`, the implementation looks like below:

```
    Subscriber* create_subscriber_with_profile(
            const std::string& /*profile_name*/,
            SubscriberListener* listener,
            const StatusMask& mask)
    {
        return create_subscriber(SUBSCRIBER_QOS_DEFAULT, listener, mask);
    }
    
    Publisher* create_publisher_with_profile(
            const std::string& /*profile_name*/,
            PublisherListener* listener,
            const StatusMask& mask)
    {
        return create_publisher(PUBLISHER_QOS_DEFAULT, listener, mask);
    }
```

**So I'm wondering:**
- are they just using the default QOS (hard-coded in the library that cannot be changed)? or, 
- the default QOS gets updated once `DomainParticipantFactory::get_instance()->load_XML_profiles_file("profiles.xml");` gets called? So that they are actually using the XML-configed settings?

Thank you very much in advance!

**Comment by jsantiago-eProsima** [comment]
Hi!

The implementation you quoted for `create_subscriber_with_profile` and `create_publisher_with_profile` from `DomainParticipantImpl.hpp` belongs to a mock class used for some tests. The correct header for those is this one:

https://github.com/eProsima/Fast-DDS/blob/5fc0d6c0331d663a44bcb3954e238ef78166bc33/src/cpp/fastdds/domain/DomainParticipantImpl.hpp#L129-L132

https://github.com/eProsima/Fast-DDS/blob/5fc0d6c0331d663a44bcb3954e238ef78166bc33/src/cpp/fastdds/domain/DomainParticipantImpl.hpp#L156-L159

And their implementation can be found here:

https://github.com/eProsima/Fast-DDS/blob/5fc0d6c0331d663a44bcb3954e238ef78166bc33/src/cpp/fastdds/domain/DomainParticipantImpl.cpp#L513-L516

https://github.com/eProsima/Fast-DDS/blob/5fc0d6c0331d663a44bcb3954e238ef78166bc33/src/cpp/fastdds/domain/DomainParticipantImpl.cpp#L994-L997

You can find more information regarding profile based creation of Publishers and Subscribers on the Fast DDS documentation:

- [Profile based creation of a Publisher](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/publisher/publisher/createPublisher.html#profile-based-creation-of-a-publisher) 
- [Profile based creation of a Subscriber](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/subscriber/subscriber/createSubscriber.html#profile-based-creation-of-a-subscriber)

**Comment by zongyaojin** [comment]
Hi @jsantiago-eProsima ,

> The implementation you quoted for create_subscriber_with_profile and create_publisher_with_profile from DomainParticipantImpl.hpp belongs to a mock class used for some tests.

Oh! I see! Gotcha! Somehow my editor's `Go to Definition` took me to the mock class. 😅
Thank you very much for the information! Much appreciated!

**Comment by zongyaojin** [comment]
Now I see them in their full glory!

```
static void set_qos_from_attributes(
        DataWriterQos& qos,
        const PublisherAttributes& attr)
{
    qos.writer_resource_limits().matched_subscriber_allocation = attr.matched_subscriber_allocation;
    qos.properties() = attr.properties;
    qos.throughput_controller() = attr.throughputController;
    qos.endpoint().unicast_locator_list = attr.unicastLocatorList;
    qos.endpoint().multicast_locator_list = attr.multicastLocatorList;
    qos.endpoint().remote_locator_list = attr.remoteLocatorList;
    qos.endpoint().history_memory_policy = attr.historyMemoryPolicy;
    qos.endpoint().user_defined_id = attr.getUserDefinedID();
    qos.endpoint().entity_id = attr.getEntityID();
    qos.reliable_writer_qos().times = attr.times;
    qos.reliable_writer_qos().disable_positive_acks = attr.qos.m_disablePositiveACKs;
    qos.durability() = attr.qos.m_durability;
    qos.durability_service() = attr.qos.m_durabilityService;
    qos.deadline() = attr.qos.m_deadline;
    qos.latency_budget() = attr.qos.m_latencyBudget;
    qos.liveliness() = attr.qos.m_liveliness;
    qos.reliability() = attr.qos.m_reliability;
    qos.lifespan() = attr.qos.m_lifespan;
    qos.user_data().setValue(attr.qos.m_userData);
    qos.ownership() = attr.qos.m_ownership;
    qos.ownership_strength() = attr.qos.m_ownershipStrength;
    qos.destination_order() = attr.qos.m_destinationOrder;
    qos.representation() = attr.qos.representation;
    qos.publish_mode() = attr.qos.m_publishMode;
    qos.history() = attr.topic.historyQos;
    qos.resource_limits() = attr.topic.resourceLimitsQos;
    qos.data_sharing() = attr.qos.data_sharing;
}
```
