### ISSUE TITLE
Writing large sequences failes

### ISSUE THREAD

**Issue by vale** [eProsima/Fast-DDS#2330]
## Expected Behavior
Sending a sequence with 1024 bytes (in 256 unsigned longs) should be possible. Connext DDS is able to process such messages.

## Current Behavior
Publishing messages with large sequences failed (writer_->write() returns false, If called with an instance handle the return code is RETCODE_ERROR)

## Steps to Reproduce

0. Use the HelloWorldPublisher/Subscriber example
1. add `sequence <unsigned long> data` to the HelloWorld.idl from the examples
2. use a vector<unit32_t> of size 256 for the data field and write to the data writer

## System information

- Fast-RTPS version: tried both 2.0.0 and 2.4.0
- OS: Linux Ubuntu 18.04 / Debian buster
- Network interfaces:  both eth0 (192.168.1.10) and lo (127.0.0.1) show the same issue
- ROS2: no ROS2 is used

## Additional context
I’m aware of the [Documentation for large Datarates](https://fast-dds.docs.eprosima.com/en/latest/fastdds/use_cases/large_data/large_data.html) But this does not seem to apply here since all limits are way larger than the tested ~1KiB

**Comment by vale** [comment]
For easier reproduction of the Issue I created a small [repository](https://github.com/vale/FastDDS_large_sequence_example) from the HelloWorldPub/Sub example.
If I have overlooked anything and this is the expected behavior I would be happy to read documentation on why this does not work or follow suggested workarounds.

**Comment by MiguelCompany** [comment]
Hi @vale 

The default behavior of Fast DDS is to preallocate data. The preallocated size is taken from `DataType::getMaxCdrSerializedSize`. When there is an unbounded sequence, the generated code assumes 100 elements on that method. You can either change that method to accommodate your real maximum size or change the [`history_memory_policy`](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/core/policy/eprosimaExtensions.html#memorymanagementpolicy) attribute within the `RTPSEndpointQos` to a dynamic value like `PREALLOCATED_WITH_REALLOC`.

```
writer_qos.endpoint().history_memory_policy = eprosima::fastrtps::rtps::PREALLOCATED_WITH_REALLOC_MEMORY_MODE;

reader_qos.endpoint().history_memory_policy = eprosima::fastrtps::rtps::PREALLOCATED_WITH_REALLOC_MEMORY_MODE;
```

**Comment by vale** [comment]
Thank you for pointing me in the right direction.
I think it would be helpful if this behaviour would be more discoverable in the documentation. But maybe this is just a beginners point of view which might change once I get more get more used to work with FastDDS.

I will test this in my project tomorrow.

**Comment by EduPonz** [comment]
Hi @vale ,

> I think it would be helpful if this behaviour would be more discoverable in the documentation.

We definitely agree with you! We are planning on adding a FAQ section in which this will definitely be one the top ones. However, we haven't found the time to do so yet. In any case, please do let us know whether your problem is solved this way!

**Comment by vale** [comment]
@MiguelCompany Thank you this also works for my application.

**Comment by Tooo-Top** [comment]
Follow the prompts to solve the problem. Thank you very much.
