### ISSUE TITLE
Fast-DDS Linux installation from binaries

### ISSUE THREAD

**Issue by Nir-Az** [eProsima/Fast-DDS#2348]
At the Fast-DDS install documentation there is a section of [installation from binaries](https://fast-dds.docs.eprosima.com/en/latest/installation/binaries/binaries_linux.html).

What it really does is building the fast-cdr & fast-rtps from source..

Is there some kind of Debian / APT package to install Fast-DDS? Or another install method that don't require building the source?

Thanks
Nir

**Comment by EduPonz** [comment]
Hi @Nir-Az,

> Is there some kind of Debian package to install Fast-DDS? Or another install method that don't require building the source?

There isn't any at the moment. However, we are currently working on generating such packages for a variety of the eProsima products (including Fast DDS). We will release them for Ubuntu 20.04 amd64 by the end of the year, so stay tunned!

**Comment by Nir-Az** [comment]
Great.. please consider building it for multiple OS / Arch., It can be done at GitHub-Actions or a similar CI engine.
Currently the installing procedure is quite long..
It will very much simplify the usage and examples of Fast DDS (Like the docker image you guys create which is great)

Thanks again @EduPonz

**Comment by EduPonz** [comment]
> please consider building it for multiple OS / Arch., It can be done at GitHub-Actions or a similar CI engine.

Yes, we will definitely do so! We just want to start small and take them one step at a time, but more architectures and OS will come soon enough!
