### ISSUE TITLE
Question about DurabilityQosPolicy and HistoryQosPolicy of Fast dds [13275]

### ISSUE THREAD

**Issue by cloudjacky** [eProsima/Fast-DDS#2352]
## Expected Behavior

I want to test the DurabilityQosPolicy and HistoryQosPolicy settings. First i start the publisher program and write data by the DataWriter,  And after some time. Start the subscriber progam, Expect the DataReader to receive the data sent by the DataWriter Including the data before DataReader access.

  
## Current Behavior

I want to test the DurabilityQosPolicy and HistoryQosPolicy settings. First i start the publisher program and write data by the DataWriter,  And after some time. Start the subscriber progam, However the DataWriter has previously written data that was't received by the DataReader's listener.

## Steps to Reproduce

1. Start a publish and subscribe program
    like Fast-DDS/examples/C++/HelloWorldExample

2. On the publisher program side Configure QoS as follows
     QoS configuration of topic:

       TopicQos topic_Qos;
        DurabilityQosPolicy& durability1 = topic_Qos.durability();
        durability1.kind = TRANSIENT_LOCAL_DURABILITY_QOS;
        HistoryQosPolicy& history1 = topic_Qos.history();
        history1.kind = KEEP_LAST_HISTORY_QOS;
        history1.depth = 10;

      QoS configuration of DataWriter:

      DataWriterQos writerQos;
      DurabilityQosPolicy& durability = writerQos.durability();
      durability.kind = TRANSIENT_LOCAL_DURABILITY_QOS;
      HistoryQosPolicy& history = writerQos.history();
      history.kind = KEEP_LAST_HISTORY_QOS;
      history.depth = 10;

3.  On the Subscriber program side Configure QoS as follows
     QoS configuration of topic:

       TopicQos topic_Qos;
        DurabilityQosPolicy& durability1 = topic_Qos.durability();
        durability1.kind = TRANSIENT_LOCAL_DURABILITY_QOS;
        HistoryQosPolicy& history1 = topic_Qos.history();
        history1.kind = KEEP_LAST_HISTORY_QOS;
        history1.depth = 10;

      QoS configuration of DataReader:

      DataReaderQos dataReaderQos;
      DurabilityQosPolicy& durability = dataReaderQos.durability();
      durability.kind = TRANSIENT_LOCAL_DURABILITY_QOS;
      HistoryQosPolicy& history = dataReaderQos.history();
      history.kind = KEEP_LAST_HISTORY_QOS;
      history.depth = 10;

4.   Start pubisher program. and after soma time. start subscriber program.

5.  on the function on_data_available of DataReaderListener. Only the data being written by the DataWriter can be received.

## System information

ubuntu 18.04

- Fast-RTPS version: 
- OS: 
- Network interfaces: 
                      
- ROS2: 
        

## Additional resources
- Wireshark capture 
- XML profiles file

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @cloudjacky,

Since Fast DDS v2.4.0 the Durability QoS Policy requires also setting the Reliability QoS Policy to `RELIABLE` in order to receive past samples in the DataReader. I have issued eProsima/Fast-DDS-docs#308 to clarify this point in our documentation. We also intend to update the `check_qos` implementations to return a `RETCODE_INCONSISTENT_POLICY` in case that the Durability QoS is set without being `RELIABLE`.

Also, seeing the snippets you provide, it is enough setting these QoS policies both in the DataWriter and the DataReader (it is not required that you also set the SubscriberQos or the TopicQos).

Please, let me know if setting the Reliability QoS Policy solves the issue. Thanks!

**Comment by cloudjacky** [comment]
When the reliability QoS policy is set, this problem is solved. Thank you very much!

**Comment by cloudjacky** [comment]
HI @JLBuenoLopez-eProsima 
When the reliability QoS policy is set, this problem is solved. Thank you very much!!!
