### ISSUE TITLE
Memory leak in SecurityManager [13295]

### ISSUE THREAD

**Issue by oleksandr-hryshchuk** [eProsima/Fast-DDS#2362]
Every time a participant gets discovered, `SecurityManager::on_process_handshake()` gets called. This method adds a new change to `participant_stateless_message_writer_history_`. But once the participant gone, this message never gets removed from the history.

## Expected Behavior
The related messages must be removed once a participant gets removed.

## Current Behavior
The related messages never removed. Since the `participant_stateless_message_writer_history_` is limited to 100 elements, such behavior can lead to the following failure:
```
2021-12-16 13:14:03.170 [RTPS_WRITER_HISTORY Warning] History full for writer d4.e8.27.e3.89.02.25.ff.38.7f.fc.76|0.2.1.c3 -> Function add_change_
2021-12-16 13:14:03.170 [SECURITY Error] WriterHistory cannot add the CacheChange_t -> Function on_process_handshake
```

## Steps to Reproduce
1. Compose a simple program with a single domain participant. Make sure to enable authentication and RTPS messages encryption.
2. Start the first instance of the program.
3. Start and the second instance.
4. Wait few seconds.
5. Stop the second instance.
6. Repeat steps 3-5.

## System information
- Fast-RTPS version: 2.4.0
- OS: Ubuntu 20.04

## Additional context
The following patch helps to solve the issue:
```
--- a/src/cpp/rtps/security/SecurityManager.cpp
+++ b/src/cpp/rtps/security/SecurityManager.cpp
@@ -550,6 +550,11 @@ void SecurityManager::remove_discovered_participant_info(
 
         authentication_plugin_->return_identity_handle(auth_ptr->identity_handle_, exception);
         auth_ptr->identity_handle_ = nullptr;
+        if (auth_ptr->change_sequence_number_ != SequenceNumber_t::unknown())
+        {
+            participant_stateless_message_writer_history_->remove_change(auth_ptr->change_sequence_number_);
+            auth_ptr->change_sequence_number_ = SequenceNumber_t::unknown();
+        }
     }
 }
```

**Comment by EduPonz** [comment]
Hi @oleksandr-hryshchuk  ,

Thanks for your report! I've got two questions:

* When you say *stop the second instance*, does this mean a clean exit, or are you killing the application?
* What are the QoS settings? We are specifically thinking about lease duration, but any modification you've made would be goo to know.

I've added this ticket to the v2.5.1 milestone, which will be release in the beginning of 2022. Do you want to contribute with a PR yourself? We could either do it ourselves, or give you a hand with regressions tests if need be, what do you think?

**Comment by oleksandr-hryshchuk** [comment]
Hi @EduPonz,

The second instance does a clean exit. Using default DomainParticipant QoS, except encryption enabled. It seems that handshake messages are never removed from the history, even when participant itself already removed. I will try to provide a test program.

This is just a quick fix. Probably you have a better opinion what exactly needs to be fixed.

**Comment by oleksandr-hryshchuk** [comment]
Test program attached.

First copy certs directory where you want to run the program.

Run the first instance (creates a single participant):
./history_leak_test

Run the second instance (creates a participant in the loop):
./history_leak_test loop

See the logs on the first participant after some time (~240 iterations of the second instance):
```
2021-12-21 12:38:43.005 [SECURITY Error] WriterHistory cannot add the CacheChange_t -> Function on_process_handshake
2021-12-21 12:38:43.507 [SECURITY Error] WriterHistory cannot retrieve a CacheChange_t -> Function 
```
[history_leak_test.zip](https://github.com/eProsima/Fast-DDS/files/7752209/history_leak_test.zip)
