### ISSUE TITLE
CMake:  Should VERSION_SCRIPT_SUPPORT_FLAGS always be PRIVATE?

### ISSUE THREAD

**Issue by clunietp** [eProsima/Fast-DDS#2370]
https://github.com/eProsima/Fast-DDS/commit/2a655a22af6dd757ced7220e17f9db01e3b1eddd#diff-e3052ec6d01ba5f9ae8d014fd3bdd8653f7e759e704a77bbfdb99ada532923daR517

Is there a reason `${VERSION_SCRIPT_SUPPORT_FLAGS}` should have PUBLIC visibility when building a shared library?  When I build my library which links to fastrtps and I set in my project `target_link_libraries( ${PROJECT_NAME} PUBLIC fastrtps )`, the `-Wl,--version-script=${CMAKE_CURRENT_SOURCE_DIR}/libfastrtps.version` linker command is pulled into my build, and destroys my library's symbol table, leading to `undefined reference` errors in my library (despite being linked properly).  I lost a day tracking this down.

When I change the linked source code line to `PRIVATE`, the linker flags are not included in my build, and linking is successful.  I'm not sure it makes sense to have this linker command be exported as `PUBLIC`, unless I'm missing something.  Thanks

**Comment by MiguelCompany** [comment]
Whoa! Nice cacth! It should definetely be private!

Please see #2371 for a fix

**Comment by clunietp** [comment]
Thanks @MiguelCompany !
