### ISSUE TITLE
data-sharing shared memory folder

### ISSUE THREAD

**Issue by Nir-Az** [eProsima/Fast-DDS#2377]
Hi,

When I specifically indicate a shared memory folder, I can see the created file names are : "fast_datasharing_01.0f.86.eb.2d.f5.90.e7.01.00.00.00_0.0.1"

and each run a new file is created.
Meaning with time I guess it could fill up the volume space.

Are the topic file names are controllable? does Fast-DDS supply a shared-memory folder cleanup?
I know that the destructors take care of it but I may need it for a product that will power down not nicely..
I would like to avoid new files on each run or at least delete the old ones..
BTW the fastdds shm clean command only relevant for the default folder right?

If not I guess I have to delete it from outside the application..

Thanks

**Comment by MiguelBarro** [comment]
Fast-DDS shared memory transport has a built-in watchdog that checks periodically the liveliness of each port and segment related file. That means that if two processes are using shared memory and one of them crashes the other is able to detect this and do cleanup.
In the specific case that all processes using Fast-DDS crashed then dangling files are unavoidable. The `fastdds shm` cli `clean` command copes with this situation by:
* cleaning only those shared memory files not in use (zombies). That is, using it while other processes are using Fast-DDS shared memory is harmless. 
* the shared memory files are stored in a per-machine folder and are shared by all Fast-DDS workspaces.
I'm afraid I don't understand the topic file names reference. Basically, the transport layer uses a common API and ignores any RTPS-DDS concepts like topics. The shared memory transport is based on ports associated with a shared memory segment. The DataReader or DataWriter endpoints will open a port and use it for data exchange in a specific topic but the transport receives no info on it.
Hope to be helpful.

**Comment by Nir-Az** [comment]
@MiguelBarro Thanks for the explanation.

When opening a shared memory segment using boost.interprocess the file name is configured by the user.
it is mapped to files as I wrote when I user Fast-DDS example the file name was `"fast_datasharing_01.0f.86.eb.2d.f5.90.e7.01.00.00.00_0.0.1"`

Can the Fast DDS user configure this files names?
I was hoping to see file names = topic names
Than I can see how much memory 1 topic took

I hope I explained myself.. :)
Thanks
Nir

**Comment by MiguelBarro** [comment]
Now I got your meaning. Unfortunately `fast_datasharing` is the **domain name** and is hardcoded. Nevertheless `01.0f.86.eb.2d.f5.90.e7.01.00.00.00_0.0.1` is the endpoint **GUID** which is unique.

Because each Endpoint is linked to a topic, you can track the memory associated with a topic,  tracking the memory associated with its endpoints. Though, the **GUIDs** will change on each execution making the process cumbersome.

**Comment by Nir-Az** [comment]
Thanks, I see what you mean...

It's may worth thinking about an enhancement for the domain name, you can still keep the GUID for the FastDDS logic but from my from my shared memory experience, it's easier to investigate memory mapped files that link to a certain topic than 1 big file that contain all.. 

If the shared memory folder looked like this:
<domain_name>_<topic_name>_<guid> or something like that
It was more human readable..

I will close this ticket.
I appreciated your help..
Thanks.
