### ISSUE TITLE
DataWriter cannot serialize (write) DynamicData struct with arrays [13359]

### ISSUE THREAD

**Issue by artwod** [eProsima/Fast-DDS#2378]
DataWriter returns an error while writing structure with an array inside after a member with smaller size than a size of an element of the array.

## Expected Behavior
DataWriter should write structures with arrays inside regardless of size of other structure members and order of it.

## Current Behavior
When DataWriter tries to write structure with an array inside after a member with smaller size than a size of an element of the array with the `write()` method it returns `False`.
When the size of the structure member before the array is equal or larger than the size of an element of the array `write()` works correctly and returns `True`.
Change of order of the structure member also works - first is an array and next the smaller member.

It seems to be a problem with data alignment in memory during data serialization.

## Steps to Reproduce
1. Create XML DynamicType file with structure definition as below:
```
  <type>
      <struct name="ArrayStruct">
      <member name="integer" type="int16"/>
      <member name="array" type="int32" arrayDimensions="10"/>
    </struct>
  </type>
```
2. Create a topic for appropriate type, register type for participant, create readers and writers etc.
3. Try to write data using DataWriter by `write()` method.

## System information
- Fast-RTPS version: 2.4.0
- OS: Ubuntu 20.04

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @artwod,

Sorry for the late reply. [Fast DDS v2.4.0 is no longer supported](https://github.com/eProsima/Fast-DDS/blob/master/RELEASE_SUPPORT.md). Can you confirm if this still happening in master?

Also, there are several known issues related with Dynamic Types in Fast DDS. Thus, a [refactor is being undertaken in order to fix the Dynamic Types implementation](https://github.com/eProsima/Fast-DDS/pull/3392). It is expected to be released with Fast DDS v2.11.0 scheduled for June 2023.

**Comment by JesusPoderoso** [comment]
Hi @artwod, Fast DDS v3.0.0 has been released, including a Dynamic Types refactor that may have fixed your issue. Could you check if the problem persists?

**Comment by artwod** [comment]
> Hi @artwod, Fast DDS v3.0.0 has been released, including a Dynamic Types refactor that may have fixed your issue. Could you check if the problem persists?

Hi @JesusPoderoso, thank you for the information but I'm no longer involved in using FastDDS

**Comment by JesusPoderoso** [comment]
Sorry for the inconvenience!
