### ISSUE TITLE
Shared Memory data protection [13457]

### ISSUE THREAD

**Issue by Nir-Az** [eProsima/Fast-DDS#2385]
Hi,

I got some security questions ( @MiguelCompany ) .

Regarding data-sharing/ zero copy transport.
The reader get the pointer to the actual shared memory region same as the writer, so:

According to the documentation, as I understands it, a reader can modify the sample :
>Important: If the samples “returned” by this method are loaned from the middleware (see take for more information on memory loaning), it is important that their contents not be changed. Because the memory in which the data is stored belongs to the middleware, any modifications made to the data will be seen the next time the same samples are read or taken; the samples will no longer reflect the state that was received from the network.

I also tried to run a subscriber only application and using `virt2phys` I see this:

```
7f8b91478000-7f8b9147e000 rw-s 00000000 00:1a 231                        /dev/shm/fast_datasharing_01.0f.86.eb.8c.8b.23.0c.01.00.00.00_0.0.1.4
7f8b882b4000-7f8b887fb000 rw-s 00000000 00:1a 224                        /dev/shm/fast_datasharing_01.0f.86.eb.96.86.1d.b7.01.00.00.00_0.0.1.3
```

The application get "rw" access to the topic.
I understand the MW need access to the "metadate/header" of the data in order to control it but the user data is vulnerable and can be mistakably override by a read only application.

according to what I read on boost/interprocess the shared memory segments can be opened as read only access mode.

Does `FastDDS` API supply some kind of protection reader overriding samples?

a misbehaved subscriber has direct access to the sample even if only a reader is created, he can update the data even without FastDDS API because the virtual address that mapped to the shared memory belongs to him and currently I see it as "rw" access.
theoretically a data overrun inside the reader only process can change the topic data for other readers.
Is that correct?
Can we possibly block this behavior?

I also tried running the zeroCopy example with 1 publisher and 1 subscriber and saw that 2 shared memory data files were created.
Can you explain why? I was expecting only 1 since both the reader and the write work with the same shared memory segment.
![image](https://user-images.githubusercontent.com/64067618/148238590-e052d07b-b6af-4e66-b09b-b57a60d72670.png)

Weird questions, I know...
But that's the world we live in :) 

Thanks
Nir

**Comment by MiguelCompany** [comment]
@Nir-Az As you already discovered, a data-sharing reader could write on the shared memory space. I just created PR #2405.

Regarding the two data files:
- The writer creates a file where the user data will be written, and from where the readers will read.
- The reader creates a file that will contain the interprocess condition where a writer will notify the reader that new data is available.

**Comment by Nir-Az** [comment]
Looking good Miguel, much appreciated!
I will do some tests using this PR soon..

That change removes a huge concern of security risk for a micro services approach applications that use FastDDS datasharing communication.
Glad to see you're so cooperative.
