### ISSUE TITLE
The FastDDS thread hangs on a participant removal. [13881]

### ISSUE THREAD

**Issue by oleksandr-hryshchuk** [eProsima/Fast-DDS#2500]
There is an issue with `ResourceEvent::unregister_timer()`. This function waits for a permission to modify the collection. Unfortunately it waits forever when `ResourceEvent::unregister_timer()` is called inside a timer callback. See the following stack trace that proves the issue:
```
#3  0x00007f9768aa5e30 in std::condition_variable::wait(std::unique_lock<std::mutex>&) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f9768e5f0f5 in eprosima::fastrtps::rtps::ResourceEvent::unregister_timer(eprosima::fastrtps::rtps::TimedEventImpl*) () from /test/libfastrtps.so.2.5
#5  0x00007f9768e61228 in eprosima::fastrtps::rtps::TimedEvent::~TimedEvent() () from /test/libfastrtps.so.2.5
#6  0x00007f9768e6127d in eprosima::fastrtps::rtps::TimedEvent::~TimedEvent() () from /test/libfastrtps.so.2.5
#7  0x00007f976922480f in eprosima::fastrtps::rtps::security::SecurityManager::remove_participant(eprosima::fastrtps::rtps::ParticipantProxyData const&) () from /test/libfastrtps.so.2.5
#8  0x00007f97690aac32 in eprosima::fastrtps::rtps::PDP::remove_remote_participant(eprosima::fastrtps::rtps::GUID_t const&, eprosima::fastrtps::rtps::ParticipantDiscoveryInfo::DISCOVERY_STATUS) () from /test/libfastrtps.so.2.5
#9  0x00007f97691b3c8c in eprosima::fastdds::rtps::PDPServer::remove_remote_participant(eprosima::fastrtps::rtps::GUID_t const&, eprosima::fastrtps::rtps::ParticipantDiscoveryInfo::DISCOVERY_STATUS) () from /test/libfastrtps.so.2.5
#10 0x00007f97690a9f90 in eprosima::fastrtps::rtps::PDP::check_remote_participant_liveliness(eprosima::fastrtps::rtps::ParticipantProxyData*) () from /test/libfastrtps.so.2.5
#11 0x00007f97690aa054 in std::_Function_handler<bool (), eprosima::fastrtps::rtps::PDP::add_participant_proxy_data(eprosima::fastrtps::rtps::GUID_t const&, bool)::{lambda()#1}>::_M_invoke(std::_Any_data const&) () from /test/libfastrtps.so.2.5
#12 0x00007f9768e61760 in eprosima::fastrtps::rtps::TimedEventImpl::trigger(std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >) () from /test/libfastrtps.so.2.5
#13 0x00007f9768e60186 in eprosima::fastrtps::rtps::ResourceEvent::do_timer_actions() () from /test/libfastrtps.so.2.5
#14 0x00007f9768e60647 in eprosima::fastrtps::rtps::ResourceEvent::event_service() () from /test/libfastrtps.so.2.5
```

## Expected Behavior
The FastDDS should not hang and it should be possible to exit the test program correctly.

## Current Behavior
The FastDDS hangs inside own thread and the test program cannot exit. It seems that FastDDS stops working properly.

## Steps to Reproduce

1. Compile the test program (attached).
2. Copy certs directory where you want to run the program.
3. Run the first reader instance: `./test`
4. Run the second reader instance: `./test`
5. Kill the second instance: `kill -9 <pid>`
6. Wait for 20-30 seconds in order to trigger the participant removal event.
7. Try to exit the first instance by pressing Ctrl+C.

## System information
- Fast-RTPS version: 2.5.0
- OS: 20.04

## Additional context
As possible solution, avoid waiting for the condition variable inside `unregister_timer()` when it is called from the own thread.
[test.zip](https://github.com/eProsima/Fast-DDS/files/8072900/test.zip)

**Comment by Mario-DL** [comment]
Hi @oleksandr-hryshchuk 
Thanks for the very complete report! Please check either that PR #3102 fixed the issue or try with a more recent version of Fast DDS.

**Comment by oleksandr-hryshchuk** [comment]
Hi @Mario-DL,

It is fixed, I'm closing the issue. Thank you.
