### ISSUE TITLE
[14256] reader is_sample_valid() return always false when DataSharing=On

### ISSUE THREAD

**Issue by Nir-Az** [eProsima/Fast-DDS#2609]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

when using `DataSharing` without using the `loan` API.
`is_sample_valid()` should return true on the reading samples

### Current behavior

`is_sample_valid()` return  false

### Steps to reproduce

Usage:
On reader creation:
`rqos.data_sharing().automatic();`

On reader usage:
```
        if( _reader->wait_for_unread_message( { 1, 0 } ) )
        {
            devices data;
            SampleInfo info;
            bool device_update_detected = false;
            // Process all the samples until no one is returned
            while( ReturnCode_t::RETCODE_OK == _reader->take_next_sample( &data, &info ) )
            {
                if( info.valid_data && _reader->**is_sample_valid**( &data, &info ) )
                {
. . .
```

setting `rqos.data_sharing().off` fix it.

@MiguelBarro , I think it had to do with `is_sample_valid()` implementation, treating `DataSharing` only as loan messages API.
See here: https://github.com/eProsima/Fast-DDS/blob/e8581dbe3e58905c108017eaa14ed225bcd8f76f/src/cpp/rtps/reader/RTPSReader.cpp#L397

As it seems the RTPS 2.3 extra header does not apply on DataSharing only, right?
 `is_sample_valid()` is only useful when using `loan` API?

### Fast DDS version/commit

Release 2.6.0

### Platform/Architecture

Windows 10 Visual Studio 2019

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by MiguelCompany** [comment]
@Nir-Az Method `is_sample_valid` is designed to be called for loaned samples only. We are clarifying this on the doxydoc on PR #2585. 

The middleware can only be responsible for the samples it owns, not the ones owned by the user.

**Comment by Nir-Az** [comment]
@MiguelCompany  The documentation was really missing, thanks for updating it.
I'll close the ticket .
