### ISSUE TITLE
Windows 10 version Build Fast-DDS an examples/ for DDS-Router

### ISSUE THREAD

**Issue by iekhanx** [eProsima/Fast-DDS#2643]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Hi There,

I am trying to build and examples for DDS-Router  from the following directory

Fast-DDS\example\C++\DDS\  for Windows 10 using MS Visual Studio 19
I did the following as prescribed procedure:

 >cmake -Bbuildexample -DFASTDDS_STATIC=ON .
> cmake --build buildexample --target install

but kep repeating "fastrtps.lib" did  not found!!

### Current behavior

>cmake -Bbuildexample -DFASTDDS_STATIC=ON ../
-- Building for: Visual Studio 16 2019
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.18363.
-- The C compiler identification is MSVC 19.29.30142.1
-- The CXX compiler identification is MSVC 19.29.30142.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring BasicConfiguration example...
-- Configuring DDS Benchmark...
-- Configuring DDSClientServerTest...
-- Configuring DDS Configurability example...
-- Configuring CustomListener example...
-- Configuring DDSDeadlineQoS example...
-- Configuring DDSDisablePositiveACKs example...
-- Configuring HelloWorld example...
-- Configuring DDSFiltering example...
-- Configuring DDS Flow Control example...
-- Configuring HelloWorld example...
-- Configuring HelloWorld example...
-- Configuring HelloWorld example...
-- Configuring DDSHelloWorldTCP example...
-- Configuring DDS History Kind example...
-- Configuring DDS Keys example...
-- Configuring DDS LateJoiners example...
-- Configuring DDS LifespanQos example...
-- Configuring DDS LifespanQoSExample example...
-- Configuring DDS OwnershipStrengthQoS example...
-- Configuring DDS SampleConfig_Controller example...
-- Configuring DDS SampleConfig_Events example...
-- Configuring DDS SampleCondig_Multimedia example...
-- Configuring DDSSecureHelloWorld example...
-- Configuring DDSStaticHelloWorld example...
-- Configuring TypeLookup example...
-- Configuring WriterLoansExample...
-- Configuring ZeroCopyExample...
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.23)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
CMake Error at BasicConfigurationExample/CMakeLists.txt:52 (target_link_libraries):
  Target "BasicConfigurationExample" links to:

    fastdds::optionparser

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

CMake Error at HelloWorldExampleTCP/CMakeLists.txt:64 (target_link_libraries):
  Target "DDSHelloWorldExampleTCP" links to:

    fastdds::optionparser

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

C:\Users\imrank\Fast-DDS\examples\C++\DDS\build>cmake --build buildexample --target install
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/BasicConfigurationExample/CMakeLis
  ts.txt
  HelloWorld.cxx
  HelloWorldPubSubTypes.cxx
  BasicConfigurationPublisher.cpp
  BasicConfigurationSubscriber.cpp
  BasicConfiguration_main.cpp
C:\Users\imrank\Fast-DDS\examples\C++\DDS\BasicConfigurationExample\arg_configuration.h(26,10): fat
al error C1083: Cannot open include file: 'optionparser.hpp': No such file or directory [C:\Users\i
mrank\Fast-DDS\examples\C++\DDS\build\buildexample\BasicConfigurationExample\BasicConfigurationExam
ple.vcxproj]
  Generating Code...
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/Benchmark/CMakeLists.txt
  Benchmark.cxx
  BenchmarkPubSubTypes.cxx
  Benchmark_big.cxx
  Benchmark_bigPubSubTypes.cxx
  Benchmark_medium.cxx
  Benchmark_mediumPubSubTypes.cxx
  Benchmark_small.cxx
  Benchmark_smallPubSubTypes.cxx
  BenchmarkPublisher.cpp
  BenchmarkSubscriber.cpp
  Benchmark_main.cpp
  DynamicTypesHelper.cpp
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\Benchmark\DDSBenchmark.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/ClientServerTest/CMakeLists.txt
  ClientServerTypes.cpp
  EprosimaClient.cpp
  EprosimaClientTest.cpp
  EprosimaServer.cpp
  main_ClientServerTestFastRTPS.cpp
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\ClientServerTest\DDSClientServerTest.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/Configurability/CMakeLists.txt
  sample.cxx
  samplePubSubTypes.cxx
  ConfigurabilityPublisher.cpp
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\Configurability\DDSConfigurabilityPublisher.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/Configurability/CMakeLists.txt
  sample.cxx
  samplePubSubTypes.cxx
  ConfigurabilitySubscriber.cpp
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\Configurability\DDSConfigurabilitySubscriber.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/CustomListenerExample/CMakeLists.t
  xt
  Topic.cxx
  TopicPubSubTypes.cxx
  CustomListenerPublisher.cpp
  CustomListenerSubscriber.cpp
  CustomListener_main.cpp
  CustomListeners.cpp
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\CustomListenerExample\DDSCustomListenerExample.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/DeadlineQoSExample/CMakeLists.txt
  deadlinepayload.cxx
  deadlinepayloadPubSubMain.cxx
C:\Users\imrank\Fast-DDS\examples\C++\DDS\DeadlineQoSExample\deadlinepayloadPubSubMain.cxx(21,10):
fatal error C1083: Cannot open include file: 'asio.hpp': No such file or directory [C:\Users\imrank
\Fast-DDS\examples\C++\DDS\build\buildexample\DeadlineQoSExample\DDSDeadlineQoSExample.vcxproj]
  deadlinepayloadPubSubTypes.cxx
  deadlinepayloadPublisher.cxx
  deadlinepayloadSubscriber.cxx
  Generating Code...
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/DisablePositiveACKs/CMakeLists.txt
  Topic.cxx
  TopicPubSubTypes.cxx
  DisablePositiveACKS_main.cpp
  DisablePositiveACKsPublisher.cpp
  DisablePositiveACKsSubscriber.cpp
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\DisablePositiveACKs\DDSDisablePositiveACKs.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/DynamicHelloWorldExample/CMakeList
  s.txt
  HelloWorldPublisher.cpp
  HelloWorldSubscriber.cpp
  HelloWorld_main.cpp
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\DynamicHelloWorldExample\DDSDynamicHelloWorldExample.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/Filtering/CMakeLists.txt
  FilteringExample.cxx
  FilteringExamplePubSubMain.cxx
  FilteringExamplePubSubTypes.cxx
  FilteringExamplePublisher.cxx
  FilteringExampleSubscriber.cxx
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\Filtering\DDSFiltering.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/FlowControlExample/CMakeLists.txt
  FlowControlExample.cxx
  FlowControlExamplePubSubMain.cxx
  FlowControlExamplePubSubTypes.cxx
  FlowControlExamplePublisher.cxx
  FlowControlExampleSubscriber.cxx
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\FlowControlExample\DDSFlowControlExample.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/HelloWorldExample/CMakeLists.txt
  HelloWorld.cxx
  HelloWorldPubSubTypes.cxx
  HelloWorldPublisher.cpp
  HelloWorldSubscriber.cpp
  HelloWorld_main.cpp
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\HelloWorldExample\DDSHelloWorldExample.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/HelloWorldExampleDataSharing/CMake
  Lists.txt
  HelloWorld.cxx
  HelloWorldPubSubTypes.cxx
  HelloWorldPublisher.cpp
  HelloWorldSubscriber.cpp
  HelloWorld_main.cpp
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\HelloWorldExampleDataSharing\DDSHelloWorldExampleDataSharing.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/HelloWorldExampleSharedMem/CMakeLi
  sts.txt
  HelloWorld.cxx
  HelloWorldPubSubTypes.cxx
  HelloWorldPublisher.cpp
  HelloWorldSubscriber.cpp
  HelloWorld_main.cpp
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\HelloWorldExampleSharedMem\DDSHelloWorldExampleSharedMem.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/HelloWorldExampleTCP/CMakeLists.tx
  t
  HelloWorld.cxx
  HelloWorldPubSubTypes.cxx
  HelloWorldPublisher.cpp
  HelloWorldSubscriber.cpp
  HelloWorld_main.cpp
C:\Users\imrank\Fast-DDS\examples\C++\DDS\HelloWorldExampleTCP\HelloWorld_main.cpp(28,10): fatal er
ror C1083: Cannot open include file: 'optionparser.hpp': No such file or directory [C:\Users\imrank
\Fast-DDS\examples\C++\DDS\build\buildexample\HelloWorldExampleTCP\DDSHelloWorldExampleTCP.vcxproj]
  Generating Code...
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/HistoryKind/CMakeLists.txt
  sample.cxx
  samplePubSubTypes.cxx
  pastsamples.cpp
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\HistoryKind\DDSHistoryKind.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/Keys/CMakeLists.txt
  sample.cxx
  samplePubSubTypes.cxx
  keys.cpp
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\Keys\DDSKeys.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/LateJoiners/CMakeLists.txt
  sample.cxx
  samplePubSubTypes.cxx
  latejoiners.cpp
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\LateJoiners\DDSLateJoiners.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/LifespanQoSExample/CMakeLists.txt
  Lifespan.cxx
  LifespanPubSubTypes.cxx
  LifespanPublisher.cpp
  LifespanSubscriber.cpp
  Lifespan_main.cpp
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\LifespanQoSExample\DDSLifespanQoSExample.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/LivelinessQoS/CMakeLists.txt
  Topic.cxx
  TopicPubSubTypes.cxx
  LivelinessPublisher.cpp
  LivelinessSubscriber.cpp
  Liveliness_main.cpp
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\LivelinessQoS\DDSLivelinessQoS.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/OwnershipStrengthQoSExample/CMakeL
  ists.txt
  OwnershipStrength.cxx
  OwnershipStrengthPubSubMain.cxx
  OwnershipStrengthPubSubTypes.cxx
  OwnershipStrengthPublisher.cxx
  OwnershipStrengthSubscriber.cxx
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\OwnershipStrengthQoSExample\DDSOwnershipStrengthQoSExample.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/SampleConfig_Controller/CMakeLists
  .txt
  sample.cxx
  samplePubSubTypes.cxx
  sampleconfig_safest.cpp
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\SampleConfig_Controller\DDSSampleConfig_Controller.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/SampleConfig_Events/CMakeLists.txt
  sample.cxx
  samplePubSubTypes.cxx
  sampleconfig_triggers.cpp
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\SampleConfig_Events\DDSSampleConfig_Events.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/SampleConfig_Multimedia/CMakeLists
  .txt
  sample.cxx
  samplePubSubTypes.cxx
  sampleconfig_fastest.cpp
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\SampleConfig_Multimedia\DDSSampleConfig_Multimedia.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/SecureHelloWorldExample/CMakeLists
  .txt
  HelloWorld.cxx
  HelloWorldPubSubTypes.cxx
  HelloWorldPublisher.cpp
  HelloWorldSubscriber.cpp
  HelloWorld_main.cpp
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\SecureHelloWorldExample\DDSSecureHelloWorldExample.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/StaticHelloWorldExample/CMakeLists
  .txt
  HelloWorld.cxx
  HelloWorldPubSubTypes.cxx
  HelloWorldPublisher.cpp
  HelloWorldSubscriber.cpp
  HelloWorld_main.cpp
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\StaticHelloWorldExample\DDSStaticHelloWorldExample.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/WriterLoansExample/CMakeLists.txt
  LoanableHelloWorld.cxx
  LoanableHelloWorldPubSubMain.cxx
  LoanableHelloWorldPubSubTypes.cxx
  LoanableHelloWorldPublisher.cxx
  LoanableHelloWorldSubscriber.cxx
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\WriterLoansExample\DDSWriterLoansExample.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/ZeroCopyExample/CMakeLists.txt
  LoanableHelloWorld.cxx
  LoanableHelloWorldPubSubMain.cxx
  LoanableHelloWorldPubSubTypes.cxx
  LoanableHelloWorldPublisher.cxx
  LoanableHelloWorldSubscriber.cxx
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\ZeroCopyExample\DDSZeroCopyExample.vcxproj]
  Building Custom Rule C:/Users/imrank/Fast-DDS/examples/C++/DDS/TypeLookupService/CMakeLists.txt
  TypeLookupPublisher.cpp
  TypeLookupSubscriber.cpp
  TypeLookup_main.cpp
  Generating Code...
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\TypeLookupService\TypeLookupExample.vcxproj]

### Steps to reproduce

 cmake -Bbuildexample -DFASTDDS_STATIC=ON .
> cmake --build buildexample --target install

### Fast DDS version/commit

I assume Fast-DDS 2.6.0v

### Platform/Architecture

Windows 10 Visual Studio 2019

### Transport layer

UDPv4

### Additional context

NONE

### XML configuration file

```xml
None
```

### Relevant log output

```shell
None
```

### Network traffic capture

None

**Comment by EduPonz** [comment]
Hi @iekhanx 

> I did the following as prescribed procedure

Where did you find this instruction? The thing is Fast DDS CMakelists.txt files are not prepared for building the examples from that directory. What they are prepared for is either (see [CMake options](https://fast-dds.docs.eprosima.com/en/latest/installation/configuration/cmake_options.html)):
1. Building Fast DDS with options `-DCOMPILE_EXAMPLES=ON` and `-DINSTALL_EXAMPLES=ON`
2. Building each example separately, e.g.:
   ```bash
   cd <Fast DDS repo>/examples/C++/DDS/HelloWorldExample
   mkdir build && cd build
   cmake ..
   cmake --build . --target install
   ```

The other CMake warnings you're seeing are indeed because the CMakelists.txt you're using is not prepared for the use you're giving to it.

> but kep repeating "fastrtps.lib" did not found!!

CMake is not finding your Fast DDS installation. You can either add it to the `PATH` (see [Windows installation](https://fast-dds.docs.eprosima.com/en/latest/installation/sources/sources_windows.html#run-app-cmake-sw)), or you can use `CMAKE_PREFIX_PATH` environment variable to tell CMake where to look for it.

> I assume Fast-DDS 2.6.0v

Actual commit hash would suffice.

In any case, I'm going to close this ticket as it's not a issue with the library but more with the use of its CMake files. Please feel free to keep commenting if needed, case in which I'll move the ticket to a discussion rather than an issue. Thanks!

**Comment by iekhanx** [comment]
1 **I am building and Testing DDS-Router** example for **Windows 10** 
2/ I installed Fast-DDS using or loading binary version From the eProsima website as a .exe file and run the installation, script know **install.sh**
3/ At the directory structure C:\Users\imrank\Fast-DDS got installed.
4/ Run a thorough search for the file 'fastrtps.lib'  cannot be found under **windows 10 OS**
5/ But there were a file exist under **C:\Users\imrank\Fast-DDS\lib\i86win32vs2019\fastrtps-2.6.lib** and 
       **C\Users/imrank\Fast-DDS\lib\x64Win64VS2019\fastrtps-2.6.lib**
6 These two directories under lib dir structure exist but still finding **fastrtps.lib** remains an issue according to build procedure.
7/ Although I set up under **Windows-10 path environment** modified and introduced these directory structures to link with
compile n link, but all avail?
7a/ Further more there were file is missing file from the build  **'optionparser.hpp**' from FastDDS\example projects as depict below:

**C:\Users\imrank\Fast-DDS\examples\C++\DDS\BasicConfigurationExample\arg_configuration.h(26,10): fat
al error C1083: Cannot open include file: 'optionparser.hpp': No such file or directory [C:\Users**

AND the usual error message for link error:

**DDS\build\buildexample\Benchmark\DDSBenchmark.vcxproj]
LINK : fatal error LNK1104: cannot open file 'fastrtps.lib' [C:\Users\imrank\Fast-DDS\examples\C++\
DDS\build\buildexample\ClientServerTest\DDSClientServerTest.vcxproj]**

7b/ **Current Directory struct for Windows-10 only**

**C:\User\Imrank\Fast-DDS    (for fastDDS)
C:\Users\imrank\DDS-Router  \(for DDS-Router)**

My current task IS to test the **Router over Linux and Windows** passing messages across
8/ Managed to build DDS-Router from source on Windows-10 environment but still did not know how to USE it?
9/ When I tried to run (in DDS-router) directory install/setup.bat it simply bring back control to it prompt
10/ If I visit DDS-Router\install\ dir the only found file 'setup.bat' 
11/ DDS-Router entire directory there **were not Example programs** hence I assumed **there was Fast-DDS directory an example\C++\DDS programs exists**. Therefore I decided to use these pre-created examples under the DDS-Router test

If you advise accordingly will be highly appreciated
Thank you
IK
