### ISSUE TITLE
Implement all encompassing performance test

### ISSUE THREAD

**Issue by dejanpan** [eProsima/Fast-DDS#266]
To assure that `FastRTPS` and `rmw_fastrtps_cpp` performance does not degrade with the introduction of new features and bug fixes, we propose an implementation and running of the following test. At least before every new release of FastRTPS. 

1. Following platform tuples:
    1. (ubuntu 16.04, x86_64, bouncy)
    1. (ubuntu 18.04, x86_64, bouncy)
    1. (ubuntu 16.04, aarch64, bouncy)
    1. (ubuntu 18.04, aarch64, bouncy)

1. Message types: 
    1. [PointCloud8m.msg](https://github.com/ApexAI/performance_test/blob/master/performance_test/src/msg/PointCloud8m.msg)
    1. [Range.msg](https://github.com/ApexAI/performance_test/blob/master/performance_test/src/msg/Range.msg)
    1. [Struct32k.msg](https://github.com/ApexAI/performance_test/blob/master/performance_test/src/msg/Struct32k.msg)
1. 1 Publisher and 1,3 and 10 Subscribers.
1. Time: 15 min per message
1. Setup recommended [sysctl settings](https://github.com/eProsima/Fast-RTPS-docs/blob/master/docs/advanced.rst#example-sending-a-unique-large-file)
1. Inter and Intra process communication
1. QoS:
    1. Best Effort/Volatile
    1. Best Effort/Local Transient
    1. Reliable/Volatile
    1. Reliable/Local Transient
1. security / without security

In terms of computers we would propose:
1. [Nuvo](https://www.coastipc.com/cart/Item/Nuvo-6108GC?gclid=EAIaIQobChMIzIqa4tz12wIVAsJkCh0wvQvOEAQYAiABEgKzIvD_BwE)
2. [Nvidia Drive AGX](https://www.nvidia.com/en-us/self-driving-cars/drive-platform/hardware/)

As a framework we would propose to use https://github.com/ApexAI/performance_test.

**Comment by MiguelCompany** [comment]
Closing, as we do have this already
