### ISSUE TITLE
[14651] Send google Protobuf over Dynamic Types failed

### ISSUE THREAD

**Issue by xixioba** [eProsima/Fast-DDS#2689]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

1. create data type
```
pBuilder = DynamicTypeBuilderFactory::get_instance()->create_struct_builder();
pBuilder->add_member(0, "index", DynamicTypeBuilderFactory::get_instance()->create_uint32_type());
pBuilder->add_member(1, "message", DynamicTypeBuilderFactory::get_instance()->create_string_type(1024 * 1024));
DynamicType_ptr dyn_type = pBuilder->build();
TypeSupport type_support(new DynamicPubSubType(dyn_type));
type_support.register_type(participant_, "protobuf");
DynamicData_ptr data_ptr_ = DynamicDataFactory::get_instance()->create_data(dyn_type);
```
2. serialize protobuf and write
```
std::string data = msg->SerializeAsString(); #data.size() == 57
data_ptr_->set_uint32_value(1, 0);
data_ptr_->set_string_value(data, 1);
writer_->write(data_ptr_.get());
```
4.  deserialize data in SubscriberListener::on_data_available
```
std::string data;
data_ptr_->get_string_value(data, 1); # data.size() == 57
```

### Current behavior

```
data_ptr_->get_string_value(data, 1); # data.size() get 40 for me
```

### Steps to reproduce

when protobuf is serialized into string, it may cause the data to contain 0x00 bytes, set_string_value cannot deal with it
For one of my examples, I have the following string (displayed as hex)
```
"\x22\x18\xd\x7b\xfb\x26\x3e\x15\x53\xc8\x3a\xbe\x1d\xe0\x11\x28\x43\x20\x2\x28\xc4\xc8\xc1\xe8\xc7\x1b\x29\x7b\xbf\xd1\x3e\xb1\x1e\xf7\x40\x30\x1\x38\x1\x50\x0\x58\xd4\xbd\x94\xc7\x8d\xc4\x15\x60\xfa\xb5\x97\xc7\x8d\xc4\x15"
```
The 41st byte is 0x00, which causes my receiver to receive only 40 bytes of data

### Fast DDS version/commit

[v2.6.0](https://github.com/eProsima/Fast-DDS/releases/tag/v2.6.0)

### Platform/Architecture

MacOS Mojave 10.14

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by xiaokezhou** [comment]
I have the same problem.

**Comment by xixioba** [comment]
@xiaokezhou 
It seems that this road cannot be taken. 
I have to use **sequence** instead, but I must use it in struct. If you also need dynamic data, my example can give you a reference
1. create data type(sequence in struct)
```
DynamicType_ptr byte_type = DynamicTypeBuilderFactory::get_instance()->create_byte_type();
DynamicTypeBuilder_ptr sequance_builder = DynamicTypeBuilderFactory::get_instance()->create_sequence_builder(byte_type,[default 100]);
DynamicTypeBuilder_ptr pBuilder = DynamicTypeBuilderFactory::get_instance()->create_struct_builder();
pBuilder->add_member(0, "size", DynamicTypeBuilderFactory::get_instance()->create_uint32_type());
pBuilder->add_member(1, "message", sequance_builder.get());
DynamicType_ptr dyn_type = pBuilder->build();
TypeSupport type_support(new DynamicPubSubType(dyn_type));
type_support.register_type(participant_, "protobuf"); #this need sequence in struct, otherwise crash
```
2. serialize protobuf and write(protobuf msg)
```
std::vector<char> data_vec(msg->ByteSizeLong());
msg->SerializeToArray(data_vec.data(), data_vec.size());
data_ptr_->set_uint32_value(data_vec.size(), 0);
MemberId id;
DynamicData *child_data = data_ptr_->loan_value(1);
child_data->clear_data();
for (int i = 0; i < data_vec.size(); i++)
{
    child_data->insert_byte_value(data_vec[i], id);
}
data_ptr_->return_loaned_value(child_data);
writer_->write(data_ptr_.get());
```
3. deserialize data in SubscriberListener::on_data_available
```
uint32_t size = data_ptr_->get_uint32_value(0);
DynamicData *child_data = data_ptr_->loan_value(1);
std::vector<char> data_vec;
for (int i = 0; i < size; i++)
{
    data_vec.push_back(child_data->get_byte_value(i));
}
data_ptr_->return_loaned_value(child_data);
msg.ParseFromArray(data_vec.data(), data_vec.size())
```
BTW, I did some searching and someone suggested that the following settings are required
```
// writer_qos.endpoint().history_memory_policy = eprosima::fastrtps::rtps::PREALLOCATED_WITH_REALLOC_MEMORY_MODE;
// reader_qos.endpoint().history_memory_policy = eprosima::fastrtps::rtps::PREALLOCATED_WITH_REALLOC_MEMORY_MODE;
```

**Comment by MiguelCompany** [comment]
@xixioba @xiaokezhou I created eProsima/Fast-CDR#123, but I then realized that IDL 4.2 does not allow strings to have null characters on the content of a string.

Section 7.4.1.4.4.3.2 states:
_IDL defines the string type string consisting of a list of all possible 8-bit quantities **except null**. A string is similar to a sequence of char._

This means that using a sequence of bytes is the way to go.

**Comment by xixioba** [comment]
@MiguelCompany 
Well, as a newbie, this really bothers me
Also, there are so few tutorials on **Dynamic Types** that you can't even find enough code

**Comment by xiaokezhou** [comment]
@xixioba Yes，sequence works well. BTW, are you also using Apollo and cyberRT platform? Double serialization : rawdata -> protobuf -> fastcdr ?

**Comment by xixioba** [comment]
@xiaokezhou 
Yes, I also use apollo (cyber rt), the **Dynamic Types** I'm using don't seem to need to be serialized again, so I just need to data->protobuf serialize-> insert sequence, I'm not sure if fastcdr serialization is required

Have you tested a large amount of data?
I set the relevant qos, but I still need to set a large initial value (100->1000000) below to communicate 
```
DynamicTypeBuilderFactory::get_instance()->create_sequence_builder(byte_type,[default 100]);
```
 If there is a successful minimization example, it would be better.

**Comment by xiaokezhou** [comment]
> @xiaokezhou Yes, I also use apollo (cyber rt), the **Dynamic Types** I'm using don't seem to need to be serialized again, so I just need to data->protobuf serialize-> insert sequence, I'm not sure if fastcdr serialization is required
> 
> Have you tested a large amount of data? I set the relevant qos, but I still need to set a large initial value (100->1000000) below to communicate
> 
> ```
> DynamicTypeBuilderFactory::get_instance()->create_sequence_builder(byte_type,[default 100]);
> ```
> 
> If there is a successful minimization example, it would be better.


I don't know whether you mean you have to preallocate memory for a sequence. But when I once tried to define a data field with "sequence" in .idl file, I found it is necessary to do like this "sequence<uint8, 1000000>", which  has to be big enough to hold a jpeg image frame.  This issue was also raised by someone else. I don't know how it is going now. Maybe you can search it in the closed issues.

And, about the fastcdr serialization, I think it happens when you use fastdds to send message. So, actually, you serialize your  data with protobuf to a byte sequence/ or a string, then you send the string after serialize it again with fastcdr. That is my understanding,  maybe not right.

**Comment by xixioba** [comment]
@xiaokezhou 
oh well someone made a hint [here](https://github.com/eProsima/Fast-DDS/issues/2330#issuecomment-989607848) but it didn't work for me, maybe I'm using **DynamicData** instead of define in **.idl**

About multiple serialization, I seem to be very similar [here](https://www.eprosima.com/index.php/products-all/tools/eprosima-dynamic-fast-buffers). I think a simple sequence struct can be satisfied, so I don't need an idl file, but I don't use cdr-related code, which really confuses me.

**Comment by willstott101** [comment]
Just a not for anyone finding this - it appears that sequence types are serilaized/deserialized very inefficiently in Fast DDS. Each element is stored in an index -> value map!
