### ISSUE TITLE
[DynamicData over DDS layer] can not send large data 

### ISSUE THREAD

**Issue by xixioba** [eProsima/Fast-DDS#2692]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Send and receive with 1mb~10mb **DynamicData** sequence without IDL.
Constructed as follows:
```
uint32_t size;
sequence<byte> message;
```

### Current behavior

```
[DYN_TYPES Error] Error inserting data. The container is full. -> Function insert_sequence_data
...
```

### Steps to reproduce

1. setup qos of DataReader and DataWriter
```
DataReaderQos qos = DATAREADER_QOS_DEFAULT;
qos.endpoint().history_memory_policy = eprosima::fastrtps::rtps::PREALLOCATED_WITH_REALLOC_MEMORY_MODE;
DataReader* reader_ = subscriber_->create_datareader(topic_, qos, sub_listener_cb_);

DataWriterQos qos = DATAWRITER_QOS_DEFAULT;
qos.endpoint().history_memory_policy = eprosima::fastrtps::rtps::PREALLOCATED_WITH_REALLOC_MEMORY_MODE;
DataWriter* writer_ = publisher_->create_datawriter(topic_, qos, pub_listener_cb_);
```
2. send and receive data like #2689

### Fast DDS version/commit

[v2.6.0](https://github.com/eProsima/Fast-DDS/releases/tag/v2.6.0)

### Platform/Architecture

MacOS Mojave 10.14

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by xixioba** [comment]
@MiguelCompany can you give some hints?

**Comment by JLBuenoLopez-eProsima** [comment]
There are several known issues related with Dynamic Types in Fast DDS. Thus, a [refactor is being undertaken in order to fix the Dynamic Types implementation](https://github.com/eProsima/Fast-DDS/pull/3392). It is expected to be released with Fast DDS v2.11.0 scheduled for June 2023.

**Comment by JesusPoderoso** [comment]
Hi @xixioba, Fast DDS v3.0.0 has been released, including the Dynamic Types refactor mentioned.
Could you check if the issue persists?

**Comment by xixioba** [comment]
It's been a long time, I can't verify it anymore, sorry
