### ISSUE TITLE
dds crashes when writing

### ISSUE THREAD

**Issue by huqin-RM** [eProsima/Fast-DDS#2701]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

I wrote 20m data

### Current behavior

I wrote 20m data，but crashed

### Steps to reproduce

void TopicPayloadPool::reserve (
        uint32_t min_num_payloads,
        uint32_t size)
{
    assert (min_num_payloads <= max_pool_size_);

    for (size_t i = all_payloads_.size(); i < min_num_payloads; ++i)
    {
        PayloadNode* payload = do_allocate(size);
        free_payloads_.push_back(payload);
    }
}

Does not judge whether the payload is nullptr。Will it crash when writing data?

### Fast DDS version/commit

2.6

### Platform/Architecture

Windows 10 Visual Studio 2019

### Transport layer

UDPv4

**Comment by Mario-DL** [comment]
Hi @huqin-RM,

Sorry for the late response and thanks for the report. The proposed `nullptr` check was added in #2976 and included in the 2.8.1 release, so I am closing this issue.
