### ISSUE TITLE
Unable to Send Large Strings of Size 4096 bytes [14846]

### ISSUE THREAD

**Issue by paulbkeelp** [eProsima/Fast-DDS#2740]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Expected to Send Large Strings

### Current behavior

Unable to Send Large Strings of Size 4096 bytes

We need to send Large Strings(json format) from publisher to susbcriber before converting in to Json at subscriber end. we are unable to send this much size of data.

### Steps to reproduce

Send any Large size of strings

### Fast DDS version/commit

Latest

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

UDPv4

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @paulbkeelp 

Could you please provide some more information about the steps you are taking? How can your use issue be reproduced? Fast DDS is a complex library with a lot of settings. Fast DDS CI includes tests checking the sending of large data messages so it is probable that it is something related to your Fast DDS setup. Some basic information that would be helpful will be:

* IDL file you are using. Are you generating the Type Support with Fast DDS-Gen?
* QoS settings (either by code or the XML file you are using).
* A small reproducer or some steps that we can follow to reproduce your issue.

Thanks in advance!

**Comment by paulbkeelp** [comment]
Dear @JLBuenoLopez-eProsima Thank you for your message. Please find the requested info
IDL : 
struct InfoMessage
{
    string message
    short type;
};

Sample Source code for the properties : 
--------------------------------------------------------------------------------------------------------------------------------------

    auto udp_transport = std::make_shared<eprosima::fastdds::rtps::UDPv4TransportDescriptor>();
    participant_ptr->transport().user_transports.push_back(udp_transport);
    participant_ptr->transport().use_builtin_transports = false;

    m_participant =
        DomainParticipantFactory::get_instance()->create_participant(0, *participant_ptr.get());

    m_commandMessagetype.register_type(m_participant);  /// type as per the above IDL
    m_infoMessagetype.register_type(m_participant);

    // Create the subscription Topic
    m_topicCommandMessageSub = m_participant->create_topic(sub, "InfoMessage", TOPIC_QOS_DEFAULT);
    if (m_topicCommandMessageSub == nullptr)
    {
        return false;
    }

    // Create the publish Topic
    m_topicInfoMessagePub =  m_participant->create_topic(pub, "CommandMessage", TOPIC_QOS_DEFAULT);
    if (m_topicInfoMessagePub == nullptr)
    {
        return false;
    }

    // Create the Subscriber
    m_subscriber = m_participant->create_subscriber(SUBSCRIBER_QOS_DEFAULT, nullptr);
    if (m_subscriber == nullptr)
    {
        return false;
    }

    // Create the DataReader
    m_reader = m_subscriber->create_datareader(m_topicCommandMessageSub, DATAREADER_QOS_DEFAULT, &m_infoMessageSubListener);
    if (m_reader == nullptr)
    {
        return false;
    }


    // Create the Publisher
    m_publisher = m_participant->create_publisher(PUBLISHER_QOS_DEFAULT, nullptr);
    if (m_publisher == nullptr)
    {
    // Create the Publisher
    m_publisher = m_participant->create_publisher(PUBLISHER_QOS_DEFAULT, nullptr);
    if (m_publisher == nullptr)
    {
        return false;
    }

    // Create the DataWriter
    m_writer = m_publisher->create_datawriter(m_topicInfoMessagePub, DATAWRITER_QOS_DEFAULT, &m_commandMessagePubListener);
    if (m_writer == nullptr)
    {
            return false;
    }
------------------------------------------------------------------------------------------------------------------
What We are writing :
Large Json string - If we write the large json formared string with large size around 4k
ex format - std::string val =  "{\"stringval\": \"my large string say 4k bytes \"}";
if (&m_commandMessagePubListener.matched_ > 0)
    {
          m_commandMessagePubType.message()  = <writing large json formated string>
          m_commandMessagePubType.type()  = 1000;
          m_writer->write(&m_commandMessagePubType);
        return true;
    }

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @paulbkeelp,

Probably your issue is a duplicate of #2330. There you have the answer: you should modify the [memory management policy](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/core/policy/eprosimaExtensions.html?highlight=memorymanagement#memorymanagementpolicy) to `PREALLOCATED_WITH_REALLOC_MEMORY_MODE`.

If this solves your issue be so kind to close it. Thanks!

**Comment by paulbkeelp** [comment]
@JLBuenoLopez-eProsima Thanks for the speedy response. I wil have a look and test with the change. I will get back to you after my testing. I will now close this for now.

Many Thanks
