### ISSUE TITLE
[15016] CPU usage increase in v2.6.0 comparing with v2.2.0

### ISSUE THREAD

**Issue by Barry-Xu-2018** [eProsima/Fast-DDS#2779]
### Expected behavior

Almost the same CPU usage

### Current behavior

v2.6.0 have more CPU usage than v2.2.0

### Steps to reproduce

Hardware platform is i.MX 6.   
Test program is the same and the used version of fastdds is v2.6.0 and v2.2.0   

One subscriber is on this hardware device.  There are other 5 devices which will be started and send message to this device.   
At subscriber side,  there are about 500 messages received immediately after matching.   
During this period,  
v2.2.0:   CPU usage (30% ~ 70%) will last for about 1 minute.  
v2.6.0:   CPU usage (28% ~ 72%) will last for about 3 minutes. 

While receiving messages from one device,   
v2.2.0: CPU usage is about 2.5%.  
v2.6.0: CPU usage is about 7.5%.  

I am modifying DDS sample code to reproduce it. After done, I will attach code.  

### Fast DDS version/commit

v2.2.0 and v2.6.0

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

For v2.6.1  
If receive 100 messages, CPU usage is about 20%.  
If receive 500 messages, CPU usage is about 50%.
If receive 1000 messages, CPU usage is about 100%.

After analysis, the function using much CPU is

https://github.com/eProsima/Fast-DDS/blob/master/src/cpp/fastdds/subscriber/DataReaderImpl.cpp#L659  

And

https://github.com/eProsima/Fast-DDS/blob/master/src/cpp/fastdds/subscriber/DataReaderImpl.cpp#L673 (It also calls above `lookup_instance`).   

Above information isn't enough. I will continue to supplement information.

**Comment by MiguelCompany** [comment]
@Barry-Xu-2018 If `lookup_instance` is the offender, I assume this is only relevant when the number of instances is high.

I've been thinking about this over the weekend, and I have some ideas on how to fix this. We'll keep you posted.

**Comment by MiguelCompany** [comment]
@Barry-Xu-2018 While not yet finished, I have some initial work on [this branch](https://github.com/eProsima/Fast-DDS/tree/bugfix/available-instances-access)

**Comment by MiguelCompany** [comment]
@Barry-Xu-2018 Please check #2785 for a possible fix. Internal checks look promising.

**Comment by Barry-Xu-2018** [comment]
@MiguelCompany 

Thanks for your quick work. I will test it tomorrow and share the result with you.

**Comment by Barry-Xu-2018** [comment]
@MiguelCompany 

According to test result, I find, from v2.6.1, the CPU usage is decreased obviously comparing with v2.6.0.  
[2785](https://github.com/eProsima/Fast-DDS/pull/2785) doesn't bring obvious performance improvement.  
I think it is related to my test cases.   
`Master (commit: 39b51489e877) before applying [2785]` and `applying [2785]` can receive more messages, comparing other test version.   

### Test environment
1. There are 5 publishers on host 
2. One subscriber is on RasPi 4 board.

A gigabit switch is used to connect host and RasPi 4 board.

Test program: https://github.com/Barry-Xu-2018/fastdds_cpu_usage_test

### Test Steps:

1. Launch subscriber on Raspi board. And use pidstat (from sysstat package) to get CPU usage pre 1 second.
2. Launch 5 publishers with different key at the same time. Each publisher send 100 messages immediately after connection. So subscriber can receive 500 messages without loss of message.

### Test result:
| Version | Average CPU Usage | 
|:--|:--|
| v2.2.0 | 6.93% |
| v2.6.0 | 17.68% | 
| v2.6.1 | 7.5% |
| master (commit: 39b51489e877) before applying [2785](https://github.com/eProsima/Fast-DDS/pull/2785) |  8% |
| Apply [2785](https://github.com/eProsima/Fast-DDS/pull/2785) |  8% |

Test 10 times for each version.  
Original test result as below:  
- v2.2.0
  | CPU usage |  Received messages |
  |:--|:--|
  |  6.93%  | 287|
  |6% |    359|
  |7% |    467|
  |7% |    296|
  |7% |    314|
  |6% |    416|
  |8% |    384|
  |6% |    391|
  |6% |    385|
  |7% |    489|

- v2.6.0
   | CPU usage |  Received messages |
   |:--|:--|
   | 17% | 413 |
   | 17% | 500 |
   | 17% | 500 |
   | 18% | 500 |
   | 18% | 498 |
   | 17% | 458 |
   | 19% | 500 |
   | 18% | 500 |
   | 18.81% | 366 |
   | 17% | 416 |

- 2.6.1
   | CPU usage |  Received messages |
   |:--|:--|
   | 7% |  321 |
   | 8% |  473 |
   | 6% |  410 |
   | 8% |  386 |
   | 9% |  500 |
   | 8% |  415 |
   | 7% |  397 |
   | 7% |  437 |
   | 8% |  498 |
   | 7% |  378 |

- Master (commit: 39b51489e877) before applying [2785](https://github.com/eProsima/Fast-DDS/pull/2785)
   | CPU usage |  Received messages |
   |:--|:--|
   | 7% |  424 |
   | 7% |  495 |
   | 9% |  500 |
   | 9% |  500 |
   | 9% |  500 |
   | 6% |  358 |
   | 7% |  428 |
   | 9% |  422 |
   | 8% |  294 |
   | 9% |  500 |

- Apply [2785](https://github.com/eProsima/Fast-DDS/pull/2785)  
   | CPU usage |  Received messages |
   |:--|:--|
   | 9%  | 426 |
   | 7%  | 453 |
   | 8%  | 403 |
   | 8%  | 419 |
   | 7%  | 500 |
   | 8%  | 498 |
   | 8%  | 439 |
   | 8%  | 500 |
   | 9%  | 500 |
   | 8%  | 445 |

**Comment by MiguelCompany** [comment]
@Barry-Xu-2018 #2785 improves the case when the number of instances is big. You will only see the improvement if each publisher writes 500 different key values.

Regarding the 2.6.0 -> 2.6.1 improvement, #2712 fixed a bug on the transport layer that greatly reduced CPU usage.

**Comment by Barry-Xu-2018** [comment]
@MiguelCompany 

> https://github.com/eProsima/Fast-DDS/pull/2785 improves the case when the number of instances is big. You will only see the improvement if each publisher writes 500 different key values.

Yes.  This patch is important for the case using large number of key.  

> Regarding the 2.6.0 -> 2.6.1 improvement, https://github.com/eProsima/Fast-DDS/pull/2712 fixed a bug on the transport layer that greatly reduced CPU usage.

Okay. Thanks for your information.
