### ISSUE TITLE
can not fully publish message when it contains '0' with fast-rtps v1.5.0

### ISSUE THREAD

**Issue by YelaShady** [eProsima/Fast-DDS#2786]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

I clone some other projects and it use the older version of fast-rtps v1.5.0,when I test the project, I found in some cases it communication fail when send message with '\0' data,the publisher can not send the data after '\0'.
Furthre,I run the "HelloWorldExample" in the fast-rtps v1.5.0 project, and I modified the example code here to find if it is the fast-rtps mechanism reason or it's the project I cloned error used reason, I found it also fails in fast-rtps v1.5.0.
I modified code here in HelloWorldPublisher.cc
```
bool HelloWorldPublisher::init()
{
    m_Hello.index(0);

    char test[12] = {"Hello\0World"};//to make message contains '\0'
    m_Hello.message().assign(test,11);
    //m_Hello.message("HelloWorld");
```
Build it and run it ,I found the subscriber print message like:
Message Hello 1 RECEIVED
It drops the data after "\0",here is "\0World"
Also I capture the data by wireshark,I found the data sent by publisher drops the data after "\0".
I think it is not reasonable to drop the data after "\0".

### Current behavior

When message contains '\0, fast-rtps may drop the data after '\0'?

### Steps to reproduce

I modified code here in HelloWorldPublisher.cc with  "HelloWorldExample" in the fast-rtps v1.5.0 project
```
bool HelloWorldPublisher::init()
{
    m_Hello.index(0);

    char test[12] = {"Hello\0World"};//to make message contains '\0'
    m_Hello.message().assign(test,11);
    //m_Hello.message("HelloWorld");
```
Build it and run it ,I found the subscriber print message like:
Message Hello 1 RECEIVED
It drops the data after "\0",here is "\0World"

### Fast DDS version/commit

Fast-rtps v1.5.0

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

UDPv4

### Additional context

NA

### XML configuration file

```xml
NA
```

### Relevant log output

```shell
Subscriber matched
Message Hello 1 RECEIVED
Message Hello 2 RECEIVED
Message Hello 3 RECEIVED
Message Hello 4 RECEIVED
Message Hello 5 RECEIVED
Message Hello 6 RECEIVED
Message Hello 7 RECEIVED
Message Hello 8 RECEIVED
Message Hello 9 RECEIVED
Message Hello 10 RECEIVED
Subscriber unmatched
```

### Network traffic capture

NA

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @YelaShady,

On the one hand, Fast RTPS v1.5.0 is no longer receiving support (please, see [Release Support](https://github.com/eProsima/Fast-DDS/blob/master/RELEASE_SUPPORT.md#release-support) for more information). On the other hand, you may find [this comment](https://github.com/eProsima/Fast-DDS/issues/2689#issuecomment-1132705252) interesting. [IDL 4.2 specification](https://www.omg.org/spec/IDL/4.2/About-IDL/) does not allow null characters on the content of strings.

**Comment by YelaShady** [comment]
> Hi @YelaShady,
> 
> On the one hand, Fast RTPS v1.5.0 is no longer receiving support (please, see [Release Support](https://github.com/eProsima/Fast-DDS/blob/master/RELEASE_SUPPORT.md#release-support) for more information). On the other hand, you may find [this comment](https://github.com/eProsima/Fast-DDS/issues/2689#issuecomment-1132705252) interesting. [IDL 4.2 specification](https://www.omg.org/spec/IDL/4.2/About-IDL/) does not allow null characters on the content of strings.

Thanks,got it
