### ISSUE TITLE
Shared mem partition fills up after many runs: how to garbage collect?

### ISSUE THREAD

**Issue by Aposhian** [eProsima/Fast-DDS#2790]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

I should be able to turn my system on and off many times with it operating the same every time.

### Current behavior

After bringing up the system a number of times, my `/dev/shm` tmpfs partition fills up, no matter how big it is. Currently, mine is 32GB and it still fills up.

### Steps to reproduce

Restart a participant many times in a loop until it can no longer create new shared mem segments.

### Fast DDS version/commit

2.6.0-3jammy.20220520.002055

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

When I run FastDDS participants many times, my `/dev/shm` partition fills up with segments until no more can be created. This is with `/dev/shm` being 32 GB in size. Does FastDDS not have any garbage collection capabilities, or does it just rely on machine restart?

This is running in containers with `ipc: host` and `network: host`

### Relevant log output

```shell
[RTPS_TRANSPORT_SHM Error] Failed to create segment fastrtps_796f9c10effb4cf1: No such file or directory -> Function Segment
[RTPS_MSG_OUT Error] No such file or directory -> Function init
[RTPS_PARTICIPANT Error] Unable to Register SHM Transport. SHM Transport is not supported in the current platform.
```

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @Aposhian,

The shared memory files are cleaned up if the application using Fast DDS exits cleanly using the corresponding API to delete the DDS DomainParticipant. If your application is crashing or you are closing it without calling `DomainParticipantFactory::delete_participant` then the files are going to be kept. Nevertheless, Fast DDS tries to reuse the shared memory files from previous runs. However, as the application has not exited cleanly, some of these files can be still marked as blocked (you may find [this comment](https://github.com/eProsima/Fast-DDS/issues/2003#issuecomment-1160245640) helpful).

**Comment by Aposhian** [comment]
I am using this from ROS2. I am typically stopping applications with SIGINT. Does `rmw_fastrtps` make a call to `DomainParticipantFactory::delete_participant` in that event?

**Comment by Aposhian** [comment]
Is it safe to run `fastdds shm clean` while nodes are running?

**Comment by llapx** [comment]
@Aposhian 
> After bringing up the system a number of times...

`fastdds shm clean` is a python script, you can call it when bring the system down to insure the tmplate files are cleaned up.

**Comment by llapx** [comment]
@JLBuenoLopez-eProsima 

Is it possible to add a feature for auto cleanup broken shared files for fastdds? I think this maybe helpful for user.

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @llapx,

It is not in Fast DDS roadmap to include such feature. If you are interested you can open a ticket in the [corresponding forum](https://github.com/eProsima/Fast-DDS/blob/master/CONTRIBUTING.md#feature-request) and see if there is enough community support. Also, you may be interested in contacting [Fast DDS support team](https://github.com/eProsima/Fast-DDS/blob/master/CONTRIBUTING.md#feature-request) for commercial support.

**Comment by JLBuenoLopez-eProsima** [comment]
> I am using this from ROS2. I am typically stopping applications with SIGINT. Does `rmw_fastrtps` make a call to `DomainParticipantFactory::delete_participant` in that event?

@Aposhian, [`rmw_fastrtps_shared_cpp::destroy_participant`](https://github.com/ros2/rmw_fastrtps/blob/rolling/rmw_fastrtps_shared_cpp/src/participant.cpp#L294)  handles the DomainParticipant destruction cleanly. I do not know how the ROS 2 stack signal handling works and if this method is called in case of SIGINT. I suppose that question should be asked in some other place.

I think this issue have been answered and can be closed. Would you mind doing it, @Aposhian? Otherwise, let me know why you consider the issue should be kept open. Maybe we should consider moving to the Q&A forum where according to [Fast DDS contributing guidelines](https://github.com/eProsima/Fast-DDS/blob/master/CONTRIBUTING.md#qa), questions should be kept.

**Comment by Aposhian** [comment]
I can see there is a way forward by using `fastdds shm clean`, but I still think this presents a bad user experience. For someone who is using FastDDS with the default config, they may not even exactly know that shared memory is being used, or how shared memory is being used. They use the system for a while, and it works, and then someday it may break with the cryptic error messages that I posted above. The error messages could be better if it said something like "Unable to create new shared memory segments: is your shared memory partition full? Try running `fastdds shm clean`." Or, if a shared memory segment is unable to be created, then fastdds could automatically try `fastdds shm clean` and retry (with a corresponding warning message as to what is going on).

**Comment by fujitatomoya** [comment]
@JLBuenoLopez-eProsima How about updating the message for user to be more user friendly as @Aposhian suggested above? i think that message is not clear for user what to do to solve the problem...

**Comment by jingTian-z** [comment]
I encountered the same issue on Android, and I never found a solution. I had to disable shared memory. This problem occurred after compiling the security module, and the problem still exists after undoing the modification again.

**Comment by JLBuenoLopez-eProsima** [comment]
I have created a ticket to track the enhancement of improving the log messages when initializing the SHM Transport (#3578). I am going to close this issue because the question was answered and there is a ticket tracking the improvement.
