### ISSUE TITLE
Continous Messaging between to components within same host Dumps Core- SIGSEGV

### ISSUE THREAD

**Issue by sreemtech** [eProsima/Fast-DDS#2803]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Continuous Messaging between to components within same host Dumps Core- SIGSEGV

We are trying to communicate between two processes via FASTDDS on a single topic dumps the core.
Process A
Publish a collection of data in a topic ( write each time) within in a continuous for loop

Process B
Subscribe the collection of data in a topic ( read each time) within in a continuous for loop

### Current behavior

after a min of processing I see the core dump 

Thread 7 "comp-handler" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeffff640 (LWP 36482)]
0x00007ffff799ae22 in eprosima::fastrtps::rtps::ReaderPool::get_next_unread_payload(eprosima::fastrtps::rtps::CacheChange_t&, eprosima::fastrtps::rtps::SequenceNumber_t&, unsigned long) () from /home/seaeye02/Fast-DDS/install/fastrtps/lib/libfastrtps.so.2.7
(gdb) list
1	../sysdeps/x86_64/crti.S: No such file or directory.
(gdb) where
#0  0x00007ffff799ae22 in eprosima::fastrtps::rtps::ReaderPool::get_next_unread_payload(eprosima::fastrtps::rtps::CacheChange_t&, eprosima::fastrtps::rtps::SequenceNumber_t&, unsigned long) () from /home/seaeye02/Fast-DDS/install/fastrtps/lib/libfastrtps.so.2.7
#1  0x00007ffff799f561 in eprosima::fastrtps::rtps::DataSharingListener::process_new_data() ()
   from /home/seaeye02/Fast-DDS/install/fastrtps/lib/libfastrtps.so.2.7
#2  0x00007ffff79a00d0 in eprosima::fastrtps::rtps::DataSharingListener::run() ()
   from /home/seaeye02/Fast-DDS/install/fastrtps/lib/libfastrtps.so.2.7
#3  0x00007ffff75362c3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff72a4b43 in start_thread (arg=<optimised out>) at ./nptl/pthread_create.c:442
#5  0x00007ffff7336a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

### Steps to reproduce

Process A
Publish a collection of data in a topic ( write each time) within in a continuous for loop

Process B
Subscribe the collection of data in a topic ( read each time) within in a continuous for loop
**

### Fast DDS version/commit

git log
commit 8540471a189aa689b9a16bbc9a85de1a73e75863 (HEAD -> master, origin/master, origin/HEAD, origin/2.7.x)
Author: Raul Sanchez-Mateos Lizano <raul@eprosima.com>
Date:   Fri Jul 1 13:29:49 2022 +0200

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

UDPv4

### Additional context

auto udp_transport = std::make_shared<eprosima::fastdds::rtps::UDPv4TransportDescriptor>();
    participant_ptr->transport().user_transports.push_back(udp_transport);

**Comment by paulbkeelp** [comment]
More Info - 
if introduce 1 milli second delay between publisher and subscriber(i.e publish a message with 1 milli second delay) I dont see the SIGSEGV coredump. Looks like surley a bug!! ?

**Comment by llapx** [comment]
@sreemtech 
How about your data size?

**Comment by sreemtech** [comment]
> @sreemtech How about your data size?

@llapx data Size less than 100 bytes.

**Comment by llapx** [comment]
I can not repeat your bug with fast-dds examples, the test steps like this:

```bash
$ Fast-DDS/build/examples/cpp/dds/ZeroCopyExample/DDSZeroCopyExample subscriber
...
$ Fast-DDS/build/examples/cpp/dds/HelloWorldExample/DDSHelloWorldExample publisher -s 0 -i 0
```

It will send continous messages from publisher to subscriber in the loop.

**Comment by sreemtech** [comment]
@llapx could you please share your examples please

**Comment by llapx** [comment]
@sreemtech 

https://github.com/eProsima/Fast-DDS/tree/master/examples/cpp/dds/HelloWorldExample

**Comment by sreemtech** [comment]
@llapx i will get back to you on this

**Comment by MiguelCompany** [comment]
Thank you @llapx for taking the time to answer this!

@sreemtech It seems you were given enough information, so I am closing this now. Feel free to reopen if still an issue
