### ISSUE TITLE
Visual Studio 2019 ： unresolved externals symbol 

### ISSUE THREAD

**Issue by zixuan-su** [eProsima/Fast-DDS#2805]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

    Hi, I have installed the Fast-DDS (version 2.6.0)  on Windows, then I create a new project on  VS  which is a sample example about "HelloWorldSubscriber", I find  lots of errors about   "unresolved externals" ,
I hope it can receive my message successfully... 

### Current behavior

I have referred to this answer [,](https://github.com/eProsima/Fast-DDS/issues/1310) but it did not solve the problem。
 By the way , I have run successfully by cmake . 
My  Include Directories and Library Directories should be no mistakes. 

![image](https://user-images.githubusercontent.com/64144933/177098853-94622189-52d7-44c6-b9f8-7f843977c676.png)
![image](https://user-images.githubusercontent.com/64144933/177098933-d9fac2cd-468a-411e-8dde-1b93a71a923b.png)
Then my judgment is that the dependency library is not configured completely
![image](https://user-images.githubusercontent.com/64144933/177099222-a3d03d0a-ee17-424b-a475-3900e58cc486.png)
The biggest problem is probably the dependency library configuration issue, and I really don't know which libraries I need to rely on
![image](https://user-images.githubusercontent.com/64144933/177099494-79ccd886-307e-4171-a2d5-afb0a670b497.png)

### Steps to reproduce

1. Create a VS2019 project
2. add Include Direction and Library Direction address 
3. add the dependency such as xxx.lib
4. Code 
5. Debug 

### Fast DDS version/commit

2.6.0

### Platform/Architecture

Windows 10 Visual Studio 2019

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by YanFuHai06** [comment]
Hi, I am using vs2019 to develop Fast-DDS. I have the same problem. Have you solved it

**Comment by zixuan-su** [comment]
> 你好，我正在使用vs2019开发Fast-DDS。我也有同样的问题。你解决了吗

no..... how about you?

**Comment by YanFuHai06** [comment]
> > 你好，我正在使用vs2019开发Fast-DDS。我也有同样的问题。你解决了吗
> 
> no..... how about you?

You can try : Project>Properties>C/C++>Preprocessor >Preprocessor Definitions; 
add "FASTRTPS_NO_LIB","FASTCDR_NO_LIB", "EPROSIMA_ALL_DYN_LINK";
Reference:[#904 ](https://github.com/eProsima/Fast-DDS/issues/904)

**Comment by zixuan-su** [comment]
> > > 你好，我正在使用vs2019开发Fast-DDS。我也有同样的问题。你解决了吗
> > 
> > 
> > no..... how about you?
> 
> You can try : Project>Properties>C/C++>Preprocessor >Preprocessor Definitions; add "FASTRTPS_NO_LIB","FASTCDR_NO_LIB", "EPROSIMA_ALL_DYN_LINK"; Reference:[#904 ](https://github.com/eProsima/Fast-DDS/issues/904)

Thanks for your reply. Then in Project>Properties>Link>Input>Additional dependencies ,   I don't have to add any libs about fast-dds，right？

**Comment by YanFuHai06** [comment]
> > > > 你好，我正在使用vs2019开发Fast-DDS。我也有同样的问题。你解决了吗
> > > 
> > > 
> > > no..... how about you?
> > 
> > 
> > You can try : Project>Properties>C/C++>Preprocessor >Preprocessor Definitions; add "FASTRTPS_NO_LIB","FASTCDR_NO_LIB", "EPROSIMA_ALL_DYN_LINK"; Reference:[#904 ](https://github.com/eProsima/Fast-DDS/issues/904)
> 
> Thanks for your reply. Then in Project>Properties>Link>Input>Additional dependencies , I don't have to add any libs about fast-dds，right？

You need add libs name ,this is my added. I have only verified the x64_Debug mode so far:
fastrtpsd-2.6.lib fastcdrd-1.0.lib foonathan_memory-0.7.1-dbg.lib VC\libssl64MDd.lib VC\libcrypto64MDd.lib

**Comment by zixuan-su** [comment]
> > > > > 你好，我正在使用vs2019开发Fast-DDS。我也有同样的问题。你解决了吗
> > > > 
> > > > 
> > > > no..... how about you?
> > > 
> > > 
> > > You can try : Project>Properties>C/C++>Preprocessor >Preprocessor Definitions; add "FASTRTPS_NO_LIB","FASTCDR_NO_LIB", "EPROSIMA_ALL_DYN_LINK"; Reference:[#904 ](https://github.com/eProsima/Fast-DDS/issues/904)
> > 
> > 
> > Thanks for your reply. Then in Project>Properties>Link>Input>Additional dependencies , I don't have to add any libs about fast-dds，right？
> 
> You need add libs name ,this is my added. I have only verified the x64_Debug mode so far: fastrtpsd-2.6.lib fastcdrd-1.0.lib foonathan_memory-0.7.1-dbg.lib VC\libssl64MDd.lib VC\libcrypto64MDd.lib

It still did not work... wtf .. Could you please upload your VS demo to the github?

**Comment by MiguelBarro** [comment]
As a guideline an actual .vcxproj file is available [here](https://gist.github.com/MiguelBarro/fd73813ec06a97da440c37a7147ba733)

**Comment by MiguelBarro** [comment]
Due to a lack of feedback on this issue, we are going to close it for now. Please, feel free to reopen it if deemed necessary.

**Comment by zixuan-su** [comment]
> Due to a lack of feedback on this issue, we are going to close it for now. Please, feel free to reopen it if deemed necessary.

Thanks,  I have solved it.
