### ISSUE TITLE
Discovery server between two computers (same LAN network)

### ISSUE THREAD

**Issue by royito55** [eProsima/Fast-DDS#2831]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

I assume setting up a discovery server in a computer would allow another to see the available topics. I am trying to implement the server due to the problems simple discovery has, where the topic communication between computers is not reliable.

### Current behavior

Currently, there is only one tutorial on setting up the discovery server in a single computer: https://fast-dds.docs.eprosima.com/en/latest/fastdds/ros2/discovery_server/ros2_discovery_server.html

This works fine in both computers I am trying to connect. However, there is no communication replicating this in two computers, and also no guidance it seems. I ran the server and the talker in one computer, and then the listener in another and it doesn't work.

Is there guidance on how to set up the server for two or more computers?

### Steps to reproduce

Followed this tutorial: https://fast-dds.docs.eprosima.com/en/latest/fastdds/ros2/discovery_server/ros2_discovery_server.html

### Fast DDS version/commit

latest (I don't know the transport layer being used but I had to select one)

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by EduPonz** [comment]
Hi @royito55 ,

How exactly are you configuring and running things? I just run the Helloworld example between two different containers, with the server running into a third, and everything worked as expected. For this, I'm using the docker image `ubuntu-fastdds:v2.7.0` (see [downloads](https://eprosima.com/index.php/downloads-all)). On one container instance run:

```bash
fastdds discovery -i 0
```

On another container instance, run:

```bash
cd /usr/local/eprosima/fastrtps/examples/cpp/dds/HelloWorldExample/bin
export ROS_DISCOVERY_SERVER=172.17.0.2
./DDSHelloWorldExample subscriber
```

On a third container instance, run:

```bash
cd /usr/local/eprosima/fastrtps/examples/cpp/dds/HelloWorldExample/bin
export ROS_DISCOVERY_SERVER=172.17.0.2
./DDSHelloWorldExample publisher
```

With all the previous, I receive data in the subscriber's container.

**Comment by royito55** [comment]
I am running ROS2 galactic in both computers, but I made sure to change the implementation to `rmw_fastrtps_cpp`. I know it works in a single computer because everything happens as instructed in the tutorial I shared above.

I then run the server and the talker in one computer and the listener in another. However, I am doing the export for the server that is specified in the tutorial: 
`export ROS_DISCOVERY_SERVER="127.0.0.1:11811"`

I think this is where the problem is but I don't understand it. I can see that you used another address and didn't specify a port. Is there somewhere in the documentation where this is explained/can you explain why you set that address?

Also, I downloaded the image `ubuntu-fastdds:v2.7.0` from your download page (https://www.eprosima.com/index.php/component/ars/repository/eprosima-fast-dds/eprosima-fast-dds-2-7-0) and then ran it in a container. I found the script `DDSHelloWorldExample` but the command `fastdds discovery -i 0` doesn't exist in the image, so I can't reproduce what you did: 
![Screenshot from 2022-07-11 12-52-18](https://user-images.githubusercontent.com/26725409/178249952-ccc2bdd6-11b9-42a5-9838-885735ab6c47.png)
![Screenshot from 2022-07-11 12-51-57](https://user-images.githubusercontent.com/26725409/178249965-5272a6ac-e7a1-4fca-b329-c3eec9b897d8.png)

**Comment by royito55** [comment]
I got it working, I was using the wrong address. Thank you for your guidance

**Comment by EduPonz** [comment]
Hi @royito55,

That's great to hear! On a side note, the `ubuntu-fastdds` image has an entry point which sets the environment. However, as it happens with Docker, this entrypoint is only run when instantiating the container with `docker run`, but not with `docker exec`. In this second scenario, you can prepare the environment with `source /usr/local/eprosima/setup.bash` (alternatively, you could also run `source ~/entrypoint.bash`). After that, you'd be able to run `fastdds discovery` without problems. Nonetheless, we are planning to add the sourcing to the `~/.bashrc` in future releases (from v2.7.1 onwards), so the environment will be all set up whenever running the container in the interactive mode (`-it`), no matter whether running with `docker run -it` or `docker exec -it`

**Comment by royito55** [comment]
Thank you for your help!
