### ISSUE TITLE
topic_name && topic_type_name output is messy

### ISSUE THREAD

**Issue by zixuan-su** [eProsima/Fast-DDS#2865]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

I sent 5 topics ,when  I use on_data_available() to show the topic name and topic type name , the printing is messy.
I hope it can print correctly.

### Current behavior

topic_ = participant_->create_topic("HelloWorldTopic1", "HelloWorld", TOPIC_QOS_DEFAULT);
topic1_ = participant_->create_topic("ByeByeTopic", "People", TOPIC_QOS_DEFAULT);
topic2_ = participant_->create_topic("ESCTopic", "ESC", TOPIC_QOS_DEFAULT);
topic3_ = participant_->create_topic("EEETopic", "EEE", TOPIC_QOS_DEFAULT);
 topic4_ = participant_->create_topic("Topic_Veh_RX_Info", "can_veh_rx", TOPIC_QOS_DEFAULT);
 topic5_ = participant_->create_topic("Topic_Veh_TX_Info", "can_veh_tx", TOPIC_QOS_DEFAULT);
by the way , idl of topic4_ and topic5_ is nested structures，The rest of the structures do not contain nested relationships

### Steps to reproduce

callback function :   on_data_available()
if (reader->get_topicdescription())
            {
               
                std::cout << "topic_name: " << reader->get_topicdescription()->get_name() <<
                    "    topic_type_name: " << reader->get_topicdescription()->get_type_name()
                    << std::endl;
            } 

### Fast DDS version/commit

2.6.0

### Platform/Architecture

Windows 10 Visual Studio 2019

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

![image](https://user-images.githubusercontent.com/64144933/180204272-e2943a43-1cbc-41ac-96c2-f27fd73d6558.png)

### Relevant log output

```shell
Starting subscriber.
Subscriber matched.
Subscriber matched.
Subscriber matched.
Subscriber matched.
Subscriber matched.
Subscriber matched.
topic_name: HelloWorldTopic1    topic_type_name: topic_name: HelloWorldTopic_Veh_RX_Info
    topic_type_name: can_veh_rxtopic_name:
topic_name: Topic_Veh_TX_InfoByeByeTopic    topic_type_name:     topic_type_name: can_veh_txPeople

topic_name: ESCTopic    topic_type_name: ESC
topic_name: EEETopic    topic_type_name: EEE
```

**Comment by zixuan-su** [comment]
![image](https://user-images.githubusercontent.com/64144933/180204727-fee18b6f-6c55-480f-968d-224a7f10016e.png)

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @zixuan-su,

This is not a Fast DDS issue. `on_data_available` might be accessed concurrently by different threads so you will need to protect `cout` access with a mutex to prevent this behavior.

**Comment by zixuan-su** [comment]
> 

Thanks， I get it！

**Comment by zixuan-su** [comment]
> Hi @zixuan-su,
> 
> This is not a Fast DDS issue. `on_data_available` might be accessed concurrently by different threads so you will need to protect `cout` access with a mutex to prevent this behavior.

oh, thanks ,I get it!

**Comment by JLBuenoLopez-eProsima** [comment]
Closing this issue because it is not a Fast DDS issue and it has been already solved!
