### ISSUE TITLE
[15370] Test regressions on Ros 2 Humble and Rolling after #2872

### ISSUE THREAD

**Issue by Blast545** [eProsima/Fast-DDS#2904]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

All tests in the buildfarm pass. As in: https://ci.ros2.org/view/nightly/job/nightly_linux_debug/2371/

### Current behavior

There are three new test regressions that occur only with Fast-DDS. 

Those started on July 28th: https://ci.ros2.org/view/nightly/job/nightly_linux_debug/2372/

As a reference, we have this

### Steps to reproduce

1. Run a ROS2 buildfarm job in debug mode for Linux.
2. The tests fail.

### Fast DDS version/commit

This commit was working fine: 2e45979bf34cd4b37339d013b7fd22cebd766b25

The next job we have at our buildfarm with the introduced test regressions is: 919b6f8749c4d0d99cf8eb9f022995418b13fe5b

So it could be any of the PR's merged in the middle.

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Intra-process

### Additional context

Tests are failing with Jammy 22.04

As a reference, these are the tests failing:
https://github.com/ros2/system_tests/blob/rolling/test_rclcpp/test/test_remote_parameters.cpp#L114-L127
https://github.com/ros2/ros2cli/blob/rolling/ros2param/test/test_verb_load.py#L132 (all module)
https://github.com/ros2/rclpy/blob/rolling/rclpy/test/test_action_client.py (aborted)

We used this ros2.repos to reproduce our builds at their state before the changes were made.
https://gist.githubusercontent.com/Crola1702/fcbec2d7b3f7ddea14e23cf13790df08/raw/393a1214a1f4155c64ea666e00af363ad7fe67e1/ros2.repos

We are not sure what's the problem at the moment, but have tested it's not related to other changes in the ROS2 stack and the errors only happen with Fast-DDS.

**Comment by Blast545** [comment]
FYI: @clalancette @Crola1702
Internal: https://github.com/osrf/buildfarmer/issues/333

**Comment by MiguelCompany** [comment]
@Blast545 This was most likely introduced by #2872, as it is where the failing assertion was added.

I have a suspicion about what could be happening, so I'll try to add a regression test and fix the issue.

**Comment by MiguelCompany** [comment]
@Blast545 I just created #2905 which should fix this
