### ISSUE TITLE
Unable to transmit an opencv stream using fast-dds

### ISSUE THREAD

**Issue by armuren** [eProsima/Fast-DDS#2917]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Following the [HelloWorld][1] example, and the [SO answer][2] from an eprosima employee, as well as a [Github issue][3], I am still unable to send an OpenCV image using Eprosima fast dds.

I started out by creating a `Picture.idl` file and using the Java gen tool, to generate `c++` classes.  Initially I tried to copy the SO answer by setting the image data to a vector of char.  I then changed this based on the avice from the SO answer, and set it as a string, for base64 encoding/decoding.

In either case, whenever I try to transmit the image of part the data Picture class, the subscriber does not seem to receive the message, nor throw an error.  If I instead just just the index and size and not the data, the subscriber's `on_data_available` is fired and I print out my message.

When I try to use the `base64` data, `on_data_available` does not fire, however when I send just "any test string", it fires and I print out my short string.

I then tried to increase the buffer length based on the [doc page][4] on large data, however this did not fix the issue.  

I will try and post as much of the code as makes sense.  It's of course a lot of boilerplate.

    This is the `Picture.idl`
    struct Picture
    {
        unsigned long index;
        unsigned long size;
        string picture;
    };
Which turns into this C++
   
    /*!
     * @file Picture.h
     * This header file contains the declaration of the described types in the IDL file.
     *
     * This file was generated by the tool gen.
     */
    
    #ifndef _FAST_DDS_GENERATED_PICTURE_H_
    #define _FAST_DDS_GENERATED_PICTURE_H_
    
    
    #include <fastrtps/utils/fixed_size_string.hpp>
    
    #include <stdint.h>
    #include <array>
    #include <string>
    #include <vector>
    #include <map>
    #include <bitset>
    
    #if defined(_WIN32)
    #if defined(EPROSIMA_USER_DLL_EXPORT)
    #define eProsima_user_DllExport __declspec( dllexport )
    #else
    #define eProsima_user_DllExport
    #endif  // EPROSIMA_USER_DLL_EXPORT
    #else
    #define eProsima_user_DllExport
    #endif  // _WIN32
    
    #if defined(_WIN32)
    #if defined(EPROSIMA_USER_DLL_EXPORT)
    #if defined(Picture_SOURCE)
    #define Picture_DllAPI __declspec( dllexport )
    #else
    #define Picture_DllAPI __declspec( dllimport )
    #endif // Picture_SOURCE
    #else
    #define Picture_DllAPI
    #endif  // EPROSIMA_USER_DLL_EXPORT
    #else
    #define Picture_DllAPI
    #endif // _WIN32
    
    namespace eprosima {
    namespace fastcdr {
    class Cdr;
    } // namespace fastcdr
    } // namespace eprosima
    
    
    /*!
     * @brief This class represents the structure Picture defined by the user in the IDL file.
     * @ingroup PICTURE
     */
    class Picture
    {
    public:
    
        /*!
         * @brief Default constructor.
         */
        eProsima_user_DllExport Picture();
    
        /*!
         * @brief Default destructor.
         */
        eProsima_user_DllExport ~Picture();
    
        /*!
         * @brief Copy constructor.
         * @param x Reference to the object Picture that will be copied.
         */
        eProsima_user_DllExport Picture(
                const Picture& x);
    
        /*!
         * @brief Move constructor.
         * @param x Reference to the object Picture that will be copied.
         */
        eProsima_user_DllExport Picture(
                Picture&& x);
    
        /*!
         * @brief Copy assignment.
         * @param x Reference to the object Picture that will be copied.
         */
        eProsima_user_DllExport Picture& operator =(
                const Picture& x);
    
        /*!
         * @brief Move assignment.
         * @param x Reference to the object Picture that will be copied.
         */
        eProsima_user_DllExport Picture& operator =(
                Picture&& x);
    
        /*!
         * @brief Comparison operator.
         * @param x Picture object to compare.
         */
        eProsima_user_DllExport bool operator ==(
                const Picture& x) const;
    
        /*!
         * @brief Comparison operator.
         * @param x Picture object to compare.
         */
        eProsima_user_DllExport bool operator !=(
                const Picture& x) const;
    
        /*!
         * @brief This function sets a value in member index
         * @param _index New value for member index
         */
        eProsima_user_DllExport void index(
                uint32_t _index);
    
        /*!
         * @brief This function returns the value of member index
         * @return Value of member index
         */
        eProsima_user_DllExport uint32_t index() const;
    
        /*!
         * @brief This function returns a reference to member index
         * @return Reference to member index
         */
        eProsima_user_DllExport uint32_t& index();
    
        /*!
         * @brief This function sets a value in member size
         * @param _size New value for member size
         */
        eProsima_user_DllExport void size(
                uint32_t _size);
    
        /*!
         * @brief This function returns the value of member size
         * @return Value of member size
         */
        eProsima_user_DllExport uint32_t size() const;
    
        /*!
         * @brief This function returns a reference to member size
         * @return Reference to member size
         */
        eProsima_user_DllExport uint32_t& size();
    
        /*!
         * @brief This function copies the value in member picture
         * @param _picture New value to be copied in member picture
         */
        eProsima_user_DllExport void picture(
                const std::string& _picture);
    
        /*!
         * @brief This function moves the value in member picture
         * @param _picture New value to be moved in member picture
         */
        eProsima_user_DllExport void picture(
                std::string&& _picture);
    
        /*!
         * @brief This function returns a constant reference to member picture
         * @return Constant reference to member picture
         */
        eProsima_user_DllExport const std::string& picture() const;
    
        /*!
         * @brief This function returns a reference to member picture
         * @return Reference to member picture
         */
        eProsima_user_DllExport std::string& picture();
    
        /*!
         * @brief This function returns the maximum serialized size of an object
         * depending on the buffer alignment.
         * @param current_alignment Buffer alignment.
         * @return Maximum serialized size.
         */
        eProsima_user_DllExport static size_t getMaxCdrSerializedSize(
                size_t current_alignment = 0);
    
        /*!
         * @brief This function returns the serialized size of a data depending on the buffer alignment.
         * @param data Data which is calculated its serialized size.
         * @param current_alignment Buffer alignment.
         * @return Serialized size.
         */
        eProsima_user_DllExport static size_t getCdrSerializedSize(
                const Picture& data,
                size_t current_alignment = 0);
    
    
        /*!
         * @brief This function serializes an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void serialize(
                eprosima::fastcdr::Cdr& cdr) const;
    
        /*!
         * @brief This function deserializes an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void deserialize(
                eprosima::fastcdr::Cdr& cdr);
    
    
    
        /*!
         * @brief This function returns the maximum serialized size of the Key of an object
         * depending on the buffer alignment.
         * @param current_alignment Buffer alignment.
         * @return Maximum serialized size.
         */
        eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(
                size_t current_alignment = 0);
    
        /*!
         * @brief This function tells you if the Key has been defined for this type
         */
        eProsima_user_DllExport static bool isKeyDefined();
    
        /*!
         * @brief This function serializes the key members of an object using CDR serialization.
         * @param cdr CDR serialization object.
         */
        eProsima_user_DllExport void serializeKey(
                eprosima::fastcdr::Cdr& cdr) const;
    
    private:
    
        uint32_t m_index;
        uint32_t m_size;
        std::string m_picture;
    };
    
    #endif // _FAST_DDS_GENERATED_PICTURE_H_

The Publisher is below

    /*!
     * @file PicturePublisher.cpp
     * This file contains the implementation of the publisher functions.
     *
     * This file was generated by the tool fastcdrgen.
     */
    
    #include <thread>
    #include <chrono>
    
    #include "base64.h"
    #include "PicturePublisher.h"
    #include "PicturePubSubTypes.h"
    
    #include <fastdds/dds/domain/DomainParticipantFactory.hpp>
    #include <fastdds/dds/publisher/Publisher.hpp>
    #include <fastdds/dds/publisher/qos/PublisherQos.hpp>
    #include <fastdds/dds/publisher/DataWriter.hpp>
    #include <fastdds/dds/publisher/qos/DataWriterQos.hpp>
    #include <fastrtps/attributes/ParticipantAttributes.h>
    
    using namespace eprosima::fastdds::dds;
    
    PicturePublisher::PicturePublisher()
        : participant_(nullptr)
        , publisher_(nullptr)
        , topic_(nullptr)
        , writer_(nullptr)
        , type_(new PicturePubSubType())
    {
    }
    
    PicturePublisher::~PicturePublisher()
    {
        if (writer_ != nullptr)
        {
            publisher_->delete_datawriter(writer_);
        }
        if (publisher_ != nullptr)
        {
            participant_->delete_publisher(publisher_);
        }
        if (topic_ != nullptr)
        {
            participant_->delete_topic(topic_);
        }
        DomainParticipantFactory::get_instance()->delete_participant(participant_);
    }
    
    
    
    bool PicturePublisher::init()
    {
        /* Initialize data_ here */
    //    openCamera();
        //CREATE THE PARTICIPANT
        DomainParticipantQos pqos;
        pqos.name("Participant_pub");
        // Increase the sending buffer size
        pqos.transport().send_socket_buffer_size = 1048576;
        // Increase the receiving buffer size
        pqos.transport().listen_socket_buffer_size = 4194304;
    
    //    eprosima::fastrtps::ParticipantAttributes PParam;
    //    PParam.rtps.setName("Picture_pub");
    //    participant_ = DomainParticipantFactory::get_instance()->create_participant(
    //            PParam, &m_part_list);
    
        participant_ = DomainParticipantFactory::get_instance()->create_participant(0, pqos);
        if (participant_ == nullptr)
        {
            return false;
        }
    
        //REGISTER THE TYPE
        type_.register_type(participant_);
    
        //CREATE THE PUBLISHER
        publisher_ = participant_->create_publisher(PUBLISHER_QOS_DEFAULT, nullptr);
        if (publisher_ == nullptr)
        {
            return false;
        }
    
        //CREATE THE TOPIC
        topic_ = participant_->create_topic(
            "PictureTopic",
            type_.get_type_name(),
            TOPIC_QOS_DEFAULT);
        if (topic_ == nullptr)
        {
            return false;
        }
    
        // CREATE THE WRITER
        writer_ = publisher_->create_datawriter(topic_, DATAWRITER_QOS_DEFAULT, &listener_);
        if (writer_ == nullptr)
        {
            return false;
        }
    
        std::cout << "Picture DataWriter created." << std::endl;
        return true;
    }
    
    void PicturePublisher::PubListener::on_publication_matched(
            eprosima::fastdds::dds::DataWriter*,
            const eprosima::fastdds::dds::PublicationMatchedStatus& info)
    {
        if (info.current_count_change == 1)
        {
            matched = info.total_count;
            std::cout << "DataWriter matched." << std::endl;
        }
        else if (info.current_count_change == -1)
        {
            matched = info.total_count;
            std::cout << "DataWriter unmatched." << std::endl;
        }
        else
        {
            std::cout << info.current_count_change
                      << " is not a valid value for PublicationMatchedStatus current count change" << std::endl;
        }
    }
    
    void PicturePublisher::run()
    {
        std::cout << "Picture DataWriter waiting for DataReaders." << std::endl;
        while (listener_.matched == 0)
        {
            std::this_thread::sleep_for(std::chrono::milliseconds(250)); // Sleep 250 ms
        }
    
        // Publication code
        Picture m_Picture;
    
        cv::Mat frame;
        //--- INITIALIZE VIDEOCAPTURE
        cv::VideoCapture cap(4);
        cap.set(cv::CAP_PROP_FRAME_WIDTH, 160);
        cap.set(cv::CAP_PROP_FRAME_HEIGHT, 90);
    
        // check if we succeeded
        if (!cap.isOpened()) {
            std::cerr << "ERROR! Unable to open camera\n";
        }
    
        //--- GRAB AND WRITE LOOP
        std::cout << "Start grabbing" << std::endl;
        std::cout << "Press any key to terminate" << std::endl;
    
        for (;;)
        {
            // wait for a new frame from camera and store it into 'frame'
            cap.read(frame);
            // check if we succeeded
            if (frame.empty()) {
                std::cerr << "ERROR! blank frame grabbed\n";
                break;
            }
    
            std::vector<uchar> buf;
            cv::imencode(".jpg", frame, buf);
            auto *enc_msg = reinterpret_cast<unsigned char*>(buf.data());
            std::string encoded = base64_encode(enc_msg, buf.size());
            std::cout << "buffer size " << buf.size() << std::endl;
            m_Picture.index(0);
            m_Picture.size(buf.size());
            m_Picture.picture(encoded);
    //        m_Picture.picture("some string here");
            writer_->write(&m_Picture);
            std::this_thread::sleep_for(std::chrono::milliseconds(250)); // Sleep 250 ms
            // show live and wait for a key with timeout long enough to show images
    //        imshow("Live", frame);
    //        if (cv::waitKey(5) >= 0)
    //            break;
        }
    }

And the subscriber is below

    /*!
     * @file PictureSubscriber.cpp
     * This file contains the implementation of the subscriber functions.
     *
     * This file was generated by the tool fastcdrgen.
     */
    #include "base64.h"
    #include <opencv2/core.hpp>
    #include <opencv2/highgui.hpp>
    #include <fastdds/dds/domain/DomainParticipantFactory.hpp>
    #include <fastdds/dds/subscriber/DataReader.hpp>
    #include <fastdds/dds/subscriber/SampleInfo.hpp>
    #include <fastdds/dds/subscriber/Subscriber.hpp>
    #include <fastdds/dds/subscriber/qos/DataReaderQos.hpp>
    
    #include "PictureSubscriber.h"
    #include "PicturePubSubTypes.h"
    
    using namespace eprosima::fastdds::dds;
    
    PictureSubscriber::PictureSubscriber()
            : participant_(nullptr), subscriber_(nullptr), topic_(nullptr), reader_(nullptr),
              type_(new PicturePubSubType()) {
    }
    
    PictureSubscriber::~PictureSubscriber() {
        if (reader_ != nullptr) {
            subscriber_->delete_datareader(reader_);
        }
        if (topic_ != nullptr) {
            participant_->delete_topic(topic_);
        }
        if (subscriber_ != nullptr) {
            participant_->delete_subscriber(subscriber_);
        }
        DomainParticipantFactory::get_instance()->delete_participant(participant_);
    }
    
    bool PictureSubscriber::init() {
        //CREATE THE PARTICIPANT
        DomainParticipantQos pqos;
        pqos.name("Participant_sub");
        // Increase the sending buffer size
        pqos.transport().send_socket_buffer_size = 1048576;
        // Increase the receiving buffer size
        pqos.transport().listen_socket_buffer_size = 4194304;
    
        participant_ = DomainParticipantFactory::get_instance()->create_participant(0, pqos);
        if (participant_ == nullptr) {
            return false;
        }
    
        //REGISTER THE TYPE
        type_.register_type(participant_);
    
        //CREATE THE SUBSCRIBER
        subscriber_ = participant_->create_subscriber(SUBSCRIBER_QOS_DEFAULT, nullptr);
        if (subscriber_ == nullptr) {
            return false;
        }
    
        //CREATE THE TOPIC
        topic_ = participant_->create_topic(
                "PictureTopic",
                type_.get_type_name(),
                TOPIC_QOS_DEFAULT);
        if (topic_ == nullptr) {
            return false;
        }
    
        //CREATE THE READER
        DataReaderQos rqos = DATAREADER_QOS_DEFAULT;
        rqos.reliability().kind = RELIABLE_RELIABILITY_QOS;
        reader_ = subscriber_->create_datareader(topic_, rqos, &listener_);
        if (reader_ == nullptr) {
            return false;
        }
    
        return true;
    }
    
    void PictureSubscriber::SubListener::on_subscription_matched(
            DataReader *,
            const SubscriptionMatchedStatus &info) {
        if (info.current_count_change == 1) {
            matched = info.total_count;
            std::cout << "Subscriber matched." << std::endl;
        } else if (info.current_count_change == -1) {
            matched = info.total_count;
            std::cout << "Subscriber unmatched." << std::endl;
        } else {
            std::cout << info.current_count_change
                      << " is not a valid value for SubscriptionMatchedStatus current count change" << std::endl;
        }
    }
    
    void PictureSubscriber::SubListener::on_data_available(
            DataReader *reader) {
        // Take data
        Picture m_Picture;
        SampleInfo m_info;
    
        std::cout << "Data received." << std::endl;
        auto ret = reader->take_next_sample((void *) &m_Picture, &m_info);
        if (ret == ReturnCode_t::RETCODE_OK)
        {std::cout << "ok." << std::endl;}
        else { std::cout << "ERROR." << std::endl; }
    
    //    std::string dec_jpg =  base64_decode(m_Picture.picture());
    //    std::vector<uchar> data(dec_jpg.begin(), dec_jpg.end());
    //    cv::Mat img = cv::imdecode(cv::Mat(data), 1);
    
    //    cv::imshow("Display window", img);
    //    if (cv::waitKey(5) >= 0) { std::cout << "break"; }
    
    
    //
    //    // Print your structure data here.
    //    uint32_t index = m_Picture.index();
    //    std::cout << "index: " << index << "; \t";
    //    std::cout << "size: " << m_Picture.size() << std::endl;
    //    cv::Mat imageDecoded = cv::imdecode(m_Picture.picture(), 1);
    
    
    }
    
    void PictureSubscriber::run() {
        std::cout << "Waiting for Data, press Enter to stop the DataReader. " << std::endl;
        std::cin.ignore();
        std::cout << "Shutting down the Subscriber." << std::endl;
    }

Does anyone have a suggestion as to how to **fix this issue**?

  [1]: https://github.com/eProsima/Fast-DDS/tree/master/examples/cpp/dds/HelloWorldExample
  [2]: https://stackoverflow.com/a/65704933/1158977
  [3]: https://github.com/eProsima/Fast-DDS/issues/975
  [4]: https://fast-dds.docs.eprosima.com/en/latest/fastdds/use_cases/large_data/large_data.html?highlight=large%20data#tuning-socket-buffer

### Current behavior

Unable to send an opencv image using fast-dds

### Steps to reproduce

Outlined above

### Fast DDS version/commit

Installed using apt-get on Ubuntu 20.04

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Shared Memory Transport (SHM)

**Comment by EduPonz** [comment]
Hi @armuren,

Please checkout [this answer](https://github.com/eProsima/Fast-DDS/issues/2903#issuecomment-1206071764). A `string` is a case of `sequence`, and therefore the [history memory policy](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/core/policy/eprosimaExtensions.html#memorymanagementpolicy) of both your `DataWriter` and `DataReader` needs to be set to something other than `PREALLOCATED_MEMORY_MODE` for your image to be sent and received.

**Comment by armuren** [comment]
Thanks @EduPonz for the suggestion, it worked great!
