### ISSUE TITLE
no document on how to run the docker command with a specific version (Example?)

### ISSUE THREAD

**Issue by ynahum** [eProsima/Fast-DDS#2963]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

should find the version

### Current behavior

no such tar error:

 docker load -i ubuntu-fastdds-suite:2.7.1.tar

open ubuntu-fastdds-suite:2.7.1.tar: no such file or directory

### Steps to reproduce

run:  docker load -i ubuntu-fastdds-suite:2.7.1.tar

### Fast DDS version/commit

latest

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by Mario-DL** [comment]
Hi @ynahum,

Latest available Fast-DDS suite docker images can be found at [eprosima´s download page](https://www.eprosima.com/index.php/downloads-all). Then you can use `docker load` command to actually point the `.tar` file to get the image. Closing this as it is not an issue.
