### ISSUE TITLE
ROS2 Foxy communication issues

### ISSUE THREAD

**Issue by MarqRazz** [eProsima/Fast-DDS#3000]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

This is on a fresh install of 22.04, Nvidia's Isaac sim and binary install of ROS2 Foxy.
As per [Nvidia's instructions](https://docs.omniverse.nvidia.com/app_isaacsim/app_isaacsim/install_ros.html#included-ros-2-packages) I have not sourced `/opt/ros/foxy/setup.bash` in my ~/.bashrc file. I have set `export RMW_IMPLEMENTATION=rmw_fastrtps_cpp` in the bashrc to ensure the correct middle-ware is being used.

When I start the computer I am able to open up two terminals, source Foxy, and run/echo the following.
- In the first terminal I can run `ros2 run demo_nodes_cpp talker`
- In the second terminal I can run `ros2 topic list` and `ros2 topic echo /chatter` to see the  published data.

### Current behavior

For my second test I am following [these instructions](https://docs.omniverse.nvidia.com/app_isaacsim/app_isaacsim/install_ros.html#enabling-the-ros-ros-2-bridge-extension) to have Isaac sim publish data to ROS.
- First I start Isaac and then enable the ROS2 bridge
- In Isaac I start the MoveIt example by selecting from the menu bar `Isaac Examples->ROS->MoveIt` and it starts a simulation with a Franka robot in the scene.
In the terminal I get the following message as a verification that data is being published to ROS. `[WARN] [1664994017.213770358] [rclcpp]: logging was initialized more than once`
- I open a  new terminal, run `source /opt/ros/foxy/setup.bash` then `ros2 topic list` but FastRTPS throws errors and is unable to discover topics from the sim.
```
$ ros2 topic list
2022-10-05 12:32:08.462 [RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7412: open_and_lock_file failed -> Function open_port_internal
2022-10-05 12:32:08.462 [RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7413: open_and_lock_file failed -> Function open_port_internal
/parameter_events
/rosout
```

### Steps to reproduce

After the system has started throwing `fastrtps` errors it throws them any time new nodes are started and topic discovery is broken even if I stop and restart the ros2 daemon. I.E.
```
$ ros2 run demo_nodes_cpp talker
2022-10-05 12:43:14.676 [RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7413: open_and_lock_file failed -> Function open_port_internal
[talker 1664995395.680405888]: Publishing: 'Hello World: 1'

$ ros2 topic list
/parameter_events
/rosout
```

From other issues in this repo I found that when you get the `Failed init_port` it is recommended you run `fastdds shm clean` but when I do this the program throws errors.
```
$ fastdds shm clean
Traceback (most recent call last):
  File "/opt/ros/foxy/bin/../tools/fastdds/fastdds.py", line 112, in <module>
    FastDDSParser()
  File "/opt/ros/foxy/bin/../tools/fastdds/fastdds.py", line 85, in __init__
    getattr(self, args.command)()
  File "/opt/ros/foxy/bin/../tools/fastdds/fastdds.py", line 103, in shm
    ShmParser(sys.argv[2:])
  File "/opt/ros/foxy/tools/fastdds/shm/parser.py", line 71, in __init__
    Clean().run()
  File "/opt/ros/foxy/tools/fastdds/shm/clean.py", line 44, in run
    zombie_segments = self.__clean_zombie_segments()
  File "/opt/ros/foxy/tools/fastdds/shm/clean.py", line 114, in __clean_zombie_segments
    self.segments_in_use += 1
AttributeError: 'Clean' object has no attribute 'segments_in_use'
```

### Fast DDS version/commit

Current Foxy binary version.

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by MarqRazz** [comment]
I was able to fix my communication issues by using [this](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/blob/main/docker/middleware_profiles/rtps_udp_profile.xml) dds configuration file provided by Nvidia. Isaac sim is using a similar version so the connecting system needs to match.

**Comment by xuzhiyuan1528** [comment]
> I was able to fix my communication issues by using [this](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/blob/main/docker/middleware_profiles/rtps_udp_profile.xml) dds configuration file provided by Nvidia. Isaac sim is using a similar version so the connecting system needs to match.

How to solve this problem? (how to use this configuration file?). I have exactly the same situation as you.

**Comment by MarqRazz** [comment]
> > I was able to fix my communication issues by using [this](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/blob/main/docker/middleware_profiles/rtps_udp_profile.xml) dds configuration file provided by Nvidia. Isaac sim is using a similar version so the connecting system needs to match.
> > @MarqRazz
> > How to solve this problem? (how to use this configuration file?). I have exactly the same situation as you.

You create a file on your computer with [this](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_common/blob/main/docker/middleware_profiles/rtps_udp_profile.xml) dds config file (I called it fastdds.xml and put it in my `~/.ros` folder)
Then in your `.bashrc` or in the command line set these two environment variables but point `FASTRTPS_DEFAULT_PROFILES_FILE` at the location you saved the configuration.
```
export FASTRTPS_DEFAULT_PROFILES_FILE=~/.ros/fastdds.xml && 
export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
```

The last thing I have been doing is shutting off all of  my network interfaces (WiFi and hard-line) because Isaac sim seems to be attaching to some random device that I cant communicate with on my host or in another docker container. FYI, I am planning on refining the DDS config to use a user specified device but need to work with Nvidia to make this an option. For example here is a DDS config I made for Cyclone that uses the `lo` interface.
```
<?xml version="1.0" encoding="UTF-8" ?>
<CycloneDDS xmlns="https://cdds.io/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://cdds.io/config https://raw.githubusercontent.com/eclipse-cyclonedds/cyclonedds/master/etc/cyclonedds.xsd">
  <Domain id="any">
    <General>
      <Interfaces>
        <NetworkInterface name="lo"/>
      </Interfaces>
      <AllowMulticast>false</AllowMulticast>
    </General>
    <Discovery>
      <ParticipantIndex>auto</ParticipantIndex>
      <Peers>
        <Peer Address="localhost"/>
      </Peers>
      <MaxAutoParticipantIndex>120</MaxAutoParticipantIndex>
    </Discovery>
  </Domain>
</CycloneDDS>
```

**Comment by kushalm** [comment]
Hey @MarqRazz I tried replacing the DDS config file but that didn't work and a friend of mine tried disabling the network adapter and it worked for him. Unfortunately I am not able to do something like that as I am working on an EC2 instance. Is there anyother way around this problem?

**Comment by MarqRazz** [comment]
@kushalm so sorry I thought I replied here. I am working with eProsima to make a new config that I would like to propose to Nvidia to make this easier. If you get it working please let me know!
