### ISSUE TITLE
Problems running SecureHelloWorldExample: subscriber will be blocked.

### ISSUE THREAD

**Issue by jingTian-z** [eProsima/Fast-DDS#3054]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Press the enter key twice and the subscriber ends normally without being blocked.

### Current behavior

After 20s of killing the publisher process by pressing ctrl-c, the subscriber receives the unmatched notification. At this time, press the enter key twice on the subscriber process, the subscriber process will not end running, and will enter a forever blocked state, and can no longer match other publishers.

## Modify Hellowork_main.cpp
```
diff --git a/examples/cpp/dds/SecureHelloWorldExample/HelloWorld_main.cpp b/examples/cpp/dds/SecureHelloWorldExample/HelloWorld_main.cpp
index 9294faf0f..b7125d7d7 100644
--- a/examples/cpp/dds/SecureHelloWorldExample/HelloWorld_main.cpp
+++ b/examples/cpp/dds/SecureHelloWorldExample/HelloWorld_main.cpp
@@ -59,6 +59,7 @@ int main(
             {
                 mypub.run(10);
             }
+            getchar();
             break;
         }
         case 2:
@@ -68,6 +69,7 @@ int main(
             {
                 mysub.run();
             }
+            getchar();
             break;
         }
     }
```
The purpose of this modification is to prolong the life cycle of the object mysub and the object mysub, preventing them from being destroyed immediately.

## Steps
- Run the subscriber process: ./DDSSecureHelloWorldExample subscriber
- Run the publisher process: ./DDSSecureHelloWorldExample publisher
- Press ctrl-c to kill the publisher process
- After 20s, the subscriber process will receive an unmatched notification and block here forever. Pressing enter does not end the process.

### Fast DDS version/commit

aa485fc7d

### Platform/Architecture

MacOS Mojave 10.14

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

1、This blocking phenomenon occurs only after the enable SECURITY function, that is, annotating the SECURITY-related code, the above reproduction steps will not block.

2、By adding logs and code tracing: It is found that the subscriber process is blocked on the wait of ResourceEvent::unregister_timer.

3、The following modification can solve this problem, but I don't know if it will introduce other bugs.

```
diff --git a/src/cpp/rtps/resources/ResourceEvent.cpp b/src/cpp/rtps/resources/ResourceEvent.cpp
index d6306a37f..451733eb9 100644
--- a/src/cpp/rtps/resources/ResourceEvent.cpp
+++ b/src/cpp/rtps/resources/ResourceEvent.cpp
@@ -1,4 +1,5 @@
 // Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
+// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
 //
 // Licensed under the Apache License, Version 2.0 (the "License");
 // you may not use this file except in compliance with the License.
@@ -75,10 +76,15 @@ void ResourceEvent::unregister_timer(
 {
     std::unique_lock<TimedMutex> lock(mutex_);
 
-    cv_manipulation_.wait(lock, [&]()
-            {
-                return allow_vector_manipulation_;
-            });
+    printf("ResourceEvent wait \n");
+    // cv_manipulation_.wait(lock, [&]()
+    //         {
+    //             return allow_vector_manipulation_;
+    //         });
+    cv_manipulation_.wait_for(lock, std::chrono::seconds(2) , [&]() {
+            return allow_vector_manipulation_;
+    });
+    printf("ResourceEvent wait end \n");
 
     bool should_notify = false;
     std::vector<TimedEventImpl*>::iterator it;

```

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @jingTian-z,

Thanks for your report! Though I am not able to reproduce your issue following your steps. On the one hand, killing the publisher process with `Ctrl+C` is not really a good idea. That signal is not being handled in the code so the Publisher leaves the communication without a clean exit. That is the reason why the Subscriber announces the unmatching after 20 s, which is the default [lease duration](https://fast-dds.docs.eprosima.com/en/latest/fastdds/discovery/general_disc_settings.html?highlight=participant%20lease%20duration#general-discovery-settings). I have added the `getchar` instructions as explained in your steps and follow those steps closely. After receiving the unmatching message the Subscriber application is still waiting for a `getchar`. After providing it, the application closes without hanging (as far as I can see). Could you provide some more detailed instructions or check if it closes correctly now?

**Comment by jingTian-z** [comment]
> Hi @jingTian-z,
> 
> Thanks for your report! Though I am not able to reproduce your issue following your steps. On the one hand, killing the publisher process with `Ctrl+C` is not really a good idea. That signal is not being handled in the code so the Publisher leaves the communication without a clean exit. That is the reason why the Subscriber announces the unmatching after 20 s, which is the default [DomainParticipant lease duration](https://fast-dds.docs.eprosima.com/en/latest/fastdds/discovery/general_disc_settings.html?highlight=participant%20lease%20duration#general-discovery-settings). I have added the `getchar` instructions as explained in your steps and follow those steps closely. After receiving the unmatching message the Subscriber application is still waiting for a `getchar`. After providing it, the application closes without hanging (as far as I can see). Could you provide some more detailed instructions or check if it closes correctly now?

I am well aware that killing the publisher via Ctrl-C is not a good way. When the publisher process ends its life cycle normally, the subscriber process does not block, because the publisher completes the resource cleanup, and I passed this test.
Then, if the process crashes, it means that resource cleanup cannot be completed. Ctrl-C simulates such a situation. If the publisher process exits unexpectedly, causing the subscriber process to block, this is a very bad experience.
I recorded the video while the blocking happened.

https://user-images.githubusercontent.com/17037192/199877537-ee2412f0-2e37-465c-a6f2-f520f0da1d10.mp4

**Comment by jingTian-z** [comment]
> > Hi @jingTian-z,
> > Thanks for your report! Though I am not able to reproduce your issue following your steps. On the one hand, killing the publisher process with `Ctrl+C` is not really a good idea. That signal is not being handled in the code so the Publisher leaves the communication without a clean exit. That is the reason why the Subscriber announces the unmatching after 20 s, which is the default [DomainParticipant lease duration](https://fast-dds.docs.eprosima.com/en/latest/fastdds/discovery/general_disc_settings.html?highlight=participant%20lease%20duration#general-discovery-settings). I have added the `getchar` instructions as explained in your steps and follow those steps closely. After receiving the unmatching message the Subscriber application is still waiting for a `getchar`. After providing it, the application closes without hanging (as far as I can see). Could you provide some more detailed instructions or check if it closes correctly now?
> 
> I am well aware that killing the publisher via Ctrl-C is not a good way. When the publisher process ends its life cycle normally, the subscriber process does not block, because the publisher completes the resource cleanup, and I passed this test. Then, if the process crashes, it means that resource cleanup cannot be completed. Ctrl-C simulates such a situation. If the publisher process exits unexpectedly, causing the subscriber process to block, this is a very bad experience. I recorded the video while the blocking happened.
> 
>  block.mp4

I traced the code and found that there is a blocking event callback after the event is triggered, which causes allow_vector_manipulation_ to not be set to true. When the unregister_timer function is called, because cv_manipulation_ is in the wait state, it enters the blocking state. 
<img width="743" alt="1" src="https://user-images.githubusercontent.com/17037192/199879470-5b30f559-0d0e-4eb3-8af4-42adac798350.png">
<img width="834" alt="2" src="https://user-images.githubusercontent.com/17037192/199879485-8eb7ae4c-d903-4309-a540-314adba5bd30.png">
<img width="780" alt="3" src="https://user-images.githubusercontent.com/17037192/199879500-5406c88c-640c-481c-ba05-94665e993385.png">

**Comment by JLBuenoLopez-eProsima** [comment]
Sorry, @jingTian-z 

Is this something that always occurs? Have you done any other changes to the code? I have reproduced your steps and record also a video (see below). Not once has the subscriber blocked. Nevertheless, you might want to try the fix introduced in #2976 in case it is related to your issue. Not being able to reproduce I am afraid I cannot help you right now. If you can send me a dockerfile where the issue is reproducible, maybe I can be of further assistance.

[Screencast from 04-11-22 10:19:15.webm](https://user-images.githubusercontent.com/69244257/199938257-fcae845c-a70e-49c9-9073-f97001725fa7.webm)

**Comment by jingTian-z** [comment]
> Sorry, @jingTian-z
> 
> Is this something that always occurs? Have you done any other changes to the code? I have reproduced your steps and record also a video (see below). Not once has the subscriber blocked. Nevertheless, you might want to try the fix introduced in #2976 in case it is related to your issue. Not being able to reproduce I am afraid I cannot help you right now. If you can send me a dockerfile where the issue is reproducible, maybe I can be of further assistance.
> 
>  Screencast.from.04-11-22.10.19.15.webm

Modify HelloWorld_main.cpp

In the test of this scenario, when Ctrl-C is performed on the publisher, the life cycle of the mypub object must be guaranteed, that is, mypub will not be destructed.

**Comment by jingTian-z** [comment]
> > Sorry, @jingTian-z
> > Is this something that always occurs? Have you done any other changes to the code? I have reproduced your steps and record also a video (see below). Not once has the subscriber blocked. Nevertheless, you might want to try the fix introduced in #2976 in case it is related to your issue. Not being able to reproduce I am afraid I cannot help you right now. If you can send me a dockerfile where the issue is reproducible, maybe I can be of further assistance.
> > Screencast.from.04-11-22.10.19.15.webm
> 
> Modify HelloWorld_main.cpp
> 
> In the test of this scenario, when Ctrl-C is performed on the publisher, the life cycle of the mypub object must be guaranteed, that is, mypub will not be destructed.

<img width="728" alt="image" src="https://user-images.githubusercontent.com/17037192/199942373-b7129f5a-d26a-4d50-bdbb-f9af6568b76e.png">

**Comment by JLBuenoLopez-eProsima** [comment]
Yeah! I have done such modification. If not done, the publisher leaves without waiting for `Ctrl+C`. So yes, I have applied your changes and not reproduced the issue. Sorry

**Comment by jingTian-z** [comment]
> Yeah! I have done such modification. If not done, the publisher leaves without waiting for `Ctrl+C`. So yes, I have applied your changes and not reproduced the issue. Sorry

It is meaningless to operate after the mypub object is destructed, because all related resources have been released and there will be no blocking.
The publisher exits unexpectedly when the related resources are not cleaned up. Have you tested this situation?

**Comment by JLBuenoLopez-eProsima** [comment]
Steps followed:

1. Modify the `main` as per your instructions adding the `getchar` method so to prevent both the Publisher and Subscriber applications to end automatically.
2. Launch Subscriber application
3. Launch Publisher application
4. Wait for discovery and check that the communication is established and the messages are sent and received.
5. Kill uncleanly the Publisher application using `Ctrl+C`
6. Check that the Subscriber application unmatches after the 20s lease duration is expired.
7. Press double enter in the Subscriber application and in my case, the application closes without hanging. Yours instead hangs.

Am I doing something different?

**Comment by JesusPoderoso** [comment]
According to our [contributing guidelines](https://github.com/eProsima/Fast-DDS/blob/master/CONTRIBUTING.md), this issue is closed due to inactivity. 

Please, feel free to reopen it if necessary.

**Comment by yszhuu** [comment]
We encountered the same problem, and the call stacks when the deadlock occurred are as follows:

"UDPRecv" prio=5 (not attached)
  | sysTid=3048 nice=0 cgrp=default
  | state=S schedstat=( 558148769 539533187 25289 ) utm=33 stm=21 core=5 HZ=100
  native: #00 pc 000000000004c25c  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28)
  native: #01 pc 0000000000050880  /apex/com.android.runtime/lib64/bionic/libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*)+144)
  native: #02 pc 00000000000b0a8c  /apex/com.android.runtime/lib64/bionic/libc.so (pthread_cond_wait+80)
  native: #03 pc 00000000000b82ec  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libpudutech_log.so (std::__ndk1::condition_variable::wait(std::__ndk1::unique_lock<std::__ndk1::mutex>&)+20)
  native: #04 pc 00000000002a98bc  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libfastrtps.so (???)
  native: #05 pc 00000000002a86f4  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libfastrtps.so (eprosima::fastrtps::rtps::ResourceEvent::unregister_timer(eprosima::fastrtps::rtps::TimedEventImpl*)+104)
  native: #06 pc 00000000002aac74  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libfastrtps.so (eprosima::fastrtps::rtps::TimedEvent::recreate_timer()+24)
  native: #07 pc 00000000002ed088  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libfastrtps.so (eprosima::fastrtps::rtps::WriterProxy::stop()+48)
  native: #08 pc 00000000002f0984  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libfastrtps.so (eprosima::fastrtps::rtps::StatefulReader::matched_writer_remove(eprosima::fastrtps::rtps::GUID_t const&, bool)+908)
  native: #09 pc 00000000004959b0  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libfastrtps.so (eprosima::fastrtps::rtps::EDP::unpairWriterProxy(eprosima::fastrtps::rtps::GUID_t const&, eprosima::fastrtps::rtps::GUID_t const&, bool)+208)
  native: #10 pc 000000000048b124  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libfastrtps.so (eprosima::fastrtps::rtps::PDP::removeWriterProxyData(eprosima::fastrtps::rtps::GUID_t const&)+352)
  native: #11 pc 00000000004a0c6c  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libfastrtps.so (eprosima::fastrtps::rtps::EDPSimplePUBListener::onNewCacheChangeAdded(eprosima::fastrtps::rtps::RTPSReader*, eprosima::fastrtps::rtps::CacheChange_t const*)+956)
  native: #12 pc 00000000002f2650  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libfastrtps.so (eprosima::fastrtps::rtps::StatefulReader::NotifyChanges(eprosima::fastrtps::rtps::WriterProxy*)+572)
  native: #13 pc 00000000002f2ca0  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libfastrtps.so (eprosima::fastrtps::rtps::StatefulReader::change_received(eprosima::fastrtps::rtps::CacheChange_t*, eprosima::fastrtps::rtps::WriterProxy*, unsigned long)+548)
  native: #14 pc 00000000002f1b38  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libfastrtps.so (eprosima::fastrtps::rtps::StatefulReader::processDataMsg(eprosima::fastrtps::rtps::CacheChange_t*)+2644)
  native: #15 pc 000000000030673c  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libfastrtps.so (eprosima::fastrtps::rtps::MessageReceiver::process_data_message_without_security(eprosima::fastrtps::rtps::EntityId_t const&, eprosima::fastrtps::rtps::CacheChange_t&)+336)
  native: #16 pc 0000000000309754  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libfastrtps.so (eprosima::fastrtps::rtps::MessageReceiver::proc_Submsg_Data(eprosima::fastrtps::rtps::CDRMessage_t*, eprosima::fastrtps::rtps::SubmessageHeader_t*, eprosima::fastrtps::rtps::EntityId_t&) const+4360)
  native: #17 pc 00000000003079c0  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libfastrtps.so (eprosima::fastrtps::rtps::MessageReceiver::processCDRMsg(eprosima::fastrtps::rtps::Locator_t const&, eprosima::fastrtps::rtps::Locator_t const&, eprosima::fastrtps::rtps::CDRMessage_t*)+2300)
  native: #18 pc 0000000000313174  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libfastrtps.so (eprosima::fastrtps::rtps::ReceiverResource::OnDataReceived(unsigned char const*, unsigned int, eprosima::fastrtps::rtps::Locator_t const&, eprosima::fastrtps::rtps::Locator_t const&)+136)
  native: #19 pc 00000000003a33bc  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libfastrtps.so (eprosima::fastdds::rtps::UDPChannelResource::perform_listen_operation(eprosima::fastrtps::rtps::Locator_t)+288)
  native: #20 pc 00000000003a51a8  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libfastrtps.so (void* std::__ndk1::__thread_proxy<std::__ndk1::tuple<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, void (eprosima::fastdds::rtps::UDPChannelResource::*)(eprosima::fastrtps::rtps::Locator_t), eprosima::fastdds::rtps::UDPChannelResource*, eprosima::fastrtps::rtps::Locator_t> >(void*)+100)
  native: #21 pc 00000000000b1810  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+264)
  native: #22 pc 00000000000512f0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)


"Binder:2704_1" prio=5 (not attached)
  | sysTid=3043 nice=0 cgrp=default
  | state=S schedstat=( 772418286 865895924 47208 ) utm=23 stm=54 core=0 HZ=100
  native: #00 pc 000000000004c25c  /apex/com.android.runtime/lib64/bionic/libc.so (syscall+28)
  native: #01 pc 0000000000050880  /apex/com.android.runtime/lib64/bionic/libc.so (__futex_wait_ex(void volatile*, bool, int, bool, timespec const*)+144)
  native: #02 pc 00000000000b2a88  /apex/com.android.runtime/lib64/bionic/libc.so (NonPI::MutexLockWithTimeout(pthread_mutex_internal_t*, bool, timespec const*)+664)
  native: #03 pc 00000000000f4ce0  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libpudutech_log.so (std::__ndk1::recursive_mutex::lock()+8)
  native: #04 pc 000000000048cfe0  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libfastrtps.so (eprosima::fastrtps::rtps::PDP::check_remote_participant_liveliness(eprosima::fastrtps::rtps::ParticipantProxyData*)+32)
  native: #05 pc 000000000048df2c  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libfastrtps.so (???)
  native: #06 pc 00000000002aae64  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libfastrtps.so (eprosima::fastrtps::rtps::TimedEventImpl::trigger(std::__ndk1::chrono::time_point<std::__ndk1::chrono::steady_clock, std::__ndk1::chrono::duration<long long, std::__ndk1::ratio<1l, 1000000000l> > >, std::__ndk1::chrono::time_point<std::__ndk1::chrono::steady_clock, std::__ndk1::chrono::duration<long long, std::__ndk1::ratio<1l, 1000000000l> > >)+76)
  native: #07 pc 00000000002a8f40  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libfastrtps.so (eprosima::fastrtps::rtps::ResourceEvent::do_timer_actions()+476)
  native: #08 pc 00000000002a8bb8  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libfastrtps.so (eprosima::fastrtps::rtps::ResourceEvent::event_service()+96)
  native: #09 pc 00000000002aa8d4  /data/app/~~LhP82lVyBPoALiea5MAd4g==/com.pudutech.launcher-OeQVqaZPqThVqY4wPahtGw==/lib/arm64/libfastrtps.so (void* std::__ndk1::__thread_proxy<std::__ndk1::tuple<std::__ndk1::unique_ptr<std::__ndk1::__thread_struct, std::__ndk1::default_delete<std::__ndk1::__thread_struct> >, void (eprosima::fastrtps::rtps::ResourceEvent::*)(), eprosima::fastrtps::rtps::ResourceEvent*> >(void*)+64)
  native: #10 pc 00000000000b1810  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+264)
  native: #11 pc 00000000000512f0  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
