### ISSUE TITLE
idl file missing

### ISSUE THREAD

**Issue by jinfeihan57** [eProsima/Fast-DDS#3075]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

[ClientServerTest ](https://github.com/eProsima/Fast-DDS/tree/master/examples/cpp/dds/ClientServerTest) should have a idl file

### Current behavior

miss idl file

### Steps to reproduce

add a idl file

### Fast DDS version/commit

master

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by Mario-DL** [comment]
Hi @jinfeihan57, 

It is true that for this particular example, types are not generated with fastdds-gen tool, but made by hand. Dont think we are providing the .idl but it would be more uniform to leave the auto-generated types. This is not really an issue, but an improvement.

**Comment by JLBuenoLopez-eProsima** [comment]
This example has been removed and instead the [RequestReplyExample](https://github.com/eProsima/Fast-DDS/tree/master/examples/cpp/dds/RequestReplyExample) has been included. This example includes the corresponding IDL file. Consequently, I am going to close this as completed.
