### ISSUE TITLE
Assertion failed in DataReaderInstance

### ISSUE THREAD

**Issue by i-and** [eProsima/Fast-DDS#3119]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

No assertion

### Current behavior

Assertion failed in file DataReaderInstance.hpp line 83:
~~~
assert(InstanceStateKind::ALIVE_INSTANCE_STATE == instance_state)
~~~

### Steps to reproduce

Accidental appearance in case of disconnection of the response part/application with DDS Enpoints. It was also observed when the Ethernet network worked with errors (loss of RTPS packets, their storm or long delays in receipt).

### Fast DDS version/commit

version 2.7.1

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

UDPv4

**Comment by chunyisong** [comment]
Same issue to me. 
fastdds v11.2
