### ISSUE TITLE
v2.8.1 CMake failure for shmtest

### ISSUE THREAD

**Issue by maloel** [eProsima/Fast-DDS#3131]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

CMake should pass

### Current behavior

```
CMake Error at C:/work/git/lrs/build/_deps/fastdds-build/src/cpp/shmtest/CMakeFiles/CMakeTmp/CMakeLists.txt:21 (add_executable):
Cannot find source file:
C:/work/git/lrs/CMake/modules/check_shared_mutex_priority.cpp
```

It's looking for the source file under `"${CMAKE_SOURCE_DIR}/cmake/modules/check_shared_mutex_priority.cpp"` but `CMAKE_SOURCE_DIR` is our repo's root, not the FastDDS root... We build FastDDS as part of own repo (`add_subdirectory`).

### Steps to reproduce

Download & build FastDDS as part of another repo.

### Fast DDS version/commit

v2.8.1

### Platform/Architecture

Windows 10 Visual Studio 2019

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by Nir-Az** [comment]
Here is a possible fix for FastDDS cmake flow:
https://lesleylai.info/en/cmake_src_directory/

**Comment by MiguelBarro** [comment]
@maloel Would you be so gentle as to check if https://github.com/eProsima/Fast-DDS/pull/3136 fixes your issue?

**Comment by maloel** [comment]
> @maloel Would you be so gentle as to check if #3136 fixes your issue?

Hi @MiguelBarro 
Yes, seems to have worked in that no error is given. I did not test anything related to `shmtest`...

**Comment by MiguelBarro** [comment]
Ok, given that the fix is approved for merging I will close the issue. It can be reopened if further related issues are detected.
