### ISSUE TITLE
SECUREHELLOWORLDEXAMPLE issue

### ISSUE THREAD

**Issue by husnaini798** [eProsima/Fast-DDS#3141]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

If the subscriber is running with the following permission file /properties ,

`   pqos.properties().properties().emplace_back(
        "dds.sec.access.builtin.Access-Permissions.permissions",
        "file://certs/permissionsless.smime");`

where permissionsless.smime is created using the following xml 

`<?xml version="1.0" encoding="utf-8"?>
<dds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.omg.org/spec/DDS-Security/20170801/omg_shared_ca_permissions.xsd">
    <permissions>
        <grant name="PublisherPermissions">
            <subject_name>emailAddress=mainpub@eprosima.com, CN=Main Publisher, OU=eProsima, O=eProsima, ST=MA, C=ES</subject_name>
            <validity>
                <not_before>2013-06-01T13:00:00</not_before>
                <not_after>2038-06-01T13:00:00</not_after>
            </validity>
            <allow_rule>
                <domains>
                    <id_range>
                        <min>0</min>
                        <max>230</max>
                    </id_range>
                </domains>
                <publish>
                    <topics>
                        <topic>HelloWorldTopic</topic>
                    </topics>
                </publish>
            </allow_rule>
            <default>DENY</default>
        </grant>
        <grant name="SubscriberPermissions">
            <subject_name> emailAddress=mainsub@eprosima.com, CN=Main Subscriber, OU=eProsima, O=eProsima, ST=MA, C=ES</subject_name>
            <validity>
                <not_before>2013-06-01T13:00:00</not_before>
                <not_after>2038-06-01T13:00:00</not_after>
            </validity>
            <allow_rule>
                <domains>
                    <id_range>
                        <min>0</min>
                        <max>230</max>
                    </id_range>
                </domains>
               </allow_rule>
            <default>DENY</default>
        </grant>
    </permissions>
</dds>
`

and publisher is running with the `permissions.smime` present in the SecureHelloWorldExample folder, it is expected that the subscriber will not receive any messages. 

However, in the following code 
` DomainParticipantQos pqos;

    pqos.properties().properties().emplace_back("dds.sec.auth.plugin",
            "builtin.PKI-DH");
    pqos.properties().properties().emplace_back("dds.sec.auth.builtin.PKI-DH.identity_ca",
            "file://certs/maincacert.pem");
    pqos.properties().properties().emplace_back("dds.sec.auth.builtin.PKI-DH.identity_certificate",
            "file://certs/mainsubcert.pem");
    pqos.properties().properties().emplace_back("dds.sec.auth.builtin.PKI-DH.private_key",
            "file://certs/mainsubkey.pem");
    pqos.properties().properties().emplace_back("dds.sec.access.plugin",
            "builtin.Access-Permissions");
    pqos.properties().properties().emplace_back(
        "dds.sec.access.builtin.Access-Permissions.permissions_ca",
        "file://certs/maincacert.pem");
    pqos.properties().properties().emplace_back(
        "dds.sec.access.builtin.Access-Permissions.governance",
        "file://certs/governance.smime");
    pqos.properties().properties().emplace_back(
        "dds.sec.access.builtin.Access-Permissions.permissions",
        "file://certs/permissionsSub.smime");
    pqos.properties().properties().emplace_back("dds.sec.crypto.plugin",
            "builtin.AES-GCM-GMAC");

    // Activate DDS:Logging:DDS_LogTopic plugin
pqos.properties().properties().emplace_back("dds.sec.log.plugin",
        "builtin.DDS_LogTopic");

// Configure DDS:Logging:DDS_LogTopic plugin
pqos.properties().properties().emplace_back(
    "dds.sec.log.builtin.DDS_LogTopic.logging_level",
    "DEBUG_LEVEL");
pqos.properties().properties().emplace_back(
    "dds.sec.log.builtin.DDS_LogTopic.log_file",
    "myLogFileSubSec.log");

    participant_ = DomainParticipantFactory::get_instance()->create_participant(0, pqos);
`

We can change the name of the .smime or .pem files to a dummy filename (which doesn't even exist). And I still get no errors and whatever the publisher sends, the receiver is able to receive it i.e. no errors. 

We are expecting some kind of errors, if the files don't exist. Also, if we are using permissionsless.smime, we are expecting the subscriber to not receive the messages that the publisher is sending.

### Current behavior

We do not get any error, if we pass in dummy (incorrect) file names.
Also, subscriber receives all messages that publisher has sent.

### Steps to reproduce

First case
---------
-Build the SECURHELLOWORLDEXAMPLE code.
-Change the .smime file name to something invalid.

Run the ./DDSSecureHelloWorldExample and there will be no errors.

Second case
-------------
-Generate permissionsless.smime using the xml pasted above.
-Use permissionsless.smime for subscriber and build the code.

Run the ./DDSSecureHelloWorldExample and the output is that whatever message publisher sends, subscriber is able to receive it (even though we expect that the subscriber should not be able to get those messages). 

### Fast DDS version/commit

Version 2.8.0

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @husnaini798,

Thanks for your report! Could you please check if Fast DDS have been built with the [security CMake option enabled](https://fast-dds.docs.eprosima.com/en/latest/installation/configuration/cmake_options.html#general-options)? Otherwise, the properties, even being set, would not be used by Fast DDS so the behavior you are describing would be the expected one: with no security, the security properties are not loaded so setting a dummy file is the same as providing a correct file. And not having loaded the security properties, the DomainParticipant is created with no security so communication is also to be expected between the endpoints.

**Comment by husnaini798** [comment]
Hi Jose,
Thanks for the prompt reply. I can confirm that I build Fast-DDS and
Fast-DDS-Python with the following cmake flags as on, and the security is
working as expected.

colcon build --cmake-args -DSECURITY=ON

Thanks, once again.

Kind Regards,
Husnain Malik

**Comment by JLBuenoLopez-eProsima** [comment]
@husnaini798 ,you are welcome! I am glad that it is working as expected! Could you please close this issue?
