### ISSUE TITLE
OutputTrafficManager assertion failure

### ISSUE THREAD

**Issue by mtheall** [eProsima/Fast-DDS#3285]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Normal behavior

### Current behavior

Assertion failure
This appears to only happen if ROS_DISCOVERY_SERVER is set.

Sometimes it fails for ROS_DISCOVERY_SERVER=127.0.0.1 and sometimes not.
Sometimes it fails for ROS_DISCOVERY_SERVER=<nic address> and sometimes not.

### Steps to reproduce

```cpp
// rtps api
#include <fastrtps/Domain.h>
#include <fastrtps/attributes/ParticipantAttributes.h>
#include <fastrtps/transport/UDPv4TransportDescriptor.h>

#include <chrono>
#include <cstdlib>
#include <memory>
#include <thread>
using namespace std::chrono_literals;

int main (int argc_, char *argv_[])
{
	eprosima::fastrtps::ParticipantAttributes partAttr{};

	auto udpTransport = std::make_shared<eprosima::fastrtps::rtps::UDPv4TransportDescriptor> ();
	udpTransport->interfaceWhiteList.emplace_back ("127.0.0.1");

	partAttr.rtps.useBuiltinTransports = false;
	partAttr.rtps.userTransports.emplace_back (udpTransport);

	auto const participant = eprosima::fastrtps::Domain::createParticipant (partAttr);
	if (!participant)
		return EXIT_FAILURE;

	std::this_thread::sleep_for (1s);

	eprosima::fastrtps::Domain::removeParticipant (participant);
}
```
```cpp
// dds api
#include <fastdds/dds/domain/DomainParticipantFactory.hpp>
#include <fastdds/statistics/dds/domain/DomainParticipant.hpp>
#include <fastrtps/transport/UDPv4TransportDescriptor.h>

#include <chrono>
#include <cstdlib>
#include <memory>
#include <thread>
using namespace std::chrono_literals;

int main (int argc_, char *argv_[])
{
	auto udpTransport = std::make_shared<eprosima::fastrtps::rtps::UDPv4TransportDescriptor> ();
	udpTransport->interfaceWhiteList.emplace_back ("127.0.0.1");

	eprosima::fastdds::dds::TransportConfigQos transport;
	transport.use_builtin_transports = false;
	transport.user_transports.emplace_back (udpTransport);

	eprosima::fastdds::dds::DomainParticipantQos qos;
	qos.transport (transport);

	auto const participant = eprosima::fastdds::dds::DomainParticipantFactory::get_instance ()->create_participant (
	    0, qos, nullptr, eprosima::fastdds::dds::StatusMask::none ());
	if (!participant)
		return EXIT_FAILURE;

	std::this_thread::sleep_for (1s);

	eprosima::fastdds::dds::DomainParticipantFactory::get_instance ()->delete_participant (participant);
}
```
```bash
$ fast-discovery-server -i 0
```
```bash
$ ROS_DISCOVERY_SERVER=127.0.0.1 ./test
```

### Fast DDS version/commit

bf181c81

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

UDPv4

### Additional context

Ubunutu 22.04 x86_64

### Relevant log output

```shell
src/cpp/statistics/rtps/messages/OutputTrafficManager.hpp:87: void eprosima::fastdds::statistics::rtps::OutputTrafficManager::set_statistics_message_data(const eprosima::fastrtps::rtps::Locator_t&, const octet*, uint32_t): Assertion `it != collection_.end()' failed.
```

### Network traffic capture

In the assertion failure case, no network traffic is observed whatsoever.

**Comment by mtheall** [comment]
Additional info: If I build FASTDDS_STATISTICS=OFF to avoid this assertion failure, then discovery server doesn't work at all if I use any whitelist.

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @mtheall,

The assertion failure should have been fixed with #3283 which has been already merged into the `master` branch. If you keep having this assertion failure after updating your branch, please, let us know.

Regarding Discovery Server and whitelisting. On the one hand, localhost is treated in a special way within Fast DDS. This network interface is not added by default to the DomainParticipant except if it is included in the whitelist or in the listening locators. Thus, in order for your test example to work, running the following command should be enough:

```
fast-discovery-server -i 0 -l 127.0.0.1
```

In case that you are interested on whitelisting any other IP address, then the Server configuration is a little more complex. The Server should also whitelist that specific network interface and add the corresponding listening locator. Find below a XML configuration file (`test.xml`) as example:

```
 <?xml version="1.0" encoding="UTF-8" ?>
<profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
    <transport_descriptors>
        <transport_descriptor>
            <transport_id>CustomTransport</transport_id>
            <type>UDPv4</type>
            <interfaceWhiteList>
                <address>192.168.2.136</address>
            </interfaceWhiteList>
        </transport_descriptor>
    </transport_descriptors>

    <participant profile_name="CustomTransportParticipant" is_default_profile="true">
        <rtps>
            <userTransports>
                <transport_id>CustomTransport</transport_id>
            </userTransports>
            <useBuiltinTransports>false</useBuiltinTransports>
            <builtin>
                <discovery_config>
                    <discoveryProtocol>SERVER</discoveryProtocol>
                </discovery_config>
                <metatrafficUnicastLocatorList>
                    <locator>
                        <udpv4>
                            <address>192.168.2.136</address>
                            <port>11811</port>
                        </udpv4>
                    </locator>
                </metatrafficUnicastLocatorList>
            </builtin>
        </rtps>
    </participant>
</profiles>
```

This XML is loaded into the Server with the following command:

```
fast-discovery-server -i 0 -x test.xml
```

**Comment by mtheall** [comment]
Looks like that fixes the crash. I did manage to get the discovery server working with whitelists by using your xml profile example. It's a bit weird that that's required when discovery clients use whitelists. This only seems to be an issue when the discovery client and discovery server are on the same machine. The whitelist on discovery clients works fine without whitelist on the discovery server if they are on separate machines.

**Comment by JLBuenoLopez-eProsima** [comment]
Thanks @mtheall for confirming that the crash has been fixed. I am going to proceed and close this issue then. Feel free to reopen if the crash happens again.
