### ISSUE TITLE
Mutex lock may be missing in the WLP::remove_local_reader() method

### ISSUE THREAD

**Issue by i-and** [eProsima/Fast-DDS#3304]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Working with mutex in the `WLP::remove_local_reader method(RTPSReader* reader)` should probably correspond to the `WLP::add_local_reader(RTPSReader* reader,const ReaderQos& rqos)` to protect access to `std::vector<RTPSReader*> readers_`.

### Current behavior

The method `WLP::remove_local_reader method(RTPSReader* reader)` does not capture mutex.

### Steps to reproduce

https://github.com/eProsima/Fast-DDS/blob/b6b178e5fddd66caf9e84a2b22561c4594fca23a/src/cpp/rtps/builtin/liveliness/WLP.cpp#L835-L850

### Fast DDS version/commit

master

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by jsantiago-eProsima** [comment]
Hi @i-and, 

Thank you for the report. I believe you are right and access to that collection should be equally protected like it's done on `add_local_reader`. I've opened PR #3311 to fix it.
