### ISSUE TITLE
cmake errors occurred   with cmake option DEPROSIMA_BUILD=ON

### ISSUE THREAD

**Issue by stilong** [eProsima/Fast-DDS#3325]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

no errro

### Current behavior

lgh@lgh-u20201:~/mydds_dup/src/fastdds/build$ cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/  -DSECURITY=ON -DEPROSIMA_BUILD=ON
-- Version: 2.9.1
-- Enforced cxx_std_11 CMake feature
-- Found fastcdr
-- Found Asio 1.12.2: /usr/include
-- Found Asio
-- Found TinyXML2
-- Found foonathan_memory: /usr/local/lib/foonathan_memory/cmake
-- Thirdparty/boost compiled OK
-- OpenSSL library 1.1.1u found...
-- Forcing third party shared_mutex
-- Using linker version script to select exported symbols
CMake Error at test/unittest/dds/topic/DDSSQLFilter/CMakeLists.txt:56 (set_tests_properties):
  set_tests_properties Can not find test to add properties to:
  DDSSQLFilterValueTests.test_filtered_value

-- Configuring AdvancedConfiguration example...
-- Configuring BasicConfiguration example...
-- Configuring DDS Benchmark...
-- Configuring DDSClientServerTest...
-- Configuring DDS Configurability example...
-- Configuring ContentFilterTopic examples...
-- Configuring CustomListener example...
-- Configuring DDSDeadlineQoS example...
-- Configuring DDSDisablePositiveACKs example...
-- Configuring HelloWorld example...
-- Configuring DDSFiltering example...
-- Configuring DDS Flow Control example...
-- Configuring HelloWorld example...
-- Configuring HelloWorld example...
-- Configuring HelloWorld example...
-- Configuring DDSHelloWorldTCP example...
-- Configuring DDS History Kind example...
-- Configuring DDS Keys example...
-- Configuring DDS LateJoiners example...
-- Configuring DDS LifespanQos example...
-- Configuring DDS LifespanQoSExample example...
-- Configuring DDS OwnershipStrengthQoS example...
-- Configuring DDS SampleConfig_Controller example...
-- Configuring DDS SampleConfig_Events example...
-- Configuring DDS SampleCondig_Multimedia example...
-- Configuring DDSStaticHelloWorld example...
-- Configuring TypeLookup example...
-- Configuring WriterLoansExample...
-- Configuring ZeroCopyExample...
-- Configuring DDSSecureHelloWorld example...
-- Configuring AsSocket...
-- Configuring Registered...
-- Configuring Persistent...
-- Configuring incomplete, errors occurred!

### Steps to reproduce

mkdir build
cd build 
cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local/  -DSECURITY=ON -DEPROSIMA_BUILD=ON

### Fast DDS version/commit

2.9.1

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by jsantiago-eProsima** [comment]
Hi @stilong,

Thanks for your report. PR https://github.com/eProsima/Fast-DDS/pull/3196 is already open to fix this issue.

**Comment by JLBuenoLopez-eProsima** [comment]
#3196 has been merged and the corresponding backports have been created. I will proceed and close this issue.
