### ISSUE TITLE
[DYN_TYPES Error] Error creating type, unsupported type kind: 242

### ISSUE THREAD

**Issue by TechVortexZ** [eProsima/Fast-DDS#3473]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

I create a publisher use structure inheritance like this:
struct topic: CommonHeader
{
    string name;
    short data_array[5];
    sequence<short> data_vec;
    map<string, unsigned long> data_map;
};
then I create a subscriber user typelookup service , when into on_type_information_received function , fastdds report ： [DYN_TYPES Error] Error creating type, unsupported type kind: 242 -> Function create_custom_builder。

### Current behavior

none

### Steps to reproduce

none

### Fast DDS version/commit

version 2.80 

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

UDPv4

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @Mrzhou-coder,

Thanks for your contribution. I am afraid that the Dynamic Types API has several known issues. That is the reason why it is being refactored right now in #3392.

**Comment by elianalf** [comment]
Hi @TechVortexZ,
We are working on the new major version of Fast DDS (v3.0.0) where we have refactored the DynamicTypes. The problem should be solved, you can try to upgrade Fast DDS to Master and try it. Please note that this is a major release, so many APIs have been changed and until the official release Master is still unstable. Let us know if the problem has been resolved.

**Comment by JesusPoderoso** [comment]
Hi @TechVortexZ, Fast DDS v3.0.0 has been released! Could you check if the issue persists?

**Comment by Mario-DL** [comment]
As the Dynamic Types refactor has been already introduced in the latest Fast DDS v3.0.0, we internally agreed to close all Dynamic-Types related issues.
We elaborated a [Migration guide](https://github.com/eProsima/Fast-DDS/blob/master/UPGRADING.md) to help with the upgrade process to this new major release.

Please, feel free to reopen it if the issue persists.
