### ISSUE TITLE
Missing cstdint includes (TypeNamesGenerator.h, TransportDescriptorInterface.h)

### ISSUE THREAD

**Issue by oysstu** [eProsima/Fast-DDS#3494]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

The following files are missing includes to cstdint
```
eProsima/Fast-DDS/include/fastrtps/types/TypeNamesGenerator.h
eProsima/Fast-DDS/include/fastdds/rtps/transport/TransportDescriptorInterface.h
```

### Current behavior

Fails to build

### Steps to reproduce

Build with GCC 13.1.1

### Fast DDS version/commit

master

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

ROS2 humble 2023.05.02 patch release

**Comment by JLBuenoLopez-eProsima** [comment]
Thanks @oysstu for your contribution. I have opened #3508 to solve the issue. Can you check that the build is fixed with this changes?

**Comment by oysstu** [comment]
Yes, that seems to fix it for me. Thanks!
