### ISSUE TITLE
fastdds-python using shm transport comminicate failed

### ISSUE THREAD

**Issue by Yang-cola** [eProsima/Fast-DDS#3552]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

1. /dev/shm/ add **12 files**, including fastrtps_portxxxx, fast_datasharingxxxxx, and so on; see the picture below:
![599a2e369854f6e203377207392dc8ce](https://github.com/eProsima/Fast-DDS/assets/66586788/67b1b872-1858-451a-add5-28d4c6bc00ab)

2. Subsceiber that created by fastdds-python can auto matched publisher that created by fastdds-C++.

### Current behavior

1. /dev/shm/ add ** only 3 files**,
2. Subsceiber that created by fastdds-python **can  not auto** matched publisher that created by fastdds-C++.

### Steps to reproduce

1. run an application, whose data communication using fastdds-C++ ;
2. run .py file,  whose data communication using fastdds-python ;
3. step1 step2 have the same domain , topic , idl。

### Fast DDS version/commit

2.8.0

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Shared Memory Transport (SHM)

### Relevant log output

```shell
no log print
```

**Comment by Yang-cola** [comment]
**Supplementary Note:**
My **python** application's XML file is in this picture:
![21833b2826eb6820141bc8714a245676](https://github.com/eProsima/Fast-DDS/assets/66586788/1142bc22-e480-4995-8008-ff141d30066d)
My **C++** application created more than 100 datasharing in /dev/shm/, like these pictures:

![0363f418f7a7ee2229630cfc547b506a](https://github.com/eProsima/Fast-DDS/assets/66586788/c7a1206b-5fa0-4c67-96b2-142eb148b7d4)
![4355effa1c7fd6190ee6bd2aacdaeeb5](https://github.com/eProsima/Fast-DDS/assets/66586788/c2dc6be4-6c63-4927-82e8-42c88c2168bf)

**Comment by Yang-cola** [comment]
> 
Hi @jsantiago-eProsima 
Firstly, C++ application only using SHM transport;
Secondly,  the screenshots below show you the Qos configuration in C++ and python:
**[python Subscriber qos]:**
![python](https://github.com/eProsima/Fast-DDS/assets/66586788/92808d83-8bdd-4f51-b4c5-1fe3cdb69d9a)

**[C++ Publisher qos]:**
![a](https://github.com/eProsima/Fast-DDS/assets/66586788/57400f18-17f9-40bc-9e04-db18b77c5c74)
![b](https://github.com/eProsima/Fast-DDS/assets/66586788/3f76afee-6d1e-4142-8ec7-4b7474db9dcc)
**[C++ Subscriber qos]:**
![c](https://github.com/eProsima/Fast-DDS/assets/66586788/9ef2af5a-1055-47e8-b010-efba0fa94e35)
![d](https://github.com/eProsima/Fast-DDS/assets/66586788/5c27541f-f8b0-4774-b2de-2d0c666ea74a)
Expect replays, thanks.

**Comment by Yang-cola** [comment]
It seems that python shm failed, because it didn't create new fastrtps_port anymore.
How to locate question and fix this issue? 
Hope reply soon.

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @Yang-cola 

As far as I understand, when both the Publisher and Subscriber are launched using C++ API, communication works as expected. The issue you are reporting is that when one endpoint is launched using the Python API, the communication is not established. Is this correct?

**Comment by Yang-cola** [comment]
> 

Thanks,  I have solved this problem. The reason is my C++ code has endpoint more than 100. I changed the parameter and fixed the issue.
