### ISSUE TITLE
[19347] Wrong encapsulation in ParticipantMessageData header

### ISSUE THREAD

**Issue by cathaysia** [eProsima/Fast-DDS#3782]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Currently, wlp data declares its serialization method as plcdr during the serialization process, but actually the serialization method is in accordance with cdr. Is this part of the description wrong?

https://github.com/eProsima/Fast-DDS/blob/f7d77cfb29bf79ad08022e67d5eb4cb58a1d71dd/src/cpp/rtps/builtin/liveliness/WLP.cpp#L905

**Comment by cathaysia** [comment]
![image](https://github.com/eProsima/Fast-DDS/assets/42114817/16940686-2ff6-4fa8-afc3-8912d6b27e37)

This specification explicitly ask for the cdr format, so a fix is needed here

**Comment by EduPonz** [comment]
Hi @cathaysia,

Thanks for the report! I have submitted a PR to fix it, could you please verify on your end?
* #3784

**Comment by cathaysia** [comment]
Except for a little comment problem, everything else is perfect
