### ISSUE TITLE
What is the XML profile configuration that corresponds to ROS_STATIC_PEERS=a.b.c.d

### ISSUE THREAD

**Issue by razr** [eProsima/Fast-DDS#3808]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Hello @MiguelCompany 

I want to communicate between the docker container and my host, both running ROS2 `humble` and Ubuntu 22.04.
It works fine on `rolling` with `ROS_STATIC_PEERS`, but does not work on `humble`.

 ```bash
# Docker side
docker run -ti -h ros2native -v $PWD:/work <image>
cd ros2_native/install/
source setup.bash

env | grep ROS
ROS_VERSION=2
ROS_PYTHON_VERSION=3
ROS_AUTOMATIC_DISCOVERY_RANGE=SUBNET
ROS2_WS=/opt/ros2_ws
ROS_DISTRO=rolling

export ROS_STATIC_PEERS=172.17.0.1
ros2 run demo_nodes_cpp listener
[INFO] [1692351185.411086291] [listener]: I heard: [Hello World: 1]
[INFO] [1692351186.410639363] [listener]: I heard: [Hello World: 2]

# Host side
cd ros2_native/install/
source setup.bash
export ROS_STATIC_PEERS=172.17.0.2
ros2 run demo_nodes_cpp talker
[INFO] [1692351185.410282463] [talker]: Publishing: 'Hello World: 1'
[INFO] [1692351186.410174763] [talker]: Publishing: 'Hello World: 2
```

What would be the proper FastDDS XML configuration for it on `humble`? I have looked [here](https://fast-dds.docs.eprosima.com/en/latest/fastdds/ros2/ros2_configure.html) but couldn't find it.

### Current behavior

communication between docker and host both running ROS 2 `humble` `talker/listener` does not work

### Steps to reproduce

build ROS 2 `humble` on Ubuntu 22.04 and run the `talker` example inside docker and the `listener` example on the host.

### Fast DDS version/commit

humble

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

Ubuntu 22.04

**Comment by JLBuenoLopez-eProsima** [comment]
Thanks for your contribution, @razr 

`ROS_STATIC_PEERS` was introduced in ROS 2 Iron so it is not available in ROS 2 Humble. You may consider upgrading to the latest ROS 2 version to leverage its latest improvements.

This ROS 2 environment variable is equivalent to the [initial peers Fast DDS feature](https://fast-dds.docs.eprosima.com/en/latest/fastdds/discovery/simple.html#initial-peers) (see the [RMW implementation code](https://github.com/ros2/rmw_fastrtps/blob/rolling/rmw_fastrtps_shared_cpp/src/participant.cpp#L243) for reference).

Also, I am moving this ticket to the Q&A discussion forum as per [Fast DDS CONTRIBUTING guidelines](https://github.com/eProsima/Fast-DDS/blob/master/CONTRIBUTING.md#issues-and-support)
