### ISSUE TITLE
SHMEM Transport errors, even after cleaning

### ISSUE THREAD

**Issue by spiderkeys** [eProsima/Fast-DDS#3817]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

After cleaning up existing shared memory segments using `fastdds shm clean`, I should be able to start a node with the SHMEM transport enabled, with no errors.

I have read the other issues relating to this, all of which seem to have been closed/resolved:
https://github.com/eProsima/Fast-DDS/issues/2003
https://github.com/eProsima/Fast-DDS/issues/2099
https://github.com/eProsima/Fast-DDS/issues/2696
https://github.com/eProsima/Fast-DDS/issues/2811

### Current behavior

Despite having sufficient shmem space available on my machine, and despite running `fastdds shm clean`, I still get errors when creating a ROS2 node with the default FastDDS settings in ROS2 Iron.

The initial error:
```
2023-08-25 13:31:00.179 [RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7410: open_and_lock_file failed -> Function open_port_internal
2023-08-25 13:31:00.179 [RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7411: open_and_lock_file failed -> Function open_port_internal
[INFO] [1692995460.196659311] [main]: Error creating node components: Failed to open port: /dev/ttyUSB0
[ros2run]: Process exited with failure 1
```
Memory usage:
```
$ sudo sysctl -a | grep shmmax
kernel.shmmax = 18446744073692774399
$ df -Th | grep '/dev/shm\|Used'
Filesystem     Type   Size  Used Avail Use% Mounted on
tmpfs          tmpfs   32G  1.4G   30G   5% /dev/shm
```
Before and after running clean:
```
$ fastdds shm clean
shm.clean:
2 ports in use
1 segments in use
0 zombie ports cleaned
25 zombie segments cleaned

$ ros2 run my_node my_node
2023-08-25 13:31:06.803 [RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7410: open_and_lock_file failed -> Function open_port_internal
2023-08-25 13:31:06.804 [RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7411: open_and_lock_file failed -> Function open_port_internal

$ fastdds shm clean
shm.clean:
2 ports in use
1 segments in use
0 zombie ports cleaned
0 zombie segments cleaned

$ ros2 run my_node my_node
2023-08-25 13:37:13.704 [RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7410: open_and_lock_file failed -> Function open_port_internal
2023-08-25 13:37:13.704 [RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7411: open_and_lock_file failed -> Function open_port_internal
```

### Steps to reproduce

I do not yet know how to reproduce the issue. It started after several tens of node runs, with some nodes being killed via SIGINT.

### Fast DDS version/commit

```
ros2 doctor --report | grep fastrtps
2023-08-25 13:39:14.544 [RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7410: open_and_lock_file failed -> Function open_port_internal
2023-08-25 13:39:14.544 [RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7411: open_and_lock_file failed -> Function open_port_internal
fastrtps_cmake_module                     : latest=3.0.1, local=3.0.1
rosidl_typesupport_fastrtps_cpp           : latest=3.0.1, local=3.0.1
rosidl_typesupport_fastrtps_c             : latest=3.0.1, local=3.0.1
rmw_fastrtps_shared_cpp                   : latest=7.1.1, local=7.1.1
rosidl_dynamic_typesupport_fastrtps       : latest=0.0.2, local=0.0.2
rmw_fastrtps_cpp                          : latest=7.1.1, local=7.1.1
middleware name    : rmw_fastrtps_cpp
```

```
dpkg -l | grep fastrtps
ii  ros-iron-fastrtps                                  2.10.1-2jammy.20230622.192622               amd64        *eprosima Fast DDS* (formerly Fast RTPS) is a C++ implementation of the DDS (Data Distribution Service) standard of the OMG (Object Management Group).
ii  ros-iron-fastrtps-cmake-module                     3.0.1-1jammy.20230713.195955                amd64        Provide CMake module to find eProsima FastRTPS.
ii  ros-iron-rmw-fastrtps-cpp                          7.1.1-2jammy.20230713.214423                amd64        Implement the ROS middleware interface using eProsima FastRTPS static code generation in C++.
ii  ros-iron-rmw-fastrtps-shared-cpp                   7.1.1-2jammy.20230713.213144                amd64        Code shared on static and dynamic type support of rmw_fastrtps_cpp.
ii  ros-iron-rosidl-dynamic-typesupport-fastrtps       0.0.2-2jammy.20230713.201717                amd64        FastDDS serialization support implementation for use with C/C++.
ii  ros-iron-rosidl-typesupport-fastrtps-c             3.0.1-1jammy.20230713.202119                amd64        Generate the C interfaces for eProsima FastRTPS.
ii  ros-iron-rosidl-typesupport-fastrtps-cpp           3.0.1-1jammy.20230713.201943                amd64        Generate the C++ interfaces for eProsima FastRTPS.
```

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Shared Memory Transport (SHM)

### Additional context

Ubuntu 22.04
x86_64
ROS2 Iron

**Comment by JLBuenoLopez-eProsima** [comment]
Thanks for your report @spiderkeys 

Several fixes have been merged in the last few weeks fixing the SHM transport. This fixes have already been backported and released into `v2.10.x` branch which is the attached branch to ROS 2 Iron. However, the latest ROS 2 Iron sync was done in August 11th and this Fast DDS v2.10.2 was release just last week. This patch release has already been bloomed into ROS 2 and it should be included in the next ROS 2 Iron sync. Until that moment, you might build ROS 2 from sources to have the fixes in your workspace.

I am going to proceed and close this ticket as it is most probably fixed. Please, feel free to reopen after testing with Fast DDS v2.10.2.

**Comment by JLBuenoLopez-eProsima** [comment]
@spiderkeys 

[ROS 2 Iron has just been synced](https://discourse.ros.org/t/new-packages-for-iron-irwini-2023-08-28/33124) so updating to the latest binaries will be enough.

**Comment by rty813** [comment]
> [@spiderkeys](https://github.com/spiderkeys)
> 
> [ROS 2 Iron has just been synced](https://discourse.ros.org/t/new-packages-for-iron-irwini-2023-08-28/33124) so updating to the latest binaries will be enough.

@JLBuenoLopez Will the fixes be synced to the ROS2 Humble?
