### ISSUE TITLE
FastDDS（2.10版本）和OPENDDS（3.24.1版本）无法建立通信

### ISSUE THREAD

**Issue by hong12234** [eProsima/Fast-DDS#3839]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

在局域网内部192.168.225.57为PC monitor，192.168.225.1为Tbox，192.168.225.32为IVI。Tbox和IVI无法通信，网络报文已经上传。再monitor中只能监视到Tbox

### Current behavior

对比查看初始化配置：
![e7b11f6d391204386a0c94a5ff597b5](https://github.com/eProsima/Fast-DDS/assets/38304396/a765312c-65d8-4b72-b937-27e325e3a9e8)
![010f82c371a90e7865134bbbdec2458](https://github.com/eProsima/Fast-DDS/assets/38304396/6cb257c4-4a18-46a9-a71a-e445e5e1e34c)
![6880bc12905c67b2f892c84a6e5a261](https://github.com/eProsima/Fast-DDS/assets/38304396/59eb7b16-ec65-4b88-98b3-d97399a270c0)
![edc8d2a4687d69c5a795cc1d44b7d48](https://github.com/eProsima/Fast-DDS/assets/38304396/376ad211-3fd9-4aa4-9b7b-00a5ec5708e0)

### Steps to reproduce

必现，目前没有通信成功过

### Fast DDS version/commit

无

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

UDPv4

### XML configuration file

```xml
无
```

### Network traffic capture

[log.zip](https://github.com/eProsima/Fast-DDS/files/12574430/log.zip)

**Comment by hong12234** [comment]
![image](https://github.com/eProsima/Fast-DDS/assets/38304396/2609d6e0-2685-4a68-b021-406bf1bd883d)
还有上面对比中这里不一样，但是我按照图片中配置，没有任何变化。

**Comment by JLBuenoLopez-eProsima** [comment]
Thanks @hong12234 for opening the ticket. Can you please provide the information in English so I can help you with your issue?

**Comment by hong12234** [comment]
FastDDS (version 2.10) and OpenDDS (version 3.24.1) cannot establish communication
Within the LAN, 192.168.225.57 is the PC monitor, 192.168.225.1 is the Tbox, and 192.168.225.32 is the IVI. Tbox and IVI cannot communicate, and the network message has been uploaded. Only Tbox can be monitored in the monitor.

Compare and view the initialization configuration:
![image](https://github.com/eProsima/Fast-DDS/assets/38304396/27251e1c-5e7c-4ee1-a141-ec287f8b3218)
![image](https://github.com/eProsima/Fast-DDS/assets/38304396/a9a6f03f-f586-4a5e-8b91-44b8fe835925)
![image](https://github.com/eProsima/Fast-DDS/assets/38304396/034eff42-789c-43c1-bfcf-8e627800b541)
![image](https://github.com/eProsima/Fast-DDS/assets/38304396/439f18e9-2f18-4b7f-a6cd-f4309e3e15bd)

There is also a difference here in the above comparison, but I configured it according to the picture and there is no change.
![image](https://github.com/eProsima/Fast-DDS/assets/38304396/df42c8aa-774e-4474-bb67-eb9d06377fcb)

Latest News：

![image](https://github.com/eProsima/Fast-DDS/assets/38304396/64e0106e-485a-425a-9c90-2c6b6166f04c)
Changing this option to XCDR has the same phenomenon.

**Comment by JLBuenoLopez-eProsima** [comment]
Thanks for the translation @hong12234 

Currently, Fast DDS only supports XCDR version 1 data representation. It seems that Open DDS is using by default XCDR version 2 which is not backwards compatible. Can you try configuring XCDR version 1 data representation in the Open DDS side of the communication and see if the communication is then established?

**Comment by mitza-oci** [comment]
For context: https://issues.omg.org/issues/task-force/DDSXTY14#issue-47022
Link to https://github.com/OpenDDS/OpenDDS/issues/4268

**Comment by hong12234** [comment]
> 感谢您的翻译@hong12234
> 
> 目前，Fast DDS 仅支持 XCDR 版本 1 数据表示。Open DDS 似乎默认使用 XCDR 版本 2，该版本不向后兼容。您可以尝试在通信的 Open DDS 端配置 XCDR 版本 1 数据表示，然后查看通信是否建立？

Thank you, it's this issue that caused it，I have another question, can fastdds be set to XCDR2？

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @hong12234 

Not yet. [Fast CDR v2.0.0](https://github.com/eProsima/Fast-CDR/releases/tag/v2.0.0) with support for XCDRv2 has just been released, but as the API has been broken, Fast DDS has to migrate to use this Fast CDR version. It is being done in #3828. Fast DDS v2.12.0 will have support for XCDRv2 and it will be released in the coming weeks.
