### ISSUE TITLE
time_t format error

### ISSUE THREAD

**Issue by cathaysia** [eProsima/Fast-DDS#3843]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

The time format is expressed as since_unix_epoch(1970) in fastdds, but the rtps specification states that the time format is an NTP format. The NTP format is since_epoch(1900).

![image](https://github.com/eProsima/Fast-DDS/assets/42114817/6fe2d38b-b269-43d4-bdbb-536ea3e4d18e)
![image](https://github.com/eProsima/Fast-DDS/assets/42114817/b35e2eed-effe-4ac3-a350-1972f2da181f)
![image](https://github.com/eProsima/Fast-DDS/assets/42114817/f6cfbed1-eefd-458b-a752-38249ea8e340)

Viewing the package through wireshark, you can clearly see that the format supported by wireshark is unix epoch.
Does this issue need to be synchronized with the specification? If it is synchronized with the specification, fastdds will have a time overflow problem in 2036. Unless rtps updates the time format to ntpv4 before that.

**Comment by cathaysia** [comment]
ref: https://github.com/wireshark/wireshark/blob/852ef4871c60e37ff5fdb042e1e7d04813d555e1/epan/dissectors/packet-rtps.c#L12864

**Comment by MiguelCompany** [comment]
All DDS vendors that I know of use unix epoch as the reference for time_t. Only the representation **format** is taken from NTP

From section 9.3.2.1 of RTPS 2.5 spec:

```
// TIME_ZERO: seconds = 0, fraction = 0
// TIME_INVALID: seconds = 0xffffffff, fraction = 0xffffffff
// TIME_INFINITE: seconds = 0xffffffff, fraction = 0xfffffffe
struct Time_t {
  unsigned long seconds; // time in seconds
  unsigned long fraction; // time in sec/2^32
};
```
Since the seconds field is an unsigned 32-bit integer, it will only be overrun somewhere in 2106.

There is an [issue](https://issues.omg.org/issues/DDS15-13) open on the DDS standard regarding this.
The seconds field might be changed to 64-bit in the future.

**Comment by cathaysia** [comment]
Yes.  Using 1900 is not a good idea anyway.  After all, it is about to expire, and it is very likely that we will fix it in the future, hahaha.  rtps specifies second as uint32_t, while dds specifies time as int32_t.  int32_t is an even worse decision
