### ISSUE TITLE
Fast-DDS build failure

### ISSUE THREAD

**Issue by neerajverma10** [eProsima/Fast-DDS#3859]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

cmake ..  -DCMAKE_INSTALL_PREFIX=~/Fast-DDS/install
cmake --build . --target install

should pass

### Current behavior

root@e84285f92023:~/Fast-DDS/Fast-DDS/build# cmake --build . --target install -j4
Scanning dependencies of target fastrtps
[  1%] Building CXX object src/cpp/CMakeFiles/fastrtps.dir/fastdds/topic/DDSSQLFilter/DDSFilterCompoundCondition.cpp.o
[  1%] Building CXX object src/cpp/CMakeFiles/fastrtps.dir/fastdds/topic/DDSSQLFilter/DDSFilterExpression.cpp.o
[  2%] Building CXX object src/cpp/CMakeFiles/fastrtps.dir/fastdds/topic/DDSSQLFilter/DDSFilterExpressionParser.cpp.o
[  2%] Building CXX object src/cpp/CMakeFiles/fastrtps.dir/fastdds/topic/DDSSQLFilter/DDSFilterFactory.cpp.o
[  3%] Building CXX object src/cpp/CMakeFiles/fastrtps.dir/fastdds/topic/DDSSQLFilter/DDSFilterField.cpp.o
In file included from /root/Fast-DDS/Fast-DDS/include/fastdds/dds/topic/IContentFilter.hpp:30,
                 from /root/Fast-DDS/Fast-DDS/src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterExpression.hpp:27,
                 from /root/Fast-DDS/Fast-DDS/src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterExpression.cpp:19:
/root/Fast-DDS/Fast-DDS/include/fastrtps/types/TypesBase.h:273:27: error: expected unqualified-id before numeric constant
  273 | #define MEMBER_ID_INVALID 0X0FFFFFFF
      |                           ^~~~~~~~~~
In file included from /root/Fast-DDS/Fast-DDS/src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterExpression.cpp:31:
/usr/local/include/fastcdr/Cdr.h: In member function 'eprosima::fastcdr::Cdr& eprosima::fastcdr::Cdr::operator<<(const _T&)':
/usr/local/include/fastcdr/Cdr.h:327:31: error: no match for 'operator==' (operand types are 'int' and 'eprosima::fastcdr::MemberId')
  327 |         if (MEMBER_ID_INVALID == next_member_id_)
      |                               ^~ ~~~~~~~~~~~~~~~
      |                                  |
      |                                  eprosima::fastcdr::MemberId
/usr/local/include/fastcdr/Cdr.h: In member function 'eprosima::fastcdr::Cdr& eprosima::fastcdr::Cdr::operator>>(_T&)':

### Steps to reproduce

https://fast-dds.docs.eprosima.com/en/latest/installation/sources/sources_linux.html
cd ~/Fast-DDS
git clone https://github.com/eProsima/Fast-DDS.git
mkdir Fast-DDS/build
cd Fast-DDS/build
cmake ..  -DCMAKE_INSTALL_PREFIX=~/Fast-DDS/install
cmake --build . --target install

I have installed all the dependencies but still getting errors. I use host uBuntu 20.04

root@e84285f92023:~/Fast-DDS/Fast-DDS/build# cmake ..  -DCMAKE_INSTALL_PREFIX=/usr/local/
-- Setting build type to 'Release' as none was specified.
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Version: 2.12.0
-- Performing Test SUPPORTS_cxx_std_23
-- Performing Test SUPPORTS_cxx_std_23 - Failed
-- Performing Test SUPPORTS_NOTFOUND
-- Performing Test SUPPORTS_NOTFOUND - Success
-- Enforced cxx_std_11 CMake feature
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Found fastcdr
-- Found Asio 1.12.2: /usr/include
-- Found Asio
-- Found TinyXML2
-- Found foonathan_memory: /usr/local/lib/foonathan_memory/cmake
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_kill
-- Looking for pthread_kill - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Thirdparty/boost compiled OK
-- Found OpenSSL: /usr/lib/aarch64-linux-gnu/libcrypto.so (found version "1.1.1f")
-- OpenSSL library 1.1.1f found...
-- Performing Test ATOMIC_WITHOUT_LIB
-- Performing Test ATOMIC_WITHOUT_LIB - Success
-- Forcing third party shared_mutex
-- Performing Test HAS_VERSION_SCRIPT_SUPPORT
-- Performing Test HAS_VERSION_SCRIPT_SUPPORT - Success
-- Using linker version script to select exported symbols
-- Performing Test SUPPORTS_CXX11
-- Performing Test SUPPORTS_CXX11 - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /root/Fast-DDS/Fast-DDS/build
root@e84285f92023:~/Fast-DDS/Fast-DDS/build# cmake --build . --target install -j4
Scanning dependencies of target fastrtps
[  1%] Building CXX object

### Fast DDS version/commit

latest

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

TCPv4

### Additional context

I am new to ROS but recently started our development. I am getting build errors due to some reason and could not figure out. also I know Fast-DDS is well maintained it shouldn't have build errors. Any help would be greatly appreciated.

https://fast-dds.docs.eprosima.com/en/latest/installation/sources/sources_linux.html
cd ~/Fast-DDS
git clone https://github.com/eProsima/Fast-DDS.git
mkdir Fast-DDS/build
cd Fast-DDS/build
cmake ..  -DCMAKE_INSTALL_PREFIX=~/Fast-DDS/install
cmake --build . --target install

I have installed all the dependencies but still getting errors. I use host uBuntu 20.04

root@e84285f92023:~/Fast-DDS/Fast-DDS/build# cmake ..  -DCMAKE_INSTALL_PREFIX=/usr/local/
-- Setting build type to 'Release' as none was specified.
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Version: 2.12.0
-- Performing Test SUPPORTS_cxx_std_23
-- Performing Test SUPPORTS_cxx_std_23 - Failed
-- Performing Test SUPPORTS_NOTFOUND
-- Performing Test SUPPORTS_NOTFOUND - Success
-- Enforced cxx_std_11 CMake feature
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Found fastcdr
-- Found Asio 1.12.2: /usr/include
-- Found Asio
-- Found TinyXML2
-- Found foonathan_memory: /usr/local/lib/foonathan_memory/cmake
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_kill
-- Looking for pthread_kill - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Thirdparty/boost compiled OK
-- Found OpenSSL: /usr/lib/aarch64-linux-gnu/libcrypto.so (found version "1.1.1f")
-- OpenSSL library 1.1.1f found...
-- Performing Test ATOMIC_WITHOUT_LIB
-- Performing Test ATOMIC_WITHOUT_LIB - Success
-- Forcing third party shared_mutex
-- Performing Test HAS_VERSION_SCRIPT_SUPPORT
-- Performing Test HAS_VERSION_SCRIPT_SUPPORT - Success
-- Using linker version script to select exported symbols
-- Performing Test SUPPORTS_CXX11
-- Performing Test SUPPORTS_CXX11 - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /root/Fast-DDS/Fast-DDS/build
root@e84285f92023:~/Fast-DDS/Fast-DDS/build# cmake --build . --target install -j4
Scanning dependencies of target fastrtps
[  1%] Building CXX object src/cpp/CMakeFiles/fastrtps.dir/fastdds/topic/DDSSQLFilter/DDSFilterCompoundCondition.cpp.o
[  1%] Building CXX object src/cpp/CMakeFiles/fastrtps.dir/fastdds/topic/DDSSQLFilter/DDSFilterExpression.cpp.o
[  2%] Building CXX object src/cpp/CMakeFiles/fastrtps.dir/fastdds/topic/DDSSQLFilter/DDSFilterExpressionParser.cpp.o
[  2%] Building CXX object src/cpp/CMakeFiles/fastrtps.dir/fastdds/topic/DDSSQLFilter/DDSFilterFactory.cpp.o
[  3%] Building CXX object src/cpp/CMakeFiles/fastrtps.dir/fastdds/topic/DDSSQLFilter/DDSFilterField.cpp.o
In file included from /root/Fast-DDS/Fast-DDS/include/fastdds/dds/topic/IContentFilter.hpp:30,
                 from /root/Fast-DDS/Fast-DDS/src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterExpression.hpp:27,
                 from /root/Fast-DDS/Fast-DDS/src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterExpression.cpp:19:
/root/Fast-DDS/Fast-DDS/include/fastrtps/types/TypesBase.h:273:27: error: expected unqualified-id before numeric constant
  273 | #define MEMBER_ID_INVALID 0X0FFFFFFF
      |                           ^~~~~~~~~~
In file included from /root/Fast-DDS/Fast-DDS/src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterExpression.cpp:31:
/usr/local/include/fastcdr/Cdr.h: In member function 'eprosima::fastcdr::Cdr& eprosima::fastcdr::Cdr::operator<<(const _T&)':
/usr/local/include/fastcdr/Cdr.h:327:31: error: no match for 'operator==' (operand types are 'int' and 'eprosima::fastcdr::MemberId')
  327 |         if (MEMBER_ID_INVALID == next_member_id_)
      |                               ^~ ~~~~~~~~~~~~~~~
      |                                  |
      |                                  eprosima::fastcdr::MemberId
/usr/local/include/fastcdr/Cdr.h: In member function 'eprosima::fastcdr::Cdr& eprosima::fastcdr::Cdr::operator>>(_T&)':
/usr/local/include/fastcdr/Cdr.h:357:31: error: no match for 'operator==' (operand types are 'int' and 'eprosima::fastcdr::MemberId')
  357 |         if (MEMBER_ID_INVALID == next_member_id_)
      |                               ^~ ~~~~~~~~~~~~~~~
      |                                  |
      |                                  eprosima::fastcdr::MemberId
/root/Fast-DDS/Fast-DDS/src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterExpression.cpp: In member function 'virtual bool eprosima::fastdds::dds::DDSSQLFilter::DDSFilterExpression::evaluate(const SerializedPayload&, const eprosima::fastdds::dds::IContentFilter::FilterSampleInfo&, const GUID_t&) const':
/root/Fast-DDS/Fast-DDS/src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterExpression.cpp:60:95: error: 'DDS_CDR' is not a member of 'eprosima::fastcdr::Cdr'
   60 |         Cdr deser(fastbuffer, eprosima::fastcdr::Cdr::DEFAULT_ENDIAN, eprosima::fastcdr::Cdr::DDS_CDR);
      |

**Comment by JLBuenoLopez-eProsima** [comment]
Hi @neerajverma10 

Are you sure that you are following the Fast DDS source installation guide? The guide gives the following command:

```
wget https://raw.githubusercontent.com/eProsima/Fast-DDS/master/fastrtps.repos
```

The [corresponding file](https://raw.githubusercontent.com/eProsima/Fast-DDS/master/fastrtps.repos) uses Fast CDR 1.1.x branch instead of master. The reported error is expected as Fast CDR has just gone through a major release version and API has been broken. This has already been reported in #3832. So I am labelling as duplicated and closing it as it is the expected behavior until the migration to the new Fast CDR API is complete.
