### ISSUE TITLE
About Vulnerabilities in HeartBeat Messages [QoS - Reliable Mode]

### ISSUE THREAD

**Issue by Desglaneurs** [eProsima/Fast-DDS#3931]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

In FastDDS in ROS2, a vulnerability was discovered a malicious attacker manipulates the sequence of Heartbeat packets to interfere with communication between Publisher & Subscriber. Manipulating the sequence of an existing Heartbeat packet to a large value that has not yet been reached can lead to a Denial of Service (DoS) condition in the system. Related details are as shown in [Link](https://github.com/BOB12thCVEIssacGleaning/BOB12th_CVEIssacGleaning/blob/main/Heartbeat/Issue%20%232/FastDDS.md)

### Current behavior

Attack Details

The attacker sniffs the RTPS packet between Publisher (Talker) and Subscriber (Listener) and then uses the Scapy tool to spoof the value of 'guid-prefix, src IP, dst IP, sport, dport, submessageID: HEARTBEAT (flag, octetsToNextHeader, reader/writerEntityId).
Subsequently, the Sequence Number within the Heartbeat message is maliciously manipulated to a very high Sequence Number and resent to the Subscriber. As a result, all data sent from the Publisher to the Subscriber is lost.
1,2,3,4... If an attacker manipulates the increasing Sequence Number to 50 and then sends a packet, the Subscriber does not receive the data content from 5 to 49 and lost it, and receives normal data after 50.
The attacked Subscriber cannot receive the Publisher's data afterward.

### Steps to reproduce

Attack Environment Required Info
Operating System : Ubuntu 22.04 LTS
ROS2 IRON FastDDS - 2 Docker environments (172.17.0.2, 172.17.0.3)
Attack Description
[Attacker] Uses the scapy tool to include a random very high Sequence Number (ex. 999999) in a HeartBeat message and sends it to the Subscriber (Listener).
[victim] The Subscriber (listener) does not receive the data sent by the publisher until the Sequence Number is 999999.

### Fast DDS version/commit

![image](https://github.com/eProsima/Fast-DDS/assets/146199020/88cc11c0-f719-4f73-bfb0-486db30b9ccd)

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

UDPv4

### Additional context

Attack Environment Required Info
Operating System : Ubuntu 22.04 LTS
ROS2 IRON FastDDS - 2 Docker environments (172.17.0.2, 172.17.0.3)

### Network traffic capture

[after an attack]
![image](https://github.com/eProsima/Fast-DDS/assets/146199020/f09ddf03-8bb8-44d6-9cca-dae45b62794a)

[Acknack]
![image](https://github.com/eProsima/Fast-DDS/assets/146199020/48f08aaf-7977-46a7-a5cb-c447e5ec3fb2)
[fastdds_heartbeat.zip](https://github.com/eProsima/Fast-DDS/files/12913972/fastdds_heartbeat.zip)

**Comment by MiguelCompany** [comment]
@Desglaneurs There's a security advisory open with this. We will follow the conversation there

**Comment by MiguelCompany** [comment]
@Desglaneurs There's a security advisory open with this. We will follow the conversation there

**Comment by MiguelCompany** [comment]
For anyone coming here, I copy the answer from the (now closed) security advisory.

Unfortunately, leveraging DDS Security is the only way to overcome this issue.
Just using message authentication codes for the meta-traffic (i.e. heartbeat, gap, acknack, etc) would make the system robust against this type of attack.

The vulnerability is publicly recognized in the [DDS-SEC](https://www.omg.org/spec/DDS-SECURITY/1.1/PDF) standard, page 49:

```
The RTPS reliable protocol allows a DataWriter to send to a DataReader Heartbeat
messages that advance the first available sequence number associated with the DataWriter.

A DataReader receiving a Heartbeat from a DataWriter will advance its first available
sequence number for that DataWriter and ignore any future messages it receives with sequence
numbers lower than the first available sequence number for the DataWriter.

The reliable DataReader will also ignore duplicate messages for that same sequence number.

This behavior of the reliability protocol would allow a malicious application to prevent other
applications from communicating by sending Heartbeats pretending to be from other
DomainParticipants that contain large values of the first available sequence number.
All the malicious application needs to do is learn the GUIDs of other applications, which can be done from
observing the initial discovery messages on the wire, and use that information to create fake
Heartbeats
```
