### ISSUE TITLE
XCDR2 is set, but not used on the wire

### ISSUE THREAD

**Issue by pingurus** [eProsima/Fast-DDS#3935]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

If I set a `DataWriter` to use XCDR2, this should not only be the case when querying it through code, but also be the representation on the wire.

### Current behavior

Even though I set the data representation to XCDR2, the representation vector is empty on the wire.
![image](https://github.com/eProsima/Fast-DDS/assets/36167579/8a08cfec-d5f5-4b3e-970d-a1618a8bcf7d)

### Steps to reproduce

Use auto-generated code by fastddgen 3.0.1 to auto-generate code and modify the publisher as follows:

```
        DataRepresentationQosPolicy dataRepQos;
        dataRepQos.m_value.push_back(DataRepresentationId_t::XCDR2_DATA_REPRESENTATION);
        DataWriterQos dwqos;
        dwqos.representation(dataRepQos);

        writer_ = publisher_->create_datawriter(topic_, dwqos, &listener_);

        std::cout << "XCDR Version: ";
        std::cout << writer_->get_qos().representation().m_value[0];
        std::cout << std::endl;
```
The console output shows that writer indeed has a qos with XCDR2 enabled.
Use Fast DDS Monitor to see that this change does not affect what is on the wire.

### Fast DDS version/commit

Release v2.12.0

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

OS: Ubuntu 22.04.3 LTS
Prior version of FastDDS was installed, but `build/` deleted and cmake reconfigured after installation of current Fast DDS Version.

**Comment by JesusPoderoso** [comment]
Hi @pingurus, despite of Fast CDR v2.0.0 introduces the XCDR2 feature, it is not introduced yet in Fast DDS (v2.12.0).
The XTypes feature, wich is needed for introducing XCDR2 in Fast DDS, is WIP right now. It will be introduced soon in future releases (see our [roadmap](https://github.com/eProsima/Fast-DDS/blob/master/roadmap.md)).
