### ISSUE TITLE
Shared Memory conflict with Fast-DDS application

### ISSUE THREAD

**Issue by LuisPoveda** [eProsima/Fast-DDS#4012]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

My application is capable of sending and receiving messages using Shared Memory

### Current behavior

My current configuration consists of two parts:

* An application with its own Fast-DDS library (Fast-DDS `2.11.2`). This application is responsible for publishing and subscribing to some data.

* ROS2 foxy installed at system level (Fast-DDS `2.0.2`). These nodes subscribe to the topics generated by the previous application.

The issue lies when running the application and the ROS2 foxy nodes on the same host machine. This causes Fast-DDS to use shared memory, as expected, but these results in the following error.

```
[RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7413: open_and_lock_file failed -> Function open_port_internal
[RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7415: open_and_lock_file failed -> Function open_port_internal
[RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7417: open_and_lock_file failed -> Function open_port_internal
[RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7419: open_and_lock_file failed -> Function open_port_internal
[RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7415: open_and_lock_file failed -> Function open_port_internal
[RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7417: open_and_lock_file failed -> Function open_port_internal
[RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7419: open_and_lock_file failed -> Function open_port_internal
[RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7421: open_and_lock_file failed -> Function open_port_internal
[RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7417: open_and_lock_file failed -> Function open_port_internal
[RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7419: open_and_lock_file failed -> Function open_port_internal
[RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7421: open_and_lock_file failed -> Function open_port_internal
[RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7419: open_and_lock_file failed -> Function open_port_internal
[RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7421: open_and_lock_file failed -> Function open_port_internal
[RTPS_TRANSPORT_SHM Error] Failed init_port fastrtps_port7421: open_and_lock_file failed -> Function open_port_internal
```

This issue can be seen from both the application and ROS2 nodes, along with any time a ROS2 command is run, such as `ros2 topic list`.

While everything works fine when changing the transport layer to use `UDP`, this is not a solution for us, as we are interested in using SHM.

### Steps to reproduce

See Current Behaviour

### Fast DDS version/commit

Application version: `2.11.2`
ROS2 foxy version: `2.0.2`

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by JLBuenoLopez-eProsima** [comment]
@LuisPoveda 

I am afraid that [ROS 2 Foxy](https://docs.ros.org/en/foxy/Releases.html) and [Fast DDS v2.0](https://github.com/eProsima/Fast-DDS/blob/master/RELEASE_SUPPORT.md) are no longer supported. The reported issue was fixed a few months ago in the alive distributions (Humble, Iron and Rolling). I suggest you upgrade to the next long term ROS 2 release: ROS 2 Humble.

As the corresponding versions are stale, I am going to close the issue. Feel free to reopen if the issue still happens after upgrading to one still maintained ROS 2 distribution.

**Comment by MiguelCompany** [comment]
Additionaly, the compatibility of SHM transport files was [intentionally](https://github.com/eProsima/Fast-DDS/blame/master/src/cpp/rtps/transport/shared_mem/SharedMemGlobal.hpp#L93) broken in PR #1856. This was introduced in Fast DDS v2.3.0
