### ISSUE TITLE
Frequently create/delete DataReader/Writer DomainParticipant in two application causes deadlock

### ISSUE THREAD

**Issue by ulongcha** [eProsima/Fast-DDS#4026]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

No deadlock

### Current behavior

Thread of funtion ResourceEvent::unregister_timer is stucked.

### Steps to reproduce

Using some (about 3) TCP Client participants connect and create DataReader then delete the DataReader and disconnect to a TCP Server participant. Few minutes later, all participants are stucked.

### Fast DDS version/commit

2.11.2

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

TCPv4

### Additional context

1. It stucked at `ResourceEvent::unregister_timer` because it needed `cv_manipulation_` awake after `ResourceEvent::do_timer_actions()`.
![unregister](https://github.com/eProsima/Fast-DDS/assets/50707687/8c5912bd-9513-4036-9df7-fea59f680f39)

2. In this case, `ResourceEvent::do_timer_actions()` triggered `RTPSParticipantImpl::sendSync`. And this function was waiting for `m_send_resources_mutex_` release.
![sendsync](https://github.com/eProsima/Fast-DDS/assets/50707687/b8605a1c-0c7b-4d6c-bd60-017a23f74171)

3. When new reader come this time, it called `RTPSParticipantImpl::createSenderResources` first and then held `m_send_resources_mutex_`.
![createSender](https://github.com/eProsima/Fast-DDS/assets/50707687/4674b6ee-7a84-4a38-84a1-0337d0d1405f)
Then it called `tcp_sender_resource->channel()->clear();`, wait the first thread join.
![clear](https://github.com/eProsima/Fast-DDS/assets/50707687/a083fbf3-79d1-48ab-a169-f815a941961f)

I am not clear why it called `tcp_sender_resource->channel()->clear();`, I think it causes all thread stucked. 
Sorry for terrible description.

**Comment by ulongcha** [comment]
I'm not sure if this is the reason cause the stuck, please check it.

**Comment by ulongcha** [comment]
The TCP Client Participant creates DataReader right now after TCP Server Participant creates DataWriter.
I'm not sure if this frequent action is causing the stuck.
How to prevent this scenario happen?

**Comment by chunyisong** [comment]
May be same Problem.
https://github.com/eProsima/Fast-DDS/issues/3621

**Comment by ulongcha** [comment]
I tried two application open locally, each with a ClientParticipant that repeatedly `create ClientParticipant-create DataReader-delete DataReader-delete ClientParticipant`, all connect to the ServerParticipant on 127.0.0.1.
The ServerParticipant create/delete DataWriter immediately after ClientParticipant create/delete DataReader.
Is it possible that repeated connections to ServerParticipant by ClientParticipant from different applications at the same ip address are causing this problem?

**Comment by ulongcha** [comment]
During test, I also find another deadlock case.

This time, the channel's `perform_listen_operation` is called twice.
![image](https://github.com/eProsima/Fast-DDS/assets/50707687/678dea59-1b2f-4c1c-8698-4082362aafe5)

One thread held `ReceiverResource::mtx`
![image](https://github.com/eProsima/Fast-DDS/assets/50707687/bf0abde4-9f69-4750-8a7e-3b86c0307bd9)
and called `tcp_sender_resource->channel()->clear()`
![image](https://github.com/eProsima/Fast-DDS/assets/50707687/3b4521d9-d33e-4b59-b7a9-4c2d3e74ba2a)
which is waiting for the other thread join.

The other thread is waiting for `ReceiverResource::mtx`, which caused deadlock.

**Comment by jepemi** [comment]
Thanks for reporting the issue. We're currently addressing it and will provide updates soon.

**Comment by ulongcha** [comment]
> Thanks for reporting the issue. We're currently addressing it and will provide updates soon.

Thank you！

**Comment by ulongcha** [comment]
Hi @jepemi ,
During recent test, I found that although ClientParticipant is deleted right, its related `send_source` is still in ServerParticipant's `send_resource_list_`, which caused warning info.
![Not connect](https://github.com/eProsima/Fast-DDS/assets/50707687/0ff7f4cf-ce5b-4c67-bb33-e104f8ceb16f)

During debug, the size of `send_resource_list_` seemed not correct. The size is 2 while I deleted a ClientParticipant and reconnected.
![send_resource_list_size](https://github.com/eProsima/Fast-DDS/assets/50707687/47dfd4e1-36d4-45e6-a354-5056230642e6)

Can you help with this too? Trhank you!
