### ISSUE TITLE
[20067] ParticipantDiscoveryInfo use-after-move

### ISSUE THREAD

**Issue by mtheall** [eProsima/Fast-DDS#4043]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

N/A

### Current behavior

N/A

### Steps to reproduce

N/A

### Fast DDS version/commit

Introduced in f15c7c7

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

`DomainParticipantImpl::MyRTPSParticipantListener::onParticipantDiscovery()`
`info` is std::move'd, and then conditionally used after that move.

I understand that moving this object is actually a no-op, since its only members are an enum and a const reference. Perhaps for future-proofing or at least adhering to move semantics, this should probably be changed to only move once.

**Comment by MiguelCompany** [comment]
On the one hand, the `std::move` in this case will be transformed into a `static_cast` so yes, they are a no-op.
On the other hand, the overload of `on_participant_discovery` not receiving `should_be_ignored` will be removed in the next major version, so this will not be an issue in the future.

I just created #4078 so we don't forget.

**Comment by MiguelCompany** [comment]
Closing since #4078 has been merged
