### ISSUE TITLE
Can't get participant id from DDS participant

### ISSUE THREAD

**Issue by mtheall** [eProsima/Fast-DDS#4044]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

`participant->get_qos ().wire_protocol ()->participant_id` is the current participant id

### Current behavior

`participant->get_qos ().wire_protocol ()->participant_id` is -1

### Steps to reproduce

```cpp
auto const factory = eprosima::fastdds::dds::DomainParticipantFactory::get_instance ();

auto const participant = factory->create_participant (0, PARTICIPANT_QOS_DEFAULT);

std::printf ("Participant ID %d\n", participant->get_qos ().wire_protocol ()->participant_id);
```

### Fast DDS version/commit

2.10.1
2.12.1

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

With a DomainParticipantListener I can get information about discovered participants. However, I can't get the same info for participants I'm creating myself. Participant IDs (and consequently unicast/multicast ports) would be very helpful in my logs to correlate how two entities communicate with each other.

With the old RTPS interface I could get these values directly.

**Comment by MiguelCompany** [comment]
I'd say the expectation, in this case, is for `participant->get_qos()` to return the same value as `factory->get_default_participant_qos()`.

The participant ID is part of the GUID, which can be retrieved by calling `participant->guid()`. The participant ID is serialized least-significant-byte first in the last 4 bytes of the prefix.

That said, I do see the value of either:
1. Call the discovery listener with the data of our own participant
2. Have a method `const ParticipantProxyData* get_discovery_data()` that returns the discovery information of the local participant (or `nullptr` if the participant is not enabled).

**Comment by kshang** [comment]
@mtheall
hi, have you get information for participants that created yourself now
