### ISSUE TITLE
ROS Discovery server - topics fail to recover from network disruptions

### ISSUE THREAD

**Issue by robert-preissl** [eProsima/Fast-DDS#4111]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

We have a multi agent/robotics system based on ROS2 (Galactic, FastRTTPS RMW, using the ROS discovery server).
After networking interruptions are over (e.g., we sometimes experience brief wifi outages on the robot side) we would expect existing ROS subscribers on machine A to automatically re-connect and stream topics again, which machine B publishes. (Machine B is the one with the temporary wifi outage).

### Current behavior

- When the network health recovers the ROS communications are permanently disrupted. No topics resume flowing along existing discovered connections, and a new super client participant cannot discover any topics from the disrupted robot.
- Topics subscribed to internally between nodes running on the affected robot continue to flow internally.
- Topics subscribed to by other entities in the system are visible with `ros2 topic list` but no actual messages flow.
- Relaunching the ROS nodes on the impacted robot properly refreshes the connections to the other system entities.
- ros2 daemon stop/start on the impacted robot predictably doesn’t fix connection issues
- No ROS or system logs indicating any sort of error.

### Steps to reproduce

Unfortunately not a deterministic way to reproduce with simple wifi off/on. seems to happen only in our production set up.

### Fast DDS version/commit

dpkg -l | grep fastrtps

ros-galactic-fastrtps                               2.3.4-1focal.20220210.213807         arm64
ros-galactic-rmw-fastrtps-cpp              5.0.1-1focal.20220210.224404         arm64

### Platform/Architecture

Ubuntu Focal 20.04 arm64

### Transport layer

UDPv4

### Additional context

- ROS2 Galactic
- Ubuntu 20
- FastRTTPS RMW
- ROS Discovery Server
- All messages have the Reliable QoS with volatile durability

### XML configuration file

```xml
<dds xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
    <profiles>

        <transport_descriptors>
            <transport_descriptor>
                <transport_id>test</transport_id>
                <type>UDPv4</type>
                <non_blocking_send>true</non_blocking_send>
            </transport_descriptor>
        </transport_descriptors>

        <participant profile_name="participant profile" is_default_profile="true">
            <rtps>
                <userTransports>
                    <transport_id>test</transport_id>
                </userTransports>
                <useBuiltinTransports>false</useBuiltinTransports>
            </rtps>
        </participant>

        <publisher profile_name="publisher profile" is_default_profile="true">
            <historyMemoryPolicy>PREALLOCATED_WITH_REALLOC</historyMemoryPolicy>
        </publisher>
        <subscriber profile_name="subscriber profile" is_default_profile="true">
            <historyMemoryPolicy>PREALLOCATED_WITH_REALLOC</historyMemoryPolicy>
        </subscriber>

    </profiles>

</dds>
```

**Comment by chunyisong** [comment]
We also have a similar problem,except that we use debian10 and tcp.
In the beginning,discovery server communicates with multiple subscribers and publishers normally,readers and writers match each other as expected,measure datas were transfored normally;But after a few hours,they unmatched and matching again never occurs.

**Comment by ulongcha** [comment]
> We also have a similar problem,except that we use tcp and fastdds v2.11.2. In the beginning,discovery server communicates with multiple subscribers and publishers normally,readers and writers match each other as expected,measure datas were transfored normally;But after a few hours,they unmatched and recovering match again never occurs. Also, we weren't sure if the network had ever been interrupted. but we did a tcpdump when we found out that we lost all match, and tcpdump shows that the communication between discovery server and other entities works fine.

This is caused by #4026, the discovery's thread is stucked. Because use discovery server, it will not stuck PublisherParticipant's thread. So the discovery service is down.

**Comment by robert-preissl** [comment]
@ulongcha thanks for your message - yes, maybe there is something happening with the discovery server.
But what puzzles me is that rebooting the client machine, or as mentioned in the bug report "_Relaunching the ROS nodes on the impacted robot properly refreshes the connections to the other system entities_." seems to improve this situation, without touching the discovery server.

also thanks @chunyisong for your report. does it mean you experienced some flaky communication but then things improved on it is own after some time? no specific actions taken also later on like upgrading ROS2 or fastDDS or anything you would recommend?

**Comment by chunyisong** [comment]
@robert-preissl Thanks for your attention. More details is as follows:

After running for a period of time, writers and readers will be unmatched, and the rematching will be quickly reestablished. However, after this process continues for a period of time, all readers lost all matching and keep unchanged (no matching and no unmatching),all writers has some matching but keep unchagned whth no new rematching ,looks like they are stucked!
But do a tcpdump at this time, communication messages ard found between related entites.

If Only restart readers process,discovery server can discover new readers,but writers has nothing  happend!
If Only restart discover server process,readers and writers can find server but no matching happend.
if only restart writers process,all matching happend and finally readers lost all matching and "stucked" after some time.

We are watiing for fastdds v2.11.3 for some  tcp deadlock bug fixes.

**Comment by JesusPoderoso** [comment]
Hi @robert-preissl, thanks for using Fast DDS.
ROS 2 Galatic is EOL, as well as its dedicated Fast DDS v2.3.x.
Could you check if it is currently happening with latest Fast DDS v2.13.1?

**Comment by Mario-DL** [comment]
According to our [CONTRIBUTING.md](https://github.com/eProsima/Fast-DDS/blob/master/CONTRIBUTING.md) guidelines, I am closing this issue due to both inactivity and because ROS `galactic` is not maintained anymore.
