### ISSUE TITLE
Filtered Subscription with LIKE / EQ condition and a parameter

### ISSUE THREAD

**Issue by p2k-ko** [eProsima/Fast-DDS#4199]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

During evaluation of FastDDS I tried to create a filtered subscription based on a STRING value. According to the documentation: [DefaultFilter](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/topic/contentFilteredTopic/defaultFilter.html) the string may be compared with LIKE/MATCH or EQUALS. 

If the check for the color is added to the filter of the ShapesDemo [ShapeSubscriber](https://github.com/eProsima/ShapesDemo/blob/ef02ba1f28aa36fc32cbc0dcd18ef13bad6117da/src/shapesdemo/ShapeSubscriber.cpp#L100) the following variants should behave identically:

1. Fixed color within filter expression
``` cpp
static uint64_t filter_index = 0;
        //const std::string color = "RED";
        std::vector<std::string> parameters;
        parameters.emplace_back(std::to_string(m_shapeHistory.m_filter.m_minX));
        parameters.emplace_back(std::to_string(m_shapeHistory.m_filter.m_maxX));
        parameters.emplace_back(std::to_string(m_shapeHistory.m_filter.m_minY));
        parameters.emplace_back(std::to_string(m_shapeHistory.m_filter.m_maxY));
        // parameters.emplace_back(color);

        mp_filtered_topic = mp_sd->getParticipant()->create_contentfilteredtopic(
            std::to_string(filter_index++), mp_topic,
            "x > %0 AND x < %1 AND y > %2 AND y < %3 AND color = 'RED'", parameters);
```

2. Color supplied as a parameter to the filter
``` cpp
        static uint64_t filter_index = 0;
        const std::string color = "RED";                
        std::vector<std::string> parameters;
        parameters.emplace_back(std::to_string(m_shapeHistory.m_filter.m_minX));
        parameters.emplace_back(std::to_string(m_shapeHistory.m_filter.m_maxX));
        parameters.emplace_back(std::to_string(m_shapeHistory.m_filter.m_minY));
        parameters.emplace_back(std::to_string(m_shapeHistory.m_filter.m_maxY));
        parameters.emplace_back(color);

        mp_filtered_topic = mp_sd->getParticipant()->create_contentfilteredtopic(
            std::to_string(filter_index++), mp_topic,
            "x > %0 AND x < %1 AND y > %2 AND y < %3 AND color = '%4'", parameters);
```

Both filters should filter the samples of the selected shape topic if the position is within the boundaries and the color is RED.

### Current behavior

1. Fixed color within filter expression

If the color is fixed within the filter expression the subscription works as expected. Only the shapes with the RED color within the boundaries are filtered. 

2. Color supplied as a parameter to the filter

If the color is provided as a parameter the subscription does not yield any samples of the RED shape.  

### Steps to reproduce

- Create a Filter with a STRING variable e.g. ""x > %0 AND x < %1 AND y > %2 AND y < %3 AND color = '%4'"
- Provide the filter value as a parameter
- Start a publisher 
- Start the matching subscriber with the content filter 
Example available at : [https://github.com/p2k-ko/ShapesDemo/tree/issue_4199](https://github.com/p2k-ko/ShapesDemo/tree/issue_4199)

### Fast DDS version/commit

commit 7195eded37bedbcf5df1d9520e383bf015d513d5

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

UDPv4

### Additional context

Some preliminary debugging points to the `DDSFilterPredicate`. If the STRING value is provided as a parameter the content of the `_right->string_value` is "%4" instead of "RED". It seems that the parser mixes up the parameter and the LIKE expression?

Compiled on: Linux 6.1.69-1-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Dec 21 12:29:38 UTC 2023 x86_64 GNU/Linux

**Comment by MiguelCompany** [comment]
Hi @p2k-ko , thank you for using Fast DDS.

You should remove the single quotes around the parameter, so your filter expression would be something like `x > %0 AND x < %1 AND y > %2 AND y < %3 AND color = %4`

**Comment by p2k-ko** [comment]
Yes, you are right. We had to add the single quotes to the color string. This combination works for us. This issue can be closed.

**Comment by p2k-ko** [comment]
No bug
