### ISSUE TITLE
Fast-DDS Oracle8.4 compilation issue

### ISSUE THREAD

**Issue by paulBismuthListen** [eProsima/Fast-DDS#4225]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

fast-DDS does compile for oracle8.4

### Current behavior

fastDDS does not compile for Oracle8.4

### reproduce
Install all the required package from the documentation.
In order to be able to reproduce installation of asio-devel-1.16.1 is needed.

Try to compile following install from source (linux) [documentation](https://fast-dds.docs.eprosima.com/en/latest/installation/sources/sources_linux.html) part:
`3.1.4.1 -> cmake --build . --target install`

As gettid() system call is not available on oracle 8 compilation fails.

Failing because of this commit:
```
git blame ./src/cpp/utils/threading/threading_pthread.ipp -L 99,101
3aa012db06 (Mario Domínguez López  2023-12-12 16:24:37 +0100  99)         {
3549fb9018 (Eduardo Ponz Segrelles 2023-11-21 08:45:30 +0100 100)             result = setpriority(PRIO_PROCESS, gettid(), sched_priority);
3aa012db06 (Mario Domínguez López  2023-12-12 16:24:37 +0100 101)   

```

### Note

I have to be on oracle 8.4 and currently training on Fast-DDS.

Found a workaround [here](https://blogs.oracle.com/linux/post/how-to-use-ublk-on-oracle-linux-8): step-6
by adding this to  threading_pthread.ipp
l.24: ```#include <sys/syscall.h>```
l.29:
```
 #ifndef SYS_gettid
#error "SYS_gettid unavailable on this system"
#endif

#define gettid() ((pid_t)syscall(SYS_gettid))
```

### Fast DDS version/commit

Commit hash: [5aa169cc](https://github.com/eProsima/Fast-DDS/commit/5aa169cce1c0ae57f44e9a7f55d10113ab2da238)
tag: 2.13.x

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

output of hostnamectl
```
[.@vm-oracle8 build]$ hostnamectl
   Static hostname: vm-oracle8.4-devel
         Icon name: computer-vm
           Chassis: vm
        Machine ID: a94edfda0cd845359113bbc0c11883df
           Boot ID: 343594b8a4dd44ea8afa2e3b314c61f6
    Virtualization: oracle
  Operating System: Oracle Linux Server 8.4
       CPE OS Name: cpe:/o:oracle:linux:8:4:server
            Kernel: Linux 5.4.17-2102.201.3.el8uek.x86_64
      Architecture: x86-64
```

### XML configuration file

```xml
None
```

### Relevant log output

```shell
[.@vm-oracle8 build]$ sudo cmake --build . --target install
Consolidate compiler generated dependencies of target fastrtps
[  0%] Building CXX object src/cpp/CMakeFiles/fastrtps.dir/utils/SystemInfo.cpp.o
In file included from ./Fast-DDS/Fast-DDS/src/cpp/utils/SystemInfo.cpp:292:
./Fast-DDS/Fast-DDS/src/cpp/utils/threading/threading_pthread.ipp: Dans la fonction « void eprosima::configure_current_thread_scheduler(int, int) »:
./Fast-DDS/Fast-DDS/src/cpp/utils/threading/threading_pthread.ipp:100:48: error: « gettid » n'a pas été déclaré dans cette portée
             result = setpriority(PRIO_PROCESS, gettid(), sched_priority);
                                                ^~~~~~
./Fast-DDS/Fast-DDS/src/cpp/utils/threading/threading_pthread.ipp:100:48: note: alternatives suggérées: « getgid »
             result = setpriority(PRIO_PROCESS, gettid(), sched_priority);
                                                ^~~~~~
                                                getgid
gmake[2]: *** [src/cpp/CMakeFiles/fastrtps.dir/build.make:2848: src/cpp/CMakeFiles/fastrtps.dir/utils/SystemInfo.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:941: src/cpp/CMakeFiles/fastrtps.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
```

### Network traffic capture

None

**Comment by paulBismuthListen** [comment]
Hello, 

Actually it is caused by GLIC version gettid() being added on version 2.30 of GLIBC (which is not available on oracle 8.4):
https://man7.org/linux/man-pages/man2/gettid.2.html

Proposed patch (once issue is acepted):
```
#if defined(__GLIBC__) && ((__GLIBC__ > 2) || ((__GLIBC__ == 2) && (__GLIBC_MINOR__ <= 30)))
    #include <sys/syscall.h>
    #ifndef SYS_gettid
        #error "SYS_gettid unavailable on this system"
    #endif
    #define gettid() ((pid_t)syscall(SYS_gettid))
#endif
```

**Comment by JesusPoderoso** [comment]
Hi @paulBismuthListen, thanks for using Fast DDS.
Although Oracle is not a [supported platform](https://github.com/eProsima/Fast-DDS/blob/master/PLATFORM_SUPPORT.md), you can open a PR with the proposed patch so we can test it and merge it.
Thank you!

**Comment by EduPonz** [comment]
Should be solved by:

* #4753

Please feel free to reopen
