### ISSUE TITLE
Fastdds2.11.2  VS2022 Redefine error during compilation

### ISSUE THREAD

**Issue by Marquis3000** [eProsima/Fast-DDS#4244]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Complete compilation

### Current behavior

readString@Cdr@fastcdr@eprosima@@AEAAPEBDAEAI@Z) already defined in fastcdr-1.1.lib(fastcdr-1.1.dll)

### Steps to reproduce

![error](https://github.com/eProsima/Fast-DDS/assets/38600482/5586775a-3682-4fe5-ace8-e0641f1e87ca)

### Fast DDS version/commit

all version

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Intra-process

**Comment by JesusPoderoso** [comment]
Hi @Marquis3000, thanks for using Fast DDS.
Could you provide the Fast DDS and Fast CDR versions used to reproduce this linking error?

**Comment by Mario-DL** [comment]
I'm afraid that according to our [CONTRIBUTING.md](https://github.com/eProsima/Fast-DDS/blob/master/CONTRIBUTING.md) guidelines, I have to close this issue due to inactivity. Please, feel free to reopen it if necessary.
