### ISSUE TITLE
Writer crash when using topic type with struct as a key

### ISSUE THREAD

**Issue by Arwynor** [eProsima/Fast-DDS#4279]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

I should be able to define a type in IDL with a key which itself is a struct. When this IDL file is generated to CPP with fastddsgen and compiled into an application, the application should run without crashing.

### Current behavior

When using the x64 windows version of FastDDS 2.13.1 if I create a visual studio example app (using fastddsgen -example) for the ExampleTopic (described below), the publisher app will crash from an assertion in the DataReader whenever it has a subscription match with a DataReader.

The error message from the assert is as follows:
`Starting`
`ExampleModule::ExampleType DataWriter created.`
`ExampleModule::ExampleType DataWriter waiting for DataReaders.`
`DataWriter matched.`
`Assertion failed: offset_ == cdr_buffer_.begin() ? current_encoding_ == type_encoding : true, file C:\FIW\src\fastcdr\src\cpp\Cdr.cpp, line 3087`

### Steps to reproduce

- Generate, with fastddsgen, the following IDL with an example app

`#ifndef EXAMPLE__IDL`
`#define EXAMPLE__IDL`

`module ExampleModule`
`{`
 `   struct identifier`
 `   {`
 `       long first;`
 `       long second;`
 `   };`

`    @mutable`
`    struct ExampleType`
`    {`
`      @autoid @key identifier src;`
`      @autoid string metadata;`
`      @autoid short counter;`
`    };`

`};`

`#endif`

- compile the example app in visual studio
- run the test app as a subscriber
- run a second instance of the test app as a publisher

If I change the type of `src` key field in `ExampleType` in the idl above to be `long long`, everything works as expected.
Also, if I remove the `@key` bit, there is no crash, but obviously the topic isn't keyed.
It only crashes when the key is a structure.

### Fast DDS version/commit

windows 64-bit  FastDDS 2.13.1

### Platform/Architecture

Windows 10 Visual Studio 2019

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by Mario-DL** [comment]
Hi @Arwynor,

As the Dynamic Types refactor has been already introduced in the latest Fast DDS v3.0.0, we internally agreed to close all Dynamic-Types related issues. The corresponding `Fast DDS Gen` to regenerate the types is `Fast DDS Gen v4.0.0`.

We elaborated a [Migration guide](https://github.com/eProsima/Fast-DDS/blob/master/UPGRADING.md) to help with the upgrade process to this new major release.

Please, feel free to reopen it if the issue persists.
