### ISSUE TITLE
[SECURITY Error] WriterHistory cannot add the CacheChange_t -> Function on_process_handshake

### ISSUE THREAD

**Issue by fujitatomoya** [eProsima/Fast-DDS#4310]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

The `Security Error` message should not be printed.

### Current behavior

The `Security Error` message are printed many times.

### Steps to reproduce

1. Build with `cmake -DSECURITY=ON`.
2. Instantiate many `SecureHelloWorldExample` publishers and a subscriber. e.g `test.sh 150` below.

```bash
#!/bin/bash

echo "---------- starting $1 publishers with security (each participant)"
for i in $(seq 1 $1);
do
  ./Fast-DDS/build/examples/cpp/dds/SecureHelloWorldExample/DDSSecureHelloWorldExample publisher &
done

echo "---------- starting a subscriber with participant security"
./Fast-DDS/build/examples/cpp/dds/SecureHelloWorldExample/DDSSecureHelloWorldExample subscriber &

exit 0
```

3. The following error message come up.

```bash
2024-01-25 01:44:42.079 [SECURITY Error] WriterHistory cannot add the CacheChange_t -> Function on_process_handshake
2024-01-25 01:44:42.540 [SECURITY Error] WriterHistory cannot retrieve a CacheChange_t -> Function on_process_handshake
...
```

### Fast DDS version/commit

So far we confirmed, this can be observed with `master`, `V2.10.1`, and `V2.11.2`

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

UDPv4

### Additional context

https://github.com/eProsima/Fast-DDS/blob/7606b96087a8bcfa7d8fe4434cd5d2d253607dfc/src/cpp/rtps/security/SecurityManager.cpp#L1061-L1062

change `HistoryAttributes.maximumReservedCaches` into `1000` can suppress the above error. 

### Relevant log output

```shell
2024-01-25 01:44:42.079 [SECURITY Error] WriterHistory cannot add the CacheChange_t -> Function on_process_handshake
2024-01-25 01:44:42.540 [SECURITY Error] WriterHistory cannot retrieve a CacheChange_t -> Function on_process_handshake
...
```

**Comment by silvara** [comment]
I'm having the same problem. how do I fix it?

**Comment by fujitatomoya** [comment]
@silvara we ended up not using the security feature, so not sure what the best practice here.

> change HistoryAttributes.maximumReservedCaches into 1000 can suppress the above error.

did you try this? as far as we experienced, this can mitigate the error messages.

**Comment by MiguelCompany** [comment]
@silvara @fujitatomoya Please see #5386, which is addressing this issue, and will be backported to 2.14.x and 2.10.x

**Comment by fujitatomoya** [comment]
@MiguelCompany thanks for the info, i will take a look!

**Comment by fujitatomoya** [comment]
CC: @Barry-Xu-2018 this one is closed.
