### ISSUE TITLE
fastdds version compatability: not able to discover topics of different ros distribution inside a docker container ( host pc -foxy, docker-humble )

### ISSUE THREAD

**Issue by guni9191** [eProsima/Fast-DDS#4349]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

environment
- host pc: ubuntu 20.04, foxy installed
- docker container: ubuntu 22.04, humble installed
- both have default fastdds rmw

problem
- demo_nodes_cpp talker executed inside docker(humble)
- demo_nodes_cpp listener executed inside host pc(foxy)

expected behavior
- host pc should be able to discover topic or listen to what humble talker says\

### Current behavior

- it won't discover topic or echo its topic
- docker container with 20.04(foxy) works fine.

### Steps to reproduce

same as what is described in expected behavior

### Fast DDS version/commit

ros-humble-fastrtps is 2.6.7-1jammy.20240125.204216
ros-foxy-fastrtps is 2.1.4-1focal.20230527.035957

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Intra-process

**Comment by Mario-DL** [comment]
Hi @guni9191,

At a first guess, I would say that the issue could be related with the deployment. Could you check if launching the docker with `--net=host --ipc=host` makes any difference ?
