### ISSUE TITLE
incompatible type format in windows files

### ISSUE THREAD

**Issue by ionutnechita-intel** [eProsima/Fast-DDS#4355]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Compiling successfully

### Current behavior

Compiling failing

### Steps to reproduce

Rebuild from sources when using rolling ros branch and ubuntu 24.04 devel and kernel 6.8.0-rc3.
Task Fast-DDS is failing when using colcon build.

### Fast DDS version/commit

4d8c4893f (HEAD -> 2.13.x, origin/master, origin/HEAD, origin/3.0.x-devel, origin/2.13.x) Make DataWriters always send the key hash on keyed topics (#4238)

Branch: 2.13.x

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

Patch to resolve this:

```
diff --git a/src/cpp/statistics/types/monitorservice_typesv1.cxx b/src/cpp/statistics/types/monitorservice_typesv1.cxx
index 89494b401..82473aed0 100644
--- a/src/cpp/statistics/types/monitorservice_typesv1.cxx
+++ b/src/cpp/statistics/types/monitorservice_typesv1.cxx
@@ -58,22 +58,22 @@ struct FindTypeH;
 
 template<>
 struct FindTypeH<Size::UInt8> {
-    using type = std::uint8_t;
+    using type = std::wint_t;
 };
 
 template<>
 struct FindTypeH<Size::UInt16> {
-    using type = std::uint16_t;
+    using type = std::wint_t;
 };
 
 template<>
 struct FindTypeH<Size::UInt32> {
-    using type = std::uint32_t;
+    using type = std::wint_t;
 };
 
 template<>
 struct FindTypeH<Size::UInt64> {
-    using type = std::uint64_t;
+    using type = std::wint_t;
 };
 }
 
diff --git a/src/cpp/statistics/types/typesv1.cxx b/src/cpp/statistics/types/typesv1.cxx
index 80c55edc2..c64b84c39 100644
--- a/src/cpp/statistics/types/typesv1.cxx
+++ b/src/cpp/statistics/types/typesv1.cxx
@@ -58,22 +58,22 @@ struct FindTypeH;
 
 template<>
 struct FindTypeH<Size::UInt8> {
-    using type = std::uint8_t;
+    using type = std::wint_t;
 };
 
 template<>
 struct FindTypeH<Size::UInt16> {
-    using type = std::uint16_t;
+    using type = std::wint_t;
 };
 
 template<>
 struct FindTypeH<Size::UInt32> {
-    using type = std::uint32_t;
+    using type = std::wint_t;
 };
 
 template<>
 struct FindTypeH<Size::UInt64> {
-    using type = std::uint64_t;
+    using type = std::wint_t;
 };
 }
 

```

**Comment by MiguelCompany** [comment]
@ionutnechita-intel This should have been fixed by #4340. Could you check on your side?

**Comment by ionutnechita-intel** [comment]
Hi @MiguelCompany,

Will try today to recompile ROS2 rolling environment to check this.

**Comment by ionutnechita-intel** [comment]
Hi @MiguelCompany,

I tested again and this issue is solved.

Thanks for all.
