### ISSUE TITLE
如何跨网段进行通信

### ISSUE THREAD

**Issue by zhuyu1932** [eProsima/Fast-DDS#4395]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

使用示例程序，helloworld进行跨网段通信

### Current behavior

不仅无法匹配到发布者和订阅者，也无法匹配到域参与者

### Steps to reproduce

示例demo

### Fast DDS version/commit

2.13.1

### Platform/Architecture

Windows 10 Visual Studio 2019

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

x

**Comment by EduPonz** [comment]
Hi @zhuyu1932, first of all, thanks for using Fast DDS. Unfortunately, I have to close this issue as the expected language for it is English. Furthermore, I tentatively translated it into English and it seems the more appropriate forum for it would be [this one](https://github.com/eProsima/Fast-DDS/discussions/categories/q-a).
