### ISSUE TITLE
Partition permission are not enforced for remote participants [5342]

### ISSUE THREAD

**Issue by ruffsl** [eProsima/Fast-DDS#443]
Partition permissions are presently only checked when creating local data readers/writers, and are consequently skipped when checking *remote* readers/writers within the current default Access Control plugin implementation. This effectively nullifies any permission restrictions mandated in the remote participant's permission file, given it must be checked locally to ensure any access control policy is faithfully enforced.

The flowing is a minimal example where only the partition permission checks for creating local data readers/writers are disabled for testing, while leaving the `check_remote_datawriter` and `check_remote_datareader` fully intact. The secure publisher and subscriber are altered to connect over a common partition that is non existent in either of the participant's permissions, i.e. the only valid partition allowed by the permission policy is that of the empty string. Such altered fast-rtps publisher and subscriber while successfully connect with each other, while consequently fail to connect to other secure dds implementation (that happen to properly provisioned with the sufficient partition permission).

``` diff
diff --git a/examples/C++/SecureHelloWorldExample/HelloWorldPublisher.cpp b/examples/C++/SecureHelloWorldExample/HelloWorldPublisher.cpp
index 3aaed739..21f1abea 100644
--- a/examples/C++/SecureHelloWorldExample/HelloWorldPublisher.cpp
+++ b/examples/C++/SecureHelloWorldExample/HelloWorldPublisher.cpp
@@ -82,6 +82,7 @@ bool HelloWorldPublisher::init()
     Wparam.times.heartbeatPeriod.seconds = 2;
     Wparam.times.heartbeatPeriod.fraction = 200*1000*1000;
     Wparam.qos.m_reliability.kind = RELIABLE_RELIABILITY_QOS;
+    Wparam.qos.m_partition.push_back("foo");
 
     mp_publisher = Domain::createPublisher(mp_participant,Wparam,(PublisherListener*)&m_listener);
     if(mp_publisher == nullptr)
diff --git a/examples/C++/SecureHelloWorldExample/HelloWorldSubscriber.cpp b/examples/C++/SecureHelloWorldExample/HelloWorldSubscriber.cpp
index d5c77fb7..f35cae7c 100644
--- a/examples/C++/SecureHelloWorldExample/HelloWorldSubscriber.cpp
+++ b/examples/C++/SecureHelloWorldExample/HelloWorldSubscriber.cpp
@@ -75,6 +75,7 @@ bool HelloWorldSubscriber::init()
     Rparam.topic.resourceLimitsQos.max_samples = 50;
     Rparam.topic.resourceLimitsQos.allocated_samples = 20;
     Rparam.qos.m_reliability.kind = RELIABLE_RELIABILITY_QOS;
+    Rparam.qos.m_partition.push_back("foo");
 
     mp_subscriber = Domain::createSubscriber(mp_participant,Rparam,(SubscriberListener*)&m_listener);
 
diff --git a/src/cpp/security/accesscontrol/Permissions.cpp b/src/cpp/security/accesscontrol/Permissions.cpp
index 34b26949..3f7696e2 100644
--- a/src/cpp/security/accesscontrol/Permissions.cpp
+++ b/src/cpp/security/accesscontrol/Permissions.cpp
@@ -1091,7 +1091,7 @@ bool Permissions::check_create_datawriter(const PermissionsHandle& local_handle,
                     {
                         if (!is_partition_in_criterias(*partition_it, rule.publishes))
                         {
-                            returned_value = false;
+//                            returned_value = false;
                             exception = _SecurityException_(*partition_it + std::string(" partition not found in rule."));
                         }
                     }
@@ -1166,7 +1166,7 @@ bool Permissions::check_create_datareader(const PermissionsHandle& local_handle,
                     {
                         if (!is_partition_in_criterias(*partition_it, rule.subscribes))
                         {
-                            returned_value = false;
+//                            returned_value = false;
                             exception = _SecurityException_(*partition_it + std::string(" partition not found in rule."));
                         }
                     }
```

I tried patching the `WriterProxyData` `ReaderProxyData` classes to bubble up the necessary partition name context, thus allow for `is_partition_in_criterias` checks (presently absent) to be evokable in the `check_remote_datawriter` and `check_remote_datareader` callbacks, however I have yet to have time to comb through layers of generic types and call sites to find where such a context (the partition name connecting the remote participant) could be passed along.

As with https://github.com/eProsima/Fast-RTPS/issues/441 , this was uncovered during my development of a formal verification framework for the default DDS Security Access Control plugins and procedurally generated permission files.

**Comment by MiguelCompany** [comment]
I did some work on this (commit 1a7ea5436fb149413f886b0bfbf203397aedba2d) but I couldn't find a way to add a blackbox test for it
