### ISSUE TITLE
dynamic-type Segmentation fault, array with struct

### ISSUE THREAD

**Issue by kshang** [eProsima/Fast-DDS#4498]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

run well

### Current behavior

crash, Segmentation fault

### Steps to reproduce

I build the DynamicHelloworld example, and change the "helloworld_example_type_profile.xml" as blew:
<?xml version="1.0" encoding="UTF-8" ?>
<types xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles" >
    <type>
        <struct name="stxxhh">
            <member name="index11" type="uint32"/>
            <member name="index22" type="uint32"/>
        </struct>
    </type>
    <type>
        <struct name="HelloWorld">
            <member name="message" type="string"/>
            <member name="index" type="uint32"/>
            <member name="array" type="nonBasic" nonBasicTypeName="stxxhh" arrayDimensions="5,2"/>
        </struct>
    </type>
</types>

then run ./DDSDynamicHelloWorldExample publisher
then it crash and print Segmentation fault
I run DDS in ubuntu--18.04(X86)

### Fast DDS version/commit

fastdds-2.11.2

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### XML configuration file

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<types xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles" >
    <type>
        <struct name="stxxhh">
            <member name="index11" type="uint32"/>
            <member name="index22" type="uint32"/>
        </struct>
    </type>
    <type>
        <struct name="HelloWorld">
            <member name="message" type="string"/>
            <member name="index" type="uint32"/>
            <member name="array" type="nonBasic" nonBasicTypeName="stxxhh" arrayDimensions="5,2"/>
        </struct>
    </type>
</types>
```

**Comment by JLBuenoLopez-eProsima** [comment]
Thanks for the report @kshang 

Currently the XTypes feature which includes the dynamic language binding is being refactored. It is well known that the current API is unstable for complex types (for instance array of structures).

**Comment by Mario-DL** [comment]
As the Dynamic Types refactor has been already introduced in the latest Fast DDS v3.0.0, we internally agreed to close all Dynamic-Types related issues.
We elaborated a [Migration guide](https://github.com/eProsima/Fast-DDS/blob/master/UPGRADING.md) to help with the upgrade process to this new major release.

Please, feel free to reopen it if the issue persists.
