### ISSUE TITLE
Allow inconsistent about resource_limits QoS

### ISSUE THREAD

**Issue by mirusu400** [eProsima/Fast-DDS#4574]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

When setting max_instances = 0 in ResourceLimitsQosPolicy, return bad parameter or inform inconsistent QoS.

### Current behavior

Despite inconsistent QoS settings, datareader is created normally.

### Steps to reproduce

It is inconsistent if `max_samples < (max_instances * max_samples_per_instance)` . But when setting max_instances=0, Despite inconsistent QoS settings, datareader is created normally.

Insert the following code in HelloWorldSubscriber.cpp in HelloWorldExample.

```
// Creating DataReader QoS like this caused error.

    DataReaderQos rqos = DATAREADER_QOS_DEFAULT;
    rqos.reliability().kind = RELIABLE_RELIABILITY_QOS;

    rqos.resource_limits().max_samples = 9972;
    rqos.resource_limits().max_instances = 0;
    rqos.resource_limits().max_samples_per_instance = 9724;
```

[Fastdds-poc_src.zip](https://github.com/eProsima/Fast-DDS/files/14629922/Fastdds-poc_src.zip)
Here are sample project, simply test:
```cpp
mkdir build
cd build
cmake ..
make
./Fastdds_poc_src
```

Cause error like:
```
Create Topic
Create DataReader
Create DataWriter
Subscription matched	1
Publication matched	1
Data available
Received: 1_1_1 with index: 0
Write: 1_1_1 with index: 0
Data available
Received: 1_1_1 with index: 1
Write: 1_1_1 with index: 1
Data available
Received: 1_1_1 with index: 2
Write: 1_1_1 with index: 2
Data available
Received: 1_1_1 with index: 3
Write: 1_1_1 with index: 3
...
```

### Fast DDS version/commit

Fast-DDS `2.11.2`

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by JLBuenoLopez-eProsima** [comment]
@mirusu400 

Please, read about the [ResourceLimitsQosPolicy](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/core/policy/standardQosPolicies.html#resourcelimitsqospolicy) in Fast DDS documentation. It is clearly stated that

> Value 0 means infinite resources

Closing this ticket as invalid

**Comment by mirusu400** [comment]
@JLBuenoLopez-eProsima 

I got it, the documentation stated `0 means infinite recourses`.
However, in other QoS examples, such as [DurabilityServiceQosPolicy](DurabilityServiceQosPolicy) said that `-1` means unlimited length. Is there any reason that only `ResourceLimitsQosPolicy` have infinite resources as 0?

I've quick search about other DDS software, such as [CycloneDDS](https://cyclonedds.io/docs/cyclonedds/latest/api/qos.html) or [OpenDDS](http://scoreboard.ociweb.com/dds_doc_trunk_mosquito_linux_doxygen_u1/Doxygen/html/dds/a02670.html#0a99ba8ebc055de34a7e5ee9c867dfea), even said that -1 as infinite resource.

Considering compatibility or consistency with other vendors, why not modify the infinite value to -1?

**Comment by JesusPoderoso** [comment]
Hi @mirusu400 
On one hand. these QoS were designed to be taken into account when the assigned value is **greater** than `0`. That means both `0` and `-1` values are treated as unlimited.
I am creating a PR to apply that behavior in those conditions where it is not applied (as in the `max_instances` case).

On the other hand, these restrictions were internally discussed and decided to be displayed as warnings from now on, allowing the inconsistent configuration (not forcing the inconsistent user configuration) until the v3.0.0 release is performed (where API breaks will take place).
