### ISSUE TITLE
Allow inconsistent about DurabilityService QoS

### ISSUE THREAD

**Issue by mirusu400** [eProsima/Fast-DDS#4609]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

When setting history_depth = 0 or max_samples = 0 in DurabilityService QoS, return bad parameter or inform inconsistent QoS.

### Current behavior

Despite inconsistent QoS settings, datareader, datawriter and topic are created normally.

### Steps to reproduce

It is inconsistent if `max_samples < (max_instances * max_samples_per_instance)` . But when setting max_instances=0 or history_depth=0, Despite inconsistent QoS settings, datareader, datawriter and topic are created normally.

Insert the following code in HelloWorldSubscriber.cpp in HelloWorldExample.

```cpp
// Creating DataReader QoS like this caused error.

    DataReaderQos rqos = DATAREADER_QOS_DEFAULT;
		rqos.durability_service().history_depth = 0;
		rqos.durability_service().max_samples = 0;
		
		DataWriterQos rqos = DATAWRITER_QOS_DEFAULT;
		rqos.durability_service().history_depth = 0;
		rqos.durability_service().max_samples = 0;
		
		TopicQoS tqos = TOPIC_QOS_DEFAULT;
		tqos.durability_service().history_depth = 0;
		tqos.durability_service().max_samples = 0;
```

### Fast DDS version/commit

`Fast-DDS v2.11.2`, but I think it's going to happen in the latest version, too

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Default configuration, UDPv4 & SHM, Intra-process

### Additional context

This issue is similar with #4574

**Comment by JesusPoderoso** [comment]
Hi @mirusu400 
As discussed [in this thread](https://github.com/eProsima/Fast-DDS/issues/4574#issuecomment-2018084790), these restrictions are displayed as warnings from now on until Fast DDS v3.0.0 is released.
