### ISSUE TITLE
SHM port OpenMode compatibility is not always enforced

### ISSUE THREAD

**Issue by MiguelCompany** [eProsima/Fast-DDS#4634]
### Discussed in https://github.com/eProsima/Fast-DDS/discussions/4504

<div type='discussions-op-text'>

<sup>Originally posted by **wddpfx** March  5, 2024</sup>
The OpenMode defined as that:
![image_24](https://github.com/eProsima/Fast-DDS/assets/19266720/e6024995-8a68-44c8-8384-a24c7e7f5671)

But when we open a port , it will call function "open_port_internal" and annotation say "If the port doesn't exist in the system a port with port_id is created。otherwise the existing port is opened.“

But if the port is existing,with the openmode is ReadShared,. Now we open as ReadExclusive. So port_node->is_opened_read_exclusive become TRUE from FALSE. But "ReadShared (multiple listeners / multiple writers): Once a port is opened ReadShared cannot be opened ReadExclusive.", now  a port is opened ReadShared we can open it ReadExclusive successful. Why?
![image_25](https://github.com/eProsima/Fast-DDS/assets/19266720/068ae469-1016-4356-9922-16e12712eefc)
</div>

**Comment by MiguelCompany** [comment]
@wddpfx Thank you for finding a bug in Fast DDS. I've just open #4635 which fixes the issue.

**Comment by wddpfx** [comment]
@MiguelCompany How about this question:https://github.com/eProsima/Fast-DDS/discussions/4505
