### ISSUE TITLE
Parameter pack could not be expanded within '...'

### ISSUE THREAD

**Issue by MengWWWWW** [eProsima/Fast-DDS#4667]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

When I was installing fastdds according to the reference manual, the last step was cmake - build-- Target install error, Fast DDS/src/cpp/utils/threading. hpp: 98:57: Error: The parameter package failed to find '...' Unfolded in: set_name_to_current_thread (name, args...);

### Current behavior

I have tried updating the gcc compiler, but the issue has not been resolved. I am using Centos7 system.

### Steps to reproduce

Consolidate compiler generated dependencies of target fasttps
[0%] Building CXX object src/cpp/CMakeFiles/fasttps. dir/fastdds/log/Log.cpp.o
In file included from/home/mw/desktop/Docker work/Fast DDS/thirdparty/filewatch/FileWatch. hpp: 29:0,
From/home/mw/desktop/Docker work/Fast DDS/src/cpp/utilities/SystemInfo. hpp: 34,
From/home/ww/desktop/Docker work/Fast DDS/src/cpp/fastdds/log/log. cpp: 28:
/Home/mwDesktop/Docker Work/Fast DDS/src/cpp/utils/threading. hpp: In the lambda function:
/Home/mwd/desktop/Docker work/Fast DDS/src/cpp/utils/threading. hpp: 98:57: Error: The parameter package could not be found in '...' Unfolded in:
Setname_to_current_thread (name, args...);
^
/Home/mwDesktop/Docker Work/Fast DDS/src/cpp/utils/threading. hpp: 98:57: Note: 'args'
/Home/mwd/desktop/Docker work/Fast DDS/src/cpp/utils/threading. hpp: 98:62: Error: Unfold style 'args' does not include parameter packages
Setname_to_current_thread (name, args...);
^
In file included from/home/mwdesktop/Docker work/Fast DDS/src/cpp/utils/SystemInfo. hpp: 34:0,
From/home/ww/desktop/Docker work/Fast DDS/src/cpp/fastdds/log/log. cpp: 28:
/Home/ww/Desktop/Docker work/Fast DDS/hirdparty/filewatch/FileWatch. hpp: In the global domain:
/Home/mwd/desktop/Docker work/Fast DDS/hirdparty/filewatch/FileWatch. hpp: 146:60: Warning: Convert '(1024 * 256)' from 'int' to a narrower type 'const size_t {aka const long unsigned int}' within {}
Static constexpr std:: size_t buffer_size={1024 * 256};
^
In file included from/home/mw/desktop/Docker work/Fast DDS/thirdparty/filewatch/FileWatch. hpp: 29:0,
From/home/mw/desktop/Docker work/Fast DDS/src/cpp/utilities/SystemInfo. hpp: 34,
From/home/ww/desktop/Docker work/Fast DDS/src/cpp/fastdds/log/log. cpp: 28:
/Home/mwd/desktop/Docker work/Fast DDS/src/cpp/utils/threading. hpp: In instantiation of 'struct eprosima:: createthread (Functional, const eprosima:: fastdds:: rtps: ThreadSettings&, const char *, Args...) [with Functional=eprosima: fastdds:: dds:: detail: LogResources:: StartThread(): __ lambda13; Args={}]: __ lambda13; Args={} mbda0':
/Home/mwd/desktop/docker work/Fast DDS/src/cpp/utils/threading. hpp: 101:21: required from 'eprosima:: thread eprosima:: create_thread' (Functional, const eprosima:: fastdds:: rtps:: ThreadSettings&, const char *, Args...) [with Functional=eprosima:: fastdds:: dds:: detail: LogResources:: StartThread(): __ lambda13; Args...)={}] '
/Home/mwd/desktop/docker work/Fast DDS/src/cpp/fastdds/log/Log. cpp: 266:93: required from here
/Home/mwd/desktop/Docker work/Fast DDS/src/cpp/utils/threading. hpp: 100:24: Error: Using invalid field 'eprosima:: create_thread (Functional, const eprosima:: fastdds:: rtps: ThreadSettings&, const char *, Args...):: __ lambda0:: __ args'
Func();
^
/Home/mwd/desktop/docker work/Fast DDS/src/cpp/utils/threading. hpp: In the function 'eprosima:: thread eprosima:: create_thread (Functor, const eprosima:: fastdds:: rtps:: ThreadSettings&, const char *, Args...)' [with Functor=eprosima:: fastdds:: dds:: detail: LogResources:: StartThread(): __ lambda13; Args={}]:
/Home/mwd/desktop/Docker work/Fast DDS/src/cpp/utils/threading. hpp: 102:1: Warning: Control flow reached the end of a function with a return value [- Wreturn type]
}

### Fast DDS version/commit

master

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by elianalf** [comment]
Hi @MengWWWWW, thanks for using Fast DDS.
It's possible that there might be a problem with the syntax or usage of the variadic arguments in GCC versions in CentOS 7. Unfortunately, we currently do not support CentOS 7. Which is your current version of GCC? You might want to have a look to [all the versions and OS](https://fast-dds.docs.eprosima.com/en/latest/notes/versions.html#build-system-dependencies) we currently support.
