### ISSUE TITLE
Hi, I got a compile error and I don't know how to solve it. Could you help me?

### ISSUE THREAD

**Issue by yuzu-ogura** [eProsima/Fast-DDS#4741]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

pass

### Current behavior

`/home/liuyu/Cross-Compile/Fast-DDS-master/src/cpp/rtps/transport/TCPAcceptorBasic.cpp:60:61: error: no viable conversion from 'const std::error_code' to 'const boost::system::error_code'
                    parent->SocketAccepted(socket, locator, error);
                                                            ^~~~~
/home/liuyu/wrsdk-vxworks7-qemu/vxsdk/host/x86_64-linux/bin/../../../sysroot/usr/h/public/boost/system/detail/error_code.hpp:38:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'const std::error_code' to 'const boost::system::error_code &' for 1st argument
class error_code
      ^
/home/liuyu/wrsdk-vxworks7-qemu/vxsdk/host/x86_64-linux/bin/../../../sysroot/usr/h/public/boost/system/detail/error_code.hpp:38:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'const std::error_code' to 'boost::system::error_code &&' for 1st argument
/home/liuyu/wrsdk-vxworks7-qemu/vxsdk/host/x86_64-linux/bin/../../../sysroot/usr/h/public/boost/system/detail/error_code.hpp:60:58: note: candidate template ignored: requirement 'is_error_code_enum<std::error_code>::value' was not satisfied [with ErrorCodeEnum = std::error_code]
    template<class ErrorCodeEnum> BOOST_SYSTEM_CONSTEXPR error_code( ErrorCodeEnum e,
                                                         ^
/home/liuyu/Cross-Compile/Fast-DDS-master/src/cpp/rtps/transport/TCPTransportInterface.h:430:46: note: passing argument to parameter 'error' here
            const boost::system::error_code& error);
                                             ^
1 error generated.`

### Steps to reproduce

/

### Fast DDS version/commit

version: 2.14.x

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by JesusPoderoso** [comment]
Closing this issue as duplicated of #4743
