### ISSUE TITLE
Process throws "std::system_error" exception and crashes after time skip

### ISSUE THREAD

**Issue by xjzer** [eProsima/Fast-DDS#4827]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

The process is running normally after the time has been adjusted backward by one hour

### Current behavior

After an hour of backward time adjustments, the process throws a "std::system_error" exception and crashes.

### Steps to reproduce

Adjusts the system time backward by a few seconds/minutes/hours after the process starts.

### Fast DDS version/commit

2.13.3

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

UDPv4

### Additional context

1. On crash, the standard error output is as follows
```
terminate called after throwing an instance of 'std::system_error'
what():  Resource deadlock avoided
```
2. backtrace
![backtrace](https://img2.imgtp.com/2024/05/22/7EFtig3M.png)

**Comment by Mario-DL** [comment]
Hi @xjzer 
The [OMG DDS Specification](https://www.omg.org/spec/DDS/1.4/About-DDS) does not impose any specific behavior for system time managing, simply that clocks among the different systems should be _sufficiently synchronized_. That said, online tweaking of system's time is not a good practice and can lead to a potential misbehavior of the library, leaving the issue out of the scope of the middleware. It is for that reason that I am closing the issue.
