### ISSUE TITLE
TCP channel suddenly disconnected causing writer deadlock

### ISSUE THREAD

**Issue by wangzm-R** [eProsima/Fast-DDS#4940]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

When a subscriber TCP channel is suddenly disconnected, it does not block the normal release data of the publisher;

### Current behavior

If a publisher and two subscribers are on unused hardware, and a subscriber's machine suddenly power off, the publisher will be blocked after 1min; once the subscriber's device is activated again, the publisher will return to normal;（use static ip）

### Steps to reproduce

use publisher and subscriber;

### Fast DDS version/commit

fastdds2.14.0
fastdds2.11.2

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

TCPv4

**Comment by wangzm-R** [comment]
![335961386-ae2b8794-d6f2-47e7-b56e-45a00ece7290](https://github.com/eProsima/Fast-DDS/assets/64530666/95672314-f552-4479-88f2-ea7569db6082)

deadlock location;

**Comment by elianalf** [comment]
Hi @wangzm-R,
Thank you for using Fast DDS.

In [Fast DDS 2.14.1](https://github.com/eProsima/Fast-DDS/tree/2.14.1) there are many improvements related to TCP and this issue might be fixed in the latest version. Can you try and let us know if it's fixed?

**Comment by JesusPoderoso** [comment]
I closing this thread for inactivity according to Fast DDS [contributing guidelines](https://github.com/eProsima/Fast-DDS/blob/master/CONTRIBUTING.md#issues).
Please, feel free to reopen it if considered

**Comment by wangzm-R** [comment]
The problem with using the latest version is still there;

**Comment by wangzm-R** [comment]
The problem with using the latest version is still there;
use examples delivery_mechanisms;

During normal communication, if the network cable of UbuntuA and UbuntuB is directly removed, the publisher and subscriberSubscriberApp_1 will be blocked (the problem of SubscriberApp_1 blocking cannot be solved even with asynchronous sending)

<img width="1608" height="739" alt="Image" src="https://github.com/user-attachments/assets/ce669ae1-282e-4f7a-bd67-960e07798692" />

**Comment by wangzm-R** [comment]
expected : if a device is suddenly powered off or disconnected(LAN disconnection), other normal publishing and subscribing will not be affected

**Comment by chunyisong** [comment]
@wangzm-R please reopen the issue

**Comment by wangzm-R** [comment]
I do not have permissions
