### ISSUE TITLE
Where is the definition of `TypeObjectFactory` in Fast-DDS Version 2?

### ISSUE THREAD

**Issue by jiapei100** [eProsima/Fast-DDS#5005]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

Looking forward to the definition of `TypeObjectFactory` inside **Fast-DDS**, without resorting to the abandoned **FastRTPS**.

### Current behavior

N/A

### Steps to reproduce

Simply search for the definition of `TypeObjectFactory`.

### Fast DDS version/commit

[2](https://github.com/eProsima/Fast-DDS/commit/d3ca40cbce231c4bdb4fc88a4b3911afaaae4f6f)

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

Ubuntu 24.04

**Comment by JesusPoderoso** [comment]
Hi @jiapei100, thanks for using Fast DDS.
`TypeObjectFactory` is still part of *Fast DDS v2*, but will not be in *v3*.
Please, ensure you are using a *Fast DDS* branch or version that belongs to *v2* (as [*2.14.x*](https://github.com/eProsima/Fast-DDS/tree/2.14.x) branch or the latest release [*v2.14.2*](https://github.com/eProsima/Fast-DDS/releases/tag/v2.14.2)).
I shall assume you are using *master*, which is undergoing major changes entailing API breaks until v3.0.0  is released (refer to our [readme](https://github.com/eProsima/Fast-DDS/blob/master/README.md) for related information).
