### ISSUE TITLE
Fast-DDS make error: static assertion failed

### ISSUE THREAD

**Issue by ksriram-bilab** [eProsima/Fast-DDS#5150]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

The expected behavior is for make to get to something like [100%] Built target fastdds, without this static assertion fail.

### Current behavior

Seeing the following static assertion failure on my arm64 machine:
-- Build files have been written to: /home/ksriram/ros2_foxy/src/eProsima/Fast-DDS/build
ksriram@tegra-ubuntu:~/ros2_foxy/src/eProsima/Fast-DDS/build$ make
[  1%] Building CXX object src/cpp/CMakeFiles/fastdds.dir/fastdds/topic/DDSSQLFilter/DDSFilterCompoundCondition.cpp.o
[  1%] Building CXX object src/cpp/CMakeFiles/fastdds.dir/fastdds/topic/DDSSQLFilter/DDSFilterExpression.cpp.o
In file included from /usr/include/c++/9/memory:65,
                 from /home/ksriram/ros2_foxy/src/eProsima/Fast-DDS/src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterExpression.hpp:23,
                 from /home/ksriram/ros2_foxy/src/eProsima/Fast-DDS/src/cpp/fastdds/topic/DDSSQLFilter/DDSFilterExpression.cpp:18:
/usr/include/c++/9/bits/stl_uninitialized.h: In instantiation of '_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = __gnu_cxx::__normal_iterator<const eprosima::fastdds::dds::AnnotationDescriptorImpl*, std::vector<eprosima::fastdds::dds::AnnotationDescriptorImpl> >; _ForwardIterator = eprosima::fastdds::dds::AnnotationDescriptorImpl*]':
/usr/include/c++/9/bits/stl_uninitialized.h:307:37:   required from '_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = __gnu_cxx::__normal_iterator<const eprosima::fastdds::dds::AnnotationDescriptorImpl*, std::vector<eprosima::fastdds::dds::AnnotationDescriptorImpl> >; _ForwardIterator = eprosima::fastdds::dds::AnnotationDescriptorImpl*; _Tp = eprosima::fastdds::dds::AnnotationDescriptorImpl]'
/usr/include/c++/9/bits/stl_vector.h:555:31:   required from 'std::vector<_Tp, _Alloc>::vector(const std::vector<_Tp, _Alloc>&) [with _Tp = eprosima::fastdds::dds::AnnotationDescriptorImpl; _Alloc = std::allocator<eprosima::fastdds::dds::AnnotationDescriptorImpl>]'
/home/ksriram/ros2_foxy/src/eProsima/Fast-DDS/src/cpp/fastdds/topic/DDSSQLFilter/../../xtypes/dynamic_types/DynamicTypeMemberImpl.hpp:52:16:   required from here
/usr/include/c++/9/bits/stl_uninitialized.h:127:72: error: static assertion failed: result type must be constructible from value type of input range
  127 |       static_assert(is_constructible<_ValueType2, decltype(*__first)>::value,
      |                                                                        ^~~~~
make[2]: *** [src/cpp/CMakeFiles/fastdds.dir/build.make:90: src/cpp/CMakeFiles/fastdds.dir/fastdds/topic/DDSSQLFilter/DDSFilterExpression.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:976: src/cpp/CMakeFiles/fastdds.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

### Steps to reproduce

cd ~/ros2_foxy/src/eProsima/Fast-DDS
rm -rf build
mkdir build
cd build
cmake .. -DCMAKE_CXX_STANDARD=14 -DCMAKE_BUILD_TYPE=Release
make
----------------------------------------fails here----------------------------------------------------
Step after:
sudo make install

### Fast DDS version/commit

master branch,
Commit hash: 817b14a017220a0c2b6fa1a562f17a4a7bc0fc39
Release tag: v2.10.1-rc1-470-g817b14a01

### Platform/Architecture

Ubuntu Focal 20.04 arm64

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by JesusPoderoso** [comment]
Hi @ksriram-bilab, thanks for using Fast DDS.
GCC 9, the default version distributed with Ubuntu 20.04, is no longer supported in master (upcoming v3.0.0 soon). Sorry for the inconvenience.

**Comment by paxifaer** [comment]
> Hi @ksriram-bilab, thanks for using Fast DDS. GCC 9, the default version distributed with Ubuntu 20.04, is no longer supported in master (upcoming v3.0.0 soon). Sorry for the inconvenience.

Does v3.0.0 will fix it or I can commit my code to fix it?

**Comment by JesusPoderoso** [comment]
No, v3.0.0 won't fix it. We are open to contributions @paxifaer, thanks!
