### ISSUE TITLE
/usr/local/include/fastcdr/CdrSizeCalculator.hpp:214:5: error: ‘TEMPLATE_SPEC’ does not name a type

### ISSUE THREAD

**Issue by noone3001** [eProsima/Fast-DDS#5168]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

build ok

### Current behavior

Fast-CDR build ok, when build Fast-DDS, error came out 
vm2004:~/Fast-DDS/Fast-DDS/build$ cmake --build . --target install

"/usr/local/include/fastcdr/CdrSizeCalculator.hpp:214:5: error: ‘TEMPLATE_SPEC’ does not name a type"

### Steps to reproduce

cd ~/Fast-DDS
git clone https://github.com/eProsima/Fast-DDS.git
mkdir Fast-DDS/build
cd Fast-DDS/build
cmake ..  -DCMAKE_INSTALL_PREFIX=~/Fast-DDS/install
cmake --build . --target install

### Fast DDS version/commit

master latest, 

### Platform/Architecture

Ubuntu Focal 20.04 arm64

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by JesusPoderoso** [comment]
Hi @noone3001, thanks for using Fast DDS.
Several changes have been introduced in current `master` branch, related to near Fast DDS v3.0.0 release.
For that reason (new major version), the [platform support](https://github.com/eProsima/Fast-DDS/blob/master/PLATFORM_SUPPORT.md#platforms) has been updated for Ubuntu cases (24.04 & 22.04).
Therefore, the current `master` branch is not supported in Ubuntu 20.04.
You may consider contacting [commercials support](https://github.com/eProsima/Fast-DDS/tree/master#getting-help) for premium support options, or use our latest released version [v2.14.3](https://github.com/eProsima/Fast-DDS/releases/tag/v2.14.3).

**Comment by noone3001** [comment]
ooo，thks for your massage. i'll try your advice



---- Replied Message ----
| From | Jesús ***@***.***> |
| Date | 08/21/2024 17:57 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [eProsima/Fast-DDS] /usr/local/include/fastcdr/CdrSizeCalculator.hpp:214:5: error: ‘TEMPLATE_SPEC’ does not name a type (Issue #5168) |

Hi @noone3001, thanks for using Fast DDS.
Several changes have been introduced in current master branch, related to near Fast DDS v3.0.0 release.
For that reason (new major version), the platform support has been updated for Ubuntu cases (24.04 & 22.04).
Therefore, the current master branch is not supported in Ubuntu 20.04.
You may consider contacting commercials support for premium support options, or use our latest released version v2.14.3.

**Comment by noone3001** [comment]
hi，if I want to install gradle manually for fastddsgen ,which version of gradle shoud I install? in ubuntu 20.04



---- Replied Message ----
| From | Jesús ***@***.***> |
| Date | 08/21/2024 17:57 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [eProsima/Fast-DDS] /usr/local/include/fastcdr/CdrSizeCalculator.hpp:214:5: error: ‘TEMPLATE_SPEC’ does not name a type (Issue #5168) |

Hi @noone3001, thanks for using Fast DDS.
Several changes have been introduced in current master branch, related to near Fast DDS v3.0.0 release.
For that reason (new major version), the platform support has been updated for Ubuntu cases (24.04 & 22.04).
Therefore, the current master branch is not supported in Ubuntu 20.04.
You may consider contacting commercials support for premium support options, or use our latest released version v2.14.3.

**Comment by MiguelCompany** [comment]
@noone3001 Just use the provided gradle wrapper. So run `./gradlew assemble` from the root of the cloned repo.

See [the docs](https://fast-dds.docs.eprosima.com/en/stable/installation/sources/sources_linux.html#fast-dds-gen-installation) for full details.
