### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by paxifaer** [eProsima/Fast-DDS#5170]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

DDS version : master 
CDR version:2.3
I also try in a  new environment,but it make error too.

### Current behavior

![Uploading image.png…]()

### Steps to reproduce

make -j8

### Fast DDS version/commit

bbb4c58ae448b0452093ea502e6d73f256f0691e

### Platform/Architecture

Ubuntu Focal 20.04 amd64, Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by JesusPoderoso** [comment]
Hi @paxifaer, thanks for using Fast DDS.
Several changes have been introduced in current `master` branch, related to the near Fast DDS v3.0.0 release.
For that reason (new major version), the [platform support](https://github.com/eProsima/Fast-DDS/blob/master/PLATFORM_SUPPORT.md#platforms) has been updated for Ubuntu cases (24.04 & 22.04).
Therefore, the current `master` branch is not supported in Ubuntu 20.04.
You may consider contacting [commercials support](https://github.com/eProsima/Fast-DDS/tree/master#getting-help) for premium support options, or use our latest released version [v2.14.3](https://github.com/eProsima/Fast-DDS/releases/tag/v2.14.3).

**Comment by paxifaer** [comment]
> 你好@paxifaer感谢您使用 Fast DDS。 当前分支中引入了一些`master`与即将发布的 Fast DDS v3.0.0 相关的更改。 出于这个原因（新的主要版本），[平台支持](https://github.com/eProsima/Fast-DDS/blob/master/PLATFORM_SUPPORT.md#platforms)已针对 Ubuntu 案例（24.04 和 22.04）进行了更新。 因此，当前`master`分支不支持 Ubuntu 20.04。 您可以考虑联系[商业支持](https://github.com/eProsima/Fast-DDS/tree/master#getting-help)以获得高级支持选项，或者使用我们最新发布的版本[v2.14.3](https://github.com/eProsima/Fast-DDS/releases/tag/v2.14.3)。

先别关闭，我已经把我修复的代码提交上去。你们开发人员合并我的代码就可以了
