### ISSUE TITLE
Wouldn't ‎DiscoveryDataBase::update second parameter (std::string topic_name) be more appropriate to use const reference?

### ISSUE THREAD

**Issue by chunyisong** [eProsima/Fast-DDS#5175]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

bool update(CacheChange_t* change, const std::string& topic_name);

### Current behavior

bool update(CacheChange_t* change, std::string topic_name);
### Steps to reproduce

[bool update(CacheChange_t* change, std::string topic_name);](https://github.com/eProsima/Fast-DDS/blob/c53cd0a425e6f5483fbd971eb584b4360c306891/src/cpp/rtps/builtin/discovery/database/DiscoveryDataBase.hpp#L133)

### Fast DDS version/commit

v3.0.0

### Platform/Architecture

Ubuntu Focal 20.04 amd64, Windows 10 Visual Studio 2019

### Transport layer

Default configuration, UDPv4 & SHM, TCPv4, Shared Memory Transport (SHM)

**Comment by JesusPoderoso** [comment]
Hi @chunyisong, thanks for your report.
I've opened a PR with the fix
- https://github.com/eProsima/Fast-DDS/pull/5179
