### ISSUE TITLE
When I create multiple publisher topics under one Participant to send data, on the subscriber side, after receiving and establishing a connection with one topic, it no longer detects the subsequent topics. I believe this is an issue.

### ISSUE THREAD

**Issue by lobmoo** [eProsima/Fast-DDS#5260]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

When I create multiple publisher topics under one Participant to send data, on the subscriber side, after receiving and establishing a connection with one topic, it no longer detects the subsequent topics. I believe this is an issue.

### Current behavior

When I create multiple publisher topics under one Participant to send data, on the subscriber side, after receiving and establishing a connection with one topic, it no longer detects the subsequent topics. I believe this is an issue.

### Steps to reproduce

When I create multiple publisher topics under one Participant to send data, on the subscriber side, after receiving and establishing a connection with one topic, it no longer detects the subsequent topics. I believe this is an issue.

### Fast DDS version/commit

When I create multiple publisher topics under one Participant to send data, on the subscriber side, after receiving and establishing a connection with one topic, it no longer detects the subsequent topics. I believe this is an issue.

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by JesusPoderoso** [comment]
Hi @lobmoo, thanks for using Fast DDS
Which Fast DDS version are you using? Are you creating one [DataWriter](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/publisher/dataWriter/dataWriter.html) per topic and one [DataReader](https://fast-dds.docs.eprosima.com/en/latest/fastdds/dds_layer/subscriber/dataReader/dataReader.html) per topic?
Could you provide a reproducer to replicate the issue?

**Comment by lobmoo** [comment]
Hello, thank you for your response. I've done some additional testing over the past couple of days. Previously, I did indeed use a single writer for multiple topics, but I created multiple readers. Currently, I've found that when I create a publisher inside the thread function of a process and start the singleton test, the service cannot be discovered. However, when I run them separately, it works fine.

![image](https://github.com/user-attachments/assets/bff41289-f0f8-442a-a79b-40976c8eafae)
In the situation mentioned above, with a delay, the data can be received, but if the delay is removed, it remains blocked. As I understand it, DDS should be decentralized and not have a specific startup order.
[DynamicHelloWorldExample.zip](https://github.com/user-attachments/files/17158459/DynamicHelloWorldExample.zip)

**Comment by JesusPoderoso** [comment]
Hi @lobmoo, this is a known issue in Fast DDS v2.
Latest Fast DDS v3 has a complete refactor of dynamic types (XTypes 1.3), so we encourage you to try this new version.
Dynamic types issues in v2 are not planned to be fixed.

**Comment by lobmoo** [comment]
"Version 3.0 does not have a demo with dynamic data types. Could you provide an example for usage?"  thinks

**Comment by JesusPoderoso** [comment]
> Version 3.0 does not have a demo with dynamic data types. Could you provide an example for usage?

Check the [XTypes example](https://github.com/eProsima/Fast-DDS/tree/master/examples/cpp/xtypes).
Examples have been refactored, take a look at the [migration guide](https://github.com/eProsima/Fast-DDS/blob/master/UPGRADING.md#step-9-refactor-examples) from Fast DDS v2 to Fast DDS v3 for more information.
