### ISSUE TITLE
FastDDS 3.1.0 cannot communicate with ROS2

### ISSUE THREAD

**Issue by p-zzg** [eProsima/Fast-DDS#5343]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

FastDDS 3.1.0 communicate with ROS2 (Ubuntu20.04 foxy)

### Current behavior

FastDDS 3.1.0 cannot communicate with ROS2

### Steps to reproduce

FastDDS 3.1.0 Create Topic release subscription, but ROS2 Topic List cannot find TOPIC

### Fast DDS version/commit

3.1.0/master

### Platform/Architecture

Ubuntu Focal 20.04 amd64

### Transport layer

Default configuration, UDPv4 & SHM

**Comment by Heyangq** [comment]
The 2.14.0 I used before 3.1.0 can communicate with ROS2. Is it a version question?

**Comment by Mario-DL** [comment]
Hi @p-zzg,
Thanks for using Fast DDS.
ROS 2 Foxy was attached to `Fast DDS 2.1.x` which reached its EOL in May 2023 (see our [RELEASE_SUPPORT](https://github.com/eProsima/Fast-DDS/blob/master/RELEASE_SUPPORT.md)) .
There is no guarantee of interoperatiblity between ROS 2 major releases. However, there should be between any pair of `Fast DDS` [currently supported branches](https://github.com/eProsima/Fast-DDS/blob/master/RELEASE_SUPPORT.md)

**Comment by Mario-DL** [comment]
Additionally, you should be aware that using SHM between `Fast DDS v2` and `Fast DDS v3` will not work since file segments name have changed.

If you need further support please please contact [out commercial support](https://github.com/eProsima/Fast-DDS?tab=readme-ov-file#commercial-support)

**Comment by p-zzg** [comment]
> Additionally, you should be aware that using SHM between `Fast DDS v2` and `Fast DDS v3` will not work since file segments name have changed.
> 
> If you need further support please please contact [our commercial support](https://github.com/eProsima/Fast-DDS?tab=readme-ov-file#commercial-support)

I also tried to close the shared memory, only UDP
But ROS2 still cannot be found
Did you find that the agreement has changed?

**Comment by p-zzg** [comment]
> Additionally, you should be aware that using SHM between `Fast DDS v2` and `Fast DDS v3` will not work since file segments name have changed.
> 
> If you need further support please please contact [our commercial support](https://github.com/eProsima/Fast-DDS?tab=readme-ov-file#commercial-support)

The current problem is that TOPIC cannot be discovered, not the data cannot be subscribed to
Topic found that the protocol should be a network protocol, not SHM
Is it a TOPIC discovery agreement?

**Comment by JesusPoderoso** [comment]
Hi @p-zzg,

> I also tried to close the shared memory, only UDP
> But ROS2 still cannot be found
> Did you find that the agreement has changed?

As @Mario-DL has mentioned, ROS 2 Foxy is EOL, and interoperability between ROS 2 major releases is not guaranteed.
In versions that came later than Foxy, compatibility with the discovery info topic was broken.

If you are looking for a custom solution, please contact our commercial support support@eprosima.com.
