### ISSUE TITLE
ROS2 nodes can't communicate between Docker containers

### ISSUE THREAD

**Issue by mmcza** [eProsima/Fast-DDS#5396]
### Is there an already existing issue for this?

- [X] I have searched the existing issues

### Expected behavior

ROS2 nodes can subscribe to ROS2 nodes running in another docker containers or on host

### Current behavior

ROS2 nodes that run in a container are able to list topics created by ROS2 nodes run on host/another container, but are not able to subscribe to them. The same applies to host if a node is running inside a container.

### Steps to reproduce

With a running Docker container from a ROS2 Humble image you can run any node or create a publisher like this:
```
ros2 topic pub /test std_msgs/msg/Bool
```
In another Docker container (not another terminal with the same image but a completely separate one) you should be able to see the topic after running
```
ros2 topic list
```
but 
```
ros2 topic echo /test
```
will not return any messages

### Fast DDS version/commit

ros-humble-fastrtps                                   2.6.8-1jammy.20240728.201342
ros-humble-fastrtps-cmake-module                      2.2.2-2jammy.20240728.202329
ros-humble-rmw-fastrtps-cpp                           6.2.7-1jammy.20240728.212513
ros-humble-rmw-fastrtps-shared-cpp                    6.2.7-1jammy.20240728.211440
ros-humble-rosidl-typesupport-fastrtps-c              2.2.2-2jammy.20240728.210059
ros-humble-rosidl-typesupport-fastrtps-cpp            2.2.2-2jammy.20240728.205803

### Platform/Architecture

Other. Please specify in Additional context section.

### Transport layer

Default configuration, UDPv4 & SHM

### Additional context

OS - Ubuntu 22.04
ROS2 Humble

I discovered the issue around a week ago, as 2 weeks ago everything was working properly. Additionally it was tested on another computers, where the same issue was experienced.

**Comment by rsanchez15** [comment]
Hi @mmcza 

I've just tested what you explained and it worked for me. Could you please send us the exact command you are using for running the Docker containers?

Could you also run the following commands and tell me what you see: 

- Terminal 1
  ```
  docker run -it --rm ros:humble
  ros2 topic pub /test std_msgs/msg/Bool
  ```

- Terminal 2 
  ```
  docker run -it --rm ros:humble
  ros2 topic list
  ros2 topic echo /test
  ```

**Comment by rsanchez15** [comment]
The problem is due to the SHM transport. When you launch a Docker with --net=host and --ipc=host configuration, the publisher and subscriber detect that they are on the same host and try to use SHM. This is due to how the calculation of SHM usage was done until now. In addition, SHM uses the `/dev/shm` directory, which in this case is being attempted to be shared by users who have different permissions: `root in the case of Docker and `$USER` in the case of the host. This causes communication to fail. 

To fix this you have several quick solutions: 
- Have the same user on Docker as on the host. 
- Launch the ROS 2 application as root (equivalent to the above but without changing the Docker configuration).
- Use UDP instead of SHM. This is as simple as running the following before launching the ROS 2 application in the Docker. 
  `export FASTDDS_BUILTIN_TRANSPORTS=UDPv4` 
- Do not set --ipc=host --net=host when running the Docker container.

**Comment by iandresolares** [comment]
> The problem is due to the SHM transport. When you launch a Docker with --net=host and --ipc=host configuration, the publisher and subscriber detect that they are on the same host and try to use SHM. This is due to how the calculation of SHM usage was done until now. In addition, SHM uses the `/dev/shm` directory, which in this case is being attempted to be shared by users who have different permissions: `root in the case of Docker and `$USER` in the case of the host. This causes communication to fail.
> 
> To fix this you have several quick solutions:
> 
>     * Have the same user on Docker as on the host.
> 
>     * Launch the ROS 2 application as root (equivalent to the above but without changing the Docker configuration).
> 
>     * Use UDP instead of SHM. This is as simple as running the following before launching the ROS 2 application in the Docker.
>       `export FASTDDS_BUILTIN_TRANSPORTS=UDPv4`
> 
>     * Do not set --ipc=host --net=host when running the Docker container.

In my case setting UDP transport worked. However I wonder, since I am testing in two different docker containers, both of them are running all ros2 related commands as root, why does SHM transport does not work in this case?

**Comment by rsanchez15** [comment]
@iandresolares 

> In my case setting UDP transport worked. However I wonder, since I am testing in two different docker containers, both of them are running all ros2 related commands as root, why does SHM transport does not work in this case?

And does the following work for you? Maybe you are missing the `--ipc=host` argument. 

* Terminal 1
  ```
  docker run -it --rm --net=host --ipc=host ros:humble
  ros2 topic pub /test std_msgs/msg/Bool
  ```

* Terminal 2
  ```
  docker run -it --rm --net=host --ipc=host ros:humble
  ros2 topic list
  ros2 topic echo /test

Also verify that you compose file looks like this one: 

```
version: '3'

services:
  ros2_pub:
    image: ros:humble
    ipc: host
    network_mode: host
    command: "ros2 topic pub /test std_msgs/msg/Bool"
  ros2_sub:
    image: ros:humble
    ipc: host
    network_mode: host
    command: bash -c "sleep 1 && ros2 topic list && ros2 topic echo /test"
```

**Comment by pqxiao** [comment]
Hi 

I am hitting exactly the same symptoms described in this issue, but with a mixed ROS 2 version setup (host Humble + container Jazzy).

### Environment
- Host: Ubuntu 22.04.5 LTS + ROS 2 Humble (native)
- Container: `dustynv/ros:jazzy-ros-base-r36.4.0-cu128-24.04` (ROS 2 Jazzy)
- Hardware: NVIDIA Jetson AGX Orin (arm64, JetPack 6.0, L4T r36.4.0)
- Docker: 27.3.1
- RMW: Fast DDS (default on both sides)

### Reproduction Steps
1. On host (ROS 2 Humble):
   ```bash
   source /opt/ros/humble/setup.bash
   export ROS_DOMAIN_ID=0
   ```

2. Start talker in Jazzy Docker container:
   ```bash
   docker run -it --rm \
     --network host \
     --ipc host \
     --pid host \
     -v /dev/shm:/dev/shm \
     -e ROS_DOMAIN_ID=0 \
     dustynv/ros:jazzy-ros-base-r36.4.0-cu128-24.04 \
     ros2 run demo_nodes_cpp talker
   ```
   → Container correctly prints: `Publishing: 'Hello World: X'`

3. On host:
   ```bash
   ros2 topic list          # → /chatter is visible
   ros2 topic echo /chatter # → no output (hangs)
   ros2 run demo_nodes_cpp listener # → no messages received
   ```

### What I tried
- Full SHM setup: `--network host --ipc host --pid host -v /dev/shm:/dev/shm`→ failed (still no data on host)
- `FASTRTPS_DEFAULT_LOG_VERBOSITY=INFO` → discovery succeeds, but data plane appears to fail

### Working Workaround
```bash
export FASTDDS_BUILTIN_TRANSPORTS=UDPv4   # on host (Humble)
```
→ Immediately works: host can now `echo` and `listener` receives messages from Jazzy container.

This seems to be a cross-version (Humble ↔ Jazzy) + Docker + SHM incompatibility on arm64/Jetson.
