### ISSUE TITLE
Link to download docker image is not valid [6188]

### ISSUE THREAD

**Issue by alireza-hosseini** [eProsima/Fast-DDS#642]
As instructed in README.md, I tried to download the docker image from https://www.eprosima.com/index.php/downloads-all, however, after filling the contact form I couldn't find any docker image there. There were only official releases.

**Comment by daileyet** [comment]
Is there any update for this issue? Thanks

**Comment by MiguelCompany** [comment]
I've checked the downloads page and I see docker files for versions 2.0 onwards.
