### ISSUE TITLE
Compiling dependency foonathan_memory for QNX [6215]

### ISSUE THREAD

**Issue by briansoe66** [eProsima/Fast-DDS#666]
I am trying to build Fast-RTPS for QNX. I am able to build Fast-CDR and Fast-RTPS, but I cannot build foonathan_memory. mutex and experimental/memory_resource are not found. Has anyone been able to build foonathan_memory for QNX (7.0.0), and could share how? 

I've attached my qnx toolchain and cmake error log.

[cmake_toolchain_and_error_log.zip](https://github.com/eProsima/Fast-RTPS/files/3493925/cmake_toolchain_and_error_log.zip)

`cmake -DCMAKE_TOOLCHAIN_FILE=../qnx-tool-chain.cmake -DCMAKE_INSTALL_PREFIX=../../install -DCMAKE_BUILD_TYPE=Release -DFOONATHAN_MEMORY_BUILD_EXAMPLES=OFF ..`

**Comment by briansoe66** [comment]
I believe the issue is that:
- QNX does not contain <experimental/memory_resource.h>
- therefore, foonathan_memory must be built with FOONATHAN_MEMORY_BUILD_TOOLS=OFF
- this results in container_node_sizes_impl.hpp being empty, and shared_ptr_stateful_node_size being undeclared.

Fast-RTPS release 1.8.1 does not have a dependency on foonathan_memory. Hopefully foothan_memory QNX depency issues will be resolved before 1.9.0

**Comment by cvilas** [comment]
Cross compiling is broken in general for foonathan-memory. There are some errors in it's `CMakeLists.txt` such as checking the non-existant `CMAKE_CROSS_COMPILING` variable instead of `CMAKE_CROSSCOMPILING`

**Comment by cvilas** [comment]
For what it's worth, https://github.com/cvilas/fastrtps_xctest provides a basic repo to test cross compilation. This works perfectly fine for FastRTPS v1.8 and below and I have used something similar to build for NVidia TX2, Android, etc. With the new foonathan-memory dependency, this fails

**Comment by MiguelCompany** [comment]
There have been several improvements related with cross-compilation to the foonathan/memory repo. I guess they might be useful in cross-compiling for QNX. 

@cvilas @briansoe66  could you check on your side?

**Comment by cvilas** [comment]
@MiguelCompany I can confirm that `memory` and `Fast-RTPS` can now be cross compiled after following the structure of cmake cross compilation toolchain setup in https://github.com/foonathan/memory/pull/60

**Comment by briansoe66** [comment]
@MiguelCompany, I am still unable to compile foonathan memory on QNX using foonathan_memory_vendor master or foonathan_memory master :( 

I have created issue https://github.com/foonathan/memory/issues/72#issue-551023679

**Comment by MiguelCompany** [comment]
> I have created issue [foonathan/memory#72 (comment)](https://github.com/foonathan/memory/issues/72#issue-551023679)

@briansoe66 Just answered there

**Comment by EduPonz** [comment]
I'm closing this issue in favor of foonathan/memory#72. Feel free to comment or reopen at any time
