### ISSUE TITLE
Failed to install Fast-RTPS from 1.8.1 binaries [8614]

### ISSUE THREAD

**Issue by TSC21** [eProsima/Fast-DDS#757]
Downloading and installing http://www.eprosima.com/index.php/component/ars/repository/eprosima-fast-rtps/eprosima-fast-rtps-1-8-1 following the instructions on the `README.txt` leads to:
```sh
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):

  Could NOT find Asio (missing: ASIO_INCLUDE_DIR)

Call Stack (most recent call first):

  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)

  cmake/modules/FindAsio.cmake:16 (find_package_handle_standard_args)

  cmake/common/eprosima_libraries.cmake:96 (find_package)

  CMakeLists.txt:213 (eprosima_find_thirdparty)





-- Configuring incomplete, errors occurred!
```
Using `-DTHIRDPARTY=ON` doesn't solve the issue. This leads me to think that your 1.8.1 binaries are incomplete. Any suggestion?

**Comment by juanbaromance** [comment]
Hi. On Ubuntu it means libasio is not properly installed. So try 
sudo apt-get install libasio-dev

**Comment by TSC21** [comment]
> Hi. On Ubuntu it means libasio is not properly installed. So try
> sudo apt-get install libasio-dev

@jacobperron actually I don't think that's the case. Asio was a thirdparty dependency that was brought as a submodule and it's not anymore. If there are dependencies that are required to be installed, they need to be referenced or they need to come with the binaries.

**Comment by juanbaromance** [comment]
@jacobperron see/check the current status on https://github.com/eProsima/Fast-RTPS  to conclude if the dependency is real or faked, included itself or should be required when you compile the package

**Comment by TSC21** [comment]
> @jacobperron see/check the current status on https://github.com/eProsima/Fast-RTPS to conclude if the dependency is real or faked, included itself or should be required when you compile the package

That doesn't really help, right? :) I know for sure that asio was pushed as a thirdparty dependency, as you can see in ttps://github.com/eProsima/Fast-RTPS/tree/1.8.x/thirdparty. Now, if it is a dependency, it needs to be included in the binaries, or at least be made as an install dependency somewhere.

**Comment by TSC21** [comment]
@richiware any inputs?

**Comment by JLBuenoLopez-eProsima** [comment]
Sorry @TSC21,

Fast DDS (formerly known as FastRTPS) 1.8.x has reached end of life. Current installers are checked before being released so this issue is not expected to appear again. I am going to proceed and close this issue.

**Comment by 4ku** [comment]
Hi. On Ubuntu it means libasio is not properly installed. So try
```
sudo apt-get install libasio-dev
```
