### ISSUE TITLE
Something Wrong when install Foonathan memory. [8616]

### ISSUE THREAD

**Issue by sparkskraps** [eProsima/Fast-DDS#801]
I followed this [tutorial](https://eprosima-fast-rtps.readthedocs.io/en/latest/sources.html#colcon-installation) to install fastRTPS. The problem is when i execute the following steps, it has something wrong:

ubuntu@raspberrypi:~/fastRTPS/foonathan_memory_vendor/build$ cmake --build . --target install
[ 12%] Performing configure step for 'foo_mem-ext'
-- Checking 13 features
CMake Error at cmake/comp/comp_base.cmake:288 (message):
  error downloading feature file cpp11_lang/literal_op.cmake: "SSL connect
  error".  Check spelling of feature.

    Trying 43.4.54.16...

  TCP_NODELAY set

  Connected to 43.4.54.16 (43.4.54.16) port 10080 (#0)

  ALPN, offering http/1.1

  successfully set certificate verify locations:

    CAfile: /etc/ssl/certs/ca-certificates.crt
    CApath: /etc/ssl/certs

  [5 bytes data]

  TLSv1.3 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  [5 bytes data]

  error:1408F10B:SSL routines:ssl3_get_record:wrong version number

  Closing connection 0

Call Stack (most recent call first):
  cmake/comp/comp_base.cmake:347 (_comp_fetch_feature)
  cmake/comp/comp_base.cmake:369 (_comp_handle_feature)
  cmake/compatibility.cmake:13 (comp_target_features)
  CMakeLists.txt:50 (include)

-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/fastRTPS/foonathan_memory_vendor/build/foo_mem-ext-prefix/src/foo_mem-ext-build/CMakeFiles/CMakeOutput.log".
CMakeFiles/foo_mem-ext.dir/build.make:106: recipe for target 'foo_mem-ext-prefix/src/foo_mem-ext-stamp/foo_mem-ext-configure' failed
make[2]: *** [foo_mem-ext-prefix/src/foo_mem-ext-stamp/foo_mem-ext-configure] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/foo_mem-ext.dir/all' failed
make[1]: *** [CMakeFiles/foo_mem-ext.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

I searched but not solve it, Does anyone know where it's going wrong? Thanks.

**Comment by zhouxinlzu** [comment]
I also meet this problem, why does this happen,I guess network download disconnect made to compile fail, does anybody known how to solve it? thanks.

**Comment by jparisu** [comment]
Solved issue in foonathan repo:
https://github.com/foonathan/memory/issues/52

_Just delete the build directory and try again._

In case you could not solve it following that step, feel free to reopen this issue.
