### ISSUE TITLE
SecureHelloWorldExample can't match in remote test [6741]

### ISSUE THREAD

**Issue by aim2nasa** [eProsima/Fast-DDS#814]
Using v1.9.2 I've tested the SecureHelloWorldExample with two machines one is ubuntu16.04 on my birtualbox in Windows and the other is raspberrypi3 with debian linux and those are on the same network, 192.168.188.x .

When I test in local environment, It works fine and the other non-secure examples(HelloWorld etc) also worked as I expected. (Unfortunately v1.9.1 sometimes showed problems in matching)

But when I tested the example in remote environment, It seemed the matching process couldn't be turn out successful.

Here are the test results.

- ip address for each machine
```
local:192.168.188.24 (ubuntu running on virtualbox in my desktop)
remote: 192.168.188.14 (raspberrypi 3)
```

- local
```
rossi@retriever:~/v1.9.2/Fast-RTPS/build/examples/C++/SecureHelloWorldExample$ ./SecureHelloWorldExample publisher
Starting 
```

- remote
```
root@linaro-developer:~/v1.9.2/Fast-RTPS/build/examples/C++/SecureHelloWorldExample# ./SecureHelloWorldExample subscriber
Starting 
Subscriber running. Please press enter to stop the Subscriber
```

As you can see above, the example shows no more progress.
For your reference I attached the wireshark capture for this test.
[secureHelloWorld.zip](https://github.com/eProsima/Fast-RTPS/files/3766451/secureHelloWorld.zip)

**Comment by aim2nasa** [comment]
I just made a video clip to clearly show what the problem is.
- Video [https://youtu.be/neVP-PlvAZ4]

**Comment by aim2nasa** [comment]
I just tested again and found one problem that could possibly affect the test.

When I run publisher,subscriber in the same local machine(192.168.188.24), they could communicate okay.
However when I test it again in the remote machine(192.168.188.14), they could not match even though they're on the same machine,

I have no idea why it didn't work in the remote machine yet but, this could the cause of the problem I guess.

Here are the test results in the remote machine, for your reference.

- publisher

```
root@linaro-developer:~/v1.9.2/Fast-RTPS/build/examples/C++/SecureHelloWorldExample# ./SecureHelloWorldExample publisher
Starting 
```

- subscriber
```
root@linaro-developer:~/v1.9.2/Fast-RTPS/build/examples/C++/SecureHelloWorldExample# ./SecureHelloWorldExample subscriber
Starting 
Subscriber running. Please press enter to stop the Subscriber

```

**Comment by LuisGP** [comment]
> However when I test it again in the remote machine(192.168.188.14), they could not match even though they're on the same machine,

We have no problem communicating locally using the raspberry. 

I'm preparing the environment to debug on the raspberry... it will take a huge long.

**Comment by aim2nasa** [comment]
To investigate the problem of remote machine(192.168.188.14), I added -DEPROSIMA_BUILD_TESTS=ON option for cmake and build again.

```
cmake -DSECURITY=ON -DEPROSIMA_BUILD_TESTS=ON -DCOMPILE_EXAMPLES=ON -DPERFORMANCE_TESTS=ON ..
cmake --build . --target install
```

For your information, in rpi3, if I don't enlarge the memory using swap memory, the compilation end up in error due to out of memory. So I had to enlarge the swap memory like this,

```
sudo dd if=/dev/zero of=/swapfile1GB bs=1M count=1024
sudo mkswap /swapfile1GB
sudo swapon /swapfile1GB
```

I ran unit tests related with security which are BuiltinPKIDH, BuiltinAESGCMGMAC, SecurityAuthentication and found out that only BuiltinAESGCMGMAC failed.
However all of them were tested successfully in local system(192.168.188.24)

```
root@linaro-developer:~/v1.9.2/Fast-RTPS/build/test/unittest/security/cryptography# ./BuiltinAESGCMGMAC 
[==========] Running 14 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 14 tests from CryptographyPluginTest
[ RUN      ] CryptographyPluginTest.factory_CreateLocalParticipantHandle
[       OK ] CryptographyPluginTest.factory_CreateLocalParticipantHandle (2101 ms)
[ RUN      ] CryptographyPluginTest.factory_RegisterRemoteParticipant
[       OK ] CryptographyPluginTest.factory_RegisterRemoteParticipant (804 ms)
[ RUN      ] CryptographyPluginTest.exchange_CDRSerializenDeserialize
[       OK ] CryptographyPluginTest.exchange_CDRSerializenDeserialize (632 ms)
[ RUN      ] CryptographyPluginTest.exchange_ParticipantCryptoTokens
[       OK ] CryptographyPluginTest.exchange_ParticipantCryptoTokens (772 ms)
[ RUN      ] CryptographyPluginTest.transform_RTPSMessage
2019-10-28 06:57:18.093 [SECURITY_CRYPTO Error] Not valid SecureDataHeader submessage id -> Function decode_rtps_message
[       OK ] CryptographyPluginTest.transform_RTPSMessage (3872 ms)
[ RUN      ] CryptographyPluginTest.factory_CreateLocalWriterHandle
[       OK ] CryptographyPluginTest.factory_CreateLocalWriterHandle (690 ms)
[ RUN      ] CryptographyPluginTest.factory_CreateLocalReaderHandle
[       OK ] CryptographyPluginTest.factory_CreateLocalReaderHandle (723 ms)
[ RUN      ] CryptographyPluginTest.factory_RegisterRemoteReaderWriter
[       OK ] CryptographyPluginTest.factory_RegisterRemoteReaderWriter (825 ms)
[ RUN      ] CryptographyPluginTest.exchange_ReaderWriterCryptoTokens
[       OK ] CryptographyPluginTest.exchange_ReaderWriterCryptoTokens (654 ms)
[ RUN      ] CryptographyPluginTest.transform_SerializedPayload
/root/v1.9.2/Fast-RTPS/test/unittest/security/cryptography/CryptographyPluginTests.hpp:841: Failure
Value of: CryptoPlugin->cryptotransform()->decode_serialized_payload(decoded_payload, encoded_payload, inline_qos, *reader, *remote_writer, exception)
  Actual: false
Expected: true
[  FAILED  ] CryptographyPluginTest.transform_SerializedPayload (4013 ms)
[ RUN      ] CryptographyPluginTest.transform_Writer_Submesage
[       OK ] CryptographyPluginTest.transform_Writer_Submesage (612 ms)
[ RUN      ] CryptographyPluginTest.transform_Reader_Submessage
[       OK ] CryptographyPluginTest.transform_Reader_Submessage (686 ms)
[ RUN      ] CryptographyPluginTest.transform_preprocess_secure_submessage
[       OK ] CryptographyPluginTest.transform_preprocess_secure_submessage (906 ms)
[ RUN      ] CryptographyPluginTest.mocktest
[       OK ] CryptographyPluginTest.mocktest (443 ms)
[----------] 14 tests from CryptographyPluginTest (22648 ms total)

[----------] Global test environment tear-down
[==========] 14 tests from 1 test suite ran. (25893 ms total)
[  PASSED  ] 13 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] CryptographyPluginTest.transform_SerializedPayload

 1 FAILED TEST
root@linaro-developer:~/v1.9.2/Fast-RTPS/build/test/unittest/security/cryptography#
```

I think this could be the cause of the problem that I addressed so far.
For your information, I left my environment in the following.

```
- Fast-RTPS v1.9.2
- Raspbrrrypi 3 Model B
- rootfs : linaro-stretch-developer-20180416-89
```

**Comment by MiguelCompany** [comment]
@aim2nasa Would you be so kind to check with either `1.10.x` or `2.0.x` branches? We added some openssl related changes on #1163 that could be solving your issue

**Comment by MiguelCompany** [comment]
@aim2nasa Friendly ping

**Comment by EduPonz** [comment]
I'll close this for now. Feel free to comment or reopen if the issue persists.
