### ISSUE TITLE
Call thread hang with 100% cpu usage, when call Publisher* DomainParticipantImpl::create_publisher(...) [8619]

### ISSUE THREAD

**Issue by kwisp** [eProsima/Fast-DDS#837]
Trouble in function:
bool RTPSParticipantImpl::get_new_entity_id(); This function do not change entry argument EntityId_t& entityId. And in  Publisher* DomainParticipantImpl::create_publisher(...), we get infinity loop. If we create second Publisher :)

**Comment by EduPonz** [comment]
Hi @kwisp ,

This issue was solved in https://github.com/eProsima/Fast-DDS/commit/39a17024024b161df0c73354d3822edd633e43da.

I'm going to close the issue. Feel free to reopen or comment at any time
