### ISSUE TITLE
Does Domain::stopAll affect future participants from publishing and subscribing? [8620]

### ISSUE THREAD

**Issue by ghostravenstorm** [eProsima/Fast-DDS#838]
I'm writing a class wrapper API around FastRTPS and part of my object's cleanup routine is calling Domain::stopAll at the end. This seems to affect my other objects from using publishers or subscribers. Other objects that are created after any prior object been shut down and called stopAll seem unable to send or receive data. So, does stopAll literally stop EVERYTHING for the duration of the program?

**Comment by imontesino** [comment]
As can be read in the docs, [Domain::stopAll](https://fast-dds.docs.eprosima.com/en/latest/fastdds/api_reference/rtps/RTPSDomain.html?highlight=stopall#_CPPv4N8eprosima8fastrtps4rtps10RTPSDomain7stopAllEv) stops and removes al participants, publishers and subscribers in that Domain. This Is intended to be called at the end of the process as it  basically removes anything created in that domain (which in most use cases is everything).

To further help you I would need to know more about the objects that you are creating. But from what you seem to want to do you should probably create one participant per object. At clean up call  Domain::removeParticipant(YourObjectParticipant) which will also destroy all the subscribers and publishers belonging to that participant, while leaving other participants (and as such other objects) in the process intact.

Multiple domains should be used to isolate communications, as participants in different domains are invisible to each other. 

As the question has been answered I am going to mark the issue as closed, feel free to comment or reopen at any time.
