### ISSUE TITLE
Is it possible to publish  and subscribe Eigen fixed-size matrices? [8980]

### ISSUE THREAD

**Issue by vincent-hui** [eProsima/Fast-DDS#860]
Is it possible to publish and subscribe Eigen fixed-size matrices? e.g. Eigen::Matrix4d
If yes, would you mind showing me sample code?

Thank you

**Comment by imontesino** [comment]
It is not possible to directly use Eigen Matrices as messages. Message format is defined in the .idl file from which the TypeSupports files are generated. You could create a message containing a `std::array<double, 16>` and then convert it to Eigen::Matrix4d.

Here would be the idl code:
```cpp
struct Eigen4dMatrix
{
	double matrix[16];
};
```

And the conversions from Eigen::Matrix4d to std::array:
```cpp
Eigen4dMatrix message_;
std::array<double, 16> A;
Eigen::Matrix4d B;
Eigen::Matrix4d::Map(A.data()) = B;
message_.matrix();
writer_->write(&matrix_);
```

And the conversions from to std::array Eigen::Matrix4d:
```cpp
std::array<double, 16> A = message_.matrix();
Eigen::Matrix4d B;
B = Eigen::Matrix4d::Map(A.data());
```

I hope this solves your problem.

**Comment by imontesino** [comment]
I leave you here a link to the IDL standard in C++11 where the suported tyes are listed. https://www.omg.org/spec/CPP11/

**Comment by EduPonz** [comment]
As the question has been answered, I'm going to close this issue for now. Feel free to comment or reopen at any time.
