### ISSUE TITLE
Dynamic Topic example WITH_KEY topic [8985]

### ISSUE THREAD

**Issue by Chatrapath** [eProsima/Fast-DDS#935]
I have been trying to build keyed topic dynamically using the Fast-RTPS stack APIs based on the Dynamkc Hello World example. https://github.com/eProsima/Fast-RTPS/tree/master/examples/C%2B%2B/DynamicHelloWorldExample
I am trying to establish communication with subscriber of OpenSplice HelloWorld example. For this, I have matched the type name, topic name, domain id and QoS on both applications. However, I am not able to make the Fast-RTPS topic as keyed type topic. I couldn't find example on how to build a keyed type topic dynamically. The type used by the DynamicHelloWorldExample is
 struct HelloWorld
{
	unsigned long index;
	string message;
};

To establish communication, I need the type to be

struct HelloWorld
{
	**@Key** unsigned long index;
	string message;
};

Please suggest me how to build a type dynamically with WITH_KEY insted of NO_KEY

**Comment by imontesino** [comment]
To build a type dynamically with key you need to add the annotation `"key"` with `"value"` set to `"true"` to the member of your message struct that you wish to designate as Key.

In your case thedynamic equivalent of:
```cpp
struct HelloWorld
{
@key unsigned long index;
string message;
};
```

would be:
```cpp
//  Create basic types
DynamicTypeBuilder_ptr created_type_ulong = DynamicTypeBuilderFactory::get_instance()->create_uint32_builder();
DynamicTypeBuilder_ptr created_type_string = DynamicTypeBuilderFactory::get_instance()->create_string_builder();
DynamicTypeBuilder_ptr struct_type_builder = DynamicTypeBuilderFactory::get_instance()->create_struct_builder();

// Add members to the struct.
struct_type_builder->add_member(0, "index", created_type_ulong.get());
struct_type_builder->apply_annotation_to_member(0,"key","value","true");
struct_type_builder->add_member(1, "message", created_type_string.get());
struct_type_builder->set_name("HelloWorld");
```

**Comment by EduPonz** [comment]
I'll go ahead and close this issue as the question has been answered. Feel free to comment or reopen at any time
