### ISSUE TITLE
Fast-RTPS and OpenSplice communication [8988]

### ISSUE THREAD

**Issue by gek40** [eProsima/Fast-DDS#958]
Hello!
I'm trying setup communication via OpenSplice and Fast-RTPS.

## Expected Behavior

I created idl message like a ROS message:
   struct std_msgs__String
   {
      string data;
   };
   #pragma keylist std_msgs__String

I look forward to exchanging messages between readers and writers of both implementations.

## Current Behavior

The schemes OpenSplice -> OpenSplice, Fast-RTPS -> Fast-RTPS, Fast-RTPS -> OpenSplice are working fine. But when I publish message from the OpenSplice node to the Fast-RTPS node I have a trouble. QoS profiles Fast-RTPS and OpenSplice nodes are identical. I built Fast-RTPS with Debug flag.The Fast-RTPS node discovers a remote participant, but function onNewDataMessage()  is not called. I get this output:
```
[RTPS_MSG_IN Warning] (ID:140351272363776) Ignoring Serialized Payload for too large key-only data(28) -> Function proc_Submsg_Data
2020-01-13 13:49:36.134 [RTPS_MSG_IN Warning] (ID:140351280756480) Ignoring Serialized Payload for too large key-only data(28) -> Function proc_Submsg_Data
2020-01-13 13:49:36.134 [RTPS_HISTORY Warning] SequenceNumber 0 not found -> Function remove_change
```
## Steps to Reproduce

I created repo with both node examples:
https://github.com/gek40/dds_experiments

## System information

- OpenSplice version: 6.9.190705
- Fast-RTPS version: 1.7.2
- OS: Ubuntu 18.04

## Additional resources
-  [Wireshark capture](https://github.com/gek40/dds_experiments/tree/master/wireshark_dump) 

I'm new to DDS. Maybe there are some details that I miss. After spending some time I can’t find the problem why this doesn't work. I would be happy for any help on this. 
Thanks!

**Comment by MiguelCompany** [comment]
May be related to #935

**Comment by gek40** [comment]
No sure, I don't use keys. 
OpenSplice examples include keys with syntax:
```
#pragma keylist std_msgs__String **data**
```
But I'm using syntax without keys:
```
#pragma keylist std_msgs__String
```
I print parameters (my custom output) from the Fast-RTPS subscriber onPublisherDiscovery() function about remote participant. I get the same output for OpenSplice publisher and Fast-RTPS publisher:
```
onPublisherDiscovery: typeName = std_msgs__String, topicName = StdMsgsString_Topic, 
 topicDiscoveryKind = 0, 
 topicKind = 0, 
 info.info.isAlive() = 1, 
 m_durability.kind = 1, 
 m_deadline.period = 2147483647.4294967295, 
 m_latencyBudget.duration = 0.0, 
 m_ownership.kind = 0, 
 m_ownershipStrength.value = 0, 
 m_liveliness.kind = 0, 
 m_liveliness.lease_duration = 2147483647.4294967295, 
 m_reliability.kind = 2, 
 m_reliability.max_blocking_time = 0.429496730, 
 m_lifespan.duration = 2147483647.4294967295, 
 m_destinationOrder.kind = 0, 
 key().isDefined() = 1, 
 m_durabilityService.max_samples = -1, 
 m_durabilityService.max_instances = -1, 
 m_durabilityService.max_samples_per_instance = -1, 
 Partitions: 
 --------------------------------
```

**Comment by imontesino** [comment]
Sorry I have been trying to reproduce your issue but open splice does not seem to be working when following the instructions from the repo you linked, I get the error: `Error in create_participant() failed: Creation failed: invalid handle`.
However, the warning message you are getting indicates you are using a key value larger than 16 bytes. Can you confirm this?

**Comment by JLBuenoLopez-eProsima** [comment]
Sorry @gek40,

Fast DDS (formerly known as FastRTPS) 1.7.x has reached [end of life](https://github.com/eProsima/Fast-DDS/blob/master/RELEASE_SUPPORT.md#release-support). Also, more information was requested last year and no response was received. Consequently I am going to close this issue due to inactivity and unsupported Fast DDS release. Feel free to reopen if you find the issue still present in one of the supported releases.
