### ISSUE TITLE
Defensive programming taken too far [9149]

### ISSUE THREAD

**Issue by juliobg** [eProsima/Fast-DDS#963]
As I was having a look into the repository, being aware that this is peer reviewed quality code, I was surprised to find this in MessageReceiver.cpp:

    for(const auto& readers : AssociatedReaders)
    {
        if (readers.second.empty())
        {
            continue;
        }

        for (const auto& it : readers.second)
        {
            if (it->m_acceptMessagesToUnknownReaders)
            {
                return true;
            }
        }
    }

It would be nice to know why the `continue` statement is necessary and how it makes the code better. Or perhaps defensive programming has been taken too far :)

**Comment by JLBuenoLopez-eProsima** [comment]
Thanks, @juliobg 

You are right! The condition checked previous to the `continue` statement is going to be false always. The `MessageReceiver::removeEndpoint` method checks if the vector is empty, and in that case, it is erased from the map `associated_readers_.`

Pull request #1362 removes the condition and `continue` statement following your suggestion.
