### ISSUE TITLE
make the maximum message size of UDP packets configurable [7416]

### ISSUE THREAD

**Issue by dirk-thomas** [eProsima/Fast-DDS#976]
Currently the maximum UDP packet size is hard coded in https://github.com/eProsima/Fast-RTPS/blob/add4226d6e8a72e2d235112ad29b2bea4e82b986/include/fastrtps/transport/TransportInterface.h#L31

We would like this to be configurable (through XML I guess).

The reason is that with the current size each UDP packet might get split into IP fragments. Depending on the bandwidth that can easily overload the subscriber sides IP stack in case some IP fragments are lost. This option would allow to lower the maximum size to be below the MTU and therefore avoid UP fragmentation (obviously with an increased overhead of a couple of %).

**Comment by richiware** [comment]
Specify new transports via XML is already supported. You can define a new transport using a [TransportDescriptor](https://eprosima-fast-rtps.readthedocs.io/en/latest/xmlprofiles.html#transport-descriptors). Then you can use a transport with this configuration in a [participant profile](https://eprosima-fast-rtps.readthedocs.io/en/latest/xmlprofiles.html#participantprofiles) in this manner:

```xml
        <userTransports>
            <transport_id>TransportId1</transport_id> <!-- string -->
        </userTransports>

        <useBuiltinTransports>false</useBuiltinTransports> <!-- boolean -->
```

Hope this helps you.
