### ISSUE TITLE
MD5 class pollutes object namespace [8990]

### ISSUE THREAD

**Issue by JC3** [eProsima/Fast-DDS#988]
The MD5 class used in this library is exported as-is from the shared library.

This causes a large amount of evilness and debugging headache when an application  links to other libraries that also use a global namespace class named MD5.

We're working with the vendor of another library to get them to move their version of this class to their namespace, and the same should be done here to reduce the chance of the problem happening to anybody else.

If possible, please move the MD5 class into a utility namespace so the lib doesn't create symbol conflicts with other libs that have this class not in a namespace.

Same with the function simply named "md5" in the global namespace, which is also exported from the shared library.

**Comment by JC3** [comment]
(https://github.com/eProsima/Fast-RTPS/blob/master/include/fastrtps/utils/md5.h)

**Comment by Yang-cola** [comment]
+1

**Comment by Mario-DL** [comment]
Hi @JC3,

Thanks for using Fast DDS. With the new [major release](https://github.com/eProsima/Fast-DDS/releases/tag/v3.0.0) this is no longer an issue, since `MD5` was moved to `eprosima::fastdds` namespace. I am feeling free to close this.
